import { VocabularyWord } from '@/lib/types';

export const adjectivesWords: VocabularyWord[] = [
  {
    id: 'adjectives-1',
    german: 'groß',
    turkish: 'Büyük / Uzun',
    english: 'Big / Tall',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['riesig', 'hoch'],
    antonyms: ['klein', 'kurz'],
    collocations: ['ein großes Haus', 'groß und stark'],
    emoji: '📏',
    exampleSentence: 'Das Haus ist sehr groß.',
    exampleTranslation: 'Ev çok büyük.',
    exampleTranslationEn: 'The house is very big.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-2',
    german: 'klein',
    turkish: 'Küçük',
    english: 'Small',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['winzig', 'gering'],
    antonyms: ['groß', 'riesig'],
    collocations: ['ein kleines Kind', 'klein aber fein'],
    emoji: '🤏',
    exampleSentence: 'Das Kind ist noch sehr klein.',
    exampleTranslation: 'Çocuk hâlâ çok küçük.',
    exampleTranslationEn: 'The child is still very small.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-3',
    german: 'gut',
    turkish: 'İyi',
    english: 'Good',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['prima', 'toll', 'super'],
    antonyms: ['schlecht'],
    collocations: ['gut gemacht', 'guter Freund', 'gut schmecken'],
    emoji: '👍',
    exampleSentence: 'Das Essen schmeckt sehr gut.',
    exampleTranslation: 'Yemek çok lezzetli.',
    exampleTranslationEn: 'The food tastes very good.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-4',
    german: 'schlecht',
    turkish: 'Kötü',
    english: 'Bad',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['mies', 'übel'],
    antonyms: ['gut'],
    collocations: ['schlechtes Wetter', 'schlecht gelaunt'],
    emoji: '👎',
    exampleSentence: 'Das Wetter ist heute schlecht.',
    exampleTranslation: 'Bugün hava kötü.',
    exampleTranslationEn: 'The weather is bad today.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-5',
    german: 'schön',
    turkish: 'Güzel',
    english: 'Beautiful',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['hübsch', 'wunderschön', 'attraktiv'],
    antonyms: ['hässlich'],
    collocations: ['ein schöner Tag', 'schönes Wetter'],
    emoji: '🌸',
    exampleSentence: 'Heute ist ein schöner Tag.',
    exampleTranslation: 'Bugün güzel bir gün.',
    exampleTranslationEn: 'Today is a beautiful day.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-6',
    german: 'neu',
    turkish: 'Yeni',
    english: 'New',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['nagelneu', 'brandneu'],
    antonyms: ['alt'],
    collocations: ['ein neues Auto', 'etwas Neues'],
    emoji: '✨',
    exampleSentence: 'Ich habe ein neues Auto.',
    exampleTranslation: 'Yeni bir arabam var.',
    exampleTranslationEn: 'I have a new car.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-7',
    german: 'alt',
    turkish: 'Eski / Yaşlı',
    english: 'Old',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['betagt', 'antik'],
    antonyms: ['neu', 'jung'],
    collocations: ['ein alter Mann', 'die alte Stadt'],
    emoji: '🏚️',
    exampleSentence: 'Die Kirche ist sehr alt.',
    exampleTranslation: 'Kilise çok eski.',
    exampleTranslationEn: 'The church is very old.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-8',
    german: 'schnell',
    turkish: 'Hızlı',
    english: 'Fast',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['rasch', 'flink', 'zügig'],
    antonyms: ['langsam'],
    collocations: ['schnell laufen', 'ein schnelles Auto'],
    emoji: '⚡',
    exampleSentence: 'Das Auto ist sehr schnell.',
    exampleTranslation: 'Araba çok hızlı.',
    exampleTranslationEn: 'The car is very fast.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-9',
    german: 'langsam',
    turkish: 'Yavaş',
    english: 'Slow',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['gemächlich', 'träge'],
    antonyms: ['schnell'],
    collocations: ['langsam fahren', 'langsam aber sicher'],
    emoji: '🐢',
    exampleSentence: 'Bitte sprechen Sie langsam.',
    exampleTranslation: 'Lütfen yavaş konuşun.',
    exampleTranslationEn: 'Please speak slowly.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-10',
    german: 'teuer',
    turkish: 'Pahalı',
    english: 'Expensive',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['kostspielig', 'hochpreisig'],
    antonyms: ['billig', 'günstig'],
    collocations: ['zu teuer', 'teures Restaurant'],
    emoji: '💰',
    exampleSentence: 'Dieses Restaurant ist sehr teuer.',
    exampleTranslation: 'Bu restoran çok pahalı.',
    exampleTranslationEn: 'This restaurant is very expensive.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-11',
    german: 'billig',
    turkish: 'Ucuz',
    english: 'Cheap',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['günstig', 'preiswert'],
    antonyms: ['teuer'],
    collocations: ['billig kaufen', 'billige Kleidung'],
    emoji: '🏷️',
    exampleSentence: 'Die Kleidung ist sehr billig.',
    exampleTranslation: 'Kıyafetler çok ucuz.',
    exampleTranslationEn: 'The clothing is very cheap.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-12',
    german: 'wichtig',
    turkish: 'Önemli',
    english: 'Important',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['bedeutend', 'wesentlich'],
    antonyms: ['unwichtig', 'nebensächlich'],
    collocations: ['sehr wichtig', 'eine wichtige Frage'],
    emoji: '❗',
    exampleSentence: 'Das ist eine sehr wichtige Nachricht.',
    exampleTranslation: 'Bu çok önemli bir haber.',
    exampleTranslationEn: 'This is a very important message.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-13',
    german: 'möglich',
    turkish: 'Mümkün',
    english: 'Possible',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['machbar', 'realisierbar'],
    antonyms: ['unmöglich'],
    collocations: ['so schnell wie möglich', 'alles Mögliche'],
    emoji: '✅',
    exampleSentence: 'Ist es möglich, den Termin zu verschieben?',
    exampleTranslation: 'Randevuyu ertelemek mümkün mü?',
    exampleTranslationEn: 'Is it possible to postpone the appointment?',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-14',
    german: 'gefährlich',
    turkish: 'Tehlikeli',
    english: 'Dangerous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['riskant', 'bedrohlich'],
    antonyms: ['sicher', 'ungefährlich'],
    collocations: ['gefährlich sein', 'eine gefährliche Situation'],
    emoji: '⚠️',
    exampleSentence: 'Diese Straße ist sehr gefährlich.',
    exampleTranslation: 'Bu yol çok tehlikeli.',
    exampleTranslationEn: 'This road is very dangerous.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-15',
    german: 'berühmt',
    turkish: 'Ünlü',
    english: 'Famous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['bekannt', 'prominent'],
    antonyms: ['unbekannt'],
    collocations: ['berühmt werden', 'ein berühmter Schauspieler'],
    emoji: '⭐',
    exampleSentence: 'Berlin ist berühmt für seine Museen.',
    exampleTranslation: 'Berlin müzeleriyle ünlüdür.',
    exampleTranslationEn: 'Berlin is famous for its museums.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-16',
    german: 'gemütlich',
    turkish: 'Rahat / Samimi',
    english: 'Cozy',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['behaglich', 'heimelig'],
    antonyms: ['ungemütlich'],
    collocations: ['eine gemütliche Wohnung', 'es sich gemütlich machen'],
    emoji: '🛋️',
    exampleSentence: 'Das Café ist sehr gemütlich.',
    exampleTranslation: 'Kafe çok rahat.',
    exampleTranslationEn: 'The café is very cozy.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-17',
    german: 'verantwortlich',
    turkish: 'Sorumlu',
    english: 'Responsible',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['zuständig', 'haftbar'],
    antonyms: ['unverantwortlich'],
    collocations: ['verantwortlich sein für', 'sich verantwortlich fühlen'],
    emoji: '🎯',
    exampleSentence: 'Wer ist verantwortlich für dieses Projekt?',
    exampleTranslation: 'Bu projeden kim sorumlu?',
    exampleTranslationEn: 'Who is responsible for this project?',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-18',
    german: 'selbstständig',
    turkish: 'Bağımsız',
    english: 'Independent / Self-employed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['unabhängig', 'eigenständig'],
    antonyms: ['abhängig'],
    collocations: ['selbstständig arbeiten', 'sich selbstständig machen'],
    emoji: '💪',
    exampleSentence: 'Sie arbeitet selbstständig als Designerin.',
    exampleTranslation: 'Bağımsız olarak tasarımcı çalışıyor.',
    exampleTranslationEn: 'She works independently as a designer.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-19',
    german: 'zuverlässig',
    turkish: 'Güvenilir',
    english: 'Reliable',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['verlässlich', 'vertrauenswürdig'],
    antonyms: ['unzuverlässig'],
    collocations: ['ein zuverlässiger Partner', 'zuverlässig arbeiten'],
    emoji: '🤝',
    exampleSentence: 'Er ist ein sehr zuverlässiger Mitarbeiter.',
    exampleTranslation: 'Çok güvenilir bir çalışan.',
    exampleTranslationEn: 'He is a very reliable employee.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-20',
    german: 'nachhaltig',
    turkish: 'Sürdürülebilir',
    english: 'Sustainable',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['dauerhaft', 'langfristig'],
    collocations: ['nachhaltige Entwicklung', 'nachhaltig leben'],
    emoji: '♻️',
    exampleSentence: 'Wir müssen nachhaltiger leben.',
    exampleTranslation: 'Daha sürdürülebilir yaşamalıyız.',
    exampleTranslationEn: 'We need to live more sustainably.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-21',
    german: 'ausgeprägt',
    turkish: 'Belirgin / Güçlü',
    english: 'Pronounced / Distinct',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['deutlich', 'markant'],
    collocations: ['ein ausgeprägter Sinn', 'stark ausgeprägt'],
    emoji: '🔎',
    exampleSentence: 'Sie hat einen ausgeprägten Sinn für Humor.',
    exampleTranslation: 'Güçlü bir mizah anlayışı var.',
    exampleTranslationEn: 'She has a pronounced sense of humor.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-22',
    german: 'vielfältig',
    turkish: 'Çeşitli / Çok yönlü',
    english: 'Diverse / Varied',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['abwechslungsreich', 'mannigfaltig'],
    antonyms: ['eintönig', 'monoton'],
    collocations: ['ein vielfältiges Angebot', 'kulturell vielfältig'],
    emoji: '🌈',
    exampleSentence: 'Berlin bietet ein vielfältiges Kulturangebot.',
    exampleTranslation: 'Berlin çeşitli bir kültürel teklif sunuyor.',
    exampleTranslationEn: 'Berlin offers a diverse cultural program.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-23',
    german: 'unentbehrlich',
    turkish: 'Vazgeçilmez',
    english: 'Indispensable',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['unverzichtbar', 'unersetzlich'],
    antonyms: ['entbehrlich', 'überflüssig'],
    collocations: ['ein unentbehrlicher Teil', 'sich unentbehrlich machen'],
    emoji: '🔑',
    exampleSentence: 'Wasser ist für das Leben unentbehrlich.',
    exampleTranslation: 'Su yaşam için vazgeçilmezdir.',
    exampleTranslationEn: 'Water is indispensable for life.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-24',
    german: 'ausschlaggebend',
    turkish: 'Belirleyici',
    english: 'Decisive / Crucial',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['entscheidend', 'maßgeblich'],
    collocations: ['der ausschlaggebende Faktor', 'ausschlaggebend sein'],
    emoji: '⚖️',
    exampleSentence: 'Ihre Erfahrung war ausschlaggebend für die Entscheidung.',
    exampleTranslation: 'Deneyimi karar için belirleyiciydi.',
    exampleTranslationEn: 'Her experience was decisive for the decision.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-25',
    german: 'heiß',
    turkish: 'Sıcak',
    english: 'Hot',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['warm', 'glühend'],
    antonyms: ['kalt'],
    collocations: ['heißer Kaffee', 'es ist heiß'],
    emoji: '🔥',
    exampleSentence: 'Der Kaffee ist noch sehr heiß.',
    exampleTranslation: 'Kahve hâlâ çok sıcak.',
    exampleTranslationEn: 'The coffee is still very hot.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-26',
    german: 'kalt',
    turkish: 'Soğuk',
    english: 'Cold',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['kühl', 'eisig'],
    antonyms: ['heiß', 'warm'],
    collocations: ['kaltes Wasser', 'mir ist kalt'],
    emoji: '🥶',
    exampleSentence: 'Im Winter ist es sehr kalt.',
    exampleTranslation: 'Kışın hava çok soğuk.',
    exampleTranslationEn: 'In winter it is very cold.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-27',
    german: 'jung',
    turkish: 'Genç',
    english: 'Young',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['jugendlich'],
    antonyms: ['alt'],
    collocations: ['ein junger Mann', 'jung bleiben'],
    emoji: '👶',
    exampleSentence: 'Sie ist noch sehr jung.',
    exampleTranslation: 'O hâlâ çok genç.',
    exampleTranslationEn: 'She is still very young.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-28',
    german: 'lang',
    turkish: 'Uzun',
    english: 'Long',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['ausgedehnt'],
    antonyms: ['kurz'],
    collocations: ['ein langer Weg', 'lange Haare'],
    emoji: '📏',
    exampleSentence: 'Der Weg ist sehr lang.',
    exampleTranslation: 'Yol çok uzun.',
    exampleTranslationEn: 'The road is very long.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-29',
    german: 'kurz',
    turkish: 'Kısa',
    english: 'Short',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['knapp', 'gering'],
    antonyms: ['lang'],
    collocations: ['ein kurzer Rock', 'kurze Haare'],
    emoji: '✂️',
    exampleSentence: 'Die Hose ist zu kurz.',
    exampleTranslation: 'Pantolon çok kısa.',
    exampleTranslationEn: 'The trousers are too short.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-30',
    german: 'schwer',
    turkish: 'Ağır / Zor',
    english: 'Heavy / Difficult',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['gewichtig', 'kompliziert'],
    antonyms: ['leicht'],
    collocations: ['ein schwerer Koffer', 'schwere Aufgabe'],
    emoji: '🏋️',
    exampleSentence: 'Der Koffer ist sehr schwer.',
    exampleTranslation: 'Bavul çok ağır.',
    exampleTranslationEn: 'The suitcase is very heavy.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-31',
    german: 'leicht',
    turkish: 'Hafif / Kolay',
    english: 'Light / Easy',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['einfach', 'mühelos'],
    antonyms: ['schwer'],
    collocations: ['leichte Aufgabe', 'leichtes Gepäck'],
    emoji: '🪶',
    exampleSentence: 'Die Aufgabe ist leicht.',
    exampleTranslation: 'Görev kolay.',
    exampleTranslationEn: 'The task is easy.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-32',
    german: 'richtig',
    turkish: 'Doğru',
    english: 'Right / Correct',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['korrekt', 'wahr'],
    antonyms: ['falsch'],
    collocations: ['die richtige Antwort', 'richtig machen'],
    emoji: '✅',
    exampleSentence: 'Das ist die richtige Antwort.',
    exampleTranslation: 'Bu doğru cevap.',
    exampleTranslationEn: 'That is the correct answer.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-33',
    german: 'falsch',
    turkish: 'Yanlış',
    english: 'Wrong / False',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['inkorrekt', 'fehlerhaft'],
    antonyms: ['richtig'],
    collocations: ['falsche Antwort', 'falsch verstehen'],
    emoji: '❌',
    exampleSentence: 'Das ist leider falsch.',
    exampleTranslation: 'Maalesef bu yanlış.',
    exampleTranslationEn: 'Unfortunately that is wrong.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-34',
    german: 'lecker',
    turkish: 'Lezzetli',
    english: 'Delicious',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['köstlich', 'schmackhaft'],
    collocations: ['leckeres Essen', 'sehr lecker'],
    emoji: '😋',
    exampleSentence: 'Das Essen war sehr lecker.',
    exampleTranslation: 'Yemek çok lezzetliydi.',
    exampleTranslationEn: 'The food was very delicious.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-35',
    german: 'sauber',
    turkish: 'Temiz',
    english: 'Clean',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['rein', 'gepflegt'],
    antonyms: ['schmutzig'],
    collocations: ['sauberes Wasser', 'sauber machen'],
    emoji: '🧹',
    exampleSentence: 'Die Wohnung ist sehr sauber.',
    exampleTranslation: 'Daire çok temiz.',
    exampleTranslationEn: 'The apartment is very clean.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-36',
    german: 'schmutzig',
    turkish: 'Kirli',
    english: 'Dirty',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['dreckig', 'unrein'],
    antonyms: ['sauber'],
    collocations: ['schmutzige Wäsche', 'schmutzig werden'],
    emoji: '🤢',
    exampleSentence: 'Die Schuhe sind schmutzig.',
    exampleTranslation: 'Ayakkabılar kirli.',
    exampleTranslationEn: 'The shoes are dirty.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-37',
    german: 'laut',
    turkish: 'Gürültülü',
    english: 'Loud',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['geräuschvoll'],
    antonyms: ['leise'],
    collocations: ['laute Musik', 'zu laut'],
    emoji: '🔊',
    exampleSentence: 'Die Musik ist zu laut.',
    exampleTranslation: 'Müzik çok gürültülü.',
    exampleTranslationEn: 'The music is too loud.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-38',
    german: 'leise',
    turkish: 'Sessiz',
    english: 'Quiet',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['still', 'ruhig'],
    antonyms: ['laut'],
    collocations: ['leise sprechen', 'leise Musik'],
    emoji: '🤫',
    exampleSentence: 'Bitte sprich leise.',
    exampleTranslation: 'Lütfen sessiz konuş.',
    exampleTranslationEn: 'Please speak quietly.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-39',
    german: 'dunkel',
    turkish: 'Karanlık',
    english: 'Dark',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['finster'],
    antonyms: ['hell'],
    collocations: ['dunkle Nacht', 'es wird dunkel'],
    emoji: '🌑',
    exampleSentence: 'Es ist schon dunkel draußen.',
    exampleTranslation: 'Dışarısı zaten karanlık.',
    exampleTranslationEn: 'It is already dark outside.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-40',
    german: 'hell',
    turkish: 'Aydınlık',
    english: 'Bright',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['leuchtend', 'licht'],
    antonyms: ['dunkel'],
    collocations: ['helles Licht', 'ein heller Raum'],
    emoji: '☀️',
    exampleSentence: 'Das Zimmer ist sehr hell.',
    exampleTranslation: 'Oda çok aydınlık.',
    exampleTranslationEn: 'The room is very bright.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-41',
    german: 'trocken',
    turkish: 'Kuru',
    english: 'Dry',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['dürr', 'ausgetrocknet'],
    antonyms: ['nass', 'feucht'],
    collocations: ['trockene Luft', 'trockenes Wetter'],
    emoji: '🏜️',
    exampleSentence: 'Die Luft ist sehr trocken.',
    exampleTranslation: 'Hava çok kuru.',
    exampleTranslationEn: 'The air is very dry.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-42',
    german: 'nass',
    turkish: 'Islak',
    english: 'Wet',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['feucht'],
    antonyms: ['trocken'],
    collocations: ['nasse Straße', 'nass werden'],
    emoji: '💧',
    exampleSentence: 'Die Straße ist nass vom Regen.',
    exampleTranslation: 'Yol yağmurdan ıslak.',
    exampleTranslationEn: 'The street is wet from the rain.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-43',
    german: 'stark',
    turkish: 'Güçlü',
    english: 'Strong',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['kräftig', 'mächtig'],
    antonyms: ['schwach'],
    collocations: ['ein starker Mann', 'starker Wind'],
    emoji: '💪',
    exampleSentence: 'Der Wind ist heute sehr stark.',
    exampleTranslation: 'Bugün rüzgâr çok güçlü.',
    exampleTranslationEn: 'The wind is very strong today.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-44',
    german: 'schwach',
    turkish: 'Zayıf',
    english: 'Weak',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['kraftlos'],
    antonyms: ['stark'],
    collocations: ['schwaches Signal', 'sich schwach fühlen'],
    emoji: '😵',
    exampleSentence: 'Nach der Krankheit fühle ich mich schwach.',
    exampleTranslation: 'Hastalıktan sonra kendimi zayıf hissediyorum.',
    exampleTranslationEn: 'After the illness I feel weak.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-45',
    german: 'dick',
    turkish: 'Kalın / Şişman',
    english: 'Thick / Fat',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['fett', 'beleibt'],
    antonyms: ['dünn', 'schlank'],
    collocations: ['ein dickes Buch', 'dick werden'],
    emoji: '📖',
    exampleSentence: 'Das Buch ist sehr dick.',
    exampleTranslation: 'Kitap çok kalın.',
    exampleTranslationEn: 'The book is very thick.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-46',
    german: 'dünn',
    turkish: 'İnce / Zayıf',
    english: 'Thin',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['schlank', 'mager'],
    antonyms: ['dick'],
    collocations: ['dünne Scheibe', 'dünn geschnitten'],
    emoji: '🪡',
    exampleSentence: 'Die Wand ist sehr dünn.',
    exampleTranslation: 'Duvar çok ince.',
    exampleTranslationEn: 'The wall is very thin.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-47',
    german: 'breit',
    turkish: 'Geniş',
    english: 'Wide / Broad',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['weit', 'ausgedehnt'],
    antonyms: ['eng', 'schmal'],
    collocations: ['eine breite Straße', 'breit grinsen'],
    emoji: '↔️',
    exampleSentence: 'Die Straße ist sehr breit.',
    exampleTranslation: 'Yol çok geniş.',
    exampleTranslationEn: 'The street is very wide.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-48',
    german: 'eng',
    turkish: 'Dar',
    english: 'Narrow / Tight',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['schmal', 'knapp'],
    antonyms: ['breit', 'weit'],
    collocations: ['eine enge Straße', 'enge Freunde'],
    emoji: '🚪',
    exampleSentence: 'Die Gasse ist sehr eng.',
    exampleTranslation: 'Sokak çok dar.',
    exampleTranslationEn: 'The alley is very narrow.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-49',
    german: 'müde',
    turkish: 'Yorgun',
    english: 'Tired',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['erschöpft', 'schläfrig'],
    antonyms: ['wach', 'munter'],
    collocations: ['todmüde sein', 'müde werden'],
    emoji: '😴',
    exampleSentence: 'Ich bin so müde, ich gehe ins Bett.',
    exampleTranslation: 'Çok yorgunum, yatağa gidiyorum.',
    exampleTranslationEn: 'I am so tired, I am going to bed.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-50',
    german: 'lustig',
    turkish: 'Komik / Eğlenceli',
    english: 'Funny',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['witzig', 'humorvoll'],
    antonyms: ['langweilig', 'ernst'],
    collocations: ['ein lustiger Film', 'lustig sein'],
    emoji: '😂',
    exampleSentence: 'Der Film war sehr lustig.',
    exampleTranslation: 'Film çok komikti.',
    exampleTranslationEn: 'The movie was very funny.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-51',
    german: 'langweilig',
    turkish: 'Sıkıcı',
    english: 'Boring',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['öde', 'eintönig'],
    antonyms: ['interessant', 'spannend'],
    collocations: ['ein langweiliger Film', 'langweilig finden'],
    emoji: '🥱',
    exampleSentence: 'Das Buch ist langweilig.',
    exampleTranslation: 'Kitap sıkıcı.',
    exampleTranslationEn: 'The book is boring.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-52',
    german: 'interessant',
    turkish: 'İlginç',
    english: 'Interesting',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['spannend', 'fesselnd'],
    antonyms: ['langweilig'],
    collocations: ['ein interessantes Thema', 'sehr interessant'],
    emoji: '🧐',
    exampleSentence: 'Das Thema ist sehr interessant.',
    exampleTranslation: 'Konu çok ilginç.',
    exampleTranslationEn: 'The topic is very interesting.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-53',
    german: 'freundlich',
    turkish: 'Cana yakın',
    english: 'Friendly',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['nett', 'liebenswürdig'],
    antonyms: ['unfreundlich'],
    collocations: ['freundlich lächeln', 'ein freundlicher Mensch'],
    emoji: '😊',
    exampleSentence: 'Die Nachbarn sind sehr freundlich.',
    exampleTranslation: 'Komşular çok cana yakın.',
    exampleTranslationEn: 'The neighbors are very friendly.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-54',
    german: 'fleißig',
    turkish: 'Çalışkan',
    english: 'Hardworking',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['arbeitssam', 'emsig'],
    antonyms: ['faul'],
    collocations: ['fleißig lernen', 'ein fleißiger Schüler'],
    emoji: '📚',
    exampleSentence: 'Sie ist eine fleißige Schülerin.',
    exampleTranslation: 'O çalışkan bir öğrenci.',
    exampleTranslationEn: 'She is a hardworking student.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-55',
    german: 'faul',
    turkish: 'Tembel',
    english: 'Lazy',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['träge', 'bequem'],
    antonyms: ['fleißig'],
    collocations: ['faul sein', 'ein fauler Tag'],
    emoji: '🦥',
    exampleSentence: 'Am Sonntag bin ich gern faul.',
    exampleTranslation: 'Pazar günü tembel olmayı severim.',
    exampleTranslationEn: 'On Sundays I like to be lazy.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-56',
    german: 'gesund',
    turkish: 'Sağlıklı',
    english: 'Healthy',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['fit', 'wohlauf'],
    antonyms: ['krank'],
    collocations: ['gesund essen', 'gesund bleiben'],
    emoji: '🥗',
    exampleSentence: 'Obst und Gemüse sind gesund.',
    exampleTranslation: 'Meyve ve sebze sağlıklıdır.',
    exampleTranslationEn: 'Fruits and vegetables are healthy.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-57',
    german: 'krank',
    turkish: 'Hasta',
    english: 'Sick',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['unwohl'],
    antonyms: ['gesund'],
    collocations: ['krank sein', 'krank werden'],
    emoji: '🤒',
    exampleSentence: 'Ich bin krank und bleibe zu Hause.',
    exampleTranslation: 'Hastayım ve evde kalıyorum.',
    exampleTranslationEn: 'I am sick and stay at home.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-58',
    german: 'voll',
    turkish: 'Dolu',
    english: 'Full',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['gefüllt'],
    antonyms: ['leer'],
    collocations: ['voll sein', 'ein voller Bus'],
    emoji: '🫙',
    exampleSentence: 'Der Bus ist voll.',
    exampleTranslation: 'Otobüs dolu.',
    exampleTranslationEn: 'The bus is full.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-59',
    german: 'leer',
    turkish: 'Boş',
    english: 'Empty',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['hohl', 'unbesetzt'],
    antonyms: ['voll'],
    collocations: ['leere Flasche', 'leer stehen'],
    emoji: '🫗',
    exampleSentence: 'Die Flasche ist leer.',
    exampleTranslation: 'Şişe boş.',
    exampleTranslationEn: 'The bottle is empty.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-60',
    german: 'offen',
    turkish: 'Açık',
    english: 'Open',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['geöffnet'],
    antonyms: ['geschlossen'],
    collocations: ['offene Tür', 'offen sein für'],
    emoji: '🚪',
    exampleSentence: 'Das Fenster ist offen.',
    exampleTranslation: 'Pencere açık.',
    exampleTranslationEn: 'The window is open.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-61',
    german: 'geschlossen',
    turkish: 'Kapalı',
    english: 'Closed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['zu', 'verschlossen'],
    antonyms: ['offen'],
    collocations: ['geschlossene Tür', 'der Laden ist geschlossen'],
    emoji: '🔒',
    exampleSentence: 'Das Geschäft ist geschlossen.',
    exampleTranslation: 'Mağaza kapalı.',
    exampleTranslationEn: 'The shop is closed.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-62',
    german: 'fertig',
    turkish: 'Hazır / Bitmiş',
    english: 'Ready / Finished',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['bereit', 'abgeschlossen'],
    collocations: ['fertig sein', 'fertig werden'],
    emoji: '🏁',
    exampleSentence: 'Das Essen ist fertig!',
    exampleTranslation: 'Yemek hazır!',
    exampleTranslationEn: 'The food is ready!',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-63',
    german: 'besonders',
    turkish: 'Özel / Özellikle',
    english: 'Special / Especially',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['speziell', 'außergewöhnlich'],
    antonyms: ['gewöhnlich', 'normal'],
    collocations: ['ein besonderer Tag', 'besonders schön'],
    emoji: '🌟',
    exampleSentence: 'Heute ist ein besonderer Tag.',
    exampleTranslation: 'Bugün özel bir gün.',
    exampleTranslationEn: 'Today is a special day.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-64',
    german: 'einfach',
    turkish: 'Basit / Kolay',
    english: 'Simple / Easy',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['unkompliziert', 'leicht'],
    antonyms: ['kompliziert', 'schwierig'],
    collocations: ['ganz einfach', 'eine einfache Lösung'],
    emoji: '👌',
    exampleSentence: 'Die Lösung ist ganz einfach.',
    exampleTranslation: 'Çözüm çok basit.',
    exampleTranslationEn: 'The solution is quite simple.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-65',
    german: 'schwierig',
    turkish: 'Zor',
    english: 'Difficult',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['kompliziert', 'anspruchsvoll'],
    antonyms: ['einfach', 'leicht'],
    collocations: ['eine schwierige Frage', 'schwierig finden'],
    emoji: '🤔',
    exampleSentence: 'Die Prüfung war sehr schwierig.',
    exampleTranslation: 'Sınav çok zordu.',
    exampleTranslationEn: 'The exam was very difficult.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-66',
    german: 'nötig',
    turkish: 'Gerekli',
    english: 'Necessary',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['notwendig', 'erforderlich'],
    antonyms: ['unnötig'],
    collocations: ['es ist nötig', 'dringend nötig'],
    emoji: '❗',
    exampleSentence: 'Es ist nötig, das sofort zu erledigen.',
    exampleTranslation: 'Bunu hemen yapmak gerekli.',
    exampleTranslationEn: 'It is necessary to do this immediately.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-67',
    german: 'höflich',
    turkish: 'Kibar / Nazik',
    english: 'Polite',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['respektvoll', 'zuvorkommend'],
    antonyms: ['unhöflich', 'grob'],
    collocations: ['höflich sein', 'höflich fragen'],
    emoji: '🎩',
    exampleSentence: 'Er ist immer sehr höflich.',
    exampleTranslation: 'O her zaman çok kibar.',
    exampleTranslationEn: 'He is always very polite.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-68',
    german: 'ehrlich',
    turkish: 'Dürüst',
    english: 'Honest',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['aufrichtig', 'wahrhaftig'],
    antonyms: ['unehrlich', 'verlogen'],
    collocations: ['ehrlich gesagt', 'ehrlich sein'],
    emoji: '🤞',
    exampleSentence: 'Ehrlich gesagt, ich weiß es nicht.',
    exampleTranslation: 'Dürüst olmak gerekirse bilmiyorum.',
    exampleTranslationEn: 'Honestly, I don\'t know.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-69',
    german: 'mutig',
    turkish: 'Cesur',
    english: 'Brave / Courageous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['tapfer', 'kühn'],
    antonyms: ['feige', 'ängstlich'],
    collocations: ['mutig sein', 'eine mutige Entscheidung'],
    emoji: '🦁',
    exampleSentence: 'Das war eine mutige Entscheidung.',
    exampleTranslation: 'Bu cesur bir karardı.',
    exampleTranslationEn: 'That was a brave decision.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-70',
    german: 'neugierig',
    turkish: 'Meraklı',
    english: 'Curious',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['wissbegierig'],
    collocations: ['neugierig sein', 'neugierig auf etwas'],
    emoji: '🔍',
    exampleSentence: 'Kinder sind von Natur aus neugierig.',
    exampleTranslation: 'Çocuklar doğası gereği meraklıdır.',
    exampleTranslationEn: 'Children are naturally curious.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-71',
    german: 'geduldig',
    turkish: 'Sabırlı',
    english: 'Patient',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['langmütig'],
    antonyms: ['ungeduldig'],
    collocations: ['geduldig warten', 'geduldig sein'],
    emoji: '⏳',
    exampleSentence: 'Bitte sei geduldig, es dauert noch.',
    exampleTranslation: 'Lütfen sabırlı ol, biraz daha sürecek.',
    exampleTranslationEn: 'Please be patient, it will take a bit longer.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-72',
    german: 'pünktlich',
    turkish: 'Dakik',
    english: 'Punctual',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['rechtzeitig'],
    antonyms: ['unpünktlich', 'verspätet'],
    collocations: ['pünktlich sein', 'pünktlich ankommen'],
    emoji: '⏰',
    exampleSentence: 'Der Zug ist heute pünktlich.',
    exampleTranslation: 'Tren bugün dakik.',
    exampleTranslationEn: 'The train is punctual today.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-73',
    german: 'bequem',
    turkish: 'Rahat',
    english: 'Comfortable',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['komfortabel', 'gemütlich'],
    antonyms: ['unbequem'],
    collocations: ['ein bequemer Stuhl', 'bequeme Schuhe'],
    emoji: '🛋️',
    exampleSentence: 'Der Sessel ist sehr bequem.',
    exampleTranslation: 'Koltuk çok rahat.',
    exampleTranslationEn: 'The armchair is very comfortable.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-74',
    german: 'praktisch',
    turkish: 'Pratik',
    english: 'Practical',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['nützlich', 'handlich'],
    antonyms: ['unpraktisch'],
    collocations: ['praktisch sein', 'eine praktische Lösung'],
    emoji: '🔧',
    exampleSentence: 'Das ist eine praktische Lösung.',
    exampleTranslation: 'Bu pratik bir çözüm.',
    exampleTranslationEn: 'That is a practical solution.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-75',
    german: 'typisch',
    turkish: 'Tipik',
    english: 'Typical',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['charakteristisch'],
    antonyms: ['untypisch', 'atypisch'],
    collocations: ['typisch deutsch', 'typisch für'],
    emoji: '🇩🇪',
    exampleSentence: 'Das ist typisch deutsch.',
    exampleTranslation: 'Bu tipik Alman.',
    exampleTranslationEn: 'That is typically German.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-76',
    german: 'ständig',
    turkish: 'Sürekli',
    english: 'Constant',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['dauernd', 'permanent'],
    collocations: ['ständig unterwegs', 'ständige Veränderung'],
    emoji: '🔄',
    exampleSentence: 'Er ist ständig beschäftigt.',
    exampleTranslation: 'Sürekli meşgul.',
    exampleTranslationEn: 'He is constantly busy.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-77',
    german: 'dringend',
    turkish: 'Acil',
    english: 'Urgent',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['eilig', 'akut'],
    collocations: ['dringend benötigen', 'ein dringendes Problem'],
    emoji: '🚨',
    exampleSentence: 'Ich brauche dringend Hilfe.',
    exampleTranslation: 'Acil yardıma ihtiyacım var.',
    exampleTranslationEn: 'I urgently need help.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-78',
    german: 'angenehm',
    turkish: 'Hoş / Keyifli',
    english: 'Pleasant',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['erfreulich', 'wohltuend'],
    antonyms: ['unangenehm'],
    collocations: ['angenehme Temperatur', 'sehr angenehm'],
    emoji: '😌',
    exampleSentence: 'Das Wetter ist sehr angenehm.',
    exampleTranslation: 'Hava çok hoş.',
    exampleTranslationEn: 'The weather is very pleasant.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-79',
    german: 'ähnlich',
    turkish: 'Benzer',
    english: 'Similar',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['vergleichbar'],
    antonyms: ['unterschiedlich', 'verschieden'],
    collocations: ['ähnlich aussehen', 'ähnlich sein'],
    emoji: '👯',
    exampleSentence: 'Die Schwestern sehen sich sehr ähnlich.',
    exampleTranslation: 'Kız kardeşler birbirine çok benziyor.',
    exampleTranslationEn: 'The sisters look very similar.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-80',
    german: 'verschieden',
    turkish: 'Farklı',
    english: 'Different / Various',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['unterschiedlich', 'anders'],
    antonyms: ['gleich', 'ähnlich'],
    collocations: ['verschiedene Meinungen', 'ganz verschieden'],
    emoji: '🎭',
    exampleSentence: 'Die Meinungen sind verschieden.',
    exampleTranslation: 'Görüşler farklı.',
    exampleTranslationEn: 'The opinions are different.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-81',
    german: 'erstaunlich',
    turkish: 'Şaşırtıcı',
    english: 'Amazing',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['verblüffend', 'bemerkenswert'],
    collocations: ['erstaunlich gut', 'ein erstaunliches Ergebnis'],
    emoji: '😮',
    exampleSentence: 'Das Ergebnis ist erstaunlich.',
    exampleTranslation: 'Sonuç şaşırtıcı.',
    exampleTranslationEn: 'The result is amazing.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-82',
    german: 'üblich',
    turkish: 'Alışılmış / Olağan',
    english: 'Usual / Common',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['gewöhnlich', 'normal'],
    antonyms: ['unüblich', 'ungewöhnlich'],
    collocations: ['wie üblich', 'das Übliche'],
    emoji: '📋',
    exampleSentence: 'Wie üblich kommt er zu spät.',
    exampleTranslation: 'Her zamanki gibi geç geliyor.',
    exampleTranslationEn: 'As usual, he arrives late.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-83',
    german: 'außergewöhnlich',
    turkish: 'Olağanüstü',
    english: 'Extraordinary',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['einzigartig', 'ungewöhnlich'],
    antonyms: ['gewöhnlich', 'normal'],
    collocations: ['außergewöhnlich begabt', 'eine außergewöhnliche Leistung'],
    emoji: '🏆',
    exampleSentence: 'Sie hat eine außergewöhnliche Stimme.',
    exampleTranslation: 'Olağanüstü bir sesi var.',
    exampleTranslationEn: 'She has an extraordinary voice.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-84',
    german: 'beeindruckend',
    turkish: 'Etkileyici',
    english: 'Impressive',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['imposant', 'imponierend'],
    collocations: ['beeindruckende Leistung', 'sehr beeindruckend'],
    emoji: '🤩',
    exampleSentence: 'Die Aussicht war beeindruckend.',
    exampleTranslation: 'Manzara etkileyiciydi.',
    exampleTranslationEn: 'The view was impressive.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-85',
    german: 'offensichtlich',
    turkish: 'Açıkça / Belli ki',
    english: 'Obvious',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['augenscheinlich', 'erkennbar'],
    collocations: ['offensichtlich falsch', 'ganz offensichtlich'],
    emoji: '👁️',
    exampleSentence: 'Das ist offensichtlich ein Fehler.',
    exampleTranslation: 'Bu açıkça bir hata.',
    exampleTranslationEn: 'That is obviously a mistake.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-86',
    german: 'angemessen',
    turkish: 'Uygun',
    english: 'Appropriate',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['passend', 'adäquat'],
    antonyms: ['unangemessen'],
    collocations: ['angemessene Kleidung', 'angemessen reagieren'],
    emoji: '✔️',
    exampleSentence: 'Das Verhalten war nicht angemessen.',
    exampleTranslation: 'Davranış uygun değildi.',
    exampleTranslationEn: 'The behavior was not appropriate.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-87',
    german: 'großzügig',
    turkish: 'Cömert',
    english: 'Generous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['freigiebig', 'spendabel'],
    antonyms: ['geizig'],
    collocations: ['großzügiges Angebot', 'großzügig sein'],
    emoji: '🎁',
    exampleSentence: 'Das war sehr großzügig von dir.',
    exampleTranslation: 'Bu senin için çok cömertti.',
    exampleTranslationEn: 'That was very generous of you.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-88',
    german: 'gründlich',
    turkish: 'Titiz / Kapsamlı',
    english: 'Thorough',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['sorgfältig', 'genau'],
    antonyms: ['oberflächlich'],
    collocations: ['gründlich prüfen', 'gründliche Arbeit'],
    emoji: '🔬',
    exampleSentence: 'Er arbeitet sehr gründlich.',
    exampleTranslation: 'Çok titiz çalışıyor.',
    exampleTranslationEn: 'He works very thoroughly.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-89',
    german: 'empfindlich',
    turkish: 'Hassas',
    english: 'Sensitive',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['sensibel', 'verletzlich'],
    antonyms: ['robust', 'unempfindlich'],
    collocations: ['empfindliche Haut', 'empfindlich reagieren'],
    emoji: '🌸',
    exampleSentence: 'Sie hat sehr empfindliche Haut.',
    exampleTranslation: 'Çok hassas bir cildi var.',
    exampleTranslationEn: 'She has very sensitive skin.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-90',
    german: 'entschlossen',
    turkish: 'Kararlı',
    english: 'Determined',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['fest entschlossen', 'resolut'],
    antonyms: ['unentschlossen', 'zögerlich'],
    collocations: ['fest entschlossen sein', 'entschlossen handeln'],
    emoji: '💥',
    exampleSentence: 'Sie ist entschlossen, ihr Ziel zu erreichen.',
    exampleTranslation: 'Hedefine ulaşmaya kararlı.',
    exampleTranslationEn: 'She is determined to reach her goal.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-91',
    german: 'umfangreich',
    turkish: 'Kapsamlı',
    english: 'Extensive / Comprehensive',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['ausführlich', 'weitreichend'],
    antonyms: ['knapp', 'gering'],
    collocations: ['umfangreiche Sammlung', 'umfangreiches Wissen'],
    emoji: '📦',
    exampleSentence: 'Er hat ein umfangreiches Wissen.',
    exampleTranslation: 'Kapsamlı bir bilgiye sahip.',
    exampleTranslationEn: 'He has extensive knowledge.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-92',
    german: 'überflüssig',
    turkish: 'Gereksiz',
    english: 'Superfluous / Unnecessary',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['unnötig', 'entbehrlich'],
    antonyms: ['nötig', 'notwendig'],
    collocations: ['überflüssige Arbeit', 'völlig überflüssig'],
    emoji: '🗑️',
    exampleSentence: 'Das war eine überflüssige Bemerkung.',
    exampleTranslation: 'Gereksiz bir yorumdu.',
    exampleTranslationEn: 'That was a superfluous remark.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-93',
    german: 'vorläufig',
    turkish: 'Geçici',
    english: 'Temporary / Preliminary',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['provisorisch', 'einstweilig'],
    antonyms: ['endgültig', 'dauerhaft'],
    collocations: ['vorläufiges Ergebnis', 'vorläufig bleiben'],
    emoji: '⏱️',
    exampleSentence: 'Das ist eine vorläufige Lösung.',
    exampleTranslation: 'Bu geçici bir çözüm.',
    exampleTranslationEn: 'This is a temporary solution.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-94',
    german: 'anspruchsvoll',
    turkish: 'Talepkâr / İddialı',
    english: 'Demanding / Ambitious',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['herausfordernd', 'wählerisch'],
    antonyms: ['anspruchslos', 'bescheiden'],
    collocations: ['anspruchsvolle Aufgabe', 'anspruchsvoller Kunde'],
    emoji: '🎯',
    exampleSentence: 'Das ist eine anspruchsvolle Aufgabe.',
    exampleTranslation: 'Bu talepkâr bir görev.',
    exampleTranslationEn: 'This is a demanding task.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-95',
    german: 'anschaulich',
    turkish: 'Açık / Anlaşılır',
    english: 'Vivid / Illustrative',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['bildlich', 'lebendig'],
    collocations: ['anschaulich erklären', 'ein anschauliches Beispiel'],
    emoji: '🎨',
    exampleSentence: 'Er hat das Thema sehr anschaulich erklärt.',
    exampleTranslation: 'Konuyu çok açık bir şekilde anlattı.',
    exampleTranslationEn: 'He explained the topic very vividly.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-96',
    german: 'wesentlich',
    turkish: 'Temel / Esaslı',
    english: 'Essential / Substantial',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['grundlegend', 'erheblich'],
    antonyms: ['unwesentlich', 'nebensächlich'],
    collocations: ['ein wesentlicher Unterschied', 'wesentlich besser'],
    emoji: '🔑',
    exampleSentence: 'Das ist ein wesentlicher Unterschied.',
    exampleTranslation: 'Bu temel bir fark.',
    exampleTranslationEn: 'That is an essential difference.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-97',
    german: 'aufwendig',
    turkish: 'Zahmetli / Masraflı',
    english: 'Elaborate / Costly',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['kostspielig', 'aufwändig'],
    antonyms: ['einfach', 'bescheiden'],
    collocations: ['ein aufwendiges Projekt', 'sehr aufwendig'],
    emoji: '💎',
    exampleSentence: 'Die Renovierung war sehr aufwendig.',
    exampleTranslation: 'Tadilat çok zahmetliydi.',
    exampleTranslationEn: 'The renovation was very elaborate.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-98',
    german: 'gerecht',
    turkish: 'Adil',
    english: 'Fair / Just',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['fair', 'angemessen'],
    antonyms: ['ungerecht'],
    collocations: ['ein gerechtes Urteil', 'gerecht behandeln'],
    emoji: '⚖️',
    exampleSentence: 'Das Urteil war gerecht.',
    exampleTranslation: 'Karar adildi.',
    exampleTranslationEn: 'The verdict was fair.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-99',
    german: 'sorgfältig',
    turkish: 'Dikkatli / Özenli',
    english: 'Careful',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['gewissenhaft', 'achtsam'],
    antonyms: ['nachlässig', 'schlampig'],
    collocations: ['sorgfältig prüfen', 'sorgfältige Arbeit'],
    emoji: '🧐',
    exampleSentence: 'Sie arbeitet sehr sorgfältig.',
    exampleTranslation: 'Çok özenli çalışıyor.',
    exampleTranslationEn: 'She works very carefully.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-100',
    german: 'hartnäckig',
    turkish: 'İnatçı / Kararlı',
    english: 'Persistent / Stubborn',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['beharrlich', 'stur'],
    antonyms: ['nachgiebig'],
    collocations: ['hartnäckig bleiben', 'hartnäckiger Husten'],
    emoji: '🐂',
    exampleSentence: 'Er ist sehr hartnäckig bei Verhandlungen.',
    exampleTranslation: 'Müzakerelerde çok inatçı.',
    exampleTranslationEn: 'He is very persistent in negotiations.',
    category: 'adjectives',
    level: 'B2',
  },
];
