import { VocabularyWord } from '@/lib/types';

export const adjectivesWords: VocabularyWord[] = [
  {
    id: 'adjectives-1',
    german: 'groß',
    turkish: 'Büyük / Uzun',
    english: 'Big / Tall',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['riesig', 'hoch'],
    antonyms: ['klein', 'kurz'],
    collocations: ['ein großes Haus', 'groß und stark'],
    emoji: '📏',
    exampleSentence: 'Das Haus ist sehr groß.',
    exampleTranslation: 'Ev çok büyük.',
    exampleTranslationEn: 'The house is very big.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-2',
    german: 'klein',
    turkish: 'Küçük',
    english: 'Small',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['winzig', 'gering'],
    antonyms: ['groß', 'riesig'],
    collocations: ['ein kleines Kind', 'klein aber fein'],
    emoji: '🤏',
    exampleSentence: 'Das Kind ist noch sehr klein.',
    exampleTranslation: 'Çocuk hâlâ çok küçük.',
    exampleTranslationEn: 'The child is still very small.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-3',
    german: 'gut',
    turkish: 'İyi',
    english: 'Good',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['prima', 'toll', 'super'],
    antonyms: ['schlecht'],
    collocations: ['gut gemacht', 'guter Freund', 'gut schmecken'],
    emoji: '👍',
    exampleSentence: 'Das Essen schmeckt sehr gut.',
    exampleTranslation: 'Yemek çok lezzetli.',
    exampleTranslationEn: 'The food tastes very good.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-4',
    german: 'schlecht',
    turkish: 'Kötü',
    english: 'Bad',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['mies', 'übel'],
    antonyms: ['gut'],
    collocations: ['schlechtes Wetter', 'schlecht gelaunt'],
    emoji: '👎',
    exampleSentence: 'Das Wetter ist heute schlecht.',
    exampleTranslation: 'Bugün hava kötü.',
    exampleTranslationEn: 'The weather is bad today.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-5',
    german: 'schön',
    turkish: 'Güzel',
    english: 'Beautiful',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['hübsch', 'wunderschön', 'attraktiv'],
    antonyms: ['hässlich'],
    collocations: ['ein schöner Tag', 'schönes Wetter'],
    emoji: '🌸',
    exampleSentence: 'Heute ist ein schöner Tag.',
    exampleTranslation: 'Bugün güzel bir gün.',
    exampleTranslationEn: 'Today is a beautiful day.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-6',
    german: 'neu',
    turkish: 'Yeni',
    english: 'New',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['nagelneu', 'brandneu'],
    antonyms: ['alt'],
    collocations: ['ein neues Auto', 'etwas Neues'],
    emoji: '✨',
    exampleSentence: 'Ich habe ein neues Auto.',
    exampleTranslation: 'Yeni bir arabam var.',
    exampleTranslationEn: 'I have a new car.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-7',
    german: 'alt',
    turkish: 'Eski / Yaşlı',
    english: 'Old',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['betagt', 'antik'],
    antonyms: ['neu', 'jung'],
    collocations: ['ein alter Mann', 'die alte Stadt'],
    emoji: '🏚️',
    exampleSentence: 'Die Kirche ist sehr alt.',
    exampleTranslation: 'Kilise çok eski.',
    exampleTranslationEn: 'The church is very old.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-8',
    german: 'schnell',
    turkish: 'Hızlı',
    english: 'Fast',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['rasch', 'flink', 'zügig'],
    antonyms: ['langsam'],
    collocations: ['schnell laufen', 'ein schnelles Auto'],
    emoji: '⚡',
    exampleSentence: 'Das Auto ist sehr schnell.',
    exampleTranslation: 'Araba çok hızlı.',
    exampleTranslationEn: 'The car is very fast.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-9',
    german: 'langsam',
    turkish: 'Yavaş',
    english: 'Slow',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['gemächlich', 'träge'],
    antonyms: ['schnell'],
    collocations: ['langsam fahren', 'langsam aber sicher'],
    emoji: '🐢',
    exampleSentence: 'Bitte sprechen Sie langsam.',
    exampleTranslation: 'Lütfen yavaş konuşun.',
    exampleTranslationEn: 'Please speak slowly.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-10',
    german: 'teuer',
    turkish: 'Pahalı',
    english: 'Expensive',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['kostspielig', 'hochpreisig'],
    antonyms: ['billig', 'günstig'],
    collocations: ['zu teuer', 'teures Restaurant'],
    emoji: '💰',
    exampleSentence: 'Dieses Restaurant ist sehr teuer.',
    exampleTranslation: 'Bu restoran çok pahalı.',
    exampleTranslationEn: 'This restaurant is very expensive.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-11',
    german: 'billig',
    turkish: 'Ucuz',
    english: 'Cheap',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['günstig', 'preiswert'],
    antonyms: ['teuer'],
    collocations: ['billig kaufen', 'billige Kleidung'],
    emoji: '🏷️',
    exampleSentence: 'Die Kleidung ist sehr billig.',
    exampleTranslation: 'Kıyafetler çok ucuz.',
    exampleTranslationEn: 'The clothing is very cheap.',
    category: 'adjectives',
    level: 'A1',
  },
  {
    id: 'adjectives-12',
    german: 'wichtig',
    turkish: 'Önemli',
    english: 'Important',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['bedeutend', 'wesentlich'],
    antonyms: ['unwichtig', 'nebensächlich'],
    collocations: ['sehr wichtig', 'eine wichtige Frage'],
    emoji: '❗',
    exampleSentence: 'Das ist eine sehr wichtige Nachricht.',
    exampleTranslation: 'Bu çok önemli bir haber.',
    exampleTranslationEn: 'This is a very important message.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-13',
    german: 'möglich',
    turkish: 'Mümkün',
    english: 'Possible',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['machbar', 'realisierbar'],
    antonyms: ['unmöglich'],
    collocations: ['so schnell wie möglich', 'alles Mögliche'],
    emoji: '✅',
    exampleSentence: 'Ist es möglich, den Termin zu verschieben?',
    exampleTranslation: 'Randevuyu ertelemek mümkün mü?',
    exampleTranslationEn: 'Is it possible to postpone the appointment?',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-14',
    german: 'gefährlich',
    turkish: 'Tehlikeli',
    english: 'Dangerous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['riskant', 'bedrohlich'],
    antonyms: ['sicher', 'ungefährlich'],
    collocations: ['gefährlich sein', 'eine gefährliche Situation'],
    emoji: '⚠️',
    exampleSentence: 'Diese Straße ist sehr gefährlich.',
    exampleTranslation: 'Bu yol çok tehlikeli.',
    exampleTranslationEn: 'This road is very dangerous.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-15',
    german: 'berühmt',
    turkish: 'Ünlü',
    english: 'Famous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['bekannt', 'prominent'],
    antonyms: ['unbekannt'],
    collocations: ['berühmt werden', 'ein berühmter Schauspieler'],
    emoji: '⭐',
    exampleSentence: 'Berlin ist berühmt für seine Museen.',
    exampleTranslation: 'Berlin müzeleriyle ünlüdür.',
    exampleTranslationEn: 'Berlin is famous for its museums.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-16',
    german: 'gemütlich',
    turkish: 'Rahat / Samimi',
    english: 'Cozy',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['behaglich', 'heimelig'],
    antonyms: ['ungemütlich'],
    collocations: ['eine gemütliche Wohnung', 'es sich gemütlich machen'],
    emoji: '🛋️',
    exampleSentence: 'Das Café ist sehr gemütlich.',
    exampleTranslation: 'Kafe çok rahat.',
    exampleTranslationEn: 'The café is very cozy.',
    category: 'adjectives',
    level: 'A2',
  },
  {
    id: 'adjectives-17',
    german: 'verantwortlich',
    turkish: 'Sorumlu',
    english: 'Responsible',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['zuständig', 'haftbar'],
    antonyms: ['unverantwortlich'],
    collocations: ['verantwortlich sein für', 'sich verantwortlich fühlen'],
    emoji: '🎯',
    exampleSentence: 'Wer ist verantwortlich für dieses Projekt?',
    exampleTranslation: 'Bu projeden kim sorumlu?',
    exampleTranslationEn: 'Who is responsible for this project?',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-18',
    german: 'selbstständig',
    turkish: 'Bağımsız',
    english: 'Independent / Self-employed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['unabhängig', 'eigenständig'],
    antonyms: ['abhängig'],
    collocations: ['selbstständig arbeiten', 'sich selbstständig machen'],
    emoji: '💪',
    exampleSentence: 'Sie arbeitet selbstständig als Designerin.',
    exampleTranslation: 'Bağımsız olarak tasarımcı çalışıyor.',
    exampleTranslationEn: 'She works independently as a designer.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-19',
    german: 'zuverlässig',
    turkish: 'Güvenilir',
    english: 'Reliable',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['verlässlich', 'vertrauenswürdig'],
    antonyms: ['unzuverlässig'],
    collocations: ['ein zuverlässiger Partner', 'zuverlässig arbeiten'],
    emoji: '🤝',
    exampleSentence: 'Er ist ein sehr zuverlässiger Mitarbeiter.',
    exampleTranslation: 'Çok güvenilir bir çalışan.',
    exampleTranslationEn: 'He is a very reliable employee.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-20',
    german: 'nachhaltig',
    turkish: 'Sürdürülebilir',
    english: 'Sustainable',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['dauerhaft', 'langfristig'],
    collocations: ['nachhaltige Entwicklung', 'nachhaltig leben'],
    emoji: '♻️',
    exampleSentence: 'Wir müssen nachhaltiger leben.',
    exampleTranslation: 'Daha sürdürülebilir yaşamalıyız.',
    exampleTranslationEn: 'We need to live more sustainably.',
    category: 'adjectives',
    level: 'B1',
  },
  {
    id: 'adjectives-21',
    german: 'ausgeprägt',
    turkish: 'Belirgin / Güçlü',
    english: 'Pronounced / Distinct',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['deutlich', 'markant'],
    collocations: ['ein ausgeprägter Sinn', 'stark ausgeprägt'],
    emoji: '🔎',
    exampleSentence: 'Sie hat einen ausgeprägten Sinn für Humor.',
    exampleTranslation: 'Güçlü bir mizah anlayışı var.',
    exampleTranslationEn: 'She has a pronounced sense of humor.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-22',
    german: 'vielfältig',
    turkish: 'Çeşitli / Çok yönlü',
    english: 'Diverse / Varied',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['abwechslungsreich', 'mannigfaltig'],
    antonyms: ['eintönig', 'monoton'],
    collocations: ['ein vielfältiges Angebot', 'kulturell vielfältig'],
    emoji: '🌈',
    exampleSentence: 'Berlin bietet ein vielfältiges Kulturangebot.',
    exampleTranslation: 'Berlin çeşitli bir kültürel teklif sunuyor.',
    exampleTranslationEn: 'Berlin offers a diverse cultural program.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-23',
    german: 'unentbehrlich',
    turkish: 'Vazgeçilmez',
    english: 'Indispensable',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['unverzichtbar', 'unersetzlich'],
    antonyms: ['entbehrlich', 'überflüssig'],
    collocations: ['ein unentbehrlicher Teil', 'sich unentbehrlich machen'],
    emoji: '🔑',
    exampleSentence: 'Wasser ist für das Leben unentbehrlich.',
    exampleTranslation: 'Su yaşam için vazgeçilmezdir.',
    exampleTranslationEn: 'Water is indispensable for life.',
    category: 'adjectives',
    level: 'B2',
  },
  {
    id: 'adjectives-24',
    german: 'ausschlaggebend',
    turkish: 'Belirleyici',
    english: 'Decisive / Crucial',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['entscheidend', 'maßgeblich'],
    collocations: ['der ausschlaggebende Faktor', 'ausschlaggebend sein'],
    emoji: '⚖️',
    exampleSentence: 'Ihre Erfahrung war ausschlaggebend für die Entscheidung.',
    exampleTranslation: 'Deneyimi karar için belirleyiciydi.',
    exampleTranslationEn: 'Her experience was decisive for the decision.',
    category: 'adjectives',
    level: 'B2',
  },
];
