import { VocabularyWord } from '@/lib/types';
export const bodyWords: VocabularyWord[] = [
  {
    id: 'body-1',
    german: 'Kopf',
    turkish: 'Baş/Kafa',
    english: 'Head',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Köpfe',
    emoji: '🗣️',
    synonyms: ['Haupt'],
    collocations: ['Kopfschmerzen haben', 'den Kopf schütteln', 'von Kopf bis Fuß'],
    exampleSentence: 'Mir tut der Kopf weh.',
    exampleTranslation: 'Başım ağrıyor.',
    exampleTranslationEn: 'My head hurts.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-2',
    german: 'Auge',
    turkish: 'Göz',
    english: 'Eye',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Augen',
    emoji: '👁️',
    collocations: ['ins Auge fallen', 'die Augen schließen', 'blaue Augen haben'],
    exampleSentence: 'Sie hat blaue Augen.',
    exampleTranslation: 'Mavi gözleri var.',
    exampleTranslationEn: 'She has blue eyes.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-3',
    german: 'Nase',
    turkish: 'Burun',
    english: 'Nose',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Nasen',
    emoji: '👃',
    collocations: ['die Nase putzen', 'eine verstopfte Nase haben'],
    exampleSentence: 'Meine Nase ist kalt.',
    exampleTranslation: 'Burnum soğuk.',
    exampleTranslationEn: 'My nose is cold.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-4',
    german: 'Mund',
    turkish: 'Ağız',
    english: 'Mouth',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Münder',
    emoji: '👄',
    synonyms: ['Maul'],
    collocations: ['den Mund öffnen', 'den Mund halten'],
    exampleSentence: 'Öffne den Mund!',
    exampleTranslation: 'Ağzını aç!',
    exampleTranslationEn: 'Open your mouth!',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-5',
    german: 'Hand',
    turkish: 'El',
    english: 'Hand',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Hände',
    emoji: '✋',
    collocations: ['die Hand geben', 'Hände waschen', 'in der Hand halten'],
    exampleSentence: 'Wasch dir die Hände!',
    exampleTranslation: 'Ellerini yıka!',
    exampleTranslationEn: 'Wash your hands!',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-6',
    german: 'Arm',
    turkish: 'Kol',
    english: 'Arm',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Arme',
    emoji: '💪',
    collocations: ['den Arm heben', 'jemanden in den Arm nehmen', 'den Arm brechen'],
    exampleSentence: 'Mein Arm tut weh.',
    exampleTranslation: 'Kolum ağrıyor.',
    exampleTranslationEn: 'My arm hurts.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-7',
    german: 'Bein',
    turkish: 'Bacak',
    english: 'Leg',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Beine',
    emoji: '🦵',
    collocations: ['die Beine übereinanderschlagen', 'auf den Beinen sein'],
    exampleSentence: 'Ich habe lange Beine.',
    exampleTranslation: 'Uzun bacaklarım var.',
    exampleTranslationEn: 'I have long legs.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-8',
    german: 'Fuß',
    turkish: 'Ayak',
    english: 'Foot',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Füße',
    emoji: '🦶',
    collocations: ['zu Fuß gehen', 'auf großem Fuß leben', 'kalte Füße haben'],
    exampleSentence: 'Mein Fuß schmerzt.',
    exampleTranslation: 'Ayağım ağrıyor.',
    exampleTranslationEn: 'My foot hurts.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-9',
    german: 'Herz',
    turkish: 'Kalp',
    english: 'Heart',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Herzen',
    emoji: '❤️',
    collocations: ['das Herz schlägt', 'ein gutes Herz haben', 'sich etwas zu Herzen nehmen'],
    exampleSentence: 'Das Herz schlägt schnell.',
    exampleTranslation: 'Kalp hızlı atıyor.',
    exampleTranslationEn: 'The heart is beating fast.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-10',
    german: 'Arzt',
    turkish: 'Doktor',
    english: 'Doctor',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Ärzte',
    emoji: '👨‍⚕️',
    synonyms: ['Doktor', 'Mediziner'],
    collocations: ['zum Arzt gehen', 'einen Arzt aufsuchen', 'den Arzt rufen'],
    exampleSentence: 'Ich muss zum Arzt gehen.',
    exampleTranslation: 'Doktora gitmem gerek.',
    exampleTranslationEn: 'I have to go to the doctor.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-11',
    german: 'Krankenhaus',
    turkish: 'Hastane',
    english: 'Hospital',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Krankenhäuser',
    emoji: '🏥',
    synonyms: ['Klinik', 'Spital'],
    collocations: ['ins Krankenhaus kommen', 'im Krankenhaus liegen', 'aus dem Krankenhaus entlassen werden'],
    exampleSentence: 'Das Krankenhaus ist in der Nähe.',
    exampleTranslation: 'Hastane yakında.',
    exampleTranslationEn: 'The hospital is nearby.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-12',
    german: 'krank',
    turkish: 'hasta',
    english: 'Sick/Ill',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🤒',
    synonyms: ['unwohl'],
    antonyms: ['gesund'],
    collocations: ['krank sein', 'krank werden', 'sich krank melden'],
    exampleSentence: 'Ich bin krank.',
    exampleTranslation: 'Hastayım.',
    exampleTranslationEn: 'I am sick.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-13',
    german: 'gesund',
    turkish: 'sağlıklı',
    english: 'Healthy',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '💚',
    antonyms: ['krank'],
    collocations: ['gesund bleiben', 'gesund werden', 'gesund leben'],
    exampleSentence: 'Bleib gesund!',
    exampleTranslation: 'Sağlıklı kal!',
    exampleTranslationEn: 'Stay healthy!',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-14',
    german: 'Schmerzen',
    turkish: 'Ağrı',
    english: 'Pain',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    emoji: '😣',
    synonyms: ['Weh', 'Leid'],
    collocations: ['Schmerzen haben', 'vor Schmerzen schreien', 'Schmerzen lindern'],
    exampleSentence: 'Ich habe Schmerzen.',
    exampleTranslation: 'Ağrım var.',
    exampleTranslationEn: 'I am in pain.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-15',
    german: 'Medikament',
    turkish: 'İlaç',
    english: 'Medication/Medicine',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Medikamente',
    emoji: '💊',
    synonyms: ['Arznei', 'Arzneimittel'],
    collocations: ['ein Medikament nehmen', 'ein Medikament verschreiben', 'Medikamente einnehmen'],
    exampleSentence: 'Nehmen Sie das Medikament!',
    exampleTranslation: 'İlacı alın!',
    exampleTranslationEn: 'Take the medication!',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-16',
    german: 'Behandlung',
    turkish: 'Tedavi',
    english: 'Treatment',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Behandlungen',
    emoji: '🩺',
    synonyms: ['Therapie', 'Heilbehandlung'],
    collocations: ['eine Behandlung beginnen', 'in Behandlung sein', 'die Behandlung abschließen'],
    exampleSentence: 'Die Behandlung dauert mehrere Wochen und erfordert regelmäßige Arztbesuche.',
    exampleTranslation: 'Tedavi birkaç hafta sürer ve düzenli doktor ziyaretleri gerektirir.',
    exampleTranslationEn: 'The treatment lasts several weeks and requires regular doctor visits.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-17',
    german: 'Diagnose',
    turkish: 'Teşhis/Tanı',
    english: 'Diagnosis',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Diagnosen',
    emoji: '🔬',
    synonyms: ['Befund', 'Feststellung'],
    collocations: ['eine Diagnose stellen', 'die Diagnose bestätigen', 'eine schwierige Diagnose'],
    exampleSentence: 'Der Arzt hat nach gründlicher Untersuchung eine genaue Diagnose gestellt.',
    exampleTranslation: 'Doktor kapsamlı bir muayeneden sonra kesin bir teşhis koydu.',
    exampleTranslationEn: 'The doctor made an accurate diagnosis after a thorough examination.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-18',
    german: 'Nebenwirkung',
    turkish: 'Yan etki',
    english: 'Side effect',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Nebenwirkungen',
    emoji: '⚠️',
    synonyms: ['unerwünschte Wirkung'],
    collocations: ['Nebenwirkungen haben', 'mögliche Nebenwirkungen', 'ohne Nebenwirkungen'],
    exampleSentence: 'Dieses Medikament kann unangenehme Nebenwirkungen wie Übelkeit und Schwindel verursachen.',
    exampleTranslation: 'Bu ilaç mide bulantısı ve baş dönmesi gibi hoş olmayan yan etkilere neden olabilir.',
    exampleTranslationEn: 'This medication can cause unpleasant side effects such as nausea and dizziness.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-19',
    german: 'Symptom',
    turkish: 'Belirti/Semptom',
    english: 'Symptom',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Symptome',
    emoji: '🤧',
    synonyms: ['Anzeichen', 'Krankheitszeichen'],
    collocations: ['Symptome zeigen', 'typische Symptome', 'Symptome behandeln'],
    exampleSentence: 'Wenn die Symptome länger als drei Tage anhalten, sollten Sie einen Arzt aufsuchen.',
    exampleTranslation: 'Belirtiler üç günden fazla devam ederse bir doktora başvurmalısınız.',
    exampleTranslationEn: 'If the symptoms persist for more than three days, you should see a doctor.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-20',
    german: 'Blutdruck',
    turkish: 'Tansiyon/Kan basıncı',
    english: 'Blood pressure',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '💉',
    synonyms: ['Blutdruckwert'],
    antonyms: [],
    collocations: ['den Blutdruck messen', 'hoher Blutdruck', 'niedriger Blutdruck'],
    exampleSentence: 'Der Arzt hat meinen Blutdruck gemessen und festgestellt, dass er zu hoch ist.',
    exampleTranslation: 'Doktor tansiyonumu ölçtü ve çok yüksek olduğunu tespit etti.',
    exampleTranslationEn: 'The doctor measured my blood pressure and found that it is too high.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-21',
    german: 'Impfung',
    turkish: 'Aşı/Aşılama',
    english: 'Vaccination',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Impfungen',
    emoji: '💉',
    synonyms: ['Vakzination', 'Schutzimpfung'],
    collocations: ['eine Impfung bekommen', 'sich impfen lassen', 'die Impfung auffrischen'],
    exampleSentence: 'Vor der Reise sollte man sich über die empfohlenen Impfungen informieren.',
    exampleTranslation: 'Seyahat öncesinde önerilen aşılar hakkında bilgi edinilmelidir.',
    exampleTranslationEn: 'Before traveling, one should find out about the recommended vaccinations.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-22',
    german: 'Allergie',
    turkish: 'Alerji',
    english: 'Allergy',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Allergien',
    emoji: '🤧',
    synonyms: ['Überempfindlichkeit'],
    collocations: ['eine Allergie haben', 'allergisch reagieren', 'eine Allergie auslösen'],
    exampleSentence: 'Viele Menschen leiden unter einer Allergie gegen Pollen oder Hausstaubmilben.',
    exampleTranslation: 'Birçok insan polen veya toz akarlarına karşı alerjiden muzdariptir.',
    exampleTranslationEn: 'Many people suffer from an allergy to pollen or dust mites.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-23',
    german: 'Überweisung',
    turkish: 'Sevk',
    english: 'Referral',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Überweisungen',
    emoji: '📋',
    collocations: ['eine Überweisung ausstellen', 'eine Überweisung zum Facharzt', 'mit Überweisung kommen'],
    exampleSentence: 'Mein Hausarzt hat mir eine Überweisung zum Facharzt für Orthopädie ausgestellt.',
    exampleTranslation: 'Aile doktorum beni ortopedi uzmanına sevk etti.',
    exampleTranslationEn: 'My family doctor gave me a referral to the orthopedic specialist.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-24',
    german: 'Notaufnahme',
    turkish: 'Acil servis',
    english: 'Emergency room',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Notaufnahmen',
    emoji: '🚑',
    synonyms: ['Notfallambulanz', 'Erste Hilfe'],
    collocations: ['in die Notaufnahme fahren', 'in der Notaufnahme warten', 'die Notaufnahme aufsuchen'],
    exampleSentence: 'Nach dem Unfall wurde er sofort in die Notaufnahme gebracht.',
    exampleTranslation: 'Kazadan sonra hemen acil servise götürüldü.',
    exampleTranslationEn: 'After the accident, he was immediately taken to the emergency room.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-25',
    german: 'Therapie',
    turkish: 'Terapi',
    english: 'Therapy',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Therapien',
    emoji: '🧠',
    synonyms: ['Behandlung', 'Heilverfahren'],
    collocations: ['eine Therapie machen', 'eine Therapie beginnen', 'die Therapie abbrechen'],
    exampleSentence: 'Nach der Operation hat sie eine intensive Therapie begonnen, um wieder laufen zu können.',
    exampleTranslation: 'Ameliyattan sonra tekrar yürüyebilmek için yoğun bir terapiye başladı.',
    exampleTranslationEn: 'After the surgery, she began intensive therapy in order to be able to walk again.',
    category: 'body',
    level: 'B2',
  },
];
