import { VocabularyWord } from '@/lib/types';
export const bodyWords: VocabularyWord[] = [
  {
    id: 'body-1',
    german: 'Kopf',
    turkish: 'Baş/Kafa',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Köpfe',
    emoji: '🗣️',
    synonyms: ['Haupt'],
    collocations: ['Kopfschmerzen haben', 'den Kopf schütteln', 'von Kopf bis Fuß'],
    exampleSentence: 'Mir tut der Kopf weh.',
    exampleTranslation: 'Başım ağrıyor.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-2',
    german: 'Auge',
    turkish: 'Göz',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Augen',
    emoji: '👁️',
    collocations: ['ins Auge fallen', 'die Augen schließen', 'blaue Augen haben'],
    exampleSentence: 'Sie hat blaue Augen.',
    exampleTranslation: 'Mavi gözleri var.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-3',
    german: 'Nase',
    turkish: 'Burun',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Nasen',
    emoji: '👃',
    collocations: ['die Nase putzen', 'eine verstopfte Nase haben'],
    exampleSentence: 'Meine Nase ist kalt.',
    exampleTranslation: 'Burnum soğuk.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-4',
    german: 'Mund',
    turkish: 'Ağız',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Münder',
    emoji: '👄',
    synonyms: ['Maul'],
    collocations: ['den Mund öffnen', 'den Mund halten'],
    exampleSentence: 'Öffne den Mund!',
    exampleTranslation: 'Ağzını aç!',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-5',
    german: 'Hand',
    turkish: 'El',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Hände',
    emoji: '✋',
    collocations: ['die Hand geben', 'Hände waschen', 'in der Hand halten'],
    exampleSentence: 'Wasch dir die Hände!',
    exampleTranslation: 'Ellerini yıka!',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-6',
    german: 'Arm',
    turkish: 'Kol',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Arme',
    emoji: '💪',
    collocations: ['den Arm heben', 'jemanden in den Arm nehmen', 'den Arm brechen'],
    exampleSentence: 'Mein Arm tut weh.',
    exampleTranslation: 'Kolum ağrıyor.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-7',
    german: 'Bein',
    turkish: 'Bacak',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Beine',
    emoji: '🦵',
    collocations: ['die Beine übereinanderschlagen', 'auf den Beinen sein'],
    exampleSentence: 'Ich habe lange Beine.',
    exampleTranslation: 'Uzun bacaklarım var.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-8',
    german: 'Fuß',
    turkish: 'Ayak',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Füße',
    emoji: '🦶',
    collocations: ['zu Fuß gehen', 'auf großem Fuß leben', 'kalte Füße haben'],
    exampleSentence: 'Mein Fuß schmerzt.',
    exampleTranslation: 'Ayağım ağrıyor.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-9',
    german: 'Herz',
    turkish: 'Kalp',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Herzen',
    emoji: '❤️',
    collocations: ['das Herz schlägt', 'ein gutes Herz haben', 'sich etwas zu Herzen nehmen'],
    exampleSentence: 'Das Herz schlägt schnell.',
    exampleTranslation: 'Kalp hızlı atıyor.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-10',
    german: 'Arzt',
    turkish: 'Doktor',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Ärzte',
    emoji: '👨‍⚕️',
    synonyms: ['Doktor', 'Mediziner'],
    collocations: ['zum Arzt gehen', 'einen Arzt aufsuchen', 'den Arzt rufen'],
    exampleSentence: 'Ich muss zum Arzt gehen.',
    exampleTranslation: 'Doktora gitmem gerek.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-11',
    german: 'Krankenhaus',
    turkish: 'Hastane',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Krankenhäuser',
    emoji: '🏥',
    synonyms: ['Klinik', 'Spital'],
    collocations: ['ins Krankenhaus kommen', 'im Krankenhaus liegen', 'aus dem Krankenhaus entlassen werden'],
    exampleSentence: 'Das Krankenhaus ist in der Nähe.',
    exampleTranslation: 'Hastane yakında.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-12',
    german: 'krank',
    turkish: 'hasta',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🤒',
    synonyms: ['unwohl'],
    antonyms: ['gesund'],
    collocations: ['krank sein', 'krank werden', 'sich krank melden'],
    exampleSentence: 'Ich bin krank.',
    exampleTranslation: 'Hastayım.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-13',
    german: 'gesund',
    turkish: 'sağlıklı',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '💚',
    antonyms: ['krank'],
    collocations: ['gesund bleiben', 'gesund werden', 'gesund leben'],
    exampleSentence: 'Bleib gesund!',
    exampleTranslation: 'Sağlıklı kal!',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-14',
    german: 'Schmerzen',
    turkish: 'Ağrı',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    emoji: '😣',
    synonyms: ['Weh', 'Leid'],
    collocations: ['Schmerzen haben', 'vor Schmerzen schreien', 'Schmerzen lindern'],
    exampleSentence: 'Ich habe Schmerzen.',
    exampleTranslation: 'Ağrım var.',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-15',
    german: 'Medikament',
    turkish: 'İlaç',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Medikamente',
    emoji: '💊',
    synonyms: ['Arznei', 'Arzneimittel'],
    collocations: ['ein Medikament nehmen', 'ein Medikament verschreiben', 'Medikamente einnehmen'],
    exampleSentence: 'Nehmen Sie das Medikament!',
    exampleTranslation: 'İlacı alın!',
    category: 'body',
    level: 'A1',
  },
  {
    id: 'body-16',
    german: 'Behandlung',
    turkish: 'Tedavi',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Behandlungen',
    emoji: '🩺',
    synonyms: ['Therapie', 'Heilbehandlung'],
    collocations: ['eine Behandlung beginnen', 'in Behandlung sein', 'die Behandlung abschließen'],
    exampleSentence: 'Die Behandlung dauert mehrere Wochen und erfordert regelmäßige Arztbesuche.',
    exampleTranslation: 'Tedavi birkaç hafta sürer ve düzenli doktor ziyaretleri gerektirir.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-17',
    german: 'Diagnose',
    turkish: 'Teşhis/Tanı',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Diagnosen',
    emoji: '🔬',
    synonyms: ['Befund', 'Feststellung'],
    collocations: ['eine Diagnose stellen', 'die Diagnose bestätigen', 'eine schwierige Diagnose'],
    exampleSentence: 'Der Arzt hat nach gründlicher Untersuchung eine genaue Diagnose gestellt.',
    exampleTranslation: 'Doktor kapsamlı bir muayeneden sonra kesin bir teşhis koydu.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-18',
    german: 'Nebenwirkung',
    turkish: 'Yan etki',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Nebenwirkungen',
    emoji: '⚠️',
    synonyms: ['unerwünschte Wirkung'],
    collocations: ['Nebenwirkungen haben', 'mögliche Nebenwirkungen', 'ohne Nebenwirkungen'],
    exampleSentence: 'Dieses Medikament kann unangenehme Nebenwirkungen wie Übelkeit und Schwindel verursachen.',
    exampleTranslation: 'Bu ilaç mide bulantısı ve baş dönmesi gibi hoş olmayan yan etkilere neden olabilir.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-19',
    german: 'Symptom',
    turkish: 'Belirti/Semptom',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Symptome',
    emoji: '🤧',
    synonyms: ['Anzeichen', 'Krankheitszeichen'],
    collocations: ['Symptome zeigen', 'typische Symptome', 'Symptome behandeln'],
    exampleSentence: 'Wenn die Symptome länger als drei Tage anhalten, sollten Sie einen Arzt aufsuchen.',
    exampleTranslation: 'Belirtiler üç günden fazla devam ederse bir doktora başvurmalısınız.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-20',
    german: 'Blutdruck',
    turkish: 'Tansiyon/Kan basıncı',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '💉',
    synonyms: ['Blutdruckwert'],
    antonyms: [],
    collocations: ['den Blutdruck messen', 'hoher Blutdruck', 'niedriger Blutdruck'],
    exampleSentence: 'Der Arzt hat meinen Blutdruck gemessen und festgestellt, dass er zu hoch ist.',
    exampleTranslation: 'Doktor tansiyonumu ölçtü ve çok yüksek olduğunu tespit etti.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-21',
    german: 'Impfung',
    turkish: 'Aşı/Aşılama',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Impfungen',
    emoji: '💉',
    synonyms: ['Vakzination', 'Schutzimpfung'],
    collocations: ['eine Impfung bekommen', 'sich impfen lassen', 'die Impfung auffrischen'],
    exampleSentence: 'Vor der Reise sollte man sich über die empfohlenen Impfungen informieren.',
    exampleTranslation: 'Seyahat öncesinde önerilen aşılar hakkında bilgi edinilmelidir.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-22',
    german: 'Allergie',
    turkish: 'Alerji',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Allergien',
    emoji: '🤧',
    synonyms: ['Überempfindlichkeit'],
    collocations: ['eine Allergie haben', 'allergisch reagieren', 'eine Allergie auslösen'],
    exampleSentence: 'Viele Menschen leiden unter einer Allergie gegen Pollen oder Hausstaubmilben.',
    exampleTranslation: 'Birçok insan polen veya toz akarlarına karşı alerjiden muzdariptir.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-23',
    german: 'Überweisung',
    turkish: 'Sevk',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Überweisungen',
    emoji: '📋',
    collocations: ['eine Überweisung ausstellen', 'eine Überweisung zum Facharzt', 'mit Überweisung kommen'],
    exampleSentence: 'Mein Hausarzt hat mir eine Überweisung zum Facharzt für Orthopädie ausgestellt.',
    exampleTranslation: 'Aile doktorum beni ortopedi uzmanına sevk etti.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-24',
    german: 'Notaufnahme',
    turkish: 'Acil servis',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Notaufnahmen',
    emoji: '🚑',
    synonyms: ['Notfallambulanz', 'Erste Hilfe'],
    collocations: ['in die Notaufnahme fahren', 'in der Notaufnahme warten', 'die Notaufnahme aufsuchen'],
    exampleSentence: 'Nach dem Unfall wurde er sofort in die Notaufnahme gebracht.',
    exampleTranslation: 'Kazadan sonra hemen acil servise götürüldü.',
    category: 'body',
    level: 'B2',
  },
  {
    id: 'body-25',
    german: 'Therapie',
    turkish: 'Terapi',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Therapien',
    emoji: '🧠',
    synonyms: ['Behandlung', 'Heilverfahren'],
    collocations: ['eine Therapie machen', 'eine Therapie beginnen', 'die Therapie abbrechen'],
    exampleSentence: 'Nach der Operation hat sie eine intensive Therapie begonnen, um wieder laufen zu können.',
    exampleTranslation: 'Ameliyattan sonra tekrar yürüyebilmek için yoğun bir terapiye başladı.',
    category: 'body',
    level: 'B2',
  },
];
