import { VocabularyWord } from '@/lib/types';

export const clothingWords: VocabularyWord[] = [
  {
    id: 'clothing-1',
    german: 'das Hemd',
    turkish: 'Gömlek',
    english: 'Shirt',
    article: 'das',
    plural: 'Hemden',
    partOfSpeech: 'noun',
    synonyms: ['Oberhemd'],
    collocations: ['ein Hemd anziehen', 'ein weißes Hemd'],
    emoji: '👔',
    exampleSentence: 'Er trägt ein weißes Hemd.',
    exampleTranslation: 'Beyaz bir gömlek giyiyor.',
    exampleTranslationEn: 'He is wearing a white shirt.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-2',
    german: 'die Hose',
    turkish: 'Pantolon',
    english: 'Trousers',
    article: 'die',
    plural: 'Hosen',
    partOfSpeech: 'noun',
    synonyms: ['Jeans', 'Stoffhose'],
    collocations: ['eine Hose anziehen', 'eine neue Hose kaufen'],
    emoji: '👖',
    exampleSentence: 'Diese Hose passt mir gut.',
    exampleTranslation: 'Bu pantolon bana iyi uyuyor.',
    exampleTranslationEn: 'These trousers fit me well.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-3',
    german: 'der Schuh',
    turkish: 'Ayakkabı',
    english: 'Shoe',
    article: 'der',
    plural: 'Schuhe',
    partOfSpeech: 'noun',
    synonyms: ['Stiefel', 'Sneaker'],
    collocations: ['Schuhe anziehen', 'neue Schuhe kaufen'],
    emoji: '👟',
    exampleSentence: 'Ich brauche neue Schuhe.',
    exampleTranslation: 'Yeni ayakkabılara ihtiyacım var.',
    exampleTranslationEn: 'I need new shoes.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-4',
    german: 'die Jacke',
    turkish: 'Ceket',
    english: 'Jacket',
    article: 'die',
    plural: 'Jacken',
    partOfSpeech: 'noun',
    synonyms: ['Mantel', 'Anorak'],
    collocations: ['die Jacke anziehen', 'eine warme Jacke'],
    emoji: '🧥',
    exampleSentence: 'Zieh deine Jacke an, es ist kalt!',
    exampleTranslation: 'Ceketini giy, hava soğuk!',
    exampleTranslationEn: 'Put on your jacket, it\'s cold!',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-5',
    german: 'das Kleid',
    turkish: 'Elbise',
    english: 'Dress',
    article: 'das',
    plural: 'Kleider',
    partOfSpeech: 'noun',
    synonyms: ['Gewand'],
    collocations: ['ein schönes Kleid', 'ein Kleid tragen'],
    emoji: '👗',
    exampleSentence: 'Sie trägt ein rotes Kleid.',
    exampleTranslation: 'Kırmızı bir elbise giyiyor.',
    exampleTranslationEn: 'She is wearing a red dress.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-6',
    german: 'der Hut',
    turkish: 'Şapka',
    english: 'Hat',
    article: 'der',
    plural: 'Hüte',
    partOfSpeech: 'noun',
    synonyms: ['Mütze', 'Kappe'],
    collocations: ['einen Hut tragen', 'den Hut aufsetzen'],
    emoji: '🎩',
    exampleSentence: 'Der Hut steht dir gut!',
    exampleTranslation: 'Şapka sana çok yakışıyor!',
    exampleTranslationEn: 'The hat looks good on you!',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-7',
    german: 'die Socke',
    turkish: 'Çorap',
    english: 'Sock',
    article: 'die',
    plural: 'Socken',
    partOfSpeech: 'noun',
    synonyms: ['Strumpf'],
    collocations: ['warme Socken', 'Socken anziehen'],
    emoji: '🧦',
    exampleSentence: 'Wo ist meine zweite Socke?',
    exampleTranslation: 'Diğer çorabım nerede?',
    exampleTranslationEn: 'Where is my other sock?',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-8',
    german: 'der Pullover',
    turkish: 'Kazak',
    english: 'Sweater',
    article: 'der',
    plural: 'Pullover',
    partOfSpeech: 'noun',
    synonyms: ['Pulli', 'Strickjacke'],
    collocations: ['einen Pullover tragen', 'einen warmen Pullover'],
    emoji: '🧶',
    exampleSentence: 'Dieser Pullover ist sehr warm.',
    exampleTranslation: 'Bu kazak çok sıcak.',
    exampleTranslationEn: 'This sweater is very warm.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-9',
    german: 'der Rock',
    turkish: 'Etek',
    english: 'Skirt',
    article: 'der',
    plural: 'Röcke',
    partOfSpeech: 'noun',
    synonyms: ['Minirock'],
    collocations: ['einen Rock tragen', 'ein kurzer Rock'],
    emoji: '👗',
    exampleSentence: 'Der Rock ist sehr elegant.',
    exampleTranslation: 'Etek çok şık.',
    exampleTranslationEn: 'The skirt is very elegant.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-10',
    german: 'der Gürtel',
    turkish: 'Kemer',
    english: 'Belt',
    article: 'der',
    plural: 'Gürtel',
    partOfSpeech: 'noun',
    synonyms: ['Ledergürtel'],
    collocations: ['einen Gürtel tragen', 'den Gürtel enger schnallen'],
    emoji: '👔',
    exampleSentence: 'Der Gürtel passt gut zur Hose.',
    exampleTranslation: 'Kemer pantolona çok yakışıyor.',
    exampleTranslationEn: 'The belt goes well with the trousers.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-11',
    german: 'die Bluse',
    turkish: 'Bluz',
    english: 'Blouse',
    article: 'die',
    plural: 'Blusen',
    partOfSpeech: 'noun',
    synonyms: ['Damenhemd'],
    collocations: ['eine Bluse anziehen', 'eine seidene Bluse'],
    emoji: '👚',
    exampleSentence: 'Die Bluse ist aus Seide.',
    exampleTranslation: 'Bluz ipekten yapılmış.',
    exampleTranslationEn: 'The blouse is made of silk.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-12',
    german: 'der Schal',
    turkish: 'Atkı / Şal',
    english: 'Scarf',
    article: 'der',
    plural: 'Schals',
    partOfSpeech: 'noun',
    synonyms: ['Tuch', 'Halstuch'],
    collocations: ['einen Schal tragen', 'einen warmen Schal'],
    emoji: '🧣',
    exampleSentence: 'Im Winter trage ich immer einen Schal.',
    exampleTranslation: 'Kışın hep atkı takarım.',
    exampleTranslationEn: 'In winter I always wear a scarf.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-13',
    german: 'die Handschuhe',
    turkish: 'Eldiven',
    english: 'Gloves',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Fäustlinge'],
    collocations: ['Handschuhe anziehen', 'warme Handschuhe'],
    emoji: '🧤',
    exampleSentence: 'Vergiss deine Handschuhe nicht!',
    exampleTranslation: 'Eldivenlerini unutma!',
    exampleTranslationEn: 'Don\'t forget your gloves!',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-14',
    german: 'der Anzug',
    turkish: 'Takım elbise',
    english: 'Suit',
    article: 'der',
    plural: 'Anzüge',
    partOfSpeech: 'noun',
    synonyms: ['Kostüm'],
    collocations: ['einen Anzug tragen', 'ein eleganter Anzug'],
    emoji: '🤵',
    exampleSentence: 'Für das Vorstellungsgespräch trage ich einen Anzug.',
    exampleTranslation: 'İş görüşmesi için takım elbise giyiyorum.',
    exampleTranslationEn: 'I wear a suit for the job interview.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-15',
    german: 'die Krawatte',
    turkish: 'Kravat',
    english: 'Tie',
    article: 'die',
    plural: 'Krawatten',
    partOfSpeech: 'noun',
    synonyms: ['Schlips', 'Binder'],
    collocations: ['eine Krawatte binden', 'eine Krawatte tragen'],
    emoji: '👔',
    exampleSentence: 'Kannst du dir eine Krawatte binden?',
    exampleTranslation: 'Kravat bağlayabiliyor musun?',
    exampleTranslationEn: 'Can you tie a tie?',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-16',
    german: 'der Badeanzug',
    turkish: 'Mayo',
    english: 'Swimsuit',
    article: 'der',
    plural: 'Badeanzüge',
    partOfSpeech: 'noun',
    synonyms: ['Bikini', 'Badehose'],
    collocations: ['einen Badeanzug tragen', 'einen neuen Badeanzug kaufen'],
    emoji: '👙',
    exampleSentence: 'Hast du deinen Badeanzug eingepackt?',
    exampleTranslation: 'Mayonu hazırladın mı?',
    exampleTranslationEn: 'Did you pack your swimsuit?',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-17',
    german: 'der Stoff',
    turkish: 'Kumaş',
    english: 'Fabric',
    article: 'der',
    plural: 'Stoffe',
    partOfSpeech: 'noun',
    synonyms: ['Material', 'Textil'],
    collocations: ['weicher Stoff', 'der Stoff fühlt sich gut an'],
    emoji: '🧵',
    exampleSentence: 'Dieser Stoff fühlt sich sehr weich an.',
    exampleTranslation: 'Bu kumaş çok yumuşak hissettiriyor.',
    exampleTranslationEn: 'This fabric feels very soft.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-18',
    german: 'die Garderobe',
    turkish: 'Gardırop',
    english: 'Wardrobe / Cloakroom',
    article: 'die',
    plural: 'Garderoben',
    partOfSpeech: 'noun',
    synonyms: ['Kleiderschrank'],
    collocations: ['die Garderobe aufräumen', 'an der Garderobe abgeben'],
    emoji: '🚪',
    exampleSentence: 'Bitte geben Sie Ihren Mantel an der Garderobe ab.',
    exampleTranslation: 'Lütfen paltonuzu vestiyere bırakın.',
    exampleTranslationEn: 'Please leave your coat at the cloakroom.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-19',
    german: 'die Maßanfertigung',
    turkish: 'Ismarlama / Özel dikim',
    english: 'Custom-made / Tailored',
    article: 'die',
    plural: 'Maßanfertigungen',
    partOfSpeech: 'noun',
    synonyms: ['Maßkleidung', 'Sonderanfertigung'],
    collocations: ['eine Maßanfertigung bestellen', 'in Maßanfertigung'],
    emoji: '✂️',
    exampleSentence: 'Der Anzug ist eine Maßanfertigung vom besten Schneider.',
    exampleTranslation: 'Takım elbise en iyi terziden ısmarlama.',
    exampleTranslationEn: 'The suit is custom-made by the best tailor.',
    category: 'clothing',
    level: 'B2',
  },
  {
    id: 'clothing-20',
    german: 'die Nachhaltigkeit',
    turkish: 'Sürdürülebilirlik',
    english: 'Sustainability',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Dauerhaftigkeit'],
    collocations: ['nachhaltige Mode', 'auf Nachhaltigkeit achten'],
    emoji: '♻️',
    exampleSentence: 'Nachhaltigkeit in der Modeindustrie wird immer wichtiger.',
    exampleTranslation: 'Moda endüstrisinde sürdürülebilirlik giderek önem kazanıyor.',
    exampleTranslationEn: 'Sustainability in the fashion industry is becoming more important.',
    category: 'clothing',
    level: 'B2',
  },
  {
    id: 'clothing-21',
    german: 'das T-Shirt',
    turkish: 'Tişört',
    english: 'T-shirt',
    article: 'das',
    plural: 'T-Shirts',
    partOfSpeech: 'noun',
    collocations: ['ein T-Shirt anziehen', 'ein weißes T-Shirt'],
    emoji: '👕',
    exampleSentence: 'Im Sommer trage ich gern T-Shirts.',
    exampleTranslation: 'Yazın tişört giymeyi severim.',
    exampleTranslationEn: 'In summer I like to wear T-shirts.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-22',
    german: 'die Jeans',
    turkish: 'Kot pantolon',
    english: 'Jeans',
    article: 'die',
    plural: 'Jeans',
    partOfSpeech: 'noun',
    collocations: ['eine Jeans tragen', 'blaue Jeans'],
    emoji: '👖',
    exampleSentence: 'Ich trage am liebsten Jeans.',
    exampleTranslation: 'En çok kot pantolon giymeyi severim.',
    exampleTranslationEn: 'I prefer wearing jeans.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-23',
    german: 'der Mantel',
    turkish: 'Palto',
    english: 'Coat',
    article: 'der',
    plural: 'Mäntel',
    partOfSpeech: 'noun',
    synonyms: ['Wintermantel'],
    collocations: ['einen Mantel tragen', 'einen warmen Mantel'],
    emoji: '🧥',
    exampleSentence: 'Vergiss deinen Mantel nicht, es ist kalt!',
    exampleTranslation: 'Paltonu unutma, hava soğuk!',
    exampleTranslationEn: 'Don\'t forget your coat, it\'s cold!',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-24',
    german: 'die Mütze',
    turkish: 'Bere',
    english: 'Beanie / Cap',
    article: 'die',
    plural: 'Mützen',
    partOfSpeech: 'noun',
    synonyms: ['Kappe'],
    collocations: ['eine Mütze aufsetzen', 'eine warme Mütze'],
    emoji: '🧢',
    exampleSentence: 'Setz deine Mütze auf, es ist kalt.',
    exampleTranslation: 'Bereni tak, hava soğuk.',
    exampleTranslationEn: 'Put on your beanie, it\'s cold.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-25',
    german: 'die Unterwäsche',
    turkish: 'İç çamaşırı',
    english: 'Underwear',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Unterhose', 'Slip'],
    collocations: ['saubere Unterwäsche', 'Unterwäsche wechseln'],
    emoji: '🩲',
    exampleSentence: 'Ich muss neue Unterwäsche kaufen.',
    exampleTranslation: 'Yeni iç çamaşırı almam lazım.',
    exampleTranslationEn: 'I need to buy new underwear.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-26',
    german: 'der Stiefel',
    turkish: 'Çizme',
    english: 'Boot',
    article: 'der',
    plural: 'Stiefel',
    partOfSpeech: 'noun',
    synonyms: ['Winterstiefel'],
    collocations: ['Stiefel anziehen', 'warme Stiefel'],
    emoji: '👢',
    exampleSentence: 'Im Winter trage ich Stiefel.',
    exampleTranslation: 'Kışın çizme giyerim.',
    exampleTranslationEn: 'In winter I wear boots.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-27',
    german: 'die Sandale',
    turkish: 'Sandalet',
    english: 'Sandal',
    article: 'die',
    plural: 'Sandalen',
    partOfSpeech: 'noun',
    collocations: ['Sandalen tragen', 'offene Sandalen'],
    emoji: '🩴',
    exampleSentence: 'Im Sommer trage ich Sandalen.',
    exampleTranslation: 'Yazın sandalet giyerim.',
    exampleTranslationEn: 'In summer I wear sandals.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-28',
    german: 'die Shorts',
    turkish: 'Şort',
    english: 'Shorts',
    article: 'die',
    plural: 'Shorts',
    partOfSpeech: 'noun',
    synonyms: ['kurze Hose'],
    collocations: ['Shorts tragen', 'kurze Shorts'],
    emoji: '🩳',
    exampleSentence: 'Es ist heiß, ich ziehe Shorts an.',
    exampleTranslation: 'Hava sıcak, şort giyiyorum.',
    exampleTranslationEn: 'It\'s hot, I\'m putting on shorts.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-29',
    german: 'die Weste',
    turkish: 'Yelek',
    english: 'Vest / Waistcoat',
    article: 'die',
    plural: 'Westen',
    partOfSpeech: 'noun',
    collocations: ['eine Weste tragen', 'eine Daunenweste'],
    emoji: '🦺',
    exampleSentence: 'Er trägt eine elegante Weste.',
    exampleTranslation: 'Şık bir yelek giyiyor.',
    exampleTranslationEn: 'He is wearing an elegant vest.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-30',
    german: 'der Regenmantel',
    turkish: 'Yağmurluk',
    english: 'Raincoat',
    article: 'der',
    plural: 'Regenmäntel',
    partOfSpeech: 'noun',
    synonyms: ['Regenjacke'],
    collocations: ['einen Regenmantel anziehen', 'wasserdichter Regenmantel'],
    emoji: '🌧️',
    exampleSentence: 'Nimm deinen Regenmantel mit, es regnet.',
    exampleTranslation: 'Yağmurluğunu al, yağmur yağıyor.',
    exampleTranslationEn: 'Take your raincoat, it\'s raining.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-31',
    german: 'der Pyjama',
    turkish: 'Pijama',
    english: 'Pajamas',
    article: 'der',
    plural: 'Pyjamas',
    partOfSpeech: 'noun',
    synonyms: ['Schlafanzug'],
    collocations: ['Pyjama anziehen', 'im Pyjama'],
    emoji: '😴',
    exampleSentence: 'Ich ziehe meinen Pyjama an und gehe ins Bett.',
    exampleTranslation: 'Pijamamı giyip yatağa gidiyorum.',
    exampleTranslationEn: 'I put on my pajamas and go to bed.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-32',
    german: 'die Sonnenbrille',
    turkish: 'Güneş gözlüğü',
    english: 'Sunglasses',
    article: 'die',
    plural: 'Sonnenbrillen',
    partOfSpeech: 'noun',
    collocations: ['Sonnenbrille tragen', 'eine neue Sonnenbrille'],
    emoji: '🕶️',
    exampleSentence: 'Vergiss deine Sonnenbrille nicht!',
    exampleTranslation: 'Güneş gözlüğünü unutma!',
    exampleTranslationEn: 'Don\'t forget your sunglasses!',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-33',
    german: 'der Regenschirm',
    turkish: 'Şemsiye',
    english: 'Umbrella',
    article: 'der',
    plural: 'Regenschirme',
    partOfSpeech: 'noun',
    synonyms: ['Schirm'],
    collocations: ['einen Regenschirm mitnehmen', 'den Regenschirm aufspannen'],
    emoji: '☂️',
    exampleSentence: 'Nimm einen Regenschirm mit!',
    exampleTranslation: 'Şemsiye al!',
    exampleTranslationEn: 'Take an umbrella with you!',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-34',
    german: 'der Knopf',
    turkish: 'Düğme',
    english: 'Button',
    article: 'der',
    plural: 'Knöpfe',
    partOfSpeech: 'noun',
    collocations: ['einen Knopf annähen', 'den Knopf schließen'],
    emoji: '🔘',
    exampleSentence: 'Ein Knopf ist abgefallen.',
    exampleTranslation: 'Bir düğme düştü.',
    exampleTranslationEn: 'A button fell off.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-35',
    german: 'der Reißverschluss',
    turkish: 'Fermuar',
    english: 'Zipper',
    article: 'der',
    plural: 'Reißverschlüsse',
    partOfSpeech: 'noun',
    collocations: ['den Reißverschluss schließen', 'der Reißverschluss klemmt'],
    emoji: '🔗',
    exampleSentence: 'Der Reißverschluss ist kaputt.',
    exampleTranslation: 'Fermuar bozuldu.',
    exampleTranslationEn: 'The zipper is broken.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-36',
    german: 'die Tasche',
    turkish: 'Çanta',
    english: 'Bag / Pocket',
    article: 'die',
    plural: 'Taschen',
    partOfSpeech: 'noun',
    synonyms: ['Handtasche', 'Beutel'],
    collocations: ['eine Tasche tragen', 'in der Tasche'],
    emoji: '👜',
    exampleSentence: 'Hast du deine Tasche dabei?',
    exampleTranslation: 'Çantan yanında mı?',
    exampleTranslationEn: 'Do you have your bag with you?',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-37',
    german: 'der Rucksack',
    turkish: 'Sırt çantası',
    english: 'Backpack',
    article: 'der',
    plural: 'Rucksäcke',
    partOfSpeech: 'noun',
    collocations: ['einen Rucksack tragen', 'den Rucksack packen'],
    emoji: '🎒',
    exampleSentence: 'Ich packe meinen Rucksack für die Wanderung.',
    exampleTranslation: 'Yürüyüş için sırt çantamı hazırlıyorum.',
    exampleTranslationEn: 'I am packing my backpack for the hike.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-38',
    german: 'die Brille',
    turkish: 'Gözlük',
    english: 'Glasses',
    article: 'die',
    plural: 'Brillen',
    partOfSpeech: 'noun',
    collocations: ['eine Brille tragen', 'die Brille aufsetzen'],
    emoji: '👓',
    exampleSentence: 'Ohne Brille kann ich nichts sehen.',
    exampleTranslation: 'Gözlüksüz hiçbir şey göremiyorum.',
    exampleTranslationEn: 'Without glasses I can\'t see anything.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-39',
    german: 'die Kette',
    turkish: 'Kolye / Zincir',
    english: 'Necklace / Chain',
    article: 'die',
    plural: 'Ketten',
    partOfSpeech: 'noun',
    synonyms: ['Halskette'],
    collocations: ['eine Kette tragen', 'goldene Kette'],
    emoji: '📿',
    exampleSentence: 'Sie trägt eine goldene Kette.',
    exampleTranslation: 'Altın bir kolye takıyor.',
    exampleTranslationEn: 'She is wearing a gold necklace.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-40',
    german: 'der Ring',
    turkish: 'Yüzük',
    english: 'Ring',
    article: 'der',
    plural: 'Ringe',
    partOfSpeech: 'noun',
    synonyms: ['Fingerring'],
    collocations: ['einen Ring tragen', 'ein goldener Ring'],
    emoji: '💍',
    exampleSentence: 'Er hat ihr einen Ring geschenkt.',
    exampleTranslation: 'Ona bir yüzük hediye etti.',
    exampleTranslationEn: 'He gave her a ring as a gift.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-41',
    german: 'die Uhr',
    turkish: 'Saat (kol saati)',
    english: 'Watch',
    article: 'die',
    plural: 'Uhren',
    partOfSpeech: 'noun',
    synonyms: ['Armbanduhr'],
    collocations: ['eine Uhr tragen', 'die Uhr ablesen'],
    emoji: '⌚',
    exampleSentence: 'Meine Uhr ist stehen geblieben.',
    exampleTranslation: 'Saatim durdu.',
    exampleTranslationEn: 'My watch has stopped.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-42',
    german: 'der Ohrring',
    turkish: 'Küpe',
    english: 'Earring',
    article: 'der',
    plural: 'Ohrringe',
    partOfSpeech: 'noun',
    collocations: ['Ohrringe tragen', 'silberne Ohrringe'],
    emoji: '💎',
    exampleSentence: 'Die Ohrringe sind sehr schön.',
    exampleTranslation: 'Küpeler çok güzel.',
    exampleTranslationEn: 'The earrings are very beautiful.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-43',
    german: 'die Lederjacke',
    turkish: 'Deri ceket',
    english: 'Leather jacket',
    article: 'die',
    plural: 'Lederjacken',
    partOfSpeech: 'noun',
    collocations: ['eine Lederjacke tragen', 'schwarze Lederjacke'],
    emoji: '🧥',
    exampleSentence: 'Seine Lederjacke ist sehr cool.',
    exampleTranslation: 'Deri ceketi çok havalı.',
    exampleTranslationEn: 'His leather jacket is very cool.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-44',
    german: 'der Absatz',
    turkish: 'Topuk (ayakkabı)',
    english: 'Heel',
    article: 'der',
    plural: 'Absätze',
    partOfSpeech: 'noun',
    collocations: ['hohe Absätze', 'flache Absätze'],
    emoji: '👠',
    exampleSentence: 'Sie kann nicht auf hohen Absätzen laufen.',
    exampleTranslation: 'Yüksek topuklarla yürüyemiyor.',
    exampleTranslationEn: 'She can\'t walk in high heels.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-45',
    german: 'der Ärmel',
    turkish: 'Kol (giysi)',
    english: 'Sleeve',
    article: 'der',
    plural: 'Ärmel',
    partOfSpeech: 'noun',
    collocations: ['lange Ärmel', 'kurze Ärmel', 'die Ärmel hochkrempeln'],
    emoji: '💪',
    exampleSentence: 'Kremple die Ärmel hoch!',
    exampleTranslation: 'Kollarını sıva!',
    exampleTranslationEn: 'Roll up your sleeves!',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-46',
    german: 'der Kragen',
    turkish: 'Yaka',
    english: 'Collar',
    article: 'der',
    plural: 'Kragen',
    partOfSpeech: 'noun',
    collocations: ['hoher Kragen', 'den Kragen hochstellen'],
    emoji: '👔',
    exampleSentence: 'Das Hemd hat einen weißen Kragen.',
    exampleTranslation: 'Gömleğin beyaz bir yakası var.',
    exampleTranslationEn: 'The shirt has a white collar.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-47',
    german: 'die Kapuze',
    turkish: 'Kapüşon',
    english: 'Hood',
    article: 'die',
    plural: 'Kapuzen',
    partOfSpeech: 'noun',
    collocations: ['die Kapuze aufsetzen', 'Jacke mit Kapuze'],
    emoji: '🧥',
    exampleSentence: 'Setz die Kapuze auf, es regnet.',
    exampleTranslation: 'Kapüşonu tak, yağmur yağıyor.',
    exampleTranslationEn: 'Put on the hood, it\'s raining.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-48',
    german: 'die Größe',
    turkish: 'Beden',
    english: 'Size',
    article: 'die',
    plural: 'Größen',
    partOfSpeech: 'noun',
    collocations: ['welche Größe', 'Größe M', 'die richtige Größe'],
    emoji: '📐',
    exampleSentence: 'Welche Größe haben Sie?',
    exampleTranslation: 'Bedeniniz kaç?',
    exampleTranslationEn: 'What size are you?',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-49',
    german: 'anprobieren',
    turkish: 'Denemek (giysi)',
    english: 'To try on',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['ein Kleid anprobieren', 'Schuhe anprobieren'],
    emoji: '🪞',
    exampleSentence: 'Kann ich das Kleid anprobieren?',
    exampleTranslation: 'Elbiseyi deneyebilir miyim?',
    exampleTranslationEn: 'Can I try on the dress?',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-50',
    german: 'passen',
    turkish: 'Uymak',
    english: 'To fit',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['gut passen', 'nicht passen', 'die Hose passt'],
    emoji: '✅',
    exampleSentence: 'Die Schuhe passen mir perfekt.',
    exampleTranslation: 'Ayakkabılar bana mükemmel uyuyor.',
    exampleTranslationEn: 'The shoes fit me perfectly.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-51',
    german: 'anziehen',
    turkish: 'Giymek',
    english: 'To put on / To dress',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['anlegen'],
    antonyms: ['ausziehen'],
    collocations: ['sich anziehen', 'warm anziehen'],
    emoji: '👔',
    exampleSentence: 'Zieh dich warm an!',
    exampleTranslation: 'Sıcak giyin!',
    exampleTranslationEn: 'Dress warmly!',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-52',
    german: 'ausziehen',
    turkish: 'Çıkarmak (giysi)',
    english: 'To take off',
    article: null,
    partOfSpeech: 'verb',
    antonyms: ['anziehen'],
    collocations: ['die Jacke ausziehen', 'sich ausziehen'],
    emoji: '🚿',
    exampleSentence: 'Zieh bitte die Schuhe aus.',
    exampleTranslation: 'Lütfen ayakkabılarını çıkar.',
    exampleTranslationEn: 'Please take off your shoes.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-53',
    german: 'tragen',
    turkish: 'Giymek / Taşımak',
    english: 'To wear / To carry',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['eine Brille tragen', 'schwarz tragen'],
    emoji: '👗',
    exampleSentence: 'Sie trägt immer Schwarz.',
    exampleTranslation: 'Her zaman siyah giyiyor.',
    exampleTranslationEn: 'She always wears black.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-54',
    german: 'die Wolle',
    turkish: 'Yün',
    english: 'Wool',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['aus Wolle', 'Wollpullover'],
    emoji: '🐑',
    exampleSentence: 'Der Pullover ist aus reiner Wolle.',
    exampleTranslation: 'Kazak saf yünden.',
    exampleTranslationEn: 'The sweater is made of pure wool.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-55',
    german: 'die Seide',
    turkish: 'İpek',
    english: 'Silk',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['aus Seide', 'Seidenkleid'],
    emoji: '✨',
    exampleSentence: 'Das Kleid ist aus echter Seide.',
    exampleTranslation: 'Elbise gerçek ipekten.',
    exampleTranslationEn: 'The dress is made of real silk.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-56',
    german: 'die Baumwolle',
    turkish: 'Pamuk',
    english: 'Cotton',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['aus Baumwolle', 'reine Baumwolle'],
    emoji: '☁️',
    exampleSentence: 'Das T-Shirt ist aus Baumwolle.',
    exampleTranslation: 'Tişört pamuktan.',
    exampleTranslationEn: 'The T-shirt is made of cotton.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-57',
    german: 'das Leder',
    turkish: 'Deri',
    english: 'Leather',
    article: 'das',
    partOfSpeech: 'noun',
    collocations: ['aus Leder', 'echtes Leder'],
    emoji: '🐄',
    exampleSentence: 'Die Tasche ist aus echtem Leder.',
    exampleTranslation: 'Çanta gerçek deriden.',
    exampleTranslationEn: 'The bag is made of real leather.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-58',
    german: 'der Schmuck',
    turkish: 'Takı / Mücevher',
    english: 'Jewelry',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Juwelen'],
    collocations: ['Schmuck tragen', 'teurer Schmuck'],
    emoji: '💎',
    exampleSentence: 'Sie liebt teuren Schmuck.',
    exampleTranslation: 'Pahalı takıları seviyor.',
    exampleTranslationEn: 'She loves expensive jewelry.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-59',
    german: 'die Umkleidekabine',
    turkish: 'Soyunma kabini',
    english: 'Fitting room',
    article: 'die',
    plural: 'Umkleidekabinen',
    partOfSpeech: 'noun',
    collocations: ['in die Umkleidekabine gehen', 'die Umkleidekabine ist frei'],
    emoji: '🚪',
    exampleSentence: 'Wo ist die Umkleidekabine?',
    exampleTranslation: 'Soyunma kabini nerede?',
    exampleTranslationEn: 'Where is the fitting room?',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-60',
    german: 'das Muster',
    turkish: 'Desen',
    english: 'Pattern',
    article: 'das',
    plural: 'Muster',
    partOfSpeech: 'noun',
    collocations: ['ein schönes Muster', 'gestreiftes Muster'],
    emoji: '🎨',
    exampleSentence: 'Das Kleid hat ein schönes Muster.',
    exampleTranslation: 'Elbisenin güzel bir deseni var.',
    exampleTranslationEn: 'The dress has a beautiful pattern.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-61',
    german: 'gestreift',
    turkish: 'Çizgili',
    english: 'Striped',
    article: null,
    partOfSpeech: 'adjective',
    collocations: ['ein gestreiftes Hemd', 'rot-weiß gestreift'],
    emoji: '📏',
    exampleSentence: 'Er trägt ein gestreiftes Hemd.',
    exampleTranslation: 'Çizgili bir gömlek giyiyor.',
    exampleTranslationEn: 'He is wearing a striped shirt.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-62',
    german: 'kariert',
    turkish: 'Ekose / Kareli',
    english: 'Checkered / Plaid',
    article: null,
    partOfSpeech: 'adjective',
    collocations: ['ein kariertes Hemd', 'karierter Rock'],
    emoji: '🏁',
    exampleSentence: 'Sie trägt einen karierten Rock.',
    exampleTranslation: 'Ekose bir etek giyiyor.',
    exampleTranslationEn: 'She is wearing a plaid skirt.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-63',
    german: 'gepunktet',
    turkish: 'Puantiyeli',
    english: 'Dotted / Polka-dotted',
    article: null,
    partOfSpeech: 'adjective',
    collocations: ['ein gepunktetes Kleid', 'rot gepunktet'],
    emoji: '⚫',
    exampleSentence: 'Das Kleid ist rot gepunktet.',
    exampleTranslation: 'Elbise kırmızı puantiyeli.',
    exampleTranslationEn: 'The dress is red with polka dots.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-64',
    german: 'eng',
    turkish: 'Dar',
    english: 'Tight',
    article: null,
    partOfSpeech: 'adjective',
    antonyms: ['weit', 'locker'],
    collocations: ['zu eng', 'eng anliegend'],
    emoji: '🤏',
    exampleSentence: 'Die Hose ist mir zu eng.',
    exampleTranslation: 'Pantolon bana çok dar.',
    exampleTranslationEn: 'The trousers are too tight for me.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-65',
    german: 'weit',
    turkish: 'Bol / Geniş',
    english: 'Wide / Loose',
    article: null,
    partOfSpeech: 'adjective',
    antonyms: ['eng'],
    collocations: ['weite Hose', 'zu weit'],
    emoji: '👘',
    exampleSentence: 'Ich trage gern weite Kleidung.',
    exampleTranslation: 'Bol kıyafetler giymeyi severim.',
    exampleTranslationEn: 'I like to wear loose clothing.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-66',
    german: 'elegant',
    turkish: 'Şık',
    english: 'Elegant',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['schick', 'stilvoll'],
    collocations: ['elegant gekleidet', 'ein elegantes Kleid'],
    emoji: '🎀',
    exampleSentence: 'Du siehst sehr elegant aus.',
    exampleTranslation: 'Çok şık görünüyorsun.',
    exampleTranslationEn: 'You look very elegant.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-67',
    german: 'modisch',
    turkish: 'Modaya uygun',
    english: 'Fashionable',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['trendig', 'modern'],
    antonyms: ['altmodisch'],
    collocations: ['modisch gekleidet', 'modische Kleidung'],
    emoji: '💃',
    exampleSentence: 'Sie ist immer modisch gekleidet.',
    exampleTranslation: 'Her zaman modaya uygun giyiniyor.',
    exampleTranslationEn: 'She is always fashionably dressed.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-68',
    german: 'altmodisch',
    turkish: 'Modası geçmiş',
    english: 'Old-fashioned',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['unmodern', 'veraltet'],
    antonyms: ['modisch', 'modern'],
    collocations: ['altmodische Kleidung', 'altmodisch aussehen'],
    emoji: '🕰️',
    exampleSentence: 'Diese Jacke sieht altmodisch aus.',
    exampleTranslation: 'Bu ceket modası geçmiş görünüyor.',
    exampleTranslationEn: 'This jacket looks old-fashioned.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-69',
    german: 'bügeln',
    turkish: 'Ütülemek',
    english: 'To iron',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['Hemden bügeln', 'das Bügeleisen'],
    emoji: '🫧',
    exampleSentence: 'Ich muss noch mein Hemd bügeln.',
    exampleTranslation: 'Gömleğimi ütülemem lazım.',
    exampleTranslationEn: 'I still need to iron my shirt.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-70',
    german: 'waschen',
    turkish: 'Yıkamak',
    english: 'To wash',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['Wäsche waschen', 'Kleidung waschen'],
    emoji: '🧺',
    exampleSentence: 'Ich muss die Wäsche waschen.',
    exampleTranslation: 'Çamaşırları yıkamam lazım.',
    exampleTranslationEn: 'I need to do the laundry.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-71',
    german: 'nähen',
    turkish: 'Dikmek',
    english: 'To sew',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['einen Knopf annähen', 'ein Kleid nähen'],
    emoji: '🪡',
    exampleSentence: 'Kannst du den Knopf annähen?',
    exampleTranslation: 'Düğmeyi dikebilir misin?',
    exampleTranslationEn: 'Can you sew on the button?',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-72',
    german: 'der Schneider',
    turkish: 'Terzi',
    english: 'Tailor',
    article: 'der',
    plural: 'Schneider',
    partOfSpeech: 'noun',
    synonyms: ['Schneiderin'],
    collocations: ['zum Schneider gehen', 'ein guter Schneider'],
    emoji: '✂️',
    exampleSentence: 'Der Schneider hat meine Hose gekürzt.',
    exampleTranslation: 'Terzi pantolonumu kısalttı.',
    exampleTranslationEn: 'The tailor shortened my trousers.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-73',
    german: 'die Schürze',
    turkish: 'Önlük',
    english: 'Apron',
    article: 'die',
    plural: 'Schürzen',
    partOfSpeech: 'noun',
    collocations: ['eine Schürze tragen', 'die Schürze umbinden'],
    emoji: '👨‍🍳',
    exampleSentence: 'Der Koch trägt eine weiße Schürze.',
    exampleTranslation: 'Aşçı beyaz bir önlük giyiyor.',
    exampleTranslationEn: 'The cook wears a white apron.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-74',
    german: 'die Uniform',
    turkish: 'Üniforma',
    english: 'Uniform',
    article: 'die',
    plural: 'Uniformen',
    partOfSpeech: 'noun',
    collocations: ['eine Uniform tragen', 'Schuluniform'],
    emoji: '🎖️',
    exampleSentence: 'In dieser Schule trägt man eine Uniform.',
    exampleTranslation: 'Bu okulda üniforma giyilir.',
    exampleTranslationEn: 'In this school they wear a uniform.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-75',
    german: 'die Schleife',
    turkish: 'Fiyonk / Kurdele',
    english: 'Bow / Ribbon',
    article: 'die',
    plural: 'Schleifen',
    partOfSpeech: 'noun',
    collocations: ['eine Schleife binden', 'eine rote Schleife'],
    emoji: '🎀',
    exampleSentence: 'Sie hat eine Schleife im Haar.',
    exampleTranslation: 'Saçında bir fiyonk var.',
    exampleTranslationEn: 'She has a bow in her hair.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-76',
    german: 'der Pelz',
    turkish: 'Kürk',
    english: 'Fur',
    article: 'der',
    plural: 'Pelze',
    partOfSpeech: 'noun',
    synonyms: ['Fell'],
    collocations: ['Pelzmantel', 'ein echter Pelz'],
    emoji: '🧥',
    exampleSentence: 'Sie trägt keinen echten Pelz.',
    exampleTranslation: 'Gerçek kürk giymiyor.',
    exampleTranslationEn: 'She does not wear real fur.',
    category: 'clothing',
    level: 'B2',
  },
  {
    id: 'clothing-77',
    german: 'die Sportkleidung',
    turkish: 'Spor kıyafeti',
    english: 'Sportswear',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Trainingskleidung'],
    collocations: ['Sportkleidung tragen', 'bequeme Sportkleidung'],
    emoji: '🏃',
    exampleSentence: 'Für das Fitnessstudio brauche ich Sportkleidung.',
    exampleTranslation: 'Spor salonu için spor kıyafetine ihtiyacım var.',
    exampleTranslationEn: 'I need sportswear for the gym.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-78',
    german: 'die Turnschuhe',
    turkish: 'Spor ayakkabı',
    english: 'Sneakers / Trainers',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Sportschuhe', 'Sneaker'],
    collocations: ['Turnschuhe tragen', 'neue Turnschuhe'],
    emoji: '👟',
    exampleSentence: 'Meine Turnschuhe sind schon alt.',
    exampleTranslation: 'Spor ayakkabılarım artık eski.',
    exampleTranslationEn: 'My sneakers are already old.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-79',
    german: 'der Schlafanzug',
    turkish: 'Pijama takımı',
    english: 'Pajamas',
    article: 'der',
    plural: 'Schlafanzüge',
    partOfSpeech: 'noun',
    synonyms: ['Pyjama'],
    collocations: ['den Schlafanzug anziehen', 'im Schlafanzug'],
    emoji: '🛌',
    exampleSentence: 'Die Kinder sind schon im Schlafanzug.',
    exampleTranslation: 'Çocuklar çoktan pijamalı.',
    exampleTranslationEn: 'The children are already in their pajamas.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-80',
    german: 'die Badehose',
    turkish: 'Deniz şortu',
    english: 'Swimming trunks',
    article: 'die',
    plural: 'Badehosen',
    partOfSpeech: 'noun',
    collocations: ['eine Badehose tragen', 'die Badehose einpacken'],
    emoji: '🩲',
    exampleSentence: 'Vergiss deine Badehose nicht!',
    exampleTranslation: 'Deniz şortunu unutma!',
    exampleTranslationEn: 'Don\'t forget your swimming trunks!',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-81',
    german: 'das Kopftuch',
    turkish: 'Başörtüsü',
    english: 'Headscarf',
    article: 'das',
    plural: 'Kopftücher',
    partOfSpeech: 'noun',
    collocations: ['ein Kopftuch tragen', 'das Kopftuch binden'],
    emoji: '🧕',
    exampleSentence: 'Sie trägt ein buntes Kopftuch.',
    exampleTranslation: 'Renkli bir başörtüsü takıyor.',
    exampleTranslationEn: 'She wears a colorful headscarf.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-82',
    german: 'der Hosenanzug',
    turkish: 'Pantolon takım',
    english: 'Pantsuit',
    article: 'der',
    plural: 'Hosenanzüge',
    partOfSpeech: 'noun',
    collocations: ['einen Hosenanzug tragen', 'ein eleganter Hosenanzug'],
    emoji: '👩‍💼',
    exampleSentence: 'Zum Meeting trägt sie einen Hosenanzug.',
    exampleTranslation: 'Toplantıya pantolon takım giyiyor.',
    exampleTranslationEn: 'She wears a pantsuit to the meeting.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-83',
    german: 'das Unterhemd',
    turkish: 'Fanila / Atlet',
    english: 'Undershirt',
    article: 'das',
    plural: 'Unterhemden',
    partOfSpeech: 'noun',
    collocations: ['ein Unterhemd tragen', 'weißes Unterhemd'],
    emoji: '🩳',
    exampleSentence: 'Unter dem Hemd trägt er ein Unterhemd.',
    exampleTranslation: 'Gömleğin altına fanila giyiyor.',
    exampleTranslationEn: 'He wears an undershirt under his shirt.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-84',
    german: 'die Fliege',
    turkish: 'Papyon',
    english: 'Bow tie',
    article: 'die',
    plural: 'Fliegen',
    partOfSpeech: 'noun',
    collocations: ['eine Fliege tragen', 'eine schwarze Fliege'],
    emoji: '🎀',
    exampleSentence: 'Zum Smoking trägt er eine Fliege.',
    exampleTranslation: 'Smokinle papyon takıyor.',
    exampleTranslationEn: 'He wears a bow tie with his tuxedo.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-85',
    german: 'der Smoking',
    turkish: 'Smokin',
    english: 'Tuxedo',
    article: 'der',
    plural: 'Smokings',
    partOfSpeech: 'noun',
    collocations: ['einen Smoking tragen', 'ein schwarzer Smoking'],
    emoji: '🤵',
    exampleSentence: 'Für die Gala braucht er einen Smoking.',
    exampleTranslation: 'Gala için bir smokine ihtiyacı var.',
    exampleTranslationEn: 'He needs a tuxedo for the gala.',
    category: 'clothing',
    level: 'B2',
  },
  {
    id: 'clothing-86',
    german: 'der Bademantel',
    turkish: 'Bornoz',
    english: 'Bathrobe',
    article: 'der',
    plural: 'Bademäntel',
    partOfSpeech: 'noun',
    collocations: ['einen Bademantel anziehen', 'im Bademantel'],
    emoji: '🛁',
    exampleSentence: 'Nach dem Duschen ziehe ich den Bademantel an.',
    exampleTranslation: 'Duştan sonra bornozu giyiyorum.',
    exampleTranslationEn: 'After showering I put on the bathrobe.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-87',
    german: 'die Strumpfhose',
    turkish: 'Külotlu çorap',
    english: 'Tights / Pantyhose',
    article: 'die',
    plural: 'Strumpfhosen',
    partOfSpeech: 'noun',
    collocations: ['eine Strumpfhose anziehen', 'schwarze Strumpfhose'],
    emoji: '🩲',
    exampleSentence: 'Im Winter trage ich eine warme Strumpfhose.',
    exampleTranslation: 'Kışın sıcak bir külotlu çorap giyerim.',
    exampleTranslationEn: 'In winter I wear warm tights.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-88',
    german: 'die Schuhsohle',
    turkish: 'Ayakkabı tabanı',
    english: 'Shoe sole',
    article: 'die',
    plural: 'Schuhsohlen',
    partOfSpeech: 'noun',
    collocations: ['die Schuhsohle ist abgelaufen', 'rutschfeste Sohle'],
    emoji: '👞',
    exampleSentence: 'Die Schuhsohle ist abgelaufen.',
    exampleTranslation: 'Ayakkabı tabanı aşınmış.',
    exampleTranslationEn: 'The shoe sole is worn out.',
    category: 'clothing',
    level: 'B2',
  },
  {
    id: 'clothing-89',
    german: 'der Schnürsenkel',
    turkish: 'Ayakkabı bağcığı',
    english: 'Shoelace',
    article: 'der',
    plural: 'Schnürsenkel',
    partOfSpeech: 'noun',
    collocations: ['die Schnürsenkel binden', 'offene Schnürsenkel'],
    emoji: '👟',
    exampleSentence: 'Deine Schnürsenkel sind offen.',
    exampleTranslation: 'Ayakkabı bağcıkların açık.',
    exampleTranslationEn: 'Your shoelaces are untied.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-90',
    german: 'der Anorak',
    turkish: 'Anorak / Yağmurluk',
    english: 'Anorak',
    article: 'der',
    plural: 'Anoraks',
    partOfSpeech: 'noun',
    collocations: ['einen Anorak tragen', 'wasserdichter Anorak'],
    emoji: '🧥',
    exampleSentence: 'Der Anorak ist wasserdicht.',
    exampleTranslation: 'Anorak su geçirmez.',
    exampleTranslationEn: 'The anorak is waterproof.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-91',
    german: 'die Schürze',
    turkish: 'Mutfak önlüğü',
    english: 'Kitchen apron',
    article: 'die',
    plural: 'Schürzen',
    partOfSpeech: 'noun',
    collocations: ['die Schürze umbinden', 'eine Kochschürze'],
    emoji: '🍳',
    exampleSentence: 'Bind dir eine Schürze um, wenn du kochst.',
    exampleTranslation: 'Yemek yaparken önlük tak.',
    exampleTranslationEn: 'Put on an apron when you cook.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-92',
    german: 'umziehen',
    turkish: 'Üstünü değiştirmek',
    english: 'To change clothes',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['sich umziehen', 'schnell umziehen'],
    emoji: '🔄',
    exampleSentence: 'Ich muss mich noch schnell umziehen.',
    exampleTranslation: 'Hızlıca üstümü değiştirmem lazım.',
    exampleTranslationEn: 'I need to change my clothes quickly.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-93',
    german: 'die Falte',
    turkish: 'Kırışık / Pli',
    english: 'Crease / Pleat',
    article: 'die',
    plural: 'Falten',
    partOfSpeech: 'noun',
    collocations: ['Falten bügeln', 'ein Rock mit Falten'],
    emoji: '📐',
    exampleSentence: 'Das Hemd hat viele Falten.',
    exampleTranslation: 'Gömleğin çok kırışığı var.',
    exampleTranslationEn: 'The shirt has many creases.',
    category: 'clothing',
    level: 'B2',
  },
  {
    id: 'clothing-94',
    german: 'die Konfektion',
    turkish: 'Konfeksiyon',
    english: 'Ready-to-wear',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['Konfektionskleidung', 'von der Stange'],
    emoji: '🏪',
    exampleSentence: 'Die meiste Kleidung ist Konfektion.',
    exampleTranslation: 'Çoğu kıyafet konfeksiyondur.',
    exampleTranslationEn: 'Most clothing is ready-to-wear.',
    category: 'clothing',
    level: 'B2',
  },
  {
    id: 'clothing-95',
    german: 'der Saum',
    turkish: 'Etek ucu / Kenar dikişi',
    english: 'Hem',
    article: 'der',
    plural: 'Säume',
    partOfSpeech: 'noun',
    collocations: ['den Saum kürzen', 'der Saum ist aufgegangen'],
    emoji: '🪡',
    exampleSentence: 'Der Saum der Hose ist zu lang.',
    exampleTranslation: 'Pantolonun etek ucu çok uzun.',
    exampleTranslationEn: 'The hem of the trousers is too long.',
    category: 'clothing',
    level: 'B2',
  },
  {
    id: 'clothing-96',
    german: 'der Fleck',
    turkish: 'Leke',
    english: 'Stain',
    article: 'der',
    plural: 'Flecken',
    partOfSpeech: 'noun',
    collocations: ['einen Fleck entfernen', 'ein Fleck auf dem Hemd'],
    emoji: '🫗',
    exampleSentence: 'Ich habe einen Fleck auf meinem Hemd.',
    exampleTranslation: 'Gömleğimde bir leke var.',
    exampleTranslationEn: 'I have a stain on my shirt.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-97',
    german: 'die Nähmaschine',
    turkish: 'Dikiş makinesi',
    english: 'Sewing machine',
    article: 'die',
    plural: 'Nähmaschinen',
    partOfSpeech: 'noun',
    collocations: ['an der Nähmaschine', 'die Nähmaschine benutzen'],
    emoji: '🧵',
    exampleSentence: 'Meine Oma hat eine alte Nähmaschine.',
    exampleTranslation: 'Büyükannemin eski bir dikiş makinesi var.',
    exampleTranslationEn: 'My grandma has an old sewing machine.',
    category: 'clothing',
    level: 'B2',
  },
  {
    id: 'clothing-98',
    german: 'der Kleiderbügel',
    turkish: 'Askı (elbise)',
    english: 'Clothes hanger',
    article: 'der',
    plural: 'Kleiderbügel',
    partOfSpeech: 'noun',
    collocations: ['auf einen Kleiderbügel hängen', 'Holz-Kleiderbügel'],
    emoji: '🪝',
    exampleSentence: 'Häng die Jacke auf den Kleiderbügel.',
    exampleTranslation: 'Ceketi askıya as.',
    exampleTranslationEn: 'Hang the jacket on the hanger.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-99',
    german: 'die Wäsche',
    turkish: 'Çamaşır',
    english: 'Laundry',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['Wäsche waschen', 'die Wäsche aufhängen'],
    emoji: '🧺',
    exampleSentence: 'Ich muss noch die Wäsche aufhängen.',
    exampleTranslation: 'Çamaşırları asmam lazım.',
    exampleTranslationEn: 'I still need to hang up the laundry.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-100',
    german: 'der Kleiderschrank',
    turkish: 'Gardırop',
    english: 'Wardrobe / Closet',
    article: 'der',
    plural: 'Kleiderschränke',
    partOfSpeech: 'noun',
    collocations: ['den Kleiderschrank aufräumen', 'ein voller Kleiderschrank'],
    emoji: '🚪',
    exampleSentence: 'Mein Kleiderschrank ist voll.',
    exampleTranslation: 'Gardırobum dolu.',
    exampleTranslationEn: 'My wardrobe is full.',
    category: 'clothing',
    level: 'B1',
  },
];
