import { VocabularyWord } from '@/lib/types';

export const clothingWords: VocabularyWord[] = [
  {
    id: 'clothing-1',
    german: 'das Hemd',
    turkish: 'Gömlek',
    english: 'Shirt',
    article: 'das',
    plural: 'Hemden',
    partOfSpeech: 'noun',
    synonyms: ['Oberhemd'],
    collocations: ['ein Hemd anziehen', 'ein weißes Hemd'],
    emoji: '👔',
    exampleSentence: 'Er trägt ein weißes Hemd.',
    exampleTranslation: 'Beyaz bir gömlek giyiyor.',
    exampleTranslationEn: 'He is wearing a white shirt.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-2',
    german: 'die Hose',
    turkish: 'Pantolon',
    english: 'Trousers',
    article: 'die',
    plural: 'Hosen',
    partOfSpeech: 'noun',
    synonyms: ['Jeans', 'Stoffhose'],
    collocations: ['eine Hose anziehen', 'eine neue Hose kaufen'],
    emoji: '👖',
    exampleSentence: 'Diese Hose passt mir gut.',
    exampleTranslation: 'Bu pantolon bana iyi uyuyor.',
    exampleTranslationEn: 'These trousers fit me well.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-3',
    german: 'der Schuh',
    turkish: 'Ayakkabı',
    english: 'Shoe',
    article: 'der',
    plural: 'Schuhe',
    partOfSpeech: 'noun',
    synonyms: ['Stiefel', 'Sneaker'],
    collocations: ['Schuhe anziehen', 'neue Schuhe kaufen'],
    emoji: '👟',
    exampleSentence: 'Ich brauche neue Schuhe.',
    exampleTranslation: 'Yeni ayakkabılara ihtiyacım var.',
    exampleTranslationEn: 'I need new shoes.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-4',
    german: 'die Jacke',
    turkish: 'Ceket',
    english: 'Jacket',
    article: 'die',
    plural: 'Jacken',
    partOfSpeech: 'noun',
    synonyms: ['Mantel', 'Anorak'],
    collocations: ['die Jacke anziehen', 'eine warme Jacke'],
    emoji: '🧥',
    exampleSentence: 'Zieh deine Jacke an, es ist kalt!',
    exampleTranslation: 'Ceketini giy, hava soğuk!',
    exampleTranslationEn: 'Put on your jacket, it\'s cold!',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-5',
    german: 'das Kleid',
    turkish: 'Elbise',
    english: 'Dress',
    article: 'das',
    plural: 'Kleider',
    partOfSpeech: 'noun',
    synonyms: ['Gewand'],
    collocations: ['ein schönes Kleid', 'ein Kleid tragen'],
    emoji: '👗',
    exampleSentence: 'Sie trägt ein rotes Kleid.',
    exampleTranslation: 'Kırmızı bir elbise giyiyor.',
    exampleTranslationEn: 'She is wearing a red dress.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-6',
    german: 'der Hut',
    turkish: 'Şapka',
    english: 'Hat',
    article: 'der',
    plural: 'Hüte',
    partOfSpeech: 'noun',
    synonyms: ['Mütze', 'Kappe'],
    collocations: ['einen Hut tragen', 'den Hut aufsetzen'],
    emoji: '🎩',
    exampleSentence: 'Der Hut steht dir gut!',
    exampleTranslation: 'Şapka sana çok yakışıyor!',
    exampleTranslationEn: 'The hat looks good on you!',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-7',
    german: 'die Socke',
    turkish: 'Çorap',
    english: 'Sock',
    article: 'die',
    plural: 'Socken',
    partOfSpeech: 'noun',
    synonyms: ['Strumpf'],
    collocations: ['warme Socken', 'Socken anziehen'],
    emoji: '🧦',
    exampleSentence: 'Wo ist meine zweite Socke?',
    exampleTranslation: 'Diğer çorabım nerede?',
    exampleTranslationEn: 'Where is my other sock?',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-8',
    german: 'der Pullover',
    turkish: 'Kazak',
    english: 'Sweater',
    article: 'der',
    plural: 'Pullover',
    partOfSpeech: 'noun',
    synonyms: ['Pulli', 'Strickjacke'],
    collocations: ['einen Pullover tragen', 'einen warmen Pullover'],
    emoji: '🧶',
    exampleSentence: 'Dieser Pullover ist sehr warm.',
    exampleTranslation: 'Bu kazak çok sıcak.',
    exampleTranslationEn: 'This sweater is very warm.',
    category: 'clothing',
    level: 'A1',
  },
  {
    id: 'clothing-9',
    german: 'der Rock',
    turkish: 'Etek',
    english: 'Skirt',
    article: 'der',
    plural: 'Röcke',
    partOfSpeech: 'noun',
    synonyms: ['Minirock'],
    collocations: ['einen Rock tragen', 'ein kurzer Rock'],
    emoji: '👗',
    exampleSentence: 'Der Rock ist sehr elegant.',
    exampleTranslation: 'Etek çok şık.',
    exampleTranslationEn: 'The skirt is very elegant.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-10',
    german: 'der Gürtel',
    turkish: 'Kemer',
    english: 'Belt',
    article: 'der',
    plural: 'Gürtel',
    partOfSpeech: 'noun',
    synonyms: ['Ledergürtel'],
    collocations: ['einen Gürtel tragen', 'den Gürtel enger schnallen'],
    emoji: '👔',
    exampleSentence: 'Der Gürtel passt gut zur Hose.',
    exampleTranslation: 'Kemer pantolona çok yakışıyor.',
    exampleTranslationEn: 'The belt goes well with the trousers.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-11',
    german: 'die Bluse',
    turkish: 'Bluz',
    english: 'Blouse',
    article: 'die',
    plural: 'Blusen',
    partOfSpeech: 'noun',
    synonyms: ['Damenhemd'],
    collocations: ['eine Bluse anziehen', 'eine seidene Bluse'],
    emoji: '👚',
    exampleSentence: 'Die Bluse ist aus Seide.',
    exampleTranslation: 'Bluz ipekten yapılmış.',
    exampleTranslationEn: 'The blouse is made of silk.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-12',
    german: 'der Schal',
    turkish: 'Atkı / Şal',
    english: 'Scarf',
    article: 'der',
    plural: 'Schals',
    partOfSpeech: 'noun',
    synonyms: ['Tuch', 'Halstuch'],
    collocations: ['einen Schal tragen', 'einen warmen Schal'],
    emoji: '🧣',
    exampleSentence: 'Im Winter trage ich immer einen Schal.',
    exampleTranslation: 'Kışın hep atkı takarım.',
    exampleTranslationEn: 'In winter I always wear a scarf.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-13',
    german: 'die Handschuhe',
    turkish: 'Eldiven',
    english: 'Gloves',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Fäustlinge'],
    collocations: ['Handschuhe anziehen', 'warme Handschuhe'],
    emoji: '🧤',
    exampleSentence: 'Vergiss deine Handschuhe nicht!',
    exampleTranslation: 'Eldivenlerini unutma!',
    exampleTranslationEn: 'Don\'t forget your gloves!',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-14',
    german: 'der Anzug',
    turkish: 'Takım elbise',
    english: 'Suit',
    article: 'der',
    plural: 'Anzüge',
    partOfSpeech: 'noun',
    synonyms: ['Kostüm'],
    collocations: ['einen Anzug tragen', 'ein eleganter Anzug'],
    emoji: '🤵',
    exampleSentence: 'Für das Vorstellungsgespräch trage ich einen Anzug.',
    exampleTranslation: 'İş görüşmesi için takım elbise giyiyorum.',
    exampleTranslationEn: 'I wear a suit for the job interview.',
    category: 'clothing',
    level: 'A2',
  },
  {
    id: 'clothing-15',
    german: 'die Krawatte',
    turkish: 'Kravat',
    english: 'Tie',
    article: 'die',
    plural: 'Krawatten',
    partOfSpeech: 'noun',
    synonyms: ['Schlips', 'Binder'],
    collocations: ['eine Krawatte binden', 'eine Krawatte tragen'],
    emoji: '👔',
    exampleSentence: 'Kannst du dir eine Krawatte binden?',
    exampleTranslation: 'Kravat bağlayabiliyor musun?',
    exampleTranslationEn: 'Can you tie a tie?',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-16',
    german: 'der Badeanzug',
    turkish: 'Mayo',
    english: 'Swimsuit',
    article: 'der',
    plural: 'Badeanzüge',
    partOfSpeech: 'noun',
    synonyms: ['Bikini', 'Badehose'],
    collocations: ['einen Badeanzug tragen', 'einen neuen Badeanzug kaufen'],
    emoji: '👙',
    exampleSentence: 'Hast du deinen Badeanzug eingepackt?',
    exampleTranslation: 'Mayonu hazırladın mı?',
    exampleTranslationEn: 'Did you pack your swimsuit?',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-17',
    german: 'der Stoff',
    turkish: 'Kumaş',
    english: 'Fabric',
    article: 'der',
    plural: 'Stoffe',
    partOfSpeech: 'noun',
    synonyms: ['Material', 'Textil'],
    collocations: ['weicher Stoff', 'der Stoff fühlt sich gut an'],
    emoji: '🧵',
    exampleSentence: 'Dieser Stoff fühlt sich sehr weich an.',
    exampleTranslation: 'Bu kumaş çok yumuşak hissettiriyor.',
    exampleTranslationEn: 'This fabric feels very soft.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-18',
    german: 'die Garderobe',
    turkish: 'Gardırop',
    english: 'Wardrobe / Cloakroom',
    article: 'die',
    plural: 'Garderoben',
    partOfSpeech: 'noun',
    synonyms: ['Kleiderschrank'],
    collocations: ['die Garderobe aufräumen', 'an der Garderobe abgeben'],
    emoji: '🚪',
    exampleSentence: 'Bitte geben Sie Ihren Mantel an der Garderobe ab.',
    exampleTranslation: 'Lütfen paltonuzu vestiyere bırakın.',
    exampleTranslationEn: 'Please leave your coat at the cloakroom.',
    category: 'clothing',
    level: 'B1',
  },
  {
    id: 'clothing-19',
    german: 'die Maßanfertigung',
    turkish: 'Ismarlama / Özel dikim',
    english: 'Custom-made / Tailored',
    article: 'die',
    plural: 'Maßanfertigungen',
    partOfSpeech: 'noun',
    synonyms: ['Maßkleidung', 'Sonderanfertigung'],
    collocations: ['eine Maßanfertigung bestellen', 'in Maßanfertigung'],
    emoji: '✂️',
    exampleSentence: 'Der Anzug ist eine Maßanfertigung vom besten Schneider.',
    exampleTranslation: 'Takım elbise en iyi terziden ısmarlama.',
    exampleTranslationEn: 'The suit is custom-made by the best tailor.',
    category: 'clothing',
    level: 'B2',
  },
  {
    id: 'clothing-20',
    german: 'die Nachhaltigkeit',
    turkish: 'Sürdürülebilirlik',
    english: 'Sustainability',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Dauerhaftigkeit'],
    collocations: ['nachhaltige Mode', 'auf Nachhaltigkeit achten'],
    emoji: '♻️',
    exampleSentence: 'Nachhaltigkeit in der Modeindustrie wird immer wichtiger.',
    exampleTranslation: 'Moda endüstrisinde sürdürülebilirlik giderek önem kazanıyor.',
    exampleTranslationEn: 'Sustainability in the fashion industry is becoming more important.',
    category: 'clothing',
    level: 'B2',
  },
];
