import { VocabularyWord } from '@/lib/types';

export const colorsWords: VocabularyWord[] = [
  { id: 'colors-1', german: 'rot', turkish: 'kırmızı', english: 'red', article: null, partOfSpeech: 'adjective', emoji: '🔴', collocations: ['rot werden', 'das Rote Kreuz', 'eine rote Ampel'], exampleSentence: 'Die Rose ist rot.', exampleTranslation: 'Gül kırmızı.', exampleTranslationEn: 'The rose is red.', category: 'colors', level: 'A1' },
  { id: 'colors-2', german: 'blau', turkish: 'mavi', english: 'blue', article: null, partOfSpeech: 'adjective', emoji: '🔵', collocations: ['blau machen', 'blaues Auge', 'blauer Himmel'], exampleSentence: 'Der Himmel ist blau.', exampleTranslation: 'Gökyüzü mavi.', exampleTranslationEn: 'The sky is blue.', category: 'colors', level: 'A1' },
  { id: 'colors-3', german: 'grün', turkish: 'yeşil', english: 'green', article: null, partOfSpeech: 'adjective', emoji: '🟢', collocations: ['grünes Licht geben', 'im Grünen', 'grüner Tee'], exampleSentence: 'Das Gras ist grün.', exampleTranslation: 'Çimen yeşil.', exampleTranslationEn: 'The grass is green.', category: 'colors', level: 'A1' },
  { id: 'colors-4', german: 'gelb', turkish: 'sarı', english: 'yellow', article: null, partOfSpeech: 'adjective', emoji: '🟡', collocations: ['gelbe Karte', 'Gelbe Seiten', 'gelb vor Neid'], exampleSentence: 'Die Sonne ist gelb.', exampleTranslation: 'Güneş sarı.', exampleTranslationEn: 'The sun is yellow.', category: 'colors', level: 'A1' },
  { id: 'colors-5', german: 'schwarz', turkish: 'siyah', english: 'black', article: null, partOfSpeech: 'adjective', emoji: '⚫', antonyms: ['weiß'], collocations: ['schwarzer Kaffee', 'schwarzes Brett', 'schwarz auf weiß'], exampleSentence: 'Ich trage ein schwarzes T-Shirt.', exampleTranslation: 'Siyah bir tişört giyiyorum.', exampleTranslationEn: 'I am wearing a black T-shirt.', category: 'colors', level: 'A1' },
  { id: 'colors-6', german: 'weiß', turkish: 'beyaz', english: 'white', article: null, partOfSpeech: 'adjective', emoji: '⚪', antonyms: ['schwarz'], collocations: ['weißer Wein', 'weiße Weihnachten', 'das Weiße Haus'], exampleSentence: 'Der Schnee ist weiß.', exampleTranslation: 'Kar beyaz.', exampleTranslationEn: 'The snow is white.', category: 'colors', level: 'A1' },
  { id: 'colors-7', german: 'grau', turkish: 'gri', english: 'gray', article: null, partOfSpeech: 'adjective', emoji: '🩶', collocations: ['grauer Alltag', 'graue Haare', 'grau in grau'], exampleSentence: 'Die Wolken sind grau.', exampleTranslation: 'Bulutlar gri.', exampleTranslationEn: 'The clouds are gray.', category: 'colors', level: 'A1' },
  { id: 'colors-8', german: 'braun', turkish: 'kahverengi', english: 'brown', article: null, partOfSpeech: 'adjective', emoji: '🟤', collocations: ['braune Augen', 'braun gebrannt', 'braunes Brot'], exampleSentence: 'Der Bär ist braun.', exampleTranslation: 'Ayı kahverengi.', exampleTranslationEn: 'The bear is brown.', category: 'colors', level: 'A1' },
  { id: 'colors-9', german: 'orange', turkish: 'turuncu', english: 'orange', article: null, partOfSpeech: 'adjective', emoji: '🟠', collocations: ['orangefarbener Saft', 'orange leuchten'], exampleSentence: 'Die Orange ist orange.', exampleTranslation: 'Portakal turuncudur.', exampleTranslationEn: 'The orange is orange.', category: 'colors', level: 'A1' },
  { id: 'colors-10', german: 'rosa', turkish: 'pembe', english: 'pink', article: null, partOfSpeech: 'adjective', emoji: '🩷', synonyms: ['pink'], collocations: ['rosa Brille', 'rosa Wolken'], exampleSentence: 'Sie mag rosa Blumen.', exampleTranslation: 'Pembe çiçekleri sever.', exampleTranslationEn: 'She likes pink flowers.', category: 'colors', level: 'A1' },
  { id: 'colors-11', german: 'lila', turkish: 'mor', english: 'purple', article: null, partOfSpeech: 'adjective', emoji: '🟣', synonyms: ['violett'], collocations: ['lila Kleid', 'lila Laune'], exampleSentence: 'Die Blume ist lila.', exampleTranslation: 'Çiçek mor.', exampleTranslationEn: 'The flower is purple.', category: 'colors', level: 'A1' },
  { id: 'colors-12', german: 'dunkel', turkish: 'koyu', english: 'dark', article: null, partOfSpeech: 'adjective', emoji: '🌑', synonyms: ['finster'], antonyms: ['hell'], collocations: ['dunkelblau', 'dunkle Wolken', 'im Dunkeln'], exampleSentence: 'Es ist schon dunkel draußen.', exampleTranslation: 'Dışarısı zaten karanlık.', exampleTranslationEn: 'It is already dark outside.', category: 'colors', level: 'A1' },
  { id: 'colors-13', german: 'hell', turkish: 'açık/parlak', english: 'light/bright', article: null, partOfSpeech: 'adjective', emoji: '🌕', antonyms: ['dunkel'], collocations: ['hellblau', 'helles Licht', 'hellwach'], exampleSentence: 'Das Zimmer ist sehr hell.', exampleTranslation: 'Oda çok aydınlık.', exampleTranslationEn: 'The room is very bright.', category: 'colors', level: 'A1' },
  { id: 'colors-14', german: 'bunt', turkish: 'renkli', english: 'colorful', article: null, partOfSpeech: 'adjective', emoji: '🌈', antonyms: ['einfarbig'], collocations: ['buntes Treiben', 'bunt gemischt', 'ein bunter Abend'], exampleSentence: 'Die Schmetterlinge sind bunt.', exampleTranslation: 'Kelebekler renkli.', exampleTranslationEn: 'The butterflies are colorful.', category: 'colors', level: 'A1' },
  { id: 'colors-15', german: 'golden', turkish: 'altın rengi', english: 'golden', article: null, partOfSpeech: 'adjective', emoji: '✨', synonyms: ['goldfarben'], collocations: ['goldene Hochzeit', 'die goldene Mitte', 'goldene Zeiten'], exampleSentence: 'Sie hat goldene Haare.', exampleTranslation: 'Altın rengi saçları var.', exampleTranslationEn: 'She has golden hair.', category: 'colors', level: 'A1' },
];
