import { VocabularyWord } from '@/lib/types';

export const colorsWords: VocabularyWord[] = [
  { id: 'colors-1', german: 'rot', turkish: 'kırmızı', article: null, partOfSpeech: 'adjective', emoji: '🔴', collocations: ['rot werden', 'das Rote Kreuz', 'eine rote Ampel'], exampleSentence: 'Die Rose ist rot.', exampleTranslation: 'Gül kırmızı.', category: 'colors', level: 'A1' },
  { id: 'colors-2', german: 'blau', turkish: 'mavi', article: null, partOfSpeech: 'adjective', emoji: '🔵', collocations: ['blau machen', 'blaues Auge', 'blauer Himmel'], exampleSentence: 'Der Himmel ist blau.', exampleTranslation: 'Gökyüzü mavi.', category: 'colors', level: 'A1' },
  { id: 'colors-3', german: 'grün', turkish: 'yeşil', article: null, partOfSpeech: 'adjective', emoji: '🟢', collocations: ['grünes Licht geben', 'im Grünen', 'grüner Tee'], exampleSentence: 'Das Gras ist grün.', exampleTranslation: 'Çimen yeşil.', category: 'colors', level: 'A1' },
  { id: 'colors-4', german: 'gelb', turkish: 'sarı', article: null, partOfSpeech: 'adjective', emoji: '🟡', collocations: ['gelbe Karte', 'Gelbe Seiten', 'gelb vor Neid'], exampleSentence: 'Die Sonne ist gelb.', exampleTranslation: 'Güneş sarı.', category: 'colors', level: 'A1' },
  { id: 'colors-5', german: 'schwarz', turkish: 'siyah', article: null, partOfSpeech: 'adjective', emoji: '⚫', antonyms: ['weiß'], collocations: ['schwarzer Kaffee', 'schwarzes Brett', 'schwarz auf weiß'], exampleSentence: 'Ich trage ein schwarzes T-Shirt.', exampleTranslation: 'Siyah bir tişört giyiyorum.', category: 'colors', level: 'A1' },
  { id: 'colors-6', german: 'weiß', turkish: 'beyaz', article: null, partOfSpeech: 'adjective', emoji: '⚪', antonyms: ['schwarz'], collocations: ['weißer Wein', 'weiße Weihnachten', 'das Weiße Haus'], exampleSentence: 'Der Schnee ist weiß.', exampleTranslation: 'Kar beyaz.', category: 'colors', level: 'A1' },
  { id: 'colors-7', german: 'grau', turkish: 'gri', article: null, partOfSpeech: 'adjective', emoji: '🩶', collocations: ['grauer Alltag', 'graue Haare', 'grau in grau'], exampleSentence: 'Die Wolken sind grau.', exampleTranslation: 'Bulutlar gri.', category: 'colors', level: 'A1' },
  { id: 'colors-8', german: 'braun', turkish: 'kahverengi', article: null, partOfSpeech: 'adjective', emoji: '🟤', collocations: ['braune Augen', 'braun gebrannt', 'braunes Brot'], exampleSentence: 'Der Bär ist braun.', exampleTranslation: 'Ayı kahverengi.', category: 'colors', level: 'A1' },
  { id: 'colors-9', german: 'orange', turkish: 'turuncu', article: null, partOfSpeech: 'adjective', emoji: '🟠', collocations: ['orangefarbener Saft', 'orange leuchten'], exampleSentence: 'Die Orange ist orange.', exampleTranslation: 'Portakal turuncudur.', category: 'colors', level: 'A1' },
  { id: 'colors-10', german: 'rosa', turkish: 'pembe', article: null, partOfSpeech: 'adjective', emoji: '🩷', synonyms: ['pink'], collocations: ['rosa Brille', 'rosa Wolken'], exampleSentence: 'Sie mag rosa Blumen.', exampleTranslation: 'Pembe çiçekleri sever.', category: 'colors', level: 'A1' },
  { id: 'colors-11', german: 'lila', turkish: 'mor', article: null, partOfSpeech: 'adjective', emoji: '🟣', synonyms: ['violett'], collocations: ['lila Kleid', 'lila Laune'], exampleSentence: 'Die Blume ist lila.', exampleTranslation: 'Çiçek mor.', category: 'colors', level: 'A1' },
  { id: 'colors-12', german: 'dunkel', turkish: 'koyu', article: null, partOfSpeech: 'adjective', emoji: '🌑', synonyms: ['finster'], antonyms: ['hell'], collocations: ['dunkelblau', 'dunkle Wolken', 'im Dunkeln'], exampleSentence: 'Es ist schon dunkel draußen.', exampleTranslation: 'Dışarısı zaten karanlık.', category: 'colors', level: 'A1' },
  { id: 'colors-13', german: 'hell', turkish: 'açık/parlak', article: null, partOfSpeech: 'adjective', emoji: '🌕', antonyms: ['dunkel'], collocations: ['hellblau', 'helles Licht', 'hellwach'], exampleSentence: 'Das Zimmer ist sehr hell.', exampleTranslation: 'Oda çok aydınlık.', category: 'colors', level: 'A1' },
  { id: 'colors-14', german: 'bunt', turkish: 'renkli', article: null, partOfSpeech: 'adjective', emoji: '🌈', antonyms: ['einfarbig'], collocations: ['buntes Treiben', 'bunt gemischt', 'ein bunter Abend'], exampleSentence: 'Die Schmetterlinge sind bunt.', exampleTranslation: 'Kelebekler renkli.', category: 'colors', level: 'A1' },
  { id: 'colors-15', german: 'golden', turkish: 'altın rengi', article: null, partOfSpeech: 'adjective', emoji: '✨', synonyms: ['goldfarben'], collocations: ['goldene Hochzeit', 'die goldene Mitte', 'goldene Zeiten'], exampleSentence: 'Sie hat goldene Haare.', exampleTranslation: 'Altın rengi saçları var.', category: 'colors', level: 'A1' },
];
