import { VocabularyWord } from '@/lib/types';

export const colorsWords: VocabularyWord[] = [
  { id: 'colors-1', german: 'rot', turkish: 'kırmızı', english: 'red', article: null, partOfSpeech: 'adjective', emoji: '🔴', collocations: ['rot werden', 'das Rote Kreuz', 'eine rote Ampel'], exampleSentence: 'Die Rose ist rot.', exampleTranslation: 'Gül kırmızı.', exampleTranslationEn: 'The rose is red.', category: 'colors', level: 'A1' },
  { id: 'colors-2', german: 'blau', turkish: 'mavi', english: 'blue', article: null, partOfSpeech: 'adjective', emoji: '🔵', collocations: ['blau machen', 'blaues Auge', 'blauer Himmel'], exampleSentence: 'Der Himmel ist blau.', exampleTranslation: 'Gökyüzü mavi.', exampleTranslationEn: 'The sky is blue.', category: 'colors', level: 'A1' },
  { id: 'colors-3', german: 'grün', turkish: 'yeşil', english: 'green', article: null, partOfSpeech: 'adjective', emoji: '🟢', collocations: ['grünes Licht geben', 'im Grünen', 'grüner Tee'], exampleSentence: 'Das Gras ist grün.', exampleTranslation: 'Çimen yeşil.', exampleTranslationEn: 'The grass is green.', category: 'colors', level: 'A1' },
  { id: 'colors-4', german: 'gelb', turkish: 'sarı', english: 'yellow', article: null, partOfSpeech: 'adjective', emoji: '🟡', collocations: ['gelbe Karte', 'Gelbe Seiten', 'gelb vor Neid'], exampleSentence: 'Die Sonne ist gelb.', exampleTranslation: 'Güneş sarı.', exampleTranslationEn: 'The sun is yellow.', category: 'colors', level: 'A1' },
  { id: 'colors-5', german: 'schwarz', turkish: 'siyah', english: 'black', article: null, partOfSpeech: 'adjective', emoji: '⚫', antonyms: ['weiß'], collocations: ['schwarzer Kaffee', 'schwarzes Brett', 'schwarz auf weiß'], exampleSentence: 'Ich trage ein schwarzes T-Shirt.', exampleTranslation: 'Siyah bir tişört giyiyorum.', exampleTranslationEn: 'I am wearing a black T-shirt.', category: 'colors', level: 'A1' },
  { id: 'colors-6', german: 'weiß', turkish: 'beyaz', english: 'white', article: null, partOfSpeech: 'adjective', emoji: '⚪', antonyms: ['schwarz'], collocations: ['weißer Wein', 'weiße Weihnachten', 'das Weiße Haus'], exampleSentence: 'Der Schnee ist weiß.', exampleTranslation: 'Kar beyaz.', exampleTranslationEn: 'The snow is white.', category: 'colors', level: 'A1' },
  { id: 'colors-7', german: 'grau', turkish: 'gri', english: 'gray', article: null, partOfSpeech: 'adjective', emoji: '🩶', collocations: ['grauer Alltag', 'graue Haare', 'grau in grau'], exampleSentence: 'Die Wolken sind grau.', exampleTranslation: 'Bulutlar gri.', exampleTranslationEn: 'The clouds are gray.', category: 'colors', level: 'A1' },
  { id: 'colors-8', german: 'braun', turkish: 'kahverengi', english: 'brown', article: null, partOfSpeech: 'adjective', emoji: '🟤', collocations: ['braune Augen', 'braun gebrannt', 'braunes Brot'], exampleSentence: 'Der Bär ist braun.', exampleTranslation: 'Ayı kahverengi.', exampleTranslationEn: 'The bear is brown.', category: 'colors', level: 'A1' },
  { id: 'colors-9', german: 'orange', turkish: 'turuncu', english: 'orange', article: null, partOfSpeech: 'adjective', emoji: '🟠', collocations: ['orangefarbener Saft', 'orange leuchten'], exampleSentence: 'Die Orange ist orange.', exampleTranslation: 'Portakal turuncudur.', exampleTranslationEn: 'The orange is orange.', category: 'colors', level: 'A1' },
  { id: 'colors-10', german: 'rosa', turkish: 'pembe', english: 'pink', article: null, partOfSpeech: 'adjective', emoji: '🩷', synonyms: ['pink'], collocations: ['rosa Brille', 'rosa Wolken'], exampleSentence: 'Sie mag rosa Blumen.', exampleTranslation: 'Pembe çiçekleri sever.', exampleTranslationEn: 'She likes pink flowers.', category: 'colors', level: 'A1' },
  { id: 'colors-11', german: 'lila', turkish: 'mor', english: 'purple', article: null, partOfSpeech: 'adjective', emoji: '🟣', synonyms: ['violett'], collocations: ['lila Kleid', 'lila Laune'], exampleSentence: 'Die Blume ist lila.', exampleTranslation: 'Çiçek mor.', exampleTranslationEn: 'The flower is purple.', category: 'colors', level: 'A1' },
  { id: 'colors-12', german: 'dunkel', turkish: 'koyu', english: 'dark', article: null, partOfSpeech: 'adjective', emoji: '🌑', synonyms: ['finster'], antonyms: ['hell'], collocations: ['dunkelblau', 'dunkle Wolken', 'im Dunkeln'], exampleSentence: 'Es ist schon dunkel draußen.', exampleTranslation: 'Dışarısı zaten karanlık.', exampleTranslationEn: 'It is already dark outside.', category: 'colors', level: 'A1' },
  { id: 'colors-13', german: 'hell', turkish: 'açık/parlak', english: 'light/bright', article: null, partOfSpeech: 'adjective', emoji: '🌕', antonyms: ['dunkel'], collocations: ['hellblau', 'helles Licht', 'hellwach'], exampleSentence: 'Das Zimmer ist sehr hell.', exampleTranslation: 'Oda çok aydınlık.', exampleTranslationEn: 'The room is very bright.', category: 'colors', level: 'A1' },
  { id: 'colors-14', german: 'bunt', turkish: 'renkli', english: 'colorful', article: null, partOfSpeech: 'adjective', emoji: '🌈', antonyms: ['einfarbig'], collocations: ['buntes Treiben', 'bunt gemischt', 'ein bunter Abend'], exampleSentence: 'Die Schmetterlinge sind bunt.', exampleTranslation: 'Kelebekler renkli.', exampleTranslationEn: 'The butterflies are colorful.', category: 'colors', level: 'A1' },
  { id: 'colors-15', german: 'golden', turkish: 'altın rengi', english: 'golden', article: null, partOfSpeech: 'adjective', emoji: '✨', synonyms: ['goldfarben'], collocations: ['goldene Hochzeit', 'die goldene Mitte', 'goldene Zeiten'], exampleSentence: 'Sie hat goldene Haare.', exampleTranslation: 'Altın rengi saçları var.', exampleTranslationEn: 'She has golden hair.', category: 'colors', level: 'A1' },
  // B1 - Shades, descriptions, textures
  {
    id: 'colors-b1-1',
    german: 'gestreift',
    turkish: 'çizgili',
    english: 'striped',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Er trägt ein gestreiftes Hemd.',
    exampleTranslation: 'Çizgili bir gömlek giyiyor.',
    exampleTranslationEn: 'He is wearing a striped shirt.',
    category: 'colors',
    level: 'B1',
    tags: ['pattern', 'clothing'],
  },
  {
    id: 'colors-b1-2',
    german: 'gemustert',
    turkish: 'desenli',
    english: 'patterned',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Die gemusterte Tapete sieht schön aus.',
    exampleTranslation: 'Desenli duvar kağıdı güzel görünüyor.',
    exampleTranslationEn: 'The patterned wallpaper looks nice.',
    category: 'colors',
    level: 'B1',
    tags: ['pattern', 'design'],
  },
  {
    id: 'colors-b1-3',
    german: 'kariert',
    turkish: 'ekose / kareli',
    english: 'checkered / plaid',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Sie hat eine karierte Decke mitgebracht.',
    exampleTranslation: 'Kareli bir battaniye getirdi.',
    exampleTranslationEn: 'She brought a checkered blanket.',
    category: 'colors',
    level: 'B1',
    tags: ['pattern', 'clothing'],
  },
  {
    id: 'colors-b1-4',
    german: 'gepunktet',
    turkish: 'puantiyeli / benekli',
    english: 'polka-dotted / spotted',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Das Kind trägt ein gepunktetes Kleid.',
    exampleTranslation: 'Çocuk puantiyeli bir elbise giyiyor.',
    exampleTranslationEn: 'The child is wearing a polka-dotted dress.',
    category: 'colors',
    level: 'B1',
    tags: ['pattern', 'clothing'],
  },
  {
    id: 'colors-b1-5',
    german: 'einfarbig',
    turkish: 'düz renk / tek renk',
    english: 'solid-colored / plain',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Ich bevorzuge einfarbige Kleidung.',
    exampleTranslation: 'Düz renk kıyafetleri tercih ederim.',
    exampleTranslationEn: 'I prefer solid-colored clothing.',
    category: 'colors',
    level: 'B1',
    tags: ['pattern', 'style'],
  },
  {
    id: 'colors-b1-6',
    german: 'der Farbton',
    turkish: 'renk tonu',
    english: 'shade / hue',
    article: 'der',
    plural: 'Farbtöne',
    partOfSpeech: 'noun',
    exampleSentence: 'Dieser Farbton passt gut zu Ihrer Haut.',
    exampleTranslation: 'Bu renk tonu cildinize çok yakışıyor.',
    exampleTranslationEn: 'This shade suits your skin well.',
    category: 'colors',
    level: 'B1',
    tags: ['color', 'shade'],
  },
  {
    id: 'colors-b1-7',
    german: 'blass',
    turkish: 'soluk / solgun',
    english: 'pale',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Du siehst blass aus. Geht es dir gut?',
    exampleTranslation: 'Solgun görünüyorsun. İyi misin?',
    exampleTranslationEn: 'You look pale. Are you feeling well?',
    category: 'colors',
    level: 'B1',
    tags: ['appearance', 'health'],
  },
  {
    id: 'colors-b1-8',
    german: 'leuchtend',
    turkish: 'parlak / canlı',
    english: 'bright / vivid',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Die Blumen haben leuchtende Farben.',
    exampleTranslation: 'Çiçeklerin canlı renkleri var.',
    exampleTranslationEn: 'The flowers have bright colors.',
    category: 'colors',
    level: 'B1',
    tags: ['color', 'intensity'],
  },
  {
    id: 'colors-b1-9',
    german: 'durchsichtig',
    turkish: 'şeffaf / saydam',
    english: 'transparent / see-through',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Die Vorhänge sind fast durchsichtig.',
    exampleTranslation: 'Perdeler neredeyse şeffaf.',
    exampleTranslationEn: 'The curtains are almost see-through.',
    category: 'colors',
    level: 'B1',
    tags: ['texture', 'material'],
  },
  {
    id: 'colors-b1-10',
    german: 'matt',
    turkish: 'mat',
    english: 'matte / dull',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Ich möchte die Wand in einem matten Weiß streichen.',
    exampleTranslation: 'Duvarı mat beyaza boyamak istiyorum.',
    exampleTranslationEn: 'I want to paint the wall in a matte white.',
    category: 'colors',
    level: 'B1',
    tags: ['finish', 'texture'],
  },
  // B2 - Advanced color vocabulary, shades, and visual effects
  {
    id: 'colors-b2-1',
    german: 'der Farbton',
    turkish: 'renk tonu',
    english: 'shade',
    article: 'der',
    plural: 'Farbtöne',
    partOfSpeech: 'noun',
    exampleSentence: 'Dieser Farbton von Grün erinnert mich an den Frühling.',
    exampleTranslation: 'Bu yeşil tonu bana baharı hatırlatıyor.',
    exampleTranslationEn: 'This shade of green reminds me of spring.',
    category: 'colors',
    level: 'B2',
    tags: ['shade', 'color theory'],
  },
  {
    id: 'colors-b2-2',
    german: 'blassblau',
    turkish: 'soluk mavi',
    english: 'pale blue',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Der blassblaue Himmel kündigte einen klaren Tag an.',
    exampleTranslation: 'Soluk mavi gökyüzü açık bir günün habercisiydi.',
    exampleTranslationEn: 'The pale blue sky announced a clear day.',
    category: 'colors',
    level: 'B2',
    tags: ['shade', 'blue'],
  },
  {
    id: 'colors-b2-3',
    german: 'kräftig',
    turkish: 'canlı / güçlü',
    english: 'vivid',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Die kräftigen Farben des Gemäldes ziehen alle Blicke auf sich.',
    exampleTranslation: 'Tablonun canlı renkleri tüm bakışları üzerine çekiyor.',
    exampleTranslationEn: 'The vivid colors of the painting attract everyone\'s attention.',
    category: 'colors',
    level: 'B2',
    tags: ['intensity', 'art'],
  },
  {
    id: 'colors-b2-4',
    german: 'schimmern',
    turkish: 'parıldamak / ışıldamak',
    english: 'to shimmer',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Das Wasser schimmert im Mondlicht.',
    exampleTranslation: 'Su ay ışığında parıldıyor.',
    exampleTranslationEn: 'The water shimmers in the moonlight.',
    category: 'colors',
    level: 'B2',
    tags: ['light', 'visual effect'],
  },
  {
    id: 'colors-b2-5',
    german: 'der Kontrast',
    turkish: 'kontrast / zıtlık',
    english: 'contrast',
    article: 'der',
    plural: 'Kontraste',
    partOfSpeech: 'noun',
    exampleSentence: 'Der Kontrast zwischen Licht und Schatten verleiht dem Bild Tiefe.',
    exampleTranslation: 'Işık ve gölge arasındaki kontrast resme derinlik katıyor.',
    exampleTranslationEn: 'The contrast between light and shadow gives the image depth.',
    category: 'colors',
    level: 'B2',
    tags: ['art', 'visual effect'],
  },
  {
    id: 'colors-b2-6',
    german: 'matt',
    turkish: 'mat',
    english: 'matte',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Für das Wohnzimmer bevorzuge ich eine matte Wandfarbe.',
    exampleTranslation: 'Oturma odası için mat bir duvar boyası tercih ederim.',
    exampleTranslationEn: 'For the living room, I prefer a matte wall paint.',
    category: 'colors',
    level: 'B2',
    tags: ['finish', 'design'],
  },
  {
    id: 'colors-b2-7',
    german: 'leuchtend',
    turkish: 'parlak / ışıl ışıl',
    english: 'luminous',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Die leuchtenden Farben des Sonnenuntergangs waren atemberaubend.',
    exampleTranslation: 'Gün batımının parlak renkleri nefes kesiciydi.',
    exampleTranslationEn: 'The luminous colors of the sunset were breathtaking.',
    category: 'colors',
    level: 'B2',
    tags: ['intensity', 'light'],
  },
  {
    id: 'colors-b2-8',
    german: 'die Nuance',
    turkish: 'nüans / ince ayrım',
    english: 'nuance',
    article: 'die',
    plural: 'Nuancen',
    partOfSpeech: 'noun',
    exampleSentence: 'Es gibt viele Nuancen zwischen Blau und Grün.',
    exampleTranslation: 'Mavi ve yeşil arasında birçok nüans var.',
    exampleTranslationEn: 'There are many nuances between blue and green.',
    category: 'colors',
    level: 'B2',
    tags: ['shade', 'subtlety'],
  },
  {
    id: 'colors-b2-9',
    german: 'verblassen',
    turkish: 'solmak',
    english: 'to fade',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Die Farben des alten Fotos sind im Laufe der Jahre verblasst.',
    exampleTranslation: 'Eski fotoğrafın renkleri yıllar içinde solmuş.',
    exampleTranslationEn: 'The colors of the old photo have faded over the years.',
    category: 'colors',
    level: 'B2',
    tags: ['change', 'aging'],
  },
  {
    id: 'colors-b2-10',
    german: 'bunt',
    turkish: 'rengarenk / çok renkli',
    english: 'colorful / multicolored',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Der Karneval ist bekannt für seine bunten Kostüme und Umzüge.',
    exampleTranslation: 'Karnaval, rengarenk kostümleri ve geçit törenleriyle tanınır.',
    exampleTranslationEn: 'The carnival is known for its colorful costumes and parades.',
    category: 'colors',
    level: 'B2',
    tags: ['variety', 'culture'],
  },
];
