import { VocabularyWord } from '@/lib/types';

export const educationWords: VocabularyWord[] = [
  {
    id: 'education-1',
    german: 'die Schule',
    turkish: 'Okul',
    english: 'School',
    article: 'die',
    plural: 'Schulen',
    partOfSpeech: 'noun',
    synonyms: ['Bildungseinrichtung'],
    collocations: ['in die Schule gehen', 'die Schule besuchen'],
    emoji: '🏫',
    exampleSentence: 'Mein Kind geht in die Schule.',
    exampleTranslation: 'Çocuğum okula gidiyor.',
    exampleTranslationEn: 'My child goes to school.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-2',
    german: 'der Lehrer',
    turkish: 'Öğretmen (erkek)',
    english: 'Teacher (male)',
    article: 'der',
    plural: 'Lehrer',
    partOfSpeech: 'noun',
    synonyms: ['Pädagoge', 'Lehrkraft'],
    collocations: ['der strenge Lehrer', 'ein guter Lehrer'],
    emoji: '👨‍🏫',
    exampleSentence: 'Der Lehrer erklärt die Aufgabe.',
    exampleTranslation: 'Öğretmen ödevi açıklıyor.',
    exampleTranslationEn: 'The teacher explains the task.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-3',
    german: 'die Lehrerin',
    turkish: 'Öğretmen (kadın)',
    english: 'Teacher (female)',
    article: 'die',
    plural: 'Lehrerinnen',
    partOfSpeech: 'noun',
    synonyms: ['Pädagogin'],
    collocations: ['die nette Lehrerin', 'unsere Lehrerin'],
    emoji: '👩‍🏫',
    exampleSentence: 'Die Lehrerin ist sehr nett.',
    exampleTranslation: 'Öğretmen çok iyi.',
    exampleTranslationEn: 'The teacher is very nice.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-4',
    german: 'das Buch',
    turkish: 'Kitap',
    english: 'Book',
    article: 'das',
    plural: 'Bücher',
    partOfSpeech: 'noun',
    synonyms: ['Lektüre', 'Werk'],
    collocations: ['ein Buch lesen', 'ein Buch schreiben'],
    emoji: '📚',
    exampleSentence: 'Ich lese ein interessantes Buch.',
    exampleTranslation: 'İlginç bir kitap okuyorum.',
    exampleTranslationEn: 'I am reading an interesting book.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-5',
    german: 'der Stift',
    turkish: 'Kalem',
    english: 'Pen',
    article: 'der',
    plural: 'Stifte',
    partOfSpeech: 'noun',
    synonyms: ['Kugelschreiber', 'Kuli'],
    collocations: ['mit dem Stift schreiben', 'einen Stift leihen'],
    emoji: '✏️',
    exampleSentence: 'Kann ich deinen Stift benutzen?',
    exampleTranslation: 'Kalemini kullanabilir miyim?',
    exampleTranslationEn: 'Can I use your pen?',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-6',
    german: 'das Heft',
    turkish: 'Defter',
    english: 'Notebook',
    article: 'das',
    plural: 'Hefte',
    partOfSpeech: 'noun',
    synonyms: ['Notizbuch', 'Schreibheft'],
    collocations: ['ins Heft schreiben', 'das Heft aufschlagen'],
    emoji: '📓',
    exampleSentence: 'Schreibt die Antwort in euer Heft.',
    exampleTranslation: 'Cevabı defterinize yazın.',
    exampleTranslationEn: 'Write the answer in your notebook.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-7',
    german: 'lernen',
    turkish: 'Öğrenmek',
    english: 'To learn',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['studieren', 'büffeln'],
    collocations: ['Deutsch lernen', 'für die Prüfung lernen'],
    emoji: '📖',
    exampleSentence: 'Ich lerne jeden Tag Deutsch.',
    exampleTranslation: 'Her gün Almanca öğreniyorum.',
    exampleTranslationEn: 'I learn German every day.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-8',
    german: 'schreiben',
    turkish: 'Yazmak',
    english: 'To write',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['verfassen', 'notieren'],
    collocations: ['einen Brief schreiben', 'eine E-Mail schreiben'],
    emoji: '✍️',
    exampleSentence: 'Ich schreibe einen Aufsatz.',
    exampleTranslation: 'Bir kompozisyon yazıyorum.',
    exampleTranslationEn: 'I am writing an essay.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-9',
    german: 'lesen',
    turkish: 'Okumak',
    english: 'To read',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['durchlesen', 'studieren'],
    collocations: ['ein Buch lesen', 'die Zeitung lesen'],
    emoji: '📖',
    exampleSentence: 'Liest du gerne Bücher?',
    exampleTranslation: 'Kitap okumayı sever misin?',
    exampleTranslationEn: 'Do you like reading books?',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-10',
    german: 'die Universität',
    turkish: 'Üniversite',
    english: 'University',
    article: 'die',
    plural: 'Universitäten',
    partOfSpeech: 'noun',
    synonyms: ['Uni', 'Hochschule'],
    collocations: ['an der Universität studieren', 'die Universität besuchen'],
    emoji: '🎓',
    exampleSentence: 'Ich studiere an der Universität Berlin.',
    exampleTranslation: 'Berlin Üniversitesinde okuyorum.',
    exampleTranslationEn: 'I study at the University of Berlin.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-11',
    german: 'die Hausaufgabe',
    turkish: 'Ödev',
    english: 'Homework',
    article: 'die',
    plural: 'Hausaufgaben',
    partOfSpeech: 'noun',
    synonyms: ['Schulaufgabe'],
    collocations: ['Hausaufgaben machen', 'die Hausaufgabe abgeben'],
    emoji: '📝',
    exampleSentence: 'Hast du deine Hausaufgaben gemacht?',
    exampleTranslation: 'Ödevlerini yaptın mı?',
    exampleTranslationEn: 'Have you done your homework?',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-12',
    german: 'die Prüfung',
    turkish: 'Sınav',
    english: 'Exam',
    article: 'die',
    plural: 'Prüfungen',
    partOfSpeech: 'noun',
    synonyms: ['Test', 'Klausur', 'Examen'],
    collocations: ['eine Prüfung bestehen', 'eine Prüfung ablegen'],
    emoji: '📋',
    exampleSentence: 'Morgen habe ich eine wichtige Prüfung.',
    exampleTranslation: 'Yarın önemli bir sınavım var.',
    exampleTranslationEn: 'Tomorrow I have an important exam.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-13',
    german: 'die Note',
    turkish: 'Not',
    english: 'Grade',
    article: 'die',
    plural: 'Noten',
    partOfSpeech: 'noun',
    synonyms: ['Zensur', 'Bewertung'],
    collocations: ['gute Noten bekommen', 'schlechte Noten haben'],
    emoji: '💯',
    exampleSentence: 'Er hat gute Noten in Mathematik.',
    exampleTranslation: 'Matematikte iyi notları var.',
    exampleTranslationEn: 'He has good grades in math.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-14',
    german: 'das Fach',
    turkish: 'Ders / Branş',
    english: 'Subject',
    article: 'das',
    plural: 'Fächer',
    partOfSpeech: 'noun',
    synonyms: ['Unterrichtsfach', 'Disziplin'],
    collocations: ['mein Lieblingsfach', 'ein schwieriges Fach'],
    emoji: '📚',
    exampleSentence: 'Welches Fach magst du am liebsten?',
    exampleTranslation: 'En çok hangi dersi seviyorsun?',
    exampleTranslationEn: 'Which subject do you like the most?',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-15',
    german: 'das Zeugnis',
    turkish: 'Karne',
    english: 'Report card',
    article: 'das',
    plural: 'Zeugnisse',
    partOfSpeech: 'noun',
    synonyms: ['Schulzeugnis'],
    collocations: ['ein gutes Zeugnis', 'das Zeugnis bekommen'],
    emoji: '📜',
    exampleSentence: 'Am Ende des Jahres bekommt jeder ein Zeugnis.',
    exampleTranslation: 'Yıl sonunda herkes karne alır.',
    exampleTranslationEn: 'At the end of the year everyone gets a report card.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-16',
    german: 'der Unterricht',
    turkish: 'Ders',
    english: 'Lesson / Class',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Stunde', 'Kurs'],
    collocations: ['am Unterricht teilnehmen', 'der Unterricht beginnt'],
    emoji: '🏫',
    exampleSentence: 'Der Unterricht beginnt um acht Uhr.',
    exampleTranslation: 'Ders saat sekizde başlıyor.',
    exampleTranslationEn: 'The lesson starts at eight o\'clock.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-17',
    german: 'das Stipendium',
    turkish: 'Burs',
    english: 'Scholarship',
    article: 'das',
    plural: 'Stipendien',
    partOfSpeech: 'noun',
    synonyms: ['Förderung'],
    collocations: ['ein Stipendium bekommen', 'sich um ein Stipendium bewerben'],
    emoji: '🎓',
    exampleSentence: 'Sie hat ein Stipendium für ihr Studium erhalten.',
    exampleTranslation: 'Eğitimi için burs aldı.',
    exampleTranslationEn: 'She received a scholarship for her studies.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-18',
    german: 'die Vorlesung',
    turkish: 'Üniversite dersi',
    english: 'Lecture',
    article: 'die',
    plural: 'Vorlesungen',
    partOfSpeech: 'noun',
    synonyms: ['Vortrag'],
    collocations: ['eine Vorlesung besuchen', 'die Vorlesung halten'],
    emoji: '🎤',
    exampleSentence: 'Die Vorlesung über Philosophie war sehr interessant.',
    exampleTranslation: 'Felsefe dersi çok ilginçti.',
    exampleTranslationEn: 'The lecture on philosophy was very interesting.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-19',
    german: 'die Forschung',
    turkish: 'Araştırma',
    english: 'Research',
    article: 'die',
    plural: 'Forschungen',
    partOfSpeech: 'noun',
    synonyms: ['Untersuchung', 'Studie'],
    collocations: ['Forschung betreiben', 'wissenschaftliche Forschung'],
    emoji: '🔬',
    exampleSentence: 'Die Forschung in der Medizin macht große Fortschritte.',
    exampleTranslation: 'Tıp alanındaki araştırmalar büyük ilerlemeler kaydediyor.',
    exampleTranslationEn: 'Research in medicine is making great progress.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-20',
    german: 'die Bildung',
    turkish: 'Eğitim',
    english: 'Education',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Ausbildung', 'Erziehung'],
    collocations: ['Bildung ist wichtig', 'eine gute Bildung'],
    emoji: '🎓',
    exampleSentence: 'Bildung ist der Schlüssel zum Erfolg.',
    exampleTranslation: 'Eğitim başarının anahtarıdır.',
    exampleTranslationEn: 'Education is the key to success.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-21',
    german: 'die Dissertation',
    turkish: 'Doktora tezi',
    english: 'Dissertation',
    article: 'die',
    plural: 'Dissertationen',
    partOfSpeech: 'noun',
    synonyms: ['Doktorarbeit'],
    collocations: ['die Dissertation schreiben', 'die Dissertation verteidigen'],
    emoji: '📄',
    exampleSentence: 'Er schreibt seine Dissertation über Quantenphysik.',
    exampleTranslation: 'Kuantum fiziği üzerine doktora tezini yazıyor.',
    exampleTranslationEn: 'He is writing his dissertation on quantum physics.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-22',
    german: 'die Weiterbildung',
    turkish: 'İleri eğitim',
    english: 'Further education',
    article: 'die',
    plural: 'Weiterbildungen',
    partOfSpeech: 'noun',
    synonyms: ['Fortbildung'],
    collocations: ['berufliche Weiterbildung', 'eine Weiterbildung machen'],
    emoji: '📈',
    exampleSentence: 'Berufliche Weiterbildung ist heutzutage unverzichtbar.',
    exampleTranslation: 'Mesleki ileri eğitim günümüzde vazgeçilmezdir.',
    exampleTranslationEn: 'Professional further education is indispensable nowadays.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-23',
    german: 'die Facharbeit',
    turkish: 'Bitirme ödevi',
    english: 'Term paper',
    article: 'die',
    plural: 'Facharbeiten',
    partOfSpeech: 'noun',
    synonyms: ['Seminararbeit', 'Hausarbeit'],
    collocations: ['eine Facharbeit schreiben', 'die Facharbeit abgeben'],
    emoji: '📝',
    exampleSentence: 'Die Facharbeit muss bis nächste Woche fertig sein.',
    exampleTranslation: 'Bitirme ödevi gelecek haftaya kadar hazır olmalı.',
    exampleTranslationEn: 'The term paper must be finished by next week.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-24',
    german: 'die Kompetenz',
    turkish: 'Yetkinlik',
    english: 'Competence',
    article: 'die',
    plural: 'Kompetenzen',
    partOfSpeech: 'noun',
    synonyms: ['Fähigkeit', 'Qualifikation'],
    collocations: ['fachliche Kompetenz', 'soziale Kompetenz'],
    emoji: '💪',
    exampleSentence: 'Interkulturelle Kompetenz wird immer wichtiger.',
    exampleTranslation: 'Kültürlerarası yetkinlik giderek daha önemli hale geliyor.',
    exampleTranslationEn: 'Intercultural competence is becoming increasingly important.',
    category: 'education',
    level: 'B2',
  },
  // === NEW WORDS START HERE ===
  // A1 Level Words (education-25 to education-40)
  {
    id: 'education-25',
    german: 'die Klasse',
    turkish: 'Sınıf',
    english: 'Class / Classroom',
    article: 'die',
    plural: 'Klassen',
    partOfSpeech: 'noun',
    synonyms: ['Schulklasse', 'Klassenzimmer'],
    collocations: ['in die Klasse gehen', 'die erste Klasse'],
    emoji: '🏫',
    exampleSentence: 'In meiner Klasse sind 25 Schüler.',
    exampleTranslation: 'Sınıfımda 25 öğrenci var.',
    exampleTranslationEn: 'There are 25 students in my class.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-26',
    german: 'der Schüler',
    turkish: 'Öğrenci (erkek)',
    english: 'Student (male, school)',
    article: 'der',
    plural: 'Schüler',
    partOfSpeech: 'noun',
    synonyms: ['Lernende'],
    collocations: ['ein guter Schüler', 'die Schüler lernen'],
    emoji: '👦',
    exampleSentence: 'Der Schüler macht seine Aufgaben.',
    exampleTranslation: 'Öğrenci ödevlerini yapıyor.',
    exampleTranslationEn: 'The student does his assignments.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-27',
    german: 'die Schülerin',
    turkish: 'Öğrenci (kadın)',
    english: 'Student (female, school)',
    article: 'die',
    plural: 'Schülerinnen',
    partOfSpeech: 'noun',
    synonyms: ['Lernende'],
    collocations: ['eine fleißige Schülerin', 'die neue Schülerin'],
    emoji: '👧',
    exampleSentence: 'Die Schülerin liest ein Buch.',
    exampleTranslation: 'Öğrenci bir kitap okuyor.',
    exampleTranslationEn: 'The student is reading a book.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-28',
    german: 'die Tafel',
    turkish: 'Yazı tahtası',
    english: 'Blackboard',
    article: 'die',
    plural: 'Tafeln',
    partOfSpeech: 'noun',
    synonyms: ['Wandtafel', 'Whiteboard'],
    collocations: ['an die Tafel schreiben', 'die Tafel wischen'],
    emoji: '📋',
    exampleSentence: 'Der Lehrer schreibt an die Tafel.',
    exampleTranslation: 'Öğretmen tahtaya yazıyor.',
    exampleTranslationEn: 'The teacher writes on the blackboard.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-29',
    german: 'der Tisch',
    turkish: 'Masa',
    english: 'Table / Desk',
    article: 'der',
    plural: 'Tische',
    partOfSpeech: 'noun',
    synonyms: ['Schreibtisch'],
    collocations: ['am Tisch sitzen', 'den Tisch decken'],
    emoji: '🪑',
    exampleSentence: 'Die Bücher liegen auf dem Tisch.',
    exampleTranslation: 'Kitaplar masanın üstünde duruyor.',
    exampleTranslationEn: 'The books are on the table.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-30',
    german: 'die Aufgabe',
    turkish: 'Görev / Ödev',
    english: 'Task / Exercise',
    article: 'die',
    plural: 'Aufgaben',
    partOfSpeech: 'noun',
    synonyms: ['Übung', 'Arbeit'],
    collocations: ['eine Aufgabe lösen', 'die Aufgabe machen'],
    emoji: '📝',
    exampleSentence: 'Bitte löst die Aufgabe auf Seite zehn.',
    exampleTranslation: 'Lütfen onuncu sayfadaki görevi çözün.',
    exampleTranslationEn: 'Please solve the exercise on page ten.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-31',
    german: 'sprechen',
    turkish: 'Konuşmak',
    english: 'To speak',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['reden', 'sagen'],
    collocations: ['Deutsch sprechen', 'laut sprechen'],
    emoji: '🗣️',
    exampleSentence: 'Kannst du Deutsch sprechen?',
    exampleTranslation: 'Almanca konuşabiliyor musun?',
    exampleTranslationEn: 'Can you speak German?',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-32',
    german: 'fragen',
    turkish: 'Sormak',
    english: 'To ask',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['befragen'],
    collocations: ['eine Frage stellen', 'den Lehrer fragen'],
    emoji: '❓',
    exampleSentence: 'Darf ich etwas fragen?',
    exampleTranslation: 'Bir şey sorabilir miyim?',
    exampleTranslationEn: 'May I ask something?',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-33',
    german: 'die Frage',
    turkish: 'Soru',
    english: 'Question',
    article: 'die',
    plural: 'Fragen',
    partOfSpeech: 'noun',
    synonyms: ['Anfrage'],
    collocations: ['eine Frage stellen', 'eine Frage beantworten'],
    emoji: '❓',
    exampleSentence: 'Hast du eine Frage?',
    exampleTranslation: 'Bir sorun var mı?',
    exampleTranslationEn: 'Do you have a question?',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-34',
    german: 'die Antwort',
    turkish: 'Cevap',
    english: 'Answer',
    article: 'die',
    plural: 'Antworten',
    partOfSpeech: 'noun',
    synonyms: ['Erwiderung', 'Reaktion'],
    collocations: ['die richtige Antwort', 'eine Antwort geben'],
    emoji: '💬',
    exampleSentence: 'Die Antwort ist richtig.',
    exampleTranslation: 'Cevap doğru.',
    exampleTranslationEn: 'The answer is correct.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-35',
    german: 'rechnen',
    turkish: 'Hesaplamak',
    english: 'To calculate',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['berechnen', 'kalkulieren'],
    collocations: ['gut rechnen können', 'im Kopf rechnen'],
    emoji: '🔢',
    exampleSentence: 'Die Kinder lernen rechnen.',
    exampleTranslation: 'Çocuklar hesap yapmayı öğreniyor.',
    exampleTranslationEn: 'The children learn to calculate.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-36',
    german: 'die Sprache',
    turkish: 'Dil',
    english: 'Language',
    article: 'die',
    plural: 'Sprachen',
    partOfSpeech: 'noun',
    synonyms: ['Fremdsprache'],
    collocations: ['eine Sprache lernen', 'eine Sprache sprechen'],
    emoji: '🌍',
    exampleSentence: 'Ich lerne eine neue Sprache.',
    exampleTranslation: 'Yeni bir dil öğreniyorum.',
    exampleTranslationEn: 'I am learning a new language.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-37',
    german: 'der Kurs',
    turkish: 'Kurs',
    english: 'Course',
    article: 'der',
    plural: 'Kurse',
    partOfSpeech: 'noun',
    synonyms: ['Lehrgang', 'Seminar'],
    collocations: ['einen Kurs besuchen', 'einen Kurs belegen'],
    emoji: '📚',
    exampleSentence: 'Ich mache einen Deutschkurs.',
    exampleTranslation: 'Bir Almanca kursu yapıyorum.',
    exampleTranslationEn: 'I am taking a German course.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-38',
    german: 'verstehen',
    turkish: 'Anlamak',
    english: 'To understand',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['begreifen', 'kapieren'],
    collocations: ['gut verstehen', 'nicht verstehen'],
    emoji: '🤔',
    exampleSentence: 'Ich verstehe die Frage nicht.',
    exampleTranslation: 'Soruyu anlamıyorum.',
    exampleTranslationEn: 'I do not understand the question.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-39',
    german: 'das Wort',
    turkish: 'Kelime / Sözcük',
    english: 'Word',
    article: 'das',
    plural: 'Wörter',
    partOfSpeech: 'noun',
    synonyms: ['Begriff', 'Ausdruck'],
    collocations: ['ein neues Wort', 'Wörter lernen'],
    emoji: '🔤',
    exampleSentence: 'Ich lerne jeden Tag neue Wörter.',
    exampleTranslation: 'Her gün yeni kelimeler öğreniyorum.',
    exampleTranslationEn: 'I learn new words every day.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-40',
    german: 'der Bleistift',
    turkish: 'Kurşun kalem',
    english: 'Pencil',
    article: 'der',
    plural: 'Bleistifte',
    partOfSpeech: 'noun',
    synonyms: ['Druckbleistift'],
    collocations: ['mit dem Bleistift zeichnen', 'den Bleistift spitzen'],
    emoji: '✏️',
    exampleSentence: 'Ich zeichne mit einem Bleistift.',
    exampleTranslation: 'Kurşun kalemle çiziyorum.',
    exampleTranslationEn: 'I draw with a pencil.',
    category: 'education',
    level: 'A1',
  },
  // A2 Level Words (education-41 to education-58)
  {
    id: 'education-41',
    german: 'der Student',
    turkish: 'Üniversite öğrencisi (erkek)',
    english: 'University student (male)',
    article: 'der',
    plural: 'Studenten',
    partOfSpeech: 'noun',
    synonyms: ['Studierender'],
    collocations: ['ein fleißiger Student', 'Studenten an der Uni'],
    emoji: '🧑‍🎓',
    exampleSentence: 'Der Student lernt für seine Prüfung.',
    exampleTranslation: 'Üniversite öğrencisi sınavına çalışıyor.',
    exampleTranslationEn: 'The university student is studying for his exam.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-42',
    german: 'die Studentin',
    turkish: 'Üniversite öğrencisi (kadın)',
    english: 'University student (female)',
    article: 'die',
    plural: 'Studentinnen',
    partOfSpeech: 'noun',
    synonyms: ['Studierende'],
    collocations: ['eine gute Studentin', 'die Studentin studiert'],
    emoji: '👩‍🎓',
    exampleSentence: 'Die Studentin schreibt ihre Arbeit.',
    exampleTranslation: 'Üniversite öğrencisi ödevini yazıyor.',
    exampleTranslationEn: 'The university student is writing her paper.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-43',
    german: 'die Pause',
    turkish: 'Teneffüs / Mola',
    english: 'Break',
    article: 'die',
    plural: 'Pausen',
    partOfSpeech: 'noun',
    synonyms: ['Unterbrechung', 'Rast'],
    collocations: ['eine Pause machen', 'in der Pause spielen'],
    emoji: '☕',
    exampleSentence: 'In der Pause essen wir unser Brot.',
    exampleTranslation: 'Teneffüste ekmeğimizi yiyoruz.',
    exampleTranslationEn: 'During the break we eat our bread.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-44',
    german: 'studieren',
    turkish: 'Üniversitede okumak',
    english: 'To study (at university)',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['an der Uni lernen'],
    collocations: ['Medizin studieren', 'an der Universität studieren'],
    emoji: '🎓',
    exampleSentence: 'Sie studiert Medizin in München.',
    exampleTranslation: 'Münih\'te tıp okuyor.',
    exampleTranslationEn: 'She studies medicine in Munich.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-45',
    german: 'die Mathematik',
    turkish: 'Matematik',
    english: 'Mathematics',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Mathe', 'Rechnen'],
    collocations: ['Mathematik lernen', 'gut in Mathematik sein'],
    emoji: '➗',
    exampleSentence: 'Mathematik ist mein Lieblingsfach.',
    exampleTranslation: 'Matematik en sevdiğim ders.',
    exampleTranslationEn: 'Mathematics is my favorite subject.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-46',
    german: 'üben',
    turkish: 'Alıştırma yapmak',
    english: 'To practice',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['trainieren', 'proben'],
    collocations: ['fleißig üben', 'Grammatik üben'],
    emoji: '🔄',
    exampleSentence: 'Wir üben jeden Tag die Grammatik.',
    exampleTranslation: 'Her gün dilbilgisi alıştırması yapıyoruz.',
    exampleTranslationEn: 'We practice grammar every day.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-47',
    german: 'die Übung',
    turkish: 'Alıştırma',
    english: 'Exercise',
    article: 'die',
    plural: 'Übungen',
    partOfSpeech: 'noun',
    synonyms: ['Aufgabe', 'Training'],
    collocations: ['eine Übung machen', 'schwierige Übungen'],
    emoji: '📝',
    exampleSentence: 'Macht bitte die Übung auf Seite fünf.',
    exampleTranslation: 'Lütfen beşinci sayfadaki alıştırmayı yapın.',
    exampleTranslationEn: 'Please do the exercise on page five.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-48',
    german: 'das Wörterbuch',
    turkish: 'Sözlük',
    english: 'Dictionary',
    article: 'das',
    plural: 'Wörterbücher',
    partOfSpeech: 'noun',
    synonyms: ['Lexikon'],
    collocations: ['im Wörterbuch nachschlagen', 'ein Wörterbuch benutzen'],
    emoji: '📖',
    exampleSentence: 'Ich schlage das Wort im Wörterbuch nach.',
    exampleTranslation: 'Kelimeyi sözlükten arıyorum.',
    exampleTranslationEn: 'I look up the word in the dictionary.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-49',
    german: 'der Computer',
    turkish: 'Bilgisayar',
    english: 'Computer',
    article: 'der',
    plural: 'Computer',
    partOfSpeech: 'noun',
    synonyms: ['Rechner', 'PC'],
    collocations: ['am Computer arbeiten', 'den Computer benutzen'],
    emoji: '💻',
    exampleSentence: 'Die Schüler arbeiten am Computer.',
    exampleTranslation: 'Öğrenciler bilgisayarda çalışıyor.',
    exampleTranslationEn: 'The students work on the computer.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-50',
    german: 'die Geschichte',
    turkish: 'Tarih',
    english: 'History',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Historie'],
    collocations: ['Geschichte lernen', 'die deutsche Geschichte'],
    emoji: '🏛️',
    exampleSentence: 'Im Geschichtsunterricht lernen wir über den Krieg.',
    exampleTranslation: 'Tarih dersinde savaş hakkında öğreniyoruz.',
    exampleTranslationEn: 'In history class we learn about the war.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-51',
    german: 'erklären',
    turkish: 'Açıklamak',
    english: 'To explain',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['erläutern', 'verdeutlichen'],
    collocations: ['etwas erklären', 'genau erklären'],
    emoji: '💡',
    exampleSentence: 'Können Sie das bitte erklären?',
    exampleTranslation: 'Bunu açıklayabilir misiniz lütfen?',
    exampleTranslationEn: 'Can you please explain that?',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-52',
    german: 'die Bibliothek',
    turkish: 'Kütüphane',
    english: 'Library',
    article: 'die',
    plural: 'Bibliotheken',
    partOfSpeech: 'noun',
    synonyms: ['Bücherei'],
    collocations: ['in die Bibliothek gehen', 'Bücher aus der Bibliothek leihen'],
    emoji: '📚',
    exampleSentence: 'Ich lerne in der Bibliothek.',
    exampleTranslation: 'Kütüphanede çalışıyorum.',
    exampleTranslationEn: 'I study in the library.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-53',
    german: 'schwer',
    turkish: 'Zor',
    english: 'Difficult / Hard',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['schwierig', 'kompliziert'],
    collocations: ['schwere Aufgabe', 'das ist schwer'],
    emoji: '😓',
    exampleSentence: 'Die Prüfung war sehr schwer.',
    exampleTranslation: 'Sınav çok zordu.',
    exampleTranslationEn: 'The exam was very difficult.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-54',
    german: 'leicht',
    turkish: 'Kolay',
    english: 'Easy',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['einfach', 'simpel'],
    collocations: ['leichte Aufgabe', 'das ist leicht'],
    emoji: '😊',
    exampleSentence: 'Diese Übung ist leicht.',
    exampleTranslation: 'Bu alıştırma kolay.',
    exampleTranslationEn: 'This exercise is easy.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-55',
    german: 'der Fehler',
    turkish: 'Hata',
    english: 'Mistake / Error',
    article: 'der',
    plural: 'Fehler',
    partOfSpeech: 'noun',
    synonyms: ['Irrtum', 'Versehen'],
    collocations: ['einen Fehler machen', 'aus Fehlern lernen'],
    emoji: '❌',
    exampleSentence: 'Jeder macht Fehler beim Lernen.',
    exampleTranslation: 'Herkes öğrenirken hata yapar.',
    exampleTranslationEn: 'Everyone makes mistakes when learning.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-56',
    german: 'richtig',
    turkish: 'Doğru',
    english: 'Correct / Right',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['korrekt', 'zutreffend'],
    collocations: ['die richtige Antwort', 'richtig antworten'],
    emoji: '✅',
    exampleSentence: 'Deine Antwort ist richtig.',
    exampleTranslation: 'Cevabın doğru.',
    exampleTranslationEn: 'Your answer is correct.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-57',
    german: 'falsch',
    turkish: 'Yanlış',
    english: 'Wrong / False',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['inkorrekt', 'fehlerhaft'],
    collocations: ['die falsche Antwort', 'falsch verstehen'],
    emoji: '❌',
    exampleSentence: 'Das ist leider falsch.',
    exampleTranslation: 'Maalesef bu yanlış.',
    exampleTranslationEn: 'That is unfortunately wrong.',
    category: 'education',
    level: 'A2',
  },
  // B1 Level Words (education-58 to education-77)
  {
    id: 'education-58',
    german: 'der Abschluss',
    turkish: 'Mezuniyet / Diploma',
    english: 'Degree / Graduation',
    article: 'der',
    plural: 'Abschlüsse',
    partOfSpeech: 'noun',
    synonyms: ['Diplom', 'Examen'],
    collocations: ['einen Abschluss machen', 'den Abschluss erreichen'],
    emoji: '🎓',
    exampleSentence: 'Nach dem Abschluss möchte ich arbeiten.',
    exampleTranslation: 'Mezuniyetten sonra çalışmak istiyorum.',
    exampleTranslationEn: 'After graduation I want to work.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-59',
    german: 'das Semester',
    turkish: 'Dönem',
    english: 'Semester',
    article: 'das',
    plural: 'Semester',
    partOfSpeech: 'noun',
    synonyms: ['Halbjahr', 'Studienhalbjahr'],
    collocations: ['im ersten Semester', 'das Wintersemester'],
    emoji: '📅',
    exampleSentence: 'Im nächsten Semester belege ich neue Kurse.',
    exampleTranslation: 'Gelecek dönem yeni dersler alacağım.',
    exampleTranslationEn: 'Next semester I will take new courses.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-60',
    german: 'bestehen',
    turkish: 'Geçmek (sınavı)',
    english: 'To pass (an exam)',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['schaffen'],
    collocations: ['die Prüfung bestehen', 'knapp bestehen'],
    emoji: '✅',
    exampleSentence: 'Sie hat die Prüfung mit einer Eins bestanden.',
    exampleTranslation: 'Sınavı birle geçti.',
    exampleTranslationEn: 'She passed the exam with top marks.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-61',
    german: 'durchfallen',
    turkish: 'Kalmak (sınavda)',
    english: 'To fail (an exam)',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['nicht bestehen', 'versagen'],
    collocations: ['durch die Prüfung fallen', 'in Mathe durchfallen'],
    emoji: '😞',
    exampleSentence: 'Er ist leider durch die Prüfung gefallen.',
    exampleTranslation: 'Maalesef sınavda kaldı.',
    exampleTranslationEn: 'Unfortunately, he failed the exam.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-62',
    german: 'das Gymnasium',
    turkish: 'Lise (akademik)',
    english: 'Grammar school / High school',
    article: 'das',
    plural: 'Gymnasien',
    partOfSpeech: 'noun',
    synonyms: ['höhere Schule'],
    collocations: ['das Gymnasium besuchen', 'auf das Gymnasium gehen'],
    emoji: '🏫',
    exampleSentence: 'Meine Tochter geht auf das Gymnasium.',
    exampleTranslation: 'Kızım liseye gidiyor.',
    exampleTranslationEn: 'My daughter goes to grammar school.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-63',
    german: 'das Abitur',
    turkish: 'Lise bitirme sınavı',
    english: 'A-levels / High school diploma',
    article: 'das',
    partOfSpeech: 'noun',
    synonyms: ['Abi', 'Hochschulreife'],
    collocations: ['das Abitur machen', 'das Abitur bestehen'],
    emoji: '📜',
    exampleSentence: 'Nach dem Abitur will er studieren.',
    exampleTranslation: 'Lise bitirme sınavından sonra üniversiteye gitmek istiyor.',
    exampleTranslationEn: 'After his A-levels he wants to study.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-64',
    german: 'die Ausbildung',
    turkish: 'Mesleki eğitim',
    english: 'Vocational training',
    article: 'die',
    plural: 'Ausbildungen',
    partOfSpeech: 'noun',
    synonyms: ['Lehre', 'Berufsausbildung'],
    collocations: ['eine Ausbildung machen', 'die Ausbildung abschließen'],
    emoji: '🔧',
    exampleSentence: 'Er macht eine Ausbildung zum Mechaniker.',
    exampleTranslation: 'Tamirci olarak mesleki eğitim alıyor.',
    exampleTranslationEn: 'He is doing vocational training as a mechanic.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-65',
    german: 'die Grammatik',
    turkish: 'Dilbilgisi',
    english: 'Grammar',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Sprachlehre'],
    collocations: ['die deutsche Grammatik', 'Grammatik üben'],
    emoji: '📏',
    exampleSentence: 'Die deutsche Grammatik ist manchmal schwierig.',
    exampleTranslation: 'Almanca dilbilgisi bazen zor.',
    exampleTranslationEn: 'German grammar is sometimes difficult.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-66',
    german: 'der Professor',
    turkish: 'Profesör',
    english: 'Professor',
    article: 'der',
    plural: 'Professoren',
    partOfSpeech: 'noun',
    synonyms: ['Hochschullehrer', 'Dozent'],
    collocations: ['der Professor hält eine Vorlesung', 'den Professor fragen'],
    emoji: '👨‍🏫',
    exampleSentence: 'Der Professor erklärt die Theorie.',
    exampleTranslation: 'Profesör teoriyi açıklıyor.',
    exampleTranslationEn: 'The professor explains the theory.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-67',
    german: 'die Klausur',
    turkish: 'Yazılı sınav',
    english: 'Written exam',
    article: 'die',
    plural: 'Klausuren',
    partOfSpeech: 'noun',
    synonyms: ['Prüfung', 'Test'],
    collocations: ['eine Klausur schreiben', 'die Klausur bestehen'],
    emoji: '📝',
    exampleSentence: 'Morgen schreiben wir eine Klausur in Physik.',
    exampleTranslation: 'Yarın fizikte yazılı sınav yapacağız.',
    exampleTranslationEn: 'Tomorrow we are writing a written exam in physics.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-68',
    german: 'sich anmelden',
    turkish: 'Kayıt olmak',
    english: 'To register / To sign up',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich einschreiben', 'sich registrieren'],
    collocations: ['sich für einen Kurs anmelden', 'sich zur Prüfung anmelden'],
    emoji: '📋',
    exampleSentence: 'Ich muss mich für den Kurs anmelden.',
    exampleTranslation: 'Kursa kayıt olmam gerekiyor.',
    exampleTranslationEn: 'I have to register for the course.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-69',
    german: 'das Referat',
    turkish: 'Sunum / Rapor',
    english: 'Presentation / Report',
    article: 'das',
    plural: 'Referate',
    partOfSpeech: 'noun',
    synonyms: ['Vortrag', 'Präsentation'],
    collocations: ['ein Referat halten', 'ein Referat vorbereiten'],
    emoji: '🎤',
    exampleSentence: 'Ich halte morgen ein Referat über Umwelt.',
    exampleTranslation: 'Yarın çevre hakkında bir sunum yapacağım.',
    exampleTranslationEn: 'Tomorrow I am giving a presentation about the environment.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-70',
    german: 'die Nachhilfe',
    turkish: 'Özel ders',
    english: 'Tutoring',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Nachhilfeunterricht', 'Privatunterricht'],
    collocations: ['Nachhilfe geben', 'Nachhilfe nehmen'],
    emoji: '👩‍🏫',
    exampleSentence: 'Er braucht Nachhilfe in Mathematik.',
    exampleTranslation: 'Matematikte özel derse ihtiyacı var.',
    exampleTranslationEn: 'He needs tutoring in mathematics.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-71',
    german: 'der Stundenplan',
    turkish: 'Ders programı',
    english: 'Timetable / Schedule',
    article: 'der',
    plural: 'Stundenpläne',
    partOfSpeech: 'noun',
    synonyms: ['Zeitplan'],
    collocations: ['den Stundenplan lesen', 'ein voller Stundenplan'],
    emoji: '📅',
    exampleSentence: 'Mein Stundenplan ist dieses Semester sehr voll.',
    exampleTranslation: 'Bu dönem ders programım çok dolu.',
    exampleTranslationEn: 'My timetable is very full this semester.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-72',
    german: 'wiederholen',
    turkish: 'Tekrarlamak',
    english: 'To repeat / To review',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['nochmals machen', 'rekapitulieren'],
    collocations: ['den Stoff wiederholen', 'eine Klasse wiederholen'],
    emoji: '🔄',
    exampleSentence: 'Wir wiederholen heute die Lektion von gestern.',
    exampleTranslation: 'Bugün dünkü dersi tekrarlıyoruz.',
    exampleTranslationEn: 'Today we are reviewing yesterday\'s lesson.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-73',
    german: 'die Grundschule',
    turkish: 'İlkokul',
    english: 'Primary school / Elementary school',
    article: 'die',
    plural: 'Grundschulen',
    partOfSpeech: 'noun',
    synonyms: ['Volksschule'],
    collocations: ['in die Grundschule gehen', 'die Grundschule beenden'],
    emoji: '🏫',
    exampleSentence: 'Kinder gehen vier Jahre in die Grundschule.',
    exampleTranslation: 'Çocuklar dört yıl ilkokula gider.',
    exampleTranslationEn: 'Children go to primary school for four years.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-74',
    german: 'das Praktikum',
    turkish: 'Staj',
    english: 'Internship',
    article: 'das',
    plural: 'Praktika',
    partOfSpeech: 'noun',
    synonyms: ['Berufspraktikum'],
    collocations: ['ein Praktikum machen', 'ein Praktikum absolvieren'],
    emoji: '💼',
    exampleSentence: 'Im Sommer mache ich ein Praktikum bei einer Firma.',
    exampleTranslation: 'Yazın bir firmada staj yapacağım.',
    exampleTranslationEn: 'In summer I am doing an internship at a company.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-75',
    german: 'sich vorbereiten',
    turkish: 'Hazırlanmak',
    english: 'To prepare',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['vorbereiten', 'planen'],
    collocations: ['sich auf die Prüfung vorbereiten', 'sich gut vorbereiten'],
    emoji: '📋',
    exampleSentence: 'Ich bereite mich auf die Prüfung vor.',
    exampleTranslation: 'Sınava hazırlanıyorum.',
    exampleTranslationEn: 'I am preparing for the exam.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-76',
    german: 'der Kindergarten',
    turkish: 'Anaokulu',
    english: 'Kindergarten',
    article: 'der',
    plural: 'Kindergärten',
    partOfSpeech: 'noun',
    synonyms: ['Kita', 'Vorschule'],
    collocations: ['in den Kindergarten gehen', 'den Kindergarten besuchen'],
    emoji: '🧒',
    exampleSentence: 'Mein Sohn geht in den Kindergarten.',
    exampleTranslation: 'Oğlum anaokuluna gidiyor.',
    exampleTranslationEn: 'My son goes to kindergarten.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-77',
    german: 'das Ergebnis',
    turkish: 'Sonuç',
    english: 'Result',
    article: 'das',
    plural: 'Ergebnisse',
    partOfSpeech: 'noun',
    synonyms: ['Resultat', 'Ausgang'],
    collocations: ['das Ergebnis der Prüfung', 'ein gutes Ergebnis'],
    emoji: '📊',
    exampleSentence: 'Die Ergebnisse der Prüfung sind sehr gut.',
    exampleTranslation: 'Sınav sonuçları çok iyi.',
    exampleTranslationEn: 'The exam results are very good.',
    category: 'education',
    level: 'B1',
  },
  // B2 Level Words (education-78 to education-100)
  {
    id: 'education-78',
    german: 'die Wissenschaft',
    turkish: 'Bilim',
    english: 'Science',
    article: 'die',
    plural: 'Wissenschaften',
    partOfSpeech: 'noun',
    synonyms: ['Forschung'],
    collocations: ['die Naturwissenschaft', 'die Geisteswissenschaft'],
    emoji: '🔬',
    exampleSentence: 'Die Wissenschaft hat viele Fortschritte gemacht.',
    exampleTranslation: 'Bilim birçok ilerleme kaydetti.',
    exampleTranslationEn: 'Science has made many advances.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-79',
    german: 'der Dozent',
    turkish: 'Öğretim görevlisi',
    english: 'Lecturer',
    article: 'der',
    plural: 'Dozenten',
    partOfSpeech: 'noun',
    synonyms: ['Hochschullehrer', 'Lehrender'],
    collocations: ['der Dozent hält eine Vorlesung', 'den Dozenten fragen'],
    emoji: '👨‍🏫',
    exampleSentence: 'Der Dozent gibt uns Feedback zu unseren Arbeiten.',
    exampleTranslation: 'Öğretim görevlisi ödevlerimiz hakkında geri bildirim veriyor.',
    exampleTranslationEn: 'The lecturer gives us feedback on our papers.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-80',
    german: 'die Fakultät',
    turkish: 'Fakülte',
    english: 'Faculty',
    article: 'die',
    plural: 'Fakultäten',
    partOfSpeech: 'noun',
    synonyms: ['Fachbereich'],
    collocations: ['die medizinische Fakultät', 'an der Fakultät studieren'],
    emoji: '🏛️',
    exampleSentence: 'Er studiert an der philosophischen Fakultät.',
    exampleTranslation: 'Felsefe fakültesinde okuyor.',
    exampleTranslationEn: 'He studies at the faculty of philosophy.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-81',
    german: 'der Studiengang',
    turkish: 'Bölüm / Lisans programı',
    english: 'Study program / Degree program',
    article: 'der',
    plural: 'Studiengänge',
    partOfSpeech: 'noun',
    synonyms: ['Studienrichtung', 'Studienfach'],
    collocations: ['einen Studiengang wählen', 'den Studiengang wechseln'],
    emoji: '📚',
    exampleSentence: 'Welchen Studiengang hast du gewählt?',
    exampleTranslation: 'Hangi bölümü seçtin?',
    exampleTranslationEn: 'Which study program did you choose?',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-82',
    german: 'die Bewerbung',
    turkish: 'Başvuru',
    english: 'Application',
    article: 'die',
    plural: 'Bewerbungen',
    partOfSpeech: 'noun',
    synonyms: ['Antrag', 'Anmeldung'],
    collocations: ['eine Bewerbung schreiben', 'die Bewerbung einreichen'],
    emoji: '📨',
    exampleSentence: 'Ich habe meine Bewerbung an die Universität geschickt.',
    exampleTranslation: 'Başvurumu üniversiteye gönderdim.',
    exampleTranslationEn: 'I sent my application to the university.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-83',
    german: 'die Zulassung',
    turkish: 'Kabul',
    english: 'Admission',
    article: 'die',
    plural: 'Zulassungen',
    partOfSpeech: 'noun',
    synonyms: ['Genehmigung', 'Erlaubnis'],
    collocations: ['die Zulassung zum Studium', 'eine Zulassung bekommen'],
    emoji: '✅',
    exampleSentence: 'Er hat die Zulassung zum Medizinstudium erhalten.',
    exampleTranslation: 'Tıp eğitimine kabul aldı.',
    exampleTranslationEn: 'He received admission to medical school.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-84',
    german: 'wissenschaftlich',
    turkish: 'Bilimsel',
    english: 'Scientific / Academic',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['akademisch', 'forschungsbezogen'],
    collocations: ['wissenschaftliche Arbeit', 'wissenschaftliche Methode'],
    emoji: '🔬',
    exampleSentence: 'Sie schreibt eine wissenschaftliche Arbeit.',
    exampleTranslation: 'Bilimsel bir çalışma yazıyor.',
    exampleTranslationEn: 'She is writing a scientific paper.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-85',
    german: 'der Lehrplan',
    turkish: 'Müfredat',
    english: 'Curriculum / Syllabus',
    article: 'der',
    plural: 'Lehrpläne',
    partOfSpeech: 'noun',
    synonyms: ['Curriculum', 'Studienplan'],
    collocations: ['den Lehrplan erstellen', 'im Lehrplan stehen'],
    emoji: '📋',
    exampleSentence: 'Der Lehrplan wird jedes Jahr aktualisiert.',
    exampleTranslation: 'Müfredat her yıl güncellenir.',
    exampleTranslationEn: 'The curriculum is updated every year.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-86',
    german: 'die Bachelorarbeit',
    turkish: 'Lisans tezi',
    english: 'Bachelor thesis',
    article: 'die',
    plural: 'Bachelorarbeiten',
    partOfSpeech: 'noun',
    synonyms: ['Abschlussarbeit'],
    collocations: ['die Bachelorarbeit schreiben', 'die Bachelorarbeit abgeben'],
    emoji: '📄',
    exampleSentence: 'Ich schreibe gerade meine Bachelorarbeit.',
    exampleTranslation: 'Şu anda lisans tezimi yazıyorum.',
    exampleTranslationEn: 'I am currently writing my bachelor thesis.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-87',
    german: 'die Masterarbeit',
    turkish: 'Yüksek lisans tezi',
    english: 'Master thesis',
    article: 'die',
    plural: 'Masterarbeiten',
    partOfSpeech: 'noun',
    synonyms: ['Magisterarbeit'],
    collocations: ['die Masterarbeit verteidigen', 'an der Masterarbeit arbeiten'],
    emoji: '📄',
    exampleSentence: 'Sie hat ihre Masterarbeit erfolgreich verteidigt.',
    exampleTranslation: 'Yüksek lisans tezini başarıyla savundu.',
    exampleTranslationEn: 'She successfully defended her master thesis.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-88',
    german: 'die Mensa',
    turkish: 'Üniversite yemekhanesi',
    english: 'Cafeteria (university)',
    article: 'die',
    plural: 'Mensen',
    partOfSpeech: 'noun',
    synonyms: ['Kantine'],
    collocations: ['in der Mensa essen', 'zur Mensa gehen'],
    emoji: '🍽️',
    exampleSentence: 'Wir essen jeden Tag in der Mensa.',
    exampleTranslation: 'Her gün yemekhanede yemek yiyoruz.',
    exampleTranslationEn: 'We eat in the cafeteria every day.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-89',
    german: 'der Hörsaal',
    turkish: 'Amfi / Konferans salonu',
    english: 'Lecture hall',
    article: 'der',
    plural: 'Hörsäle',
    partOfSpeech: 'noun',
    synonyms: ['Auditorium', 'Vorlesungssaal'],
    collocations: ['im Hörsaal sitzen', 'den Hörsaal finden'],
    emoji: '🏛️',
    exampleSentence: 'Der Hörsaal ist heute voll besetzt.',
    exampleTranslation: 'Amfi bugün tamamen dolu.',
    exampleTranslationEn: 'The lecture hall is fully occupied today.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-90',
    german: 'analysieren',
    turkish: 'Analiz etmek',
    english: 'To analyze',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['untersuchen', 'auswerten'],
    collocations: ['Daten analysieren', 'einen Text analysieren'],
    emoji: '🔍',
    exampleSentence: 'Wir analysieren die Ergebnisse der Studie.',
    exampleTranslation: 'Çalışmanın sonuçlarını analiz ediyoruz.',
    exampleTranslationEn: 'We are analyzing the results of the study.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-91',
    german: 'die Quelle',
    turkish: 'Kaynak',
    english: 'Source',
    article: 'die',
    plural: 'Quellen',
    partOfSpeech: 'noun',
    synonyms: ['Referenz', 'Nachweis'],
    collocations: ['Quellen angeben', 'eine zuverlässige Quelle'],
    emoji: '📑',
    exampleSentence: 'Bitte geben Sie Ihre Quellen an.',
    exampleTranslation: 'Lütfen kaynaklarınızı belirtin.',
    exampleTranslationEn: 'Please cite your sources.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-92',
    german: 'die Frist',
    turkish: 'Son tarih / Süre',
    english: 'Deadline',
    article: 'die',
    plural: 'Fristen',
    partOfSpeech: 'noun',
    synonyms: ['Termin', 'Zeitlimit'],
    collocations: ['die Frist einhalten', 'die Frist verlängern'],
    emoji: '⏰',
    exampleSentence: 'Die Frist für die Bewerbung ist nächste Woche.',
    exampleTranslation: 'Başvuru son tarihi gelecek hafta.',
    exampleTranslationEn: 'The deadline for the application is next week.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-93',
    german: 'der Schwerpunkt',
    turkish: 'Ağırlıklı alan / Odak',
    english: 'Focus / Specialization',
    article: 'der',
    plural: 'Schwerpunkte',
    partOfSpeech: 'noun',
    synonyms: ['Fokus', 'Hauptthema'],
    collocations: ['den Schwerpunkt setzen', 'einen Schwerpunkt wählen'],
    emoji: '🎯',
    exampleSentence: 'Mein Schwerpunkt im Studium ist Linguistik.',
    exampleTranslation: 'Eğitimdeki ağırlıklı alanım dilbilim.',
    exampleTranslationEn: 'My specialization in my studies is linguistics.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-94',
    german: 'die Pflichtveranstaltung',
    turkish: 'Zorunlu ders',
    english: 'Compulsory course',
    article: 'die',
    plural: 'Pflichtveranstaltungen',
    partOfSpeech: 'noun',
    synonyms: ['Pflichtkurs', 'Pflichtfach'],
    collocations: ['eine Pflichtveranstaltung besuchen', 'die Pflichtveranstaltungen belegen'],
    emoji: '📌',
    exampleSentence: 'Diese Vorlesung ist eine Pflichtveranstaltung.',
    exampleTranslation: 'Bu ders zorunlu bir derstir.',
    exampleTranslationEn: 'This lecture is a compulsory course.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-95',
    german: 'das Wahlfach',
    turkish: 'Seçmeli ders',
    english: 'Elective subject',
    article: 'das',
    plural: 'Wahlfächer',
    partOfSpeech: 'noun',
    synonyms: ['Wahlpflichtfach'],
    collocations: ['ein Wahlfach wählen', 'Wahlfächer belegen'],
    emoji: '🔀',
    exampleSentence: 'Kunst ist mein Wahlfach.',
    exampleTranslation: 'Sanat benim seçmeli dersim.',
    exampleTranslationEn: 'Art is my elective subject.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-96',
    german: 'promovieren',
    turkish: 'Doktora yapmak',
    english: 'To do a doctorate',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['den Doktor machen'],
    collocations: ['in Physik promovieren', 'an der Universität promovieren'],
    emoji: '🎓',
    exampleSentence: 'Sie promoviert in Biologie an der Universität Heidelberg.',
    exampleTranslation: 'Heidelberg Üniversitesinde biyoloji doktorası yapıyor.',
    exampleTranslationEn: 'She is doing a doctorate in biology at Heidelberg University.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-97',
    german: 'der Notendurchschnitt',
    turkish: 'Not ortalaması',
    english: 'Grade point average',
    article: 'der',
    plural: 'Notendurchschnitte',
    partOfSpeech: 'noun',
    synonyms: ['Durchschnittsnote'],
    collocations: ['einen guten Notendurchschnitt haben', 'den Notendurchschnitt verbessern'],
    emoji: '📊',
    exampleSentence: 'Mein Notendurchschnitt beträgt 1,8.',
    exampleTranslation: 'Not ortalamam 1,8.',
    exampleTranslationEn: 'My grade point average is 1.8.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-98',
    german: 'die Immatrikulation',
    turkish: 'Üniversite kaydı',
    english: 'Enrollment / Matriculation',
    article: 'die',
    plural: 'Immatrikulationen',
    partOfSpeech: 'noun',
    synonyms: ['Einschreibung'],
    collocations: ['die Immatrikulation vornehmen', 'die Immatrikulationsfrist'],
    emoji: '📋',
    exampleSentence: 'Die Immatrikulation für das Wintersemester beginnt im September.',
    exampleTranslation: 'Kış dönemi için üniversite kaydı Eylül ayında başlıyor.',
    exampleTranslationEn: 'Enrollment for the winter semester begins in September.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-99',
    german: 'die Regelstudienzeit',
    turkish: 'Standart eğitim süresi',
    english: 'Standard period of study',
    article: 'die',
    plural: 'Regelstudienzeiten',
    partOfSpeech: 'noun',
    synonyms: ['Studiendauer'],
    collocations: ['die Regelstudienzeit einhalten', 'innerhalb der Regelstudienzeit'],
    emoji: '⏳',
    exampleSentence: 'Die Regelstudienzeit für den Bachelor beträgt sechs Semester.',
    exampleTranslation: 'Lisans için standart eğitim süresi altı dönemdir.',
    exampleTranslationEn: 'The standard period of study for a bachelor\'s degree is six semesters.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-100',
    german: 'die Exmatrikulation',
    turkish: 'Üniversite kaydının silinmesi',
    english: 'De-registration / Unenrollment',
    article: 'die',
    plural: 'Exmatrikulationen',
    partOfSpeech: 'noun',
    synonyms: ['Abmeldung'],
    collocations: ['die Exmatrikulation beantragen', 'nach der Exmatrikulation'],
    emoji: '📤',
    exampleSentence: 'Nach dem Abschluss erfolgt die Exmatrikulation automatisch.',
    exampleTranslation: 'Mezuniyetten sonra üniversite kaydı otomatik olarak silinir.',
    exampleTranslationEn: 'After graduation, de-registration happens automatically.',
    category: 'education',
    level: 'B2',
  },
];
