import { VocabularyWord } from '@/lib/types';

export const educationWords: VocabularyWord[] = [
  {
    id: 'education-1',
    german: 'die Schule',
    turkish: 'Okul',
    english: 'School',
    article: 'die',
    plural: 'Schulen',
    partOfSpeech: 'noun',
    synonyms: ['Bildungseinrichtung'],
    collocations: ['in die Schule gehen', 'die Schule besuchen'],
    emoji: '🏫',
    exampleSentence: 'Mein Kind geht in die Schule.',
    exampleTranslation: 'Çocuğum okula gidiyor.',
    exampleTranslationEn: 'My child goes to school.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-2',
    german: 'der Lehrer',
    turkish: 'Öğretmen (erkek)',
    english: 'Teacher (male)',
    article: 'der',
    plural: 'Lehrer',
    partOfSpeech: 'noun',
    synonyms: ['Pädagoge', 'Lehrkraft'],
    collocations: ['der strenge Lehrer', 'ein guter Lehrer'],
    emoji: '👨‍🏫',
    exampleSentence: 'Der Lehrer erklärt die Aufgabe.',
    exampleTranslation: 'Öğretmen ödevi açıklıyor.',
    exampleTranslationEn: 'The teacher explains the task.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-3',
    german: 'die Lehrerin',
    turkish: 'Öğretmen (kadın)',
    english: 'Teacher (female)',
    article: 'die',
    plural: 'Lehrerinnen',
    partOfSpeech: 'noun',
    synonyms: ['Pädagogin'],
    collocations: ['die nette Lehrerin', 'unsere Lehrerin'],
    emoji: '👩‍🏫',
    exampleSentence: 'Die Lehrerin ist sehr nett.',
    exampleTranslation: 'Öğretmen çok iyi.',
    exampleTranslationEn: 'The teacher is very nice.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-4',
    german: 'das Buch',
    turkish: 'Kitap',
    english: 'Book',
    article: 'das',
    plural: 'Bücher',
    partOfSpeech: 'noun',
    synonyms: ['Lektüre', 'Werk'],
    collocations: ['ein Buch lesen', 'ein Buch schreiben'],
    emoji: '📚',
    exampleSentence: 'Ich lese ein interessantes Buch.',
    exampleTranslation: 'İlginç bir kitap okuyorum.',
    exampleTranslationEn: 'I am reading an interesting book.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-5',
    german: 'der Stift',
    turkish: 'Kalem',
    english: 'Pen',
    article: 'der',
    plural: 'Stifte',
    partOfSpeech: 'noun',
    synonyms: ['Kugelschreiber', 'Kuli'],
    collocations: ['mit dem Stift schreiben', 'einen Stift leihen'],
    emoji: '✏️',
    exampleSentence: 'Kann ich deinen Stift benutzen?',
    exampleTranslation: 'Kalemini kullanabilir miyim?',
    exampleTranslationEn: 'Can I use your pen?',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-6',
    german: 'das Heft',
    turkish: 'Defter',
    english: 'Notebook',
    article: 'das',
    plural: 'Hefte',
    partOfSpeech: 'noun',
    synonyms: ['Notizbuch', 'Schreibheft'],
    collocations: ['ins Heft schreiben', 'das Heft aufschlagen'],
    emoji: '📓',
    exampleSentence: 'Schreibt die Antwort in euer Heft.',
    exampleTranslation: 'Cevabı defterinize yazın.',
    exampleTranslationEn: 'Write the answer in your notebook.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-7',
    german: 'lernen',
    turkish: 'Öğrenmek',
    english: 'To learn',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['studieren', 'büffeln'],
    collocations: ['Deutsch lernen', 'für die Prüfung lernen'],
    emoji: '📖',
    exampleSentence: 'Ich lerne jeden Tag Deutsch.',
    exampleTranslation: 'Her gün Almanca öğreniyorum.',
    exampleTranslationEn: 'I learn German every day.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-8',
    german: 'schreiben',
    turkish: 'Yazmak',
    english: 'To write',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['verfassen', 'notieren'],
    collocations: ['einen Brief schreiben', 'eine E-Mail schreiben'],
    emoji: '✍️',
    exampleSentence: 'Ich schreibe einen Aufsatz.',
    exampleTranslation: 'Bir kompozisyon yazıyorum.',
    exampleTranslationEn: 'I am writing an essay.',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-9',
    german: 'lesen',
    turkish: 'Okumak',
    english: 'To read',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['durchlesen', 'studieren'],
    collocations: ['ein Buch lesen', 'die Zeitung lesen'],
    emoji: '📖',
    exampleSentence: 'Liest du gerne Bücher?',
    exampleTranslation: 'Kitap okumayı sever misin?',
    exampleTranslationEn: 'Do you like reading books?',
    category: 'education',
    level: 'A1',
  },
  {
    id: 'education-10',
    german: 'die Universität',
    turkish: 'Üniversite',
    english: 'University',
    article: 'die',
    plural: 'Universitäten',
    partOfSpeech: 'noun',
    synonyms: ['Uni', 'Hochschule'],
    collocations: ['an der Universität studieren', 'die Universität besuchen'],
    emoji: '🎓',
    exampleSentence: 'Ich studiere an der Universität Berlin.',
    exampleTranslation: 'Berlin Üniversitesinde okuyorum.',
    exampleTranslationEn: 'I study at the University of Berlin.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-11',
    german: 'die Hausaufgabe',
    turkish: 'Ödev',
    english: 'Homework',
    article: 'die',
    plural: 'Hausaufgaben',
    partOfSpeech: 'noun',
    synonyms: ['Schulaufgabe'],
    collocations: ['Hausaufgaben machen', 'die Hausaufgabe abgeben'],
    emoji: '📝',
    exampleSentence: 'Hast du deine Hausaufgaben gemacht?',
    exampleTranslation: 'Ödevlerini yaptın mı?',
    exampleTranslationEn: 'Have you done your homework?',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-12',
    german: 'die Prüfung',
    turkish: 'Sınav',
    english: 'Exam',
    article: 'die',
    plural: 'Prüfungen',
    partOfSpeech: 'noun',
    synonyms: ['Test', 'Klausur', 'Examen'],
    collocations: ['eine Prüfung bestehen', 'eine Prüfung ablegen'],
    emoji: '📋',
    exampleSentence: 'Morgen habe ich eine wichtige Prüfung.',
    exampleTranslation: 'Yarın önemli bir sınavım var.',
    exampleTranslationEn: 'Tomorrow I have an important exam.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-13',
    german: 'die Note',
    turkish: 'Not',
    english: 'Grade',
    article: 'die',
    plural: 'Noten',
    partOfSpeech: 'noun',
    synonyms: ['Zensur', 'Bewertung'],
    collocations: ['gute Noten bekommen', 'schlechte Noten haben'],
    emoji: '💯',
    exampleSentence: 'Er hat gute Noten in Mathematik.',
    exampleTranslation: 'Matematikte iyi notları var.',
    exampleTranslationEn: 'He has good grades in math.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-14',
    german: 'das Fach',
    turkish: 'Ders / Branş',
    english: 'Subject',
    article: 'das',
    plural: 'Fächer',
    partOfSpeech: 'noun',
    synonyms: ['Unterrichtsfach', 'Disziplin'],
    collocations: ['mein Lieblingsfach', 'ein schwieriges Fach'],
    emoji: '📚',
    exampleSentence: 'Welches Fach magst du am liebsten?',
    exampleTranslation: 'En çok hangi dersi seviyorsun?',
    exampleTranslationEn: 'Which subject do you like the most?',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-15',
    german: 'das Zeugnis',
    turkish: 'Karne',
    english: 'Report card',
    article: 'das',
    plural: 'Zeugnisse',
    partOfSpeech: 'noun',
    synonyms: ['Schulzeugnis'],
    collocations: ['ein gutes Zeugnis', 'das Zeugnis bekommen'],
    emoji: '📜',
    exampleSentence: 'Am Ende des Jahres bekommt jeder ein Zeugnis.',
    exampleTranslation: 'Yıl sonunda herkes karne alır.',
    exampleTranslationEn: 'At the end of the year everyone gets a report card.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-16',
    german: 'der Unterricht',
    turkish: 'Ders',
    english: 'Lesson / Class',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Stunde', 'Kurs'],
    collocations: ['am Unterricht teilnehmen', 'der Unterricht beginnt'],
    emoji: '🏫',
    exampleSentence: 'Der Unterricht beginnt um acht Uhr.',
    exampleTranslation: 'Ders saat sekizde başlıyor.',
    exampleTranslationEn: 'The lesson starts at eight o\'clock.',
    category: 'education',
    level: 'A2',
  },
  {
    id: 'education-17',
    german: 'das Stipendium',
    turkish: 'Burs',
    english: 'Scholarship',
    article: 'das',
    plural: 'Stipendien',
    partOfSpeech: 'noun',
    synonyms: ['Förderung'],
    collocations: ['ein Stipendium bekommen', 'sich um ein Stipendium bewerben'],
    emoji: '🎓',
    exampleSentence: 'Sie hat ein Stipendium für ihr Studium erhalten.',
    exampleTranslation: 'Eğitimi için burs aldı.',
    exampleTranslationEn: 'She received a scholarship for her studies.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-18',
    german: 'die Vorlesung',
    turkish: 'Üniversite dersi',
    english: 'Lecture',
    article: 'die',
    plural: 'Vorlesungen',
    partOfSpeech: 'noun',
    synonyms: ['Vortrag'],
    collocations: ['eine Vorlesung besuchen', 'die Vorlesung halten'],
    emoji: '🎤',
    exampleSentence: 'Die Vorlesung über Philosophie war sehr interessant.',
    exampleTranslation: 'Felsefe dersi çok ilginçti.',
    exampleTranslationEn: 'The lecture on philosophy was very interesting.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-19',
    german: 'die Forschung',
    turkish: 'Araştırma',
    english: 'Research',
    article: 'die',
    plural: 'Forschungen',
    partOfSpeech: 'noun',
    synonyms: ['Untersuchung', 'Studie'],
    collocations: ['Forschung betreiben', 'wissenschaftliche Forschung'],
    emoji: '🔬',
    exampleSentence: 'Die Forschung in der Medizin macht große Fortschritte.',
    exampleTranslation: 'Tıp alanındaki araştırmalar büyük ilerlemeler kaydediyor.',
    exampleTranslationEn: 'Research in medicine is making great progress.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-20',
    german: 'die Bildung',
    turkish: 'Eğitim',
    english: 'Education',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Ausbildung', 'Erziehung'],
    collocations: ['Bildung ist wichtig', 'eine gute Bildung'],
    emoji: '🎓',
    exampleSentence: 'Bildung ist der Schlüssel zum Erfolg.',
    exampleTranslation: 'Eğitim başarının anahtarıdır.',
    exampleTranslationEn: 'Education is the key to success.',
    category: 'education',
    level: 'B1',
  },
  {
    id: 'education-21',
    german: 'die Dissertation',
    turkish: 'Doktora tezi',
    english: 'Dissertation',
    article: 'die',
    plural: 'Dissertationen',
    partOfSpeech: 'noun',
    synonyms: ['Doktorarbeit'],
    collocations: ['die Dissertation schreiben', 'die Dissertation verteidigen'],
    emoji: '📄',
    exampleSentence: 'Er schreibt seine Dissertation über Quantenphysik.',
    exampleTranslation: 'Kuantum fiziği üzerine doktora tezini yazıyor.',
    exampleTranslationEn: 'He is writing his dissertation on quantum physics.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-22',
    german: 'die Weiterbildung',
    turkish: 'İleri eğitim',
    english: 'Further education',
    article: 'die',
    plural: 'Weiterbildungen',
    partOfSpeech: 'noun',
    synonyms: ['Fortbildung'],
    collocations: ['berufliche Weiterbildung', 'eine Weiterbildung machen'],
    emoji: '📈',
    exampleSentence: 'Berufliche Weiterbildung ist heutzutage unverzichtbar.',
    exampleTranslation: 'Mesleki ileri eğitim günümüzde vazgeçilmezdir.',
    exampleTranslationEn: 'Professional further education is indispensable nowadays.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-23',
    german: 'die Facharbeit',
    turkish: 'Bitirme ödevi',
    english: 'Term paper',
    article: 'die',
    plural: 'Facharbeiten',
    partOfSpeech: 'noun',
    synonyms: ['Seminararbeit', 'Hausarbeit'],
    collocations: ['eine Facharbeit schreiben', 'die Facharbeit abgeben'],
    emoji: '📝',
    exampleSentence: 'Die Facharbeit muss bis nächste Woche fertig sein.',
    exampleTranslation: 'Bitirme ödevi gelecek haftaya kadar hazır olmalı.',
    exampleTranslationEn: 'The term paper must be finished by next week.',
    category: 'education',
    level: 'B2',
  },
  {
    id: 'education-24',
    german: 'die Kompetenz',
    turkish: 'Yetkinlik',
    english: 'Competence',
    article: 'die',
    plural: 'Kompetenzen',
    partOfSpeech: 'noun',
    synonyms: ['Fähigkeit', 'Qualifikation'],
    collocations: ['fachliche Kompetenz', 'soziale Kompetenz'],
    emoji: '💪',
    exampleSentence: 'Interkulturelle Kompetenz wird immer wichtiger.',
    exampleTranslation: 'Kültürlerarası yetkinlik giderek daha önemli hale geliyor.',
    exampleTranslationEn: 'Intercultural competence is becoming increasingly important.',
    category: 'education',
    level: 'B2',
  },
];
