import { VocabularyWord } from '@/lib/types';

export const emotionsWords: VocabularyWord[] = [
  {
    id: 'emotions-1',
    german: 'glücklich',
    turkish: 'Mutlu',
    english: 'Happy',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['froh', 'fröhlich', 'zufrieden'],
    antonyms: ['traurig', 'unglücklich'],
    collocations: ['glücklich sein', 'glücklich machen'],
    emoji: '😊',
    exampleSentence: 'Ich bin heute sehr glücklich.',
    exampleTranslation: 'Bugün çok mutluyum.',
    exampleTranslationEn: 'I am very happy today.',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-2',
    german: 'traurig',
    turkish: 'Üzgün',
    english: 'Sad',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['betrübt', 'niedergeschlagen'],
    antonyms: ['glücklich', 'froh'],
    collocations: ['traurig sein', 'traurig aussehen'],
    emoji: '😢',
    exampleSentence: 'Warum bist du so traurig?',
    exampleTranslation: 'Neden bu kadar üzgünsün?',
    exampleTranslationEn: 'Why are you so sad?',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-3',
    german: 'müde',
    turkish: 'Yorgun',
    english: 'Tired',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['erschöpft', 'schlapp'],
    antonyms: ['wach', 'munter'],
    collocations: ['müde sein', 'müde werden'],
    emoji: '😴',
    exampleSentence: 'Ich bin sehr müde nach der Arbeit.',
    exampleTranslation: 'İşten sonra çok yorgunum.',
    exampleTranslationEn: 'I am very tired after work.',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-4',
    german: 'böse',
    turkish: 'Kızgın',
    english: 'Angry',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['wütend', 'zornig', 'sauer'],
    antonyms: ['freundlich', 'nett'],
    collocations: ['böse sein', 'böse werden'],
    emoji: '😠',
    exampleSentence: 'Sei nicht böse auf mich!',
    exampleTranslation: 'Bana kızma!',
    exampleTranslationEn: 'Don\'t be angry with me!',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-5',
    german: 'die Angst',
    turkish: 'Korku',
    english: 'Fear',
    article: 'die',
    plural: 'Ängste',
    partOfSpeech: 'noun',
    synonyms: ['Furcht', 'Schrecken'],
    collocations: ['Angst haben', 'Angst vor etwas'],
    emoji: '😨',
    exampleSentence: 'Ich habe Angst vor Spinnen.',
    exampleTranslation: 'Örümceklerden korkuyorum.',
    exampleTranslationEn: 'I am afraid of spiders.',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-6',
    german: 'die Liebe',
    turkish: 'Aşk / Sevgi',
    english: 'Love',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Zuneigung', 'Hingabe'],
    antonyms: ['Hass'],
    collocations: ['die große Liebe', 'Liebe auf den ersten Blick'],
    emoji: '❤️',
    exampleSentence: 'Die Liebe ist das Schönste im Leben.',
    exampleTranslation: 'Aşk hayattaki en güzel şeydir.',
    exampleTranslationEn: 'Love is the most beautiful thing in life.',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-7',
    german: 'aufgeregt',
    turkish: 'Heyecanlı',
    english: 'Excited',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['begeistert', 'gespannt'],
    antonyms: ['gelassen', 'ruhig'],
    collocations: ['aufgeregt sein', 'ganz aufgeregt'],
    emoji: '🤩',
    exampleSentence: 'Ich bin so aufgeregt wegen der Reise!',
    exampleTranslation: 'Seyahat yüzünden çok heyecanlıyım!',
    exampleTranslationEn: 'I am so excited about the trip!',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-8',
    german: 'überrascht',
    turkish: 'Şaşırmış',
    english: 'Surprised',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['erstaunt', 'verblüfft'],
    collocations: ['überrascht sein', 'überrascht aussehen'],
    emoji: '😲',
    exampleSentence: 'Ich war total überrascht von dem Geschenk.',
    exampleTranslation: 'Hediyeye çok şaşırdım.',
    exampleTranslationEn: 'I was totally surprised by the gift.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-9',
    german: 'stolz',
    turkish: 'Gururlu',
    english: 'Proud',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['selbstbewusst'],
    antonyms: ['beschämt'],
    collocations: ['stolz auf jemanden sein', 'stolz sein'],
    emoji: '🦚',
    exampleSentence: 'Ich bin stolz auf dich!',
    exampleTranslation: 'Seninle gurur duyuyorum!',
    exampleTranslationEn: 'I am proud of you!',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-10',
    german: 'eifersüchtig',
    turkish: 'Kıskanç',
    english: 'Jealous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['neidisch', 'missgünstig'],
    collocations: ['eifersüchtig sein', 'eifersüchtig auf jemanden'],
    emoji: '😒',
    exampleSentence: 'Er ist eifersüchtig auf seinen Bruder.',
    exampleTranslation: 'Kardeşini kıskanıyor.',
    exampleTranslationEn: 'He is jealous of his brother.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-11',
    german: 'nervös',
    turkish: 'Gergin',
    english: 'Nervous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['angespannt', 'unruhig'],
    antonyms: ['ruhig', 'gelassen'],
    collocations: ['nervös sein', 'nervös machen'],
    emoji: '😬',
    exampleSentence: 'Vor der Prüfung bin ich immer nervös.',
    exampleTranslation: 'Sınavdan önce hep gerginim.',
    exampleTranslationEn: 'I am always nervous before the exam.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-12',
    german: 'dankbar',
    turkish: 'Minnettar',
    english: 'Grateful',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['erkenntlich'],
    antonyms: ['undankbar'],
    collocations: ['dankbar sein', 'sehr dankbar'],
    emoji: '🙏',
    exampleSentence: 'Ich bin dir sehr dankbar für deine Hilfe.',
    exampleTranslation: 'Yardımın için sana çok minnettarım.',
    exampleTranslationEn: 'I am very grateful to you for your help.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-13',
    german: 'die Sehnsucht',
    turkish: 'Özlem',
    english: 'Longing / Yearning',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Verlangen', 'Heimweh'],
    collocations: ['Sehnsucht haben', 'Sehnsucht nach der Heimat'],
    emoji: '💭',
    exampleSentence: 'Ich habe große Sehnsucht nach meiner Familie.',
    exampleTranslation: 'Aileme çok özlem duyuyorum.',
    exampleTranslationEn: 'I have a great longing for my family.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-14',
    german: 'enttäuscht',
    turkish: 'Hayal kırıklığına uğramış',
    english: 'Disappointed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['frustriert', 'desillusioniert'],
    collocations: ['enttäuscht sein', 'tief enttäuscht'],
    emoji: '😞',
    exampleSentence: 'Ich bin enttäuscht von dem Ergebnis.',
    exampleTranslation: 'Sonuçtan hayal kırıklığına uğradım.',
    exampleTranslationEn: 'I am disappointed with the result.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-15',
    german: 'begeistert',
    turkish: 'Coşkulu / Hevesli',
    english: 'Enthusiastic',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['fasziniert', 'hingerissen'],
    antonyms: ['gelangweilt'],
    collocations: ['begeistert sein von', 'total begeistert'],
    emoji: '🎉',
    exampleSentence: 'Die Zuschauer waren begeistert von der Aufführung.',
    exampleTranslation: 'Seyirciler gösteriden çok etkilendi.',
    exampleTranslationEn: 'The audience was enthusiastic about the performance.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-16',
    german: 'einsam',
    turkish: 'Yalnız',
    english: 'Lonely',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['allein', 'verlassen'],
    antonyms: ['gesellig'],
    collocations: ['sich einsam fühlen', 'einsam sein'],
    emoji: '🥺',
    exampleSentence: 'In der neuen Stadt fühle ich mich manchmal einsam.',
    exampleTranslation: 'Yeni şehirde bazen kendimi yalnız hissediyorum.',
    exampleTranslationEn: 'In the new city I sometimes feel lonely.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-17',
    german: 'die Gelassenheit',
    turkish: 'Sakinlik / Huzur',
    english: 'Serenity / Composure',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Ruhe', 'Gleichmut'],
    antonyms: ['Aufregung', 'Unruhe'],
    collocations: ['innere Gelassenheit', 'mit Gelassenheit reagieren'],
    emoji: '🧘',
    exampleSentence: 'Sie reagierte mit bewundernswerter Gelassenheit.',
    exampleTranslation: 'Hayranlık verici bir sakinlikle tepki verdi.',
    exampleTranslationEn: 'She reacted with admirable composure.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-18',
    german: 'die Verzweiflung',
    turkish: 'Çaresizlik',
    english: 'Despair',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Hoffnungslosigkeit'],
    antonyms: ['Hoffnung', 'Zuversicht'],
    collocations: ['in Verzweiflung geraten', 'aus Verzweiflung'],
    emoji: '😩',
    exampleSentence: 'Er handelte aus purer Verzweiflung.',
    exampleTranslation: 'Saf çaresizlikten böyle davrandı.',
    exampleTranslationEn: 'He acted out of pure despair.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-19',
    german: 'die Zuversicht',
    turkish: 'Güven / İyimserlik',
    english: 'Confidence / Optimism',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Optimismus', 'Vertrauen'],
    antonyms: ['Pessimismus', 'Zweifel'],
    collocations: ['voller Zuversicht', 'mit Zuversicht in die Zukunft blicken'],
    emoji: '✨',
    exampleSentence: 'Trotz aller Schwierigkeiten blicke ich mit Zuversicht in die Zukunft.',
    exampleTranslation: 'Tüm zorluklara rağmen geleceğe güvenle bakıyorum.',
    exampleTranslationEn: 'Despite all difficulties, I look to the future with confidence.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-20',
    german: 'die Empathie',
    turkish: 'Empati',
    english: 'Empathy',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Mitgefühl', 'Einfühlungsvermögen'],
    collocations: ['Empathie zeigen', 'Empathie empfinden'],
    emoji: '🤝',
    exampleSentence: 'Empathie ist eine wichtige soziale Kompetenz.',
    exampleTranslation: 'Empati önemli bir sosyal beceridir.',
    exampleTranslationEn: 'Empathy is an important social skill.',
    category: 'emotions',
    level: 'B2',
  },
];
