import { VocabularyWord } from '@/lib/types';

export const emotionsWords: VocabularyWord[] = [
  {
    id: 'emotions-1',
    german: 'glücklich',
    turkish: 'Mutlu',
    english: 'Happy',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['froh', 'fröhlich', 'zufrieden'],
    antonyms: ['traurig', 'unglücklich'],
    collocations: ['glücklich sein', 'glücklich machen'],
    emoji: '😊',
    exampleSentence: 'Ich bin heute sehr glücklich.',
    exampleTranslation: 'Bugün çok mutluyum.',
    exampleTranslationEn: 'I am very happy today.',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-2',
    german: 'traurig',
    turkish: 'Üzgün',
    english: 'Sad',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['betrübt', 'niedergeschlagen'],
    antonyms: ['glücklich', 'froh'],
    collocations: ['traurig sein', 'traurig aussehen'],
    emoji: '😢',
    exampleSentence: 'Warum bist du so traurig?',
    exampleTranslation: 'Neden bu kadar üzgünsün?',
    exampleTranslationEn: 'Why are you so sad?',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-3',
    german: 'müde',
    turkish: 'Yorgun',
    english: 'Tired',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['erschöpft', 'schlapp'],
    antonyms: ['wach', 'munter'],
    collocations: ['müde sein', 'müde werden'],
    emoji: '😴',
    exampleSentence: 'Ich bin sehr müde nach der Arbeit.',
    exampleTranslation: 'İşten sonra çok yorgunum.',
    exampleTranslationEn: 'I am very tired after work.',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-4',
    german: 'böse',
    turkish: 'Kızgın',
    english: 'Angry',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['wütend', 'zornig', 'sauer'],
    antonyms: ['freundlich', 'nett'],
    collocations: ['böse sein', 'böse werden'],
    emoji: '😠',
    exampleSentence: 'Sei nicht böse auf mich!',
    exampleTranslation: 'Bana kızma!',
    exampleTranslationEn: 'Don\'t be angry with me!',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-5',
    german: 'die Angst',
    turkish: 'Korku',
    english: 'Fear',
    article: 'die',
    plural: 'Ängste',
    partOfSpeech: 'noun',
    synonyms: ['Furcht', 'Schrecken'],
    collocations: ['Angst haben', 'Angst vor etwas'],
    emoji: '😨',
    exampleSentence: 'Ich habe Angst vor Spinnen.',
    exampleTranslation: 'Örümceklerden korkuyorum.',
    exampleTranslationEn: 'I am afraid of spiders.',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-6',
    german: 'die Liebe',
    turkish: 'Aşk / Sevgi',
    english: 'Love',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Zuneigung', 'Hingabe'],
    antonyms: ['Hass'],
    collocations: ['die große Liebe', 'Liebe auf den ersten Blick'],
    emoji: '❤️',
    exampleSentence: 'Die Liebe ist das Schönste im Leben.',
    exampleTranslation: 'Aşk hayattaki en güzel şeydir.',
    exampleTranslationEn: 'Love is the most beautiful thing in life.',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-7',
    german: 'aufgeregt',
    turkish: 'Heyecanlı',
    english: 'Excited',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['begeistert', 'gespannt'],
    antonyms: ['gelassen', 'ruhig'],
    collocations: ['aufgeregt sein', 'ganz aufgeregt'],
    emoji: '🤩',
    exampleSentence: 'Ich bin so aufgeregt wegen der Reise!',
    exampleTranslation: 'Seyahat yüzünden çok heyecanlıyım!',
    exampleTranslationEn: 'I am so excited about the trip!',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-8',
    german: 'überrascht',
    turkish: 'Şaşırmış',
    english: 'Surprised',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['erstaunt', 'verblüfft'],
    collocations: ['überrascht sein', 'überrascht aussehen'],
    emoji: '😲',
    exampleSentence: 'Ich war total überrascht von dem Geschenk.',
    exampleTranslation: 'Hediyeye çok şaşırdım.',
    exampleTranslationEn: 'I was totally surprised by the gift.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-9',
    german: 'stolz',
    turkish: 'Gururlu',
    english: 'Proud',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['selbstbewusst'],
    antonyms: ['beschämt'],
    collocations: ['stolz auf jemanden sein', 'stolz sein'],
    emoji: '🦚',
    exampleSentence: 'Ich bin stolz auf dich!',
    exampleTranslation: 'Seninle gurur duyuyorum!',
    exampleTranslationEn: 'I am proud of you!',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-10',
    german: 'eifersüchtig',
    turkish: 'Kıskanç',
    english: 'Jealous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['neidisch', 'missgünstig'],
    collocations: ['eifersüchtig sein', 'eifersüchtig auf jemanden'],
    emoji: '😒',
    exampleSentence: 'Er ist eifersüchtig auf seinen Bruder.',
    exampleTranslation: 'Kardeşini kıskanıyor.',
    exampleTranslationEn: 'He is jealous of his brother.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-11',
    german: 'nervös',
    turkish: 'Gergin',
    english: 'Nervous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['angespannt', 'unruhig'],
    antonyms: ['ruhig', 'gelassen'],
    collocations: ['nervös sein', 'nervös machen'],
    emoji: '😬',
    exampleSentence: 'Vor der Prüfung bin ich immer nervös.',
    exampleTranslation: 'Sınavdan önce hep gerginim.',
    exampleTranslationEn: 'I am always nervous before the exam.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-12',
    german: 'dankbar',
    turkish: 'Minnettar',
    english: 'Grateful',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['erkenntlich'],
    antonyms: ['undankbar'],
    collocations: ['dankbar sein', 'sehr dankbar'],
    emoji: '🙏',
    exampleSentence: 'Ich bin dir sehr dankbar für deine Hilfe.',
    exampleTranslation: 'Yardımın için sana çok minnettarım.',
    exampleTranslationEn: 'I am very grateful to you for your help.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-13',
    german: 'die Sehnsucht',
    turkish: 'Özlem',
    english: 'Longing / Yearning',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Verlangen', 'Heimweh'],
    collocations: ['Sehnsucht haben', 'Sehnsucht nach der Heimat'],
    emoji: '💭',
    exampleSentence: 'Ich habe große Sehnsucht nach meiner Familie.',
    exampleTranslation: 'Aileme çok özlem duyuyorum.',
    exampleTranslationEn: 'I have a great longing for my family.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-14',
    german: 'enttäuscht',
    turkish: 'Hayal kırıklığına uğramış',
    english: 'Disappointed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['frustriert', 'desillusioniert'],
    collocations: ['enttäuscht sein', 'tief enttäuscht'],
    emoji: '😞',
    exampleSentence: 'Ich bin enttäuscht von dem Ergebnis.',
    exampleTranslation: 'Sonuçtan hayal kırıklığına uğradım.',
    exampleTranslationEn: 'I am disappointed with the result.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-15',
    german: 'begeistert',
    turkish: 'Coşkulu / Hevesli',
    english: 'Enthusiastic',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['fasziniert', 'hingerissen'],
    antonyms: ['gelangweilt'],
    collocations: ['begeistert sein von', 'total begeistert'],
    emoji: '🎉',
    exampleSentence: 'Die Zuschauer waren begeistert von der Aufführung.',
    exampleTranslation: 'Seyirciler gösteriden çok etkilendi.',
    exampleTranslationEn: 'The audience was enthusiastic about the performance.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-16',
    german: 'einsam',
    turkish: 'Yalnız',
    english: 'Lonely',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['allein', 'verlassen'],
    antonyms: ['gesellig'],
    collocations: ['sich einsam fühlen', 'einsam sein'],
    emoji: '🥺',
    exampleSentence: 'In der neuen Stadt fühle ich mich manchmal einsam.',
    exampleTranslation: 'Yeni şehirde bazen kendimi yalnız hissediyorum.',
    exampleTranslationEn: 'In the new city I sometimes feel lonely.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-17',
    german: 'die Gelassenheit',
    turkish: 'Sakinlik / Huzur',
    english: 'Serenity / Composure',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Ruhe', 'Gleichmut'],
    antonyms: ['Aufregung', 'Unruhe'],
    collocations: ['innere Gelassenheit', 'mit Gelassenheit reagieren'],
    emoji: '🧘',
    exampleSentence: 'Sie reagierte mit bewundernswerter Gelassenheit.',
    exampleTranslation: 'Hayranlık verici bir sakinlikle tepki verdi.',
    exampleTranslationEn: 'She reacted with admirable composure.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-18',
    german: 'die Verzweiflung',
    turkish: 'Çaresizlik',
    english: 'Despair',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Hoffnungslosigkeit'],
    antonyms: ['Hoffnung', 'Zuversicht'],
    collocations: ['in Verzweiflung geraten', 'aus Verzweiflung'],
    emoji: '😩',
    exampleSentence: 'Er handelte aus purer Verzweiflung.',
    exampleTranslation: 'Saf çaresizlikten böyle davrandı.',
    exampleTranslationEn: 'He acted out of pure despair.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-19',
    german: 'die Zuversicht',
    turkish: 'Güven / İyimserlik',
    english: 'Confidence / Optimism',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Optimismus', 'Vertrauen'],
    antonyms: ['Pessimismus', 'Zweifel'],
    collocations: ['voller Zuversicht', 'mit Zuversicht in die Zukunft blicken'],
    emoji: '✨',
    exampleSentence: 'Trotz aller Schwierigkeiten blicke ich mit Zuversicht in die Zukunft.',
    exampleTranslation: 'Tüm zorluklara rağmen geleceğe güvenle bakıyorum.',
    exampleTranslationEn: 'Despite all difficulties, I look to the future with confidence.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-20',
    german: 'die Empathie',
    turkish: 'Empati',
    english: 'Empathy',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Mitgefühl', 'Einfühlungsvermögen'],
    collocations: ['Empathie zeigen', 'Empathie empfinden'],
    emoji: '🤝',
    exampleSentence: 'Empathie ist eine wichtige soziale Kompetenz.',
    exampleTranslation: 'Empati önemli bir sosyal beceridir.',
    exampleTranslationEn: 'Empathy is an important social skill.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-21',
    german: 'fröhlich',
    turkish: 'Neşeli',
    english: 'Cheerful',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['heiter', 'vergnügt'],
    antonyms: ['traurig', 'betrübt'],
    collocations: ['fröhlich sein', 'fröhlich lachen'],
    emoji: '😄',
    exampleSentence: 'Die Kinder sind immer fröhlich.',
    exampleTranslation: 'Çocuklar her zaman neşeli.',
    exampleTranslationEn: 'The children are always cheerful.',
    category: 'emotions',
    level: 'A1',
  },
  {
    id: 'emotions-22',
    german: 'wütend',
    turkish: 'Öfkeli',
    english: 'Furious',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['zornig', 'rasend'],
    antonyms: ['ruhig', 'gelassen'],
    collocations: ['wütend werden', 'wütend auf jemanden sein'],
    emoji: '🤬',
    exampleSentence: 'Er wurde wütend über die Nachricht.',
    exampleTranslation: 'Habere öfkelendi.',
    exampleTranslationEn: 'He became furious about the news.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-23',
    german: 'zufrieden',
    turkish: 'Memnun',
    english: 'Satisfied / Content',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['befriedigt'],
    antonyms: ['unzufrieden'],
    collocations: ['zufrieden sein mit', 'sehr zufrieden'],
    emoji: '😌',
    exampleSentence: 'Ich bin mit dem Ergebnis zufrieden.',
    exampleTranslation: 'Sonuçtan memnunum.',
    exampleTranslationEn: 'I am satisfied with the result.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-24',
    german: 'ängstlich',
    turkish: 'Korkak / Endişeli',
    english: 'Anxious / Fearful',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['furchtsam', 'verängstigt'],
    antonyms: ['mutig', 'furchtlos'],
    collocations: ['ängstlich sein', 'ängstlich reagieren'],
    emoji: '😰',
    exampleSentence: 'Sie ist ein ängstliches Kind.',
    exampleTranslation: 'Korkak bir çocuk.',
    exampleTranslationEn: 'She is a fearful child.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-25',
    german: 'gelangweilt',
    turkish: 'Sıkılmış',
    english: 'Bored',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['desinteressiert'],
    antonyms: ['begeistert', 'fasziniert'],
    collocations: ['sich gelangweilt fühlen', 'gelangweilt aussehen'],
    emoji: '😑',
    exampleSentence: 'Die Schüler waren gelangweilt.',
    exampleTranslation: 'Öğrenciler sıkılmıştı.',
    exampleTranslationEn: 'The students were bored.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-26',
    german: 'verwirrt',
    turkish: 'Kafası karışmış',
    english: 'Confused',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['durcheinander', 'irritiert'],
    collocations: ['verwirrt sein', 'verwirrt aussehen'],
    emoji: '😵‍💫',
    exampleSentence: 'Ich bin total verwirrt.',
    exampleTranslation: 'Kafam çok karışık.',
    exampleTranslationEn: 'I am totally confused.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-27',
    german: 'verlegen',
    turkish: 'Utanmış',
    english: 'Embarrassed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['peinlich berührt'],
    collocations: ['verlegen werden', 'verlegen lächeln'],
    emoji: '😳',
    exampleSentence: 'Er wurde ganz verlegen.',
    exampleTranslation: 'Çok utandı.',
    exampleTranslationEn: 'He became very embarrassed.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-28',
    german: 'erleichtert',
    turkish: 'Rahatlamış',
    english: 'Relieved',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['beruhigt'],
    collocations: ['erleichtert sein', 'erleichtert aufatmen'],
    emoji: '😮‍💨',
    exampleSentence: 'Ich bin erleichtert, dass alles gut ging.',
    exampleTranslation: 'Her şeyin iyi gittiğine rahatladım.',
    exampleTranslationEn: 'I am relieved that everything went well.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-29',
    german: 'schuldig',
    turkish: 'Suçlu',
    english: 'Guilty',
    article: null,
    partOfSpeech: 'adjective',
    antonyms: ['unschuldig'],
    collocations: ['sich schuldig fühlen', 'schuldig sein'],
    emoji: '😔',
    exampleSentence: 'Ich fühle mich schuldig.',
    exampleTranslation: 'Kendimi suçlu hissediyorum.',
    exampleTranslationEn: 'I feel guilty.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-30',
    german: 'neidisch',
    turkish: 'Kıskanç',
    english: 'Envious',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['missgünstig'],
    collocations: ['neidisch sein auf', 'neidisch werden'],
    emoji: '😒',
    exampleSentence: 'Sei nicht neidisch auf andere.',
    exampleTranslation: 'Başkalarını kıskanma.',
    exampleTranslationEn: 'Don\'t be envious of others.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-31',
    german: 'hoffnungsvoll',
    turkish: 'Umutlu',
    english: 'Hopeful',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['optimistisch', 'zuversichtlich'],
    antonyms: ['hoffnungslos'],
    collocations: ['hoffnungsvoll sein', 'hoffnungsvoll in die Zukunft blicken'],
    emoji: '🌅',
    exampleSentence: 'Wir sind hoffnungsvoll für die Zukunft.',
    exampleTranslation: 'Gelecek için umutluyuz.',
    exampleTranslationEn: 'We are hopeful for the future.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-32',
    german: 'frustriert',
    turkish: 'Hüsrana uğramış',
    english: 'Frustrated',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['genervt'],
    collocations: ['frustriert sein', 'zunehmend frustriert'],
    emoji: '😤',
    exampleSentence: 'Ich bin frustriert über den langsamen Fortschritt.',
    exampleTranslation: 'Yavaş ilerleme yüzünden hüsrana uğradım.',
    exampleTranslationEn: 'I am frustrated with the slow progress.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-33',
    german: 'erschrocken',
    turkish: 'Korkmuş / Ürkmüş',
    english: 'Startled / Frightened',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['verängstigt', 'geschockt'],
    collocations: ['erschrocken sein', 'erschrocken aufspringen'],
    emoji: '😱',
    exampleSentence: 'Sie war erschrocken über das laute Geräusch.',
    exampleTranslation: 'Yüksek sesten korktu.',
    exampleTranslationEn: 'She was startled by the loud noise.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-34',
    german: 'gerührt',
    turkish: 'Duygulanmış',
    english: 'Touched / Moved',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['bewegt', 'ergriffen'],
    collocations: ['gerührt sein', 'zu Tränen gerührt'],
    emoji: '🥹',
    exampleSentence: 'Ich war zu Tränen gerührt.',
    exampleTranslation: 'Gözyaşlarına kadar duygulandım.',
    exampleTranslationEn: 'I was moved to tears.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-35',
    german: 'sehnsüchtig',
    turkish: 'Özlem dolu',
    english: 'Longing / Yearning',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['sehnsuchtsvoll'],
    collocations: ['sehnsüchtig warten', 'ein sehnsüchtiger Blick'],
    emoji: '💫',
    exampleSentence: 'Sie wartet sehnsüchtig auf seine Rückkehr.',
    exampleTranslation: 'Onun dönüşünü özlemle bekliyor.',
    exampleTranslationEn: 'She waits longingly for his return.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-36',
    german: 'der Ärger',
    turkish: 'Öfke / Sıkıntı',
    english: 'Anger / Annoyance',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Wut', 'Zorn'],
    collocations: ['Ärger haben', 'Ärger machen'],
    emoji: '😡',
    exampleSentence: 'Er hatte viel Ärger auf der Arbeit.',
    exampleTranslation: 'İşte çok sıkıntısı vardı.',
    exampleTranslationEn: 'He had a lot of trouble at work.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-37',
    german: 'die Freude',
    turkish: 'Sevinç',
    english: 'Joy',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Glück', 'Fröhlichkeit'],
    antonyms: ['Trauer'],
    collocations: ['Freude empfinden', 'vor Freude weinen'],
    emoji: '🎊',
    exampleSentence: 'Die Kinder schrien vor Freude.',
    exampleTranslation: 'Çocuklar sevinçten çığlık attı.',
    exampleTranslationEn: 'The children screamed with joy.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-38',
    german: 'die Trauer',
    turkish: 'Yas / Hüzün',
    english: 'Grief / Mourning',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Traurigkeit', 'Kummer'],
    antonyms: ['Freude'],
    collocations: ['in Trauer sein', 'tiefe Trauer'],
    emoji: '🕊️',
    exampleSentence: 'Die ganze Familie ist in tiefer Trauer.',
    exampleTranslation: 'Tüm aile derin yas içinde.',
    exampleTranslationEn: 'The whole family is in deep mourning.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-39',
    german: 'die Wut',
    turkish: 'Öfke / Hiddet',
    english: 'Rage / Fury',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Zorn', 'Raserei'],
    collocations: ['vor Wut kochen', 'Wut empfinden'],
    emoji: '🔥',
    exampleSentence: 'Er kochte vor Wut.',
    exampleTranslation: 'Öfkeden köpürüyordu.',
    exampleTranslationEn: 'He was boiling with rage.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-40',
    german: 'die Eifersucht',
    turkish: 'Kıskançlık',
    english: 'Jealousy',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Neid'],
    collocations: ['aus Eifersucht', 'blinde Eifersucht'],
    emoji: '💚',
    exampleSentence: 'Eifersucht zerstört jede Beziehung.',
    exampleTranslation: 'Kıskançlık her ilişkiyi yıkar.',
    exampleTranslationEn: 'Jealousy destroys every relationship.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-41',
    german: 'die Hoffnung',
    turkish: 'Umut',
    english: 'Hope',
    article: 'die',
    plural: 'Hoffnungen',
    partOfSpeech: 'noun',
    synonyms: ['Zuversicht'],
    antonyms: ['Hoffnungslosigkeit'],
    collocations: ['Hoffnung haben', 'die Hoffnung aufgeben'],
    emoji: '🌱',
    exampleSentence: 'Gib die Hoffnung nicht auf!',
    exampleTranslation: 'Umudu bırakma!',
    exampleTranslationEn: 'Don\'t give up hope!',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-42',
    german: 'der Neid',
    turkish: 'Haset / Kıskançlık',
    english: 'Envy',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Missgunst'],
    collocations: ['vor Neid platzen', 'Neid empfinden'],
    emoji: '😤',
    exampleSentence: 'Neid ist kein guter Ratgeber.',
    exampleTranslation: 'Kıskançlık iyi bir danışman değildir.',
    exampleTranslationEn: 'Envy is not a good advisor.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-43',
    german: 'die Scham',
    turkish: 'Utanç',
    english: 'Shame',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Schande'],
    collocations: ['vor Scham erröten', 'Scham empfinden'],
    emoji: '😳',
    exampleSentence: 'Er wurde rot vor Scham.',
    exampleTranslation: 'Utançtan kızardı.',
    exampleTranslationEn: 'He blushed with shame.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-44',
    german: 'genervt',
    turkish: 'Sinirlenmiş',
    english: 'Annoyed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['verärgert', 'gereizt'],
    collocations: ['genervt sein', 'total genervt'],
    emoji: '😤',
    exampleSentence: 'Ich bin total genervt von dem Lärm.',
    exampleTranslation: 'Gürültüden çok sinirlenmiş durumdayım.',
    exampleTranslationEn: 'I am totally annoyed by the noise.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-45',
    german: 'entspannt',
    turkish: 'Rahat / Gevşemiş',
    english: 'Relaxed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['locker', 'gelöst'],
    antonyms: ['angespannt', 'gestresst'],
    collocations: ['entspannt sein', 'sich entspannt fühlen'],
    emoji: '😎',
    exampleSentence: 'Nach dem Urlaub bin ich ganz entspannt.',
    exampleTranslation: 'Tatilden sonra çok rahatım.',
    exampleTranslationEn: 'After the vacation I am completely relaxed.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-46',
    german: 'gestresst',
    turkish: 'Stresli',
    english: 'Stressed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['überfordert', 'belastet'],
    antonyms: ['entspannt'],
    collocations: ['gestresst sein', 'sich gestresst fühlen'],
    emoji: '😫',
    exampleSentence: 'Ich bin zurzeit sehr gestresst.',
    exampleTranslation: 'Şu an çok stresli.',
    exampleTranslationEn: 'I am very stressed at the moment.',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-47',
    german: 'deprimiert',
    turkish: 'Bunalımlı / Depresif',
    english: 'Depressed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['niedergeschlagen'],
    collocations: ['deprimiert sein', 'sich deprimiert fühlen'],
    emoji: '😞',
    exampleSentence: 'Sie war nach der Trennung deprimiert.',
    exampleTranslation: 'Ayrılıktan sonra bunalımdaydı.',
    exampleTranslationEn: 'She was depressed after the breakup.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-48',
    german: 'besorgt',
    turkish: 'Endişeli',
    english: 'Worried / Concerned',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['beunruhigt'],
    antonyms: ['unbesorgt', 'sorglos'],
    collocations: ['besorgt sein um', 'ein besorgter Blick'],
    emoji: '😟',
    exampleSentence: 'Die Eltern sind besorgt um ihr Kind.',
    exampleTranslation: 'Ebeveynler çocukları için endişeli.',
    exampleTranslationEn: 'The parents are worried about their child.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-49',
    german: 'beschämt',
    turkish: 'Utanmış / Mahcup',
    english: 'Ashamed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['verschämt'],
    collocations: ['sich beschämt fühlen', 'beschämt schweigen'],
    emoji: '😶',
    exampleSentence: 'Er schwieg beschämt.',
    exampleTranslation: 'Mahcup bir şekilde sustu.',
    exampleTranslationEn: 'He was silent with shame.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-50',
    german: 'fasziniert',
    turkish: 'Büyülenmiş',
    english: 'Fascinated',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['begeistert', 'gebannt'],
    collocations: ['fasziniert sein von', 'fasziniert zuhören'],
    emoji: '🤩',
    exampleSentence: 'Ich bin fasziniert von dieser Stadt.',
    exampleTranslation: 'Bu şehirden büyülenmiş durumdayım.',
    exampleTranslationEn: 'I am fascinated by this city.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-51',
    german: 'verärgert',
    turkish: 'Kızmış',
    english: 'Irritated / Upset',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['sauer', 'aufgebracht'],
    collocations: ['verärgert sein über', 'verärgert reagieren'],
    emoji: '😠',
    exampleSentence: 'Sie war verärgert über seine Verspätung.',
    exampleTranslation: 'Gecikmesine kızmıştı.',
    exampleTranslationEn: 'She was upset about his delay.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-52',
    german: 'verzweifelt',
    turkish: 'Çaresiz',
    english: 'Desperate',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['hoffnungslos'],
    collocations: ['verzweifelt suchen', 'verzweifelt sein'],
    emoji: '😰',
    exampleSentence: 'Er suchte verzweifelt nach einer Lösung.',
    exampleTranslation: 'Çaresizce bir çözüm arıyordu.',
    exampleTranslationEn: 'He desperately searched for a solution.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-53',
    german: 'erstaunt',
    turkish: 'Şaşkın',
    english: 'Astonished',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['verblüfft', 'überrascht'],
    collocations: ['erstaunt sein', 'erstaunt feststellen'],
    emoji: '😮',
    exampleSentence: 'Ich war erstaunt über sein Talent.',
    exampleTranslation: 'Yeteneğine şaşırdım.',
    exampleTranslationEn: 'I was astonished by his talent.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-54',
    german: 'der Kummer',
    turkish: 'Keder / Dert',
    english: 'Grief / Sorrow',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Leid', 'Sorge'],
    collocations: ['Kummer haben', 'jemandem Kummer machen'],
    emoji: '💔',
    exampleSentence: 'Sie hat großen Kummer wegen der Trennung.',
    exampleTranslation: 'Ayrılık yüzünden büyük keder duyuyor.',
    exampleTranslationEn: 'She has great sorrow because of the breakup.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-55',
    german: 'die Langeweile',
    turkish: 'Sıkıntı / Can sıkıntısı',
    english: 'Boredom',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['vor Langeweile sterben', 'Langeweile haben'],
    emoji: '😴',
    exampleSentence: 'Mir ist vor Langeweile fast eingeschlafen.',
    exampleTranslation: 'Can sıkıntısından neredeyse uyuyakaldım.',
    exampleTranslationEn: 'I almost fell asleep from boredom.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-56',
    german: 'die Leidenschaft',
    turkish: 'Tutku',
    english: 'Passion',
    article: 'die',
    plural: 'Leidenschaften',
    partOfSpeech: 'noun',
    synonyms: ['Begeisterung', 'Hingabe'],
    collocations: ['mit Leidenschaft', 'eine Leidenschaft für'],
    emoji: '🔥',
    exampleSentence: 'Er spielt Klavier mit großer Leidenschaft.',
    exampleTranslation: 'Büyük bir tutkuyla piyano çalıyor.',
    exampleTranslationEn: 'He plays piano with great passion.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-57',
    german: 'die Überraschung',
    turkish: 'Sürpriz',
    english: 'Surprise',
    article: 'die',
    plural: 'Überraschungen',
    partOfSpeech: 'noun',
    collocations: ['eine Überraschung planen', 'zu meiner Überraschung'],
    emoji: '🎁',
    exampleSentence: 'Das war eine große Überraschung!',
    exampleTranslation: 'Bu büyük bir sürprizdi!',
    exampleTranslationEn: 'That was a big surprise!',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-58',
    german: 'die Erleichterung',
    turkish: 'Rahatlama',
    english: 'Relief',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['Erleichterung empfinden', 'zu meiner Erleichterung'],
    emoji: '😮‍💨',
    exampleSentence: 'Zu meiner Erleichterung war alles in Ordnung.',
    exampleTranslation: 'Rahatlamama neden olacak şekilde her şey yolundaydı.',
    exampleTranslationEn: 'To my relief, everything was fine.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-59',
    german: 'die Aufregung',
    turkish: 'Heyecan / Telaş',
    english: 'Excitement / Agitation',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Nervosität', 'Spannung'],
    collocations: ['vor Aufregung zittern', 'große Aufregung'],
    emoji: '🫨',
    exampleSentence: 'Die Aufregung vor dem Konzert war groß.',
    exampleTranslation: 'Konser öncesi heyecan büyüktü.',
    exampleTranslationEn: 'The excitement before the concert was great.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-60',
    german: 'die Dankbarkeit',
    turkish: 'Minnettarlık',
    english: 'Gratitude',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Erkenntlichkeit'],
    collocations: ['Dankbarkeit empfinden', 'voller Dankbarkeit'],
    emoji: '🙏',
    exampleSentence: 'Ich empfinde große Dankbarkeit für Ihre Hilfe.',
    exampleTranslation: 'Yardımınız için büyük minnettarlık duyuyorum.',
    exampleTranslationEn: 'I feel great gratitude for your help.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-61',
    german: 'die Begeisterung',
    turkish: 'Coşku',
    english: 'Enthusiasm',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Faszination', 'Schwärmerei'],
    collocations: ['mit Begeisterung', 'Begeisterung wecken'],
    emoji: '🎆',
    exampleSentence: 'Die Begeisterung der Fans war riesig.',
    exampleTranslation: 'Taraftarların coşkusu çok büyüktü.',
    exampleTranslationEn: 'The enthusiasm of the fans was enormous.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-62',
    german: 'der Stolz',
    turkish: 'Gurur',
    english: 'Pride',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Selbstbewusstsein'],
    collocations: ['voller Stolz', 'Stolz empfinden'],
    emoji: '🦁',
    exampleSentence: 'Er war voller Stolz auf seine Tochter.',
    exampleTranslation: 'Kızıyla gurur doluydu.',
    exampleTranslationEn: 'He was full of pride for his daughter.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-63',
    german: 'die Einsamkeit',
    turkish: 'Yalnızlık',
    english: 'Loneliness',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Verlassenheit'],
    collocations: ['unter Einsamkeit leiden', 'tiefe Einsamkeit'],
    emoji: '🌑',
    exampleSentence: 'Die Einsamkeit in der Großstadt kann sehr belastend sein.',
    exampleTranslation: 'Büyük şehirdeki yalnızlık çok yıpratıcı olabilir.',
    exampleTranslationEn: 'Loneliness in the big city can be very distressing.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-64',
    german: 'die Enttäuschung',
    turkish: 'Hayal kırıklığı',
    english: 'Disappointment',
    article: 'die',
    plural: 'Enttäuschungen',
    partOfSpeech: 'noun',
    collocations: ['eine große Enttäuschung', 'Enttäuschung empfinden'],
    emoji: '😞',
    exampleSentence: 'Das Ergebnis war eine große Enttäuschung.',
    exampleTranslation: 'Sonuç büyük bir hayal kırıklığıydı.',
    exampleTranslationEn: 'The result was a big disappointment.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-65',
    german: 'die Ohnmacht',
    turkish: 'Çaresizlik / Güçsüzlük',
    english: 'Helplessness / Powerlessness',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Hilflosigkeit', 'Machtlosigkeit'],
    collocations: ['ein Gefühl der Ohnmacht', 'Ohnmacht empfinden'],
    emoji: '😶',
    exampleSentence: 'Er fühlte eine tiefe Ohnmacht angesichts der Situation.',
    exampleTranslation: 'Durum karşısında derin bir çaresizlik hissetti.',
    exampleTranslationEn: 'He felt a deep helplessness in face of the situation.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-66',
    german: 'die Erregung',
    turkish: 'Heyecan / Uyarılma',
    english: 'Agitation / Arousal',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Aufregung'],
    collocations: ['in Erregung geraten', 'vor Erregung zittern'],
    emoji: '⚡',
    exampleSentence: 'Seine Erregung war deutlich zu spüren.',
    exampleTranslation: 'Heyecanı açıkça hissediliyordu.',
    exampleTranslationEn: 'His agitation was clearly noticeable.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-67',
    german: 'die Demut',
    turkish: 'Alçakgönüllülük',
    english: 'Humility',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Bescheidenheit'],
    antonyms: ['Hochmut', 'Arroganz'],
    collocations: ['Demut zeigen', 'mit Demut'],
    emoji: '🙇',
    exampleSentence: 'Er zeigte große Demut nach seinem Sieg.',
    exampleTranslation: 'Zaferinden sonra büyük alçakgönüllülük gösterdi.',
    exampleTranslationEn: 'He showed great humility after his victory.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-68',
    german: 'die Reue',
    turkish: 'Pişmanlık',
    english: 'Remorse / Regret',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Bedauern'],
    collocations: ['Reue empfinden', 'ohne Reue'],
    emoji: '😔',
    exampleSentence: 'Er empfand tiefe Reue für sein Verhalten.',
    exampleTranslation: 'Davranışı için derin pişmanlık duydu.',
    exampleTranslationEn: 'He felt deep remorse for his behavior.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-69',
    german: 'die Verachtung',
    turkish: 'Küçümseme',
    english: 'Contempt',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Geringschätzung'],
    antonyms: ['Respekt', 'Achtung'],
    collocations: ['Verachtung zeigen', 'voller Verachtung'],
    emoji: '😤',
    exampleSentence: 'Er schaute sie mit Verachtung an.',
    exampleTranslation: 'Ona küçümseyerek baktı.',
    exampleTranslationEn: 'He looked at her with contempt.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-70',
    german: 'die Zärtlichkeit',
    turkish: 'Şefkat',
    english: 'Tenderness',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Sanftheit', 'Liebkosung'],
    collocations: ['Zärtlichkeit zeigen', 'voller Zärtlichkeit'],
    emoji: '🤗',
    exampleSentence: 'Sie streichelte das Baby mit Zärtlichkeit.',
    exampleTranslation: 'Bebeği şefkatle okşadı.',
    exampleTranslationEn: 'She caressed the baby with tenderness.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-71',
    german: 'betrübt',
    turkish: 'Üzüntülü',
    english: 'Sorrowful / Saddened',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['bekümmert', 'traurig'],
    collocations: ['betrübt sein', 'betrübt schweigen'],
    emoji: '🥺',
    exampleSentence: 'Sie war tief betrübt über den Verlust.',
    exampleTranslation: 'Kayıptan dolayı çok üzüntülüydü.',
    exampleTranslationEn: 'She was deeply saddened by the loss.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-72',
    german: 'empört',
    turkish: 'Öfkeli / İsyankâr',
    english: 'Outraged / Indignant',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['entrüstet'],
    collocations: ['empört sein über', 'empört reagieren'],
    emoji: '😡',
    exampleSentence: 'Die Bürger waren empört über die Entscheidung.',
    exampleTranslation: 'Vatandaşlar karara öfkelendi.',
    exampleTranslationEn: 'The citizens were outraged by the decision.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-73',
    german: 'melancholisch',
    turkish: 'Melankolik',
    english: 'Melancholic',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['wehmütig', 'schwermütig'],
    collocations: ['melancholisch sein', 'eine melancholische Stimmung'],
    emoji: '🌧️',
    exampleSentence: 'An Herbsttagen werde ich oft melancholisch.',
    exampleTranslation: 'Sonbahar günlerinde sık sık melankolik oluyorum.',
    exampleTranslationEn: 'On autumn days I often become melancholic.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-74',
    german: 'sentimental',
    turkish: 'Duygusal',
    english: 'Sentimental',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['gefühlvoll', 'rührselig'],
    collocations: ['sentimental werden', 'ein sentimentaler Mensch'],
    emoji: '🥲',
    exampleSentence: 'Bei alten Fotos werde ich immer sentimental.',
    exampleTranslation: 'Eski fotoğraflara bakınca hep duygusallaşıyorum.',
    exampleTranslationEn: 'I always become sentimental with old photos.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-75',
    german: 'überwältigt',
    turkish: 'Bunalmış / Etkilenmiş',
    english: 'Overwhelmed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['ergriffen', 'hingerissen'],
    collocations: ['überwältigt sein', 'emotional überwältigt'],
    emoji: '🤯',
    exampleSentence: 'Ich war überwältigt von der Schönheit der Natur.',
    exampleTranslation: 'Doğanın güzelliğinden çok etkilendim.',
    exampleTranslationEn: 'I was overwhelmed by the beauty of nature.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-76',
    german: 'verbittert',
    turkish: 'Acılaşmış',
    english: 'Embittered',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['erbittert', 'grollend'],
    collocations: ['verbittert sein', 'ein verbitterter Mensch'],
    emoji: '😤',
    exampleSentence: 'Er war verbittert nach der Kündigung.',
    exampleTranslation: 'İşten çıkarılmasından sonra acılaşmıştı.',
    exampleTranslationEn: 'He was embittered after the dismissal.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-77',
    german: 'gleichgültig',
    turkish: 'Kayıtsız',
    english: 'Indifferent',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['teilnahmslos', 'desinteressiert'],
    collocations: ['gleichgültig sein', 'es ist mir gleichgültig'],
    emoji: '😐',
    exampleSentence: 'Es ist mir gleichgültig, was er denkt.',
    exampleTranslation: 'Ne düşündüğü umurumda değil.',
    exampleTranslationEn: 'I am indifferent to what he thinks.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-78',
    german: 'nostalgisch',
    turkish: 'Nostaljik',
    english: 'Nostalgic',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['wehmütig'],
    collocations: ['nostalgisch werden', 'nostalgische Erinnerungen'],
    emoji: '📸',
    exampleSentence: 'Alte Lieder machen mich nostalgisch.',
    exampleTranslation: 'Eski şarkılar beni nostaljik yapıyor.',
    exampleTranslationEn: 'Old songs make me nostalgic.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-79',
    german: 'die Heiterkeit',
    turkish: 'Neşe / Şenlik',
    english: 'Cheerfulness / Merriment',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Fröhlichkeit'],
    antonyms: ['Trübsinn'],
    collocations: ['Heiterkeit verbreiten', 'allgemeine Heiterkeit'],
    emoji: '🌞',
    exampleSentence: 'Seine Witze sorgten für Heiterkeit.',
    exampleTranslation: 'Şakaları neşe yarattı.',
    exampleTranslationEn: 'His jokes caused merriment.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-80',
    german: 'die Wehmut',
    turkish: 'Hüzün / İç burukluğu',
    english: 'Wistfulness',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Melancholie', 'Schwermut'],
    collocations: ['mit Wehmut', 'Wehmut empfinden'],
    emoji: '🍂',
    exampleSentence: 'Sie dachte mit Wehmut an die alten Zeiten.',
    exampleTranslation: 'Eski zamanları hüzünle düşündü.',
    exampleTranslationEn: 'She thought of the old times with wistfulness.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-81',
    german: 'leidenschaftlich',
    turkish: 'Tutkulu',
    english: 'Passionate',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['hingebungsvoll', 'glühend'],
    antonyms: ['leidenschaftslos'],
    collocations: ['leidenschaftlich diskutieren', 'ein leidenschaftlicher Mensch'],
    emoji: '❤️‍🔥',
    exampleSentence: 'Sie ist eine leidenschaftliche Köchin.',
    exampleTranslation: 'Tutkulu bir aşçıdır.',
    exampleTranslationEn: 'She is a passionate cook.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-82',
    german: 'gelassen',
    turkish: 'Sakin / Huzurlu',
    english: 'Calm / Composed',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['ruhig', 'entspannt'],
    antonyms: ['aufgeregt', 'nervös'],
    collocations: ['gelassen bleiben', 'gelassen reagieren'],
    emoji: '🧘',
    exampleSentence: 'Bleib gelassen, es wird alles gut.',
    exampleTranslation: 'Sakin ol, her şey iyi olacak.',
    exampleTranslationEn: 'Stay calm, everything will be fine.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-83',
    german: 'misstrauisch',
    turkish: 'Kuşkucu',
    english: 'Suspicious / Distrustful',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['argwöhnisch', 'skeptisch'],
    antonyms: ['vertrauensvoll'],
    collocations: ['misstrauisch sein', 'misstrauisch werden'],
    emoji: '🤨',
    exampleSentence: 'Er ist misstrauisch gegenüber Fremden.',
    exampleTranslation: 'Yabancılara karşı kuşkucu.',
    exampleTranslationEn: 'He is suspicious of strangers.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-84',
    german: 'sorglos',
    turkish: 'Kaygısız / Tasasız',
    english: 'Carefree',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['unbekümmert', 'leichtlebig'],
    antonyms: ['besorgt', 'ängstlich'],
    collocations: ['sorglos leben', 'sorglose Kindheit'],
    emoji: '🦋',
    exampleSentence: 'Kinder sind oft sorglos.',
    exampleTranslation: 'Çocuklar genellikle kaygısızdır.',
    exampleTranslationEn: 'Children are often carefree.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-85',
    german: 'hilflos',
    turkish: 'Çaresiz',
    english: 'Helpless',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['machtlos'],
    collocations: ['hilflos sein', 'sich hilflos fühlen'],
    emoji: '🆘',
    exampleSentence: 'Ohne Handy fühlte ich mich hilflos.',
    exampleTranslation: 'Telefon olmadan kendimi çaresiz hissettim.',
    exampleTranslationEn: 'Without a phone I felt helpless.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-86',
    german: 'liebevoll',
    turkish: 'Sevgi dolu',
    english: 'Loving / Affectionate',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['zärtlich', 'fürsorglich'],
    collocations: ['liebevoll sein', 'liebevolle Eltern'],
    emoji: '💕',
    exampleSentence: 'Sie ist eine liebevolle Mutter.',
    exampleTranslation: 'Sevgi dolu bir anne.',
    exampleTranslationEn: 'She is a loving mother.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-87',
    german: 'vertraut',
    turkish: 'Tanıdık / Güvenli',
    english: 'Familiar / Intimate',
    article: null,
    partOfSpeech: 'adjective',
    collocations: ['vertraut sein mit', 'eine vertraute Stimme'],
    emoji: '🏡',
    exampleSentence: 'Ihre Stimme klingt vertraut.',
    exampleTranslation: 'Sesi tanıdık geliyor.',
    exampleTranslationEn: 'Her voice sounds familiar.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-88',
    german: 'irritiert',
    turkish: 'Sinirlenmiş / Rahatsız',
    english: 'Irritated',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['verunsichert', 'verwirrt'],
    collocations: ['irritiert sein', 'irritiert reagieren'],
    emoji: '😒',
    exampleSentence: 'Ich war irritiert von seinem Verhalten.',
    exampleTranslation: 'Davranışından rahatsız oldum.',
    exampleTranslationEn: 'I was irritated by his behavior.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-89',
    german: 'panisch',
    turkish: 'Panikli',
    english: 'Panicked',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['kopflos'],
    collocations: ['panisch werden', 'panische Angst'],
    emoji: '🫣',
    exampleSentence: 'Die Leute wurden panisch.',
    exampleTranslation: 'İnsanlar paniğe kapıldı.',
    exampleTranslationEn: 'People became panicked.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-90',
    german: 'der Hass',
    turkish: 'Nefret',
    english: 'Hatred',
    article: 'der',
    partOfSpeech: 'noun',
    antonyms: ['Liebe'],
    collocations: ['Hass empfinden', 'voller Hass'],
    emoji: '🖤',
    exampleSentence: 'Hass zerstört mehr als Liebe heilen kann.',
    exampleTranslation: 'Nefret, sevginin iyileştirebileceğinden fazlasını yıkar.',
    exampleTranslationEn: 'Hatred destroys more than love can heal.',
    category: 'emotions',
    level: 'B1',
  },
  {
    id: 'emotions-91',
    german: 'die Sorge',
    turkish: 'Endişe / Kaygı',
    english: 'Worry / Concern',
    article: 'die',
    plural: 'Sorgen',
    partOfSpeech: 'noun',
    synonyms: ['Besorgnis'],
    collocations: ['sich Sorgen machen', 'keine Sorge'],
    emoji: '😟',
    exampleSentence: 'Mach dir keine Sorgen!',
    exampleTranslation: 'Endişelenme!',
    exampleTranslationEn: 'Don\'t worry!',
    category: 'emotions',
    level: 'A2',
  },
  {
    id: 'emotions-92',
    german: 'die Euphorie',
    turkish: 'Coşku / Öfori',
    english: 'Euphoria',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Hochgefühl'],
    collocations: ['in Euphorie geraten', 'pure Euphorie'],
    emoji: '🎉',
    exampleSentence: 'Nach dem Sieg herrschte Euphorie.',
    exampleTranslation: 'Zaferden sonra coşku hâkimdi.',
    exampleTranslationEn: 'After the victory there was euphoria.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-93',
    german: 'die Bitterkeit',
    turkish: 'Acı / Kırgınlık',
    english: 'Bitterness',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Verbitterung'],
    collocations: ['Bitterkeit empfinden', 'voller Bitterkeit'],
    emoji: '🍋',
    exampleSentence: 'Er sprach ohne Bitterkeit über die Vergangenheit.',
    exampleTranslation: 'Geçmişten acı duymadan bahsetti.',
    exampleTranslationEn: 'He spoke about the past without bitterness.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-94',
    german: 'ausgelassen',
    turkish: 'Coşkun / Neşeli',
    english: 'Exuberant / Boisterous',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['übermütig', 'wild'],
    antonyms: ['ruhig', 'zurückhaltend'],
    collocations: ['ausgelassen feiern', 'ausgelassene Stimmung'],
    emoji: '🥳',
    exampleSentence: 'Die Kinder spielten ausgelassen im Garten.',
    exampleTranslation: 'Çocuklar bahçede coşkuyla oynuyordu.',
    exampleTranslationEn: 'The children played exuberantly in the garden.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-95',
    german: 'niedergeschlagen',
    turkish: 'Moral bozuk',
    english: 'Dejected / Downcast',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['deprimiert', 'bedrückt'],
    collocations: ['niedergeschlagen sein', 'sich niedergeschlagen fühlen'],
    emoji: '😿',
    exampleSentence: 'Nach der Niederlage war er niedergeschlagen.',
    exampleTranslation: 'Yenilgiden sonra morali bozuktu.',
    exampleTranslationEn: 'After the defeat he was dejected.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-96',
    german: 'die Zuneigung',
    turkish: 'Sevgi / Bağlılık',
    english: 'Affection',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Sympathie', 'Hingabe'],
    antonyms: ['Abneigung'],
    collocations: ['Zuneigung zeigen', 'voller Zuneigung'],
    emoji: '💗',
    exampleSentence: 'Sie zeigt ihre Zuneigung durch kleine Gesten.',
    exampleTranslation: 'Sevgisini küçük jestlerle gösteriyor.',
    exampleTranslationEn: 'She shows her affection through small gestures.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-97',
    german: 'die Abneigung',
    turkish: 'Antipatik / Hoşlanmama',
    english: 'Aversion / Dislike',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Widerwille', 'Antipathie'],
    antonyms: ['Zuneigung', 'Sympathie'],
    collocations: ['eine Abneigung haben gegen', 'tiefe Abneigung'],
    emoji: '👎',
    exampleSentence: 'Er hat eine Abneigung gegen Spinat.',
    exampleTranslation: 'Ispanaktan hoşlanmıyor.',
    exampleTranslationEn: 'He has an aversion to spinach.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-98',
    german: 'bedrückt',
    turkish: 'Sıkıntılı / Üzgün',
    english: 'Oppressed / Heavy-hearted',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['betrübt', 'gedrückt'],
    collocations: ['bedrückt sein', 'bedrückt schweigen'],
    emoji: '😶',
    exampleSentence: 'Sie war bedrückt wegen der schlechten Nachrichten.',
    exampleTranslation: 'Kötü haberler yüzünden sıkıntılıydı.',
    exampleTranslationEn: 'She was heavy-hearted because of the bad news.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-99',
    german: 'die Hingabe',
    turkish: 'Adanmışlık',
    english: 'Devotion / Dedication',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Aufopferung', 'Ergebenheit'],
    collocations: ['mit Hingabe', 'voller Hingabe'],
    emoji: '🎯',
    exampleSentence: 'Sie arbeitet mit großer Hingabe.',
    exampleTranslation: 'Büyük bir adanmışlıkla çalışıyor.',
    exampleTranslationEn: 'She works with great dedication.',
    category: 'emotions',
    level: 'B2',
  },
  {
    id: 'emotions-100',
    german: 'die Ehrfurcht',
    turkish: 'Huşu / Saygı',
    english: 'Awe / Reverence',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Respekt', 'Scheu'],
    collocations: ['Ehrfurcht einflößen', 'mit Ehrfurcht'],
    emoji: '🏔️',
    exampleSentence: 'Die Berge flößen mir Ehrfurcht ein.',
    exampleTranslation: 'Dağlar bana huşu veriyor.',
    exampleTranslationEn: 'The mountains inspire awe in me.',
    category: 'emotions',
    level: 'B2',
  },
];
