import { VocabularyWord } from '@/lib/types';

export const familyWords: VocabularyWord[] = [
  {
    id: 'family-1',
    german: 'Mutter',
    turkish: 'Anne',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Mütter',
    synonyms: ['Mama', 'Mutti'],
    antonyms: ['Vater'],
    collocations: ['meine Mutter', 'Mutter werden', 'wie eine Mutter'],
    emoji: '👩',
    exampleSentence: 'Meine Mutter kocht sehr gut.',
    exampleTranslation: 'Annem çok iyi yemek yapar.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-2',
    german: 'Vater',
    turkish: 'Baba',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Väter',
    synonyms: ['Papa', 'Vati'],
    antonyms: ['Mutter'],
    collocations: ['mein Vater', 'Vater werden', 'wie ein Vater'],
    emoji: '👨',
    exampleSentence: 'Mein Vater arbeitet als Ingenieur.',
    exampleTranslation: 'Babam mühendis olarak çalışır.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-3',
    german: 'Bruder',
    turkish: 'Erkek kardeş',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Brüder',
    antonyms: ['Schwester'],
    collocations: ['mein großer Bruder', 'mein kleiner Bruder', 'wie ein Bruder'],
    emoji: '👦',
    exampleSentence: 'Mein Bruder ist älter als ich.',
    exampleTranslation: 'Erkek kardeşim benden büyük.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-4',
    german: 'Schwester',
    turkish: 'Kız kardeş',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Schwestern',
    antonyms: ['Bruder'],
    collocations: ['meine große Schwester', 'meine kleine Schwester', 'wie eine Schwester'],
    emoji: '👧',
    exampleSentence: 'Meine Schwester studiert Medizin.',
    exampleTranslation: 'Kız kardeşim tıp okuyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-5',
    german: 'Kind',
    turkish: 'Çocuk',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Kinder',
    antonyms: ['Erwachsener'],
    collocations: ['ein kleines Kind', 'Kinder bekommen', 'als Kind'],
    emoji: '👶',
    exampleSentence: 'Das Kind spielt im Garten.',
    exampleTranslation: 'Çocuk bahçede oynuyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-6',
    german: 'Sohn',
    turkish: 'Oğul',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Söhne',
    antonyms: ['Tochter'],
    collocations: ['unser Sohn', 'der älteste Sohn', 'Sohn und Tochter'],
    emoji: '👦',
    exampleSentence: 'Unser Sohn geht in die Schule.',
    exampleTranslation: 'Oğlumuz okula gidiyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-7',
    german: 'Tochter',
    turkish: 'Kız',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Töchter',
    antonyms: ['Sohn'],
    collocations: ['unsere Tochter', 'die älteste Tochter', 'Tochter und Sohn'],
    emoji: '👧',
    exampleSentence: 'Unsere Tochter ist fünf Jahre alt.',
    exampleTranslation: 'Kızımız beş yaşında.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-8',
    german: 'Großmutter',
    turkish: 'Büyükanne',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Großmütter',
    synonyms: ['Oma', 'Omi'],
    antonyms: ['Großvater'],
    collocations: ['meine Großmutter', 'bei der Großmutter', 'Großmutter mütterlicherseits'],
    emoji: '👵',
    exampleSentence: 'Meine Großmutter erzählt schöne Geschichten.',
    exampleTranslation: 'Büyükannem güzel hikayeler anlatır.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-9',
    german: 'Großvater',
    turkish: 'Büyükbaba',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Großväter',
    synonyms: ['Opa', 'Opi'],
    antonyms: ['Großmutter'],
    collocations: ['mein Großvater', 'beim Großvater', 'Großvater väterlicherseits'],
    emoji: '👴',
    exampleSentence: 'Mein Großvater ist 80 Jahre alt.',
    exampleTranslation: 'Büyükbabam 80 yaşında.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-10',
    german: 'Eltern',
    turkish: 'Ebeveynler/Anne-baba',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    antonyms: ['Kinder'],
    collocations: ['meine Eltern', 'bei den Eltern wohnen', 'Eltern werden'],
    emoji: '👫',
    exampleSentence: 'Meine Eltern wohnen in Istanbul.',
    exampleTranslation: 'Ailem İstanbul\'da yaşıyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-11',
    german: 'Familie',
    turkish: 'Aile',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Familien',
    collocations: ['eine große Familie', 'Familie gründen', 'in der Familie'],
    emoji: '👨‍👩‍👧‍👦',
    exampleSentence: 'Familie ist sehr wichtig.',
    exampleTranslation: 'Aile çok önemli.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-12',
    german: 'Ehemann',
    turkish: 'Koca/Eş',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Ehemänner',
    synonyms: ['Mann', 'Gatte'],
    antonyms: ['Ehefrau'],
    collocations: ['mein Ehemann', 'ihr Ehemann', 'Ehemann und Ehefrau'],
    emoji: '🤵',
    exampleSentence: 'Mein Ehemann kocht heute.',
    exampleTranslation: 'Kocam bugün yemek yapıyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-13',
    german: 'Ehefrau',
    turkish: 'Karı/Eş',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Ehefrauen',
    synonyms: ['Frau', 'Gattin'],
    antonyms: ['Ehemann'],
    collocations: ['meine Ehefrau', 'seine Ehefrau', 'Ehefrau und Ehemann'],
    emoji: '👰',
    exampleSentence: 'Seine Ehefrau ist Ärztin.',
    exampleTranslation: 'Karısı doktor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-14',
    german: 'Freund',
    turkish: 'Arkadaş (erkek)',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Freunde',
    synonyms: ['Kumpel', 'Kamerad'],
    antonyms: ['Feind'],
    collocations: ['mein bester Freund', 'ein guter Freund', 'Freunde treffen'],
    emoji: '🧑',
    exampleSentence: 'Mein bester Freund heißt Ali.',
    exampleTranslation: 'En iyi arkadaşımın adı Ali.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-15',
    german: 'Freundin',
    turkish: 'Arkadaş (kadın)',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Freundinnen',
    antonyms: ['Feindin'],
    collocations: ['meine beste Freundin', 'eine gute Freundin', 'Freundinnen treffen'],
    emoji: '👩',
    exampleSentence: 'Meine Freundin kommt aus Berlin.',
    exampleTranslation: 'Arkadaşım Berlin\'den.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-16',
    german: 'Onkel',
    turkish: 'Amca/Dayı',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Onkel',
    antonyms: ['Tante'],
    collocations: ['mein Onkel', 'Onkel und Tante', 'beim Onkel'],
    emoji: '👨',
    exampleSentence: 'Mein Onkel wohnt in München.',
    exampleTranslation: 'Amcam Münih\'te yaşıyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-17',
    german: 'Tante',
    turkish: 'Hala/Teyze',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Tanten',
    antonyms: ['Onkel'],
    collocations: ['meine Tante', 'Tante und Onkel', 'bei der Tante'],
    emoji: '👩',
    exampleSentence: 'Meine Tante hat drei Kinder.',
    exampleTranslation: 'Teyzem\'in üç çocuğu var.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-18',
    german: 'Geschwister',
    turkish: 'Kardeşler',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    collocations: ['Geschwister haben', 'meine Geschwister', 'Geschwisterliebe'],
    emoji: '👦👧',
    exampleSentence: 'Hast du Geschwister?',
    exampleTranslation: 'Kardeşin var mı?',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-19',
    german: 'Baby',
    turkish: 'Bebek',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Babys',
    synonyms: ['Säugling', 'Neugeborenes'],
    collocations: ['ein Baby bekommen', 'das Baby füttern', 'das Baby schläft'],
    emoji: '👶',
    exampleSentence: 'Das Baby schläft ruhig.',
    exampleTranslation: 'Bebek sessizce uyuyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-20',
    german: 'Nachbar',
    turkish: 'Komşu',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Nachbarn',
    collocations: ['unser Nachbar', 'der nette Nachbar', 'Nachbarn kennenlernen'],
    emoji: '🏘️',
    exampleSentence: 'Unser Nachbar ist sehr freundlich.',
    exampleTranslation: 'Komşumuz çok arkadaş canlısı.',
    category: 'family',
    level: 'A1',
  },
];
