import { VocabularyWord } from '@/lib/types';

export const familyWords: VocabularyWord[] = [
  {
    id: 'family-1',
    german: 'Mutter',
    turkish: 'Anne',
    english: 'Mother',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Mütter',
    synonyms: ['Mama', 'Mutti'],
    antonyms: ['Vater'],
    collocations: ['meine Mutter', 'Mutter werden', 'wie eine Mutter'],
    emoji: '👩',
    exampleSentence: 'Meine Mutter kocht sehr gut.',
    exampleTranslation: 'Annem çok iyi yemek yapar.',
    exampleTranslationEn: 'My mother cooks very well.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-2',
    german: 'Vater',
    turkish: 'Baba',
    english: 'Father',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Väter',
    synonyms: ['Papa', 'Vati'],
    antonyms: ['Mutter'],
    collocations: ['mein Vater', 'Vater werden', 'wie ein Vater'],
    emoji: '👨',
    exampleSentence: 'Mein Vater arbeitet als Ingenieur.',
    exampleTranslation: 'Babam mühendis olarak çalışır.',
    exampleTranslationEn: 'My father works as an engineer.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-3',
    german: 'Bruder',
    turkish: 'Erkek kardeş',
    english: 'Brother',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Brüder',
    antonyms: ['Schwester'],
    collocations: ['mein großer Bruder', 'mein kleiner Bruder', 'wie ein Bruder'],
    emoji: '👦',
    exampleSentence: 'Mein Bruder ist älter als ich.',
    exampleTranslation: 'Erkek kardeşim benden büyük.',
    exampleTranslationEn: 'My brother is older than me.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-4',
    german: 'Schwester',
    turkish: 'Kız kardeş',
    english: 'Sister',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Schwestern',
    antonyms: ['Bruder'],
    collocations: ['meine große Schwester', 'meine kleine Schwester', 'wie eine Schwester'],
    emoji: '👧',
    exampleSentence: 'Meine Schwester studiert Medizin.',
    exampleTranslation: 'Kız kardeşim tıp okuyor.',
    exampleTranslationEn: 'My sister studies medicine.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-5',
    german: 'Kind',
    turkish: 'Çocuk',
    english: 'Child',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Kinder',
    antonyms: ['Erwachsener'],
    collocations: ['ein kleines Kind', 'Kinder bekommen', 'als Kind'],
    emoji: '👶',
    exampleSentence: 'Das Kind spielt im Garten.',
    exampleTranslation: 'Çocuk bahçede oynuyor.',
    exampleTranslationEn: 'The child is playing in the garden.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-6',
    german: 'Sohn',
    turkish: 'Oğul',
    english: 'Son',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Söhne',
    antonyms: ['Tochter'],
    collocations: ['unser Sohn', 'der älteste Sohn', 'Sohn und Tochter'],
    emoji: '👦',
    exampleSentence: 'Unser Sohn geht in die Schule.',
    exampleTranslation: 'Oğlumuz okula gidiyor.',
    exampleTranslationEn: 'Our son goes to school.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-7',
    german: 'Tochter',
    turkish: 'Kız',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Töchter',
    antonyms: ['Sohn'],
    collocations: ['unsere Tochter', 'die älteste Tochter', 'Tochter und Sohn'],
    emoji: '👧',
    exampleSentence: 'Unsere Tochter ist fünf Jahre alt.',
    exampleTranslation: 'Kızımız beş yaşında.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-8',
    german: 'Großmutter',
    turkish: 'Büyükanne',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Großmütter',
    synonyms: ['Oma', 'Omi'],
    antonyms: ['Großvater'],
    collocations: ['meine Großmutter', 'bei der Großmutter', 'Großmutter mütterlicherseits'],
    emoji: '👵',
    exampleSentence: 'Meine Großmutter erzählt schöne Geschichten.',
    exampleTranslation: 'Büyükannem güzel hikayeler anlatır.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-9',
    german: 'Großvater',
    turkish: 'Büyükbaba',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Großväter',
    synonyms: ['Opa', 'Opi'],
    antonyms: ['Großmutter'],
    collocations: ['mein Großvater', 'beim Großvater', 'Großvater väterlicherseits'],
    emoji: '👴',
    exampleSentence: 'Mein Großvater ist 80 Jahre alt.',
    exampleTranslation: 'Büyükbabam 80 yaşında.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-10',
    german: 'Eltern',
    turkish: 'Ebeveynler/Anne-baba',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    antonyms: ['Kinder'],
    collocations: ['meine Eltern', 'bei den Eltern wohnen', 'Eltern werden'],
    emoji: '👫',
    exampleSentence: 'Meine Eltern wohnen in Istanbul.',
    exampleTranslation: 'Ailem İstanbul\'da yaşıyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-11',
    german: 'Familie',
    turkish: 'Aile',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Familien',
    collocations: ['eine große Familie', 'Familie gründen', 'in der Familie'],
    emoji: '👨‍👩‍👧‍👦',
    exampleSentence: 'Familie ist sehr wichtig.',
    exampleTranslation: 'Aile çok önemli.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-12',
    german: 'Ehemann',
    turkish: 'Koca/Eş',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Ehemänner',
    synonyms: ['Mann', 'Gatte'],
    antonyms: ['Ehefrau'],
    collocations: ['mein Ehemann', 'ihr Ehemann', 'Ehemann und Ehefrau'],
    emoji: '🤵',
    exampleSentence: 'Mein Ehemann kocht heute.',
    exampleTranslation: 'Kocam bugün yemek yapıyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-13',
    german: 'Ehefrau',
    turkish: 'Karı/Eş',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Ehefrauen',
    synonyms: ['Frau', 'Gattin'],
    antonyms: ['Ehemann'],
    collocations: ['meine Ehefrau', 'seine Ehefrau', 'Ehefrau und Ehemann'],
    emoji: '👰',
    exampleSentence: 'Seine Ehefrau ist Ärztin.',
    exampleTranslation: 'Karısı doktor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-14',
    german: 'Freund',
    turkish: 'Arkadaş (erkek)',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Freunde',
    synonyms: ['Kumpel', 'Kamerad'],
    antonyms: ['Feind'],
    collocations: ['mein bester Freund', 'ein guter Freund', 'Freunde treffen'],
    emoji: '🧑',
    exampleSentence: 'Mein bester Freund heißt Ali.',
    exampleTranslation: 'En iyi arkadaşımın adı Ali.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-15',
    german: 'Freundin',
    turkish: 'Arkadaş (kadın)',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Freundinnen',
    antonyms: ['Feindin'],
    collocations: ['meine beste Freundin', 'eine gute Freundin', 'Freundinnen treffen'],
    emoji: '👩',
    exampleSentence: 'Meine Freundin kommt aus Berlin.',
    exampleTranslation: 'Arkadaşım Berlin\'den.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-16',
    german: 'Onkel',
    turkish: 'Amca/Dayı',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Onkel',
    antonyms: ['Tante'],
    collocations: ['mein Onkel', 'Onkel und Tante', 'beim Onkel'],
    emoji: '👨',
    exampleSentence: 'Mein Onkel wohnt in München.',
    exampleTranslation: 'Amcam Münih\'te yaşıyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-17',
    german: 'Tante',
    turkish: 'Hala/Teyze',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Tanten',
    antonyms: ['Onkel'],
    collocations: ['meine Tante', 'Tante und Onkel', 'bei der Tante'],
    emoji: '👩',
    exampleSentence: 'Meine Tante hat drei Kinder.',
    exampleTranslation: 'Teyzem\'in üç çocuğu var.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-18',
    german: 'Geschwister',
    turkish: 'Kardeşler',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    collocations: ['Geschwister haben', 'meine Geschwister', 'Geschwisterliebe'],
    emoji: '👦👧',
    exampleSentence: 'Hast du Geschwister?',
    exampleTranslation: 'Kardeşin var mı?',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-19',
    german: 'Baby',
    turkish: 'Bebek',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Babys',
    synonyms: ['Säugling', 'Neugeborenes'],
    collocations: ['ein Baby bekommen', 'das Baby füttern', 'das Baby schläft'],
    emoji: '👶',
    exampleSentence: 'Das Baby schläft ruhig.',
    exampleTranslation: 'Bebek sessizce uyuyor.',
    category: 'family',
    level: 'A1',
  },
  {
    id: 'family-20',
    german: 'Nachbar',
    turkish: 'Komşu',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Nachbarn',
    collocations: ['unser Nachbar', 'der nette Nachbar', 'Nachbarn kennenlernen'],
    emoji: '🏘️',
    exampleSentence: 'Unser Nachbar ist sehr freundlich.',
    exampleTranslation: 'Komşumuz çok arkadaş canlısı.',
    category: 'family',
    level: 'A1',
  },
  // B1 - Relationships, life events
  {
    id: 'family-b1-1',
    german: 'die Beziehung',
    turkish: 'ilişki',
    english: 'relationship',
    article: 'die',
    plural: 'Beziehungen',
    partOfSpeech: 'noun',
    exampleSentence: 'Sie führen eine glückliche Beziehung.',
    exampleTranslation: 'Mutlu bir ilişki yürütüyorlar.',
    exampleTranslationEn: 'They have a happy relationship.',
    category: 'family',
    level: 'B1',
    tags: ['relationship', 'love'],
  },
  {
    id: 'family-b1-2',
    german: 'sich verloben',
    turkish: 'nişanlanmak',
    english: 'to get engaged',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Sie haben sich letzten Sommer verlobt.',
    exampleTranslation: 'Geçen yaz nişanlandılar.',
    exampleTranslationEn: 'They got engaged last summer.',
    category: 'family',
    level: 'B1',
    tags: ['engagement', 'life-event'],
  },
  {
    id: 'family-b1-3',
    german: 'die Scheidung',
    turkish: 'boşanma',
    english: 'divorce',
    article: 'die',
    plural: 'Scheidungen',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Scheidung war für beide sehr schwer.',
    exampleTranslation: 'Boşanma ikisi için de çok zordu.',
    exampleTranslationEn: 'The divorce was very hard for both of them.',
    category: 'family',
    level: 'B1',
    tags: ['divorce', 'life-event'],
  },
  {
    id: 'family-b1-4',
    german: 'heiraten',
    turkish: 'evlenmek',
    english: 'to marry / to get married',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Sie möchten nächstes Jahr heiraten.',
    exampleTranslation: 'Gelecek yıl evlenmek istiyorlar.',
    exampleTranslationEn: 'They want to get married next year.',
    category: 'family',
    level: 'B1',
    tags: ['marriage', 'life-event'],
  },
  {
    id: 'family-b1-5',
    german: 'der Verwandte',
    turkish: 'akraba',
    english: 'relative',
    article: 'der',
    plural: 'Verwandten',
    partOfSpeech: 'noun',
    exampleSentence: 'Zu Weihnachten besuchen wir unsere Verwandten.',
    exampleTranslation: 'Noel\'de akrabalarımızı ziyaret ediyoruz.',
    exampleTranslationEn: 'At Christmas we visit our relatives.',
    category: 'family',
    level: 'B1',
    tags: ['family', 'relatives'],
  },
  {
    id: 'family-b1-6',
    german: 'sich streiten',
    turkish: 'kavga etmek / tartışmak',
    english: 'to argue / to quarrel',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Die Kinder streiten sich oft um Spielzeug.',
    exampleTranslation: 'Çocuklar sık sık oyuncaklar yüzünden kavga eder.',
    exampleTranslationEn: 'The children often argue about toys.',
    category: 'family',
    level: 'B1',
    tags: ['conflict', 'family'],
  },
  {
    id: 'family-b1-7',
    german: 'sich versöhnen',
    turkish: 'barışmak',
    english: 'to reconcile / to make up',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Nach dem Streit haben sie sich wieder versöhnt.',
    exampleTranslation: 'Kavgadan sonra tekrar barıştılar.',
    exampleTranslationEn: 'After the argument they reconciled again.',
    category: 'family',
    level: 'B1',
    tags: ['reconciliation', 'family'],
  },
  {
    id: 'family-b1-8',
    german: 'die Geburt',
    turkish: 'doğum',
    english: 'birth',
    article: 'die',
    plural: 'Geburten',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Geburt ihres ersten Kindes war ein besonderer Moment.',
    exampleTranslation: 'İlk çocuklarının doğumu özel bir andı.',
    exampleTranslationEn: 'The birth of their first child was a special moment.',
    category: 'family',
    level: 'B1',
    tags: ['birth', 'life-event'],
  },
  {
    id: 'family-b1-9',
    german: 'sich kümmern um',
    turkish: 'ilgilenmek / bakmak',
    english: 'to take care of',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Sie kümmert sich um ihre kranke Mutter.',
    exampleTranslation: 'Hasta annesine bakıyor.',
    exampleTranslationEn: 'She takes care of her sick mother.',
    category: 'family',
    level: 'B1',
    tags: ['care', 'family'],
  },
  {
    id: 'family-b1-10',
    german: 'die Kindheit',
    turkish: 'çocukluk',
    english: 'childhood',
    article: 'die',
    partOfSpeech: 'noun',
    exampleSentence: 'Er hatte eine glückliche Kindheit auf dem Land.',
    exampleTranslation: 'Kırsal bölgede mutlu bir çocukluk geçirdi.',
    exampleTranslationEn: 'He had a happy childhood in the countryside.',
    category: 'family',
    level: 'B1',
    tags: ['childhood', 'life'],
  },
  {
    id: 'family-21',
    german: 'Beziehung',
    turkish: 'İlişki',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Beziehungen',
    emoji: '💑',
    synonyms: ['Verhältnis', 'Partnerschaft'],
    collocations: ['eine Beziehung führen', 'in einer Beziehung sein', 'die Beziehung beenden'],
    exampleSentence: 'Eine gute Beziehung erfordert gegenseitiges Vertrauen und offene Kommunikation.',
    exampleTranslation: 'İyi bir ilişki karşılıklı güven ve açık iletişim gerektirir.',
    category: 'family',
    level: 'B2',
  },
  {
    id: 'family-22',
    german: 'Verlobung',
    turkish: 'Nişan/Nişanlanma',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Verlobungen',
    emoji: '💍',
    synonyms: ['Eheversprechen'],
    collocations: ['die Verlobung feiern', 'die Verlobung bekannt geben', 'die Verlobung lösen'],
    exampleSentence: 'Nach der Verlobung haben sie sofort mit den Hochzeitsvorbereitungen begonnen.',
    exampleTranslation: 'Nişandan sonra hemen düğün hazırlıklarına başladılar.',
    category: 'family',
    level: 'B2',
  },
  {
    id: 'family-23',
    german: 'Hochzeit',
    turkish: 'Düğün/Evlilik',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Hochzeiten',
    emoji: '👰',
    synonyms: ['Trauung', 'Heirat', 'Eheschließung'],
    collocations: ['eine Hochzeit feiern', 'zur Hochzeit einladen', 'die Hochzeit planen'],
    exampleSentence: 'Die Hochzeit fand in einer kleinen Kirche auf dem Land statt und war sehr feierlich.',
    exampleTranslation: 'Düğün kırsalda küçük bir kilisede yapıldı ve çok görkemli oldu.',
    category: 'family',
    level: 'B2',
  },
  {
    id: 'family-24',
    german: 'Scheidung',
    turkish: 'Boşanma',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Scheidungen',
    emoji: '💔',
    synonyms: ['Trennung', 'Eheauflösung'],
    antonyms: ['Hochzeit', 'Heirat'],
    collocations: ['die Scheidung einreichen', 'eine Scheidung durchmachen', 'die Scheidung aussprechen'],
    exampleSentence: 'Nach jahrelangen Konflikten haben sie sich schließlich zur Scheidung entschlossen.',
    exampleTranslation: 'Yıllarca süren çatışmalardan sonra sonunda boşanmaya karar verdiler.',
    category: 'family',
    level: 'B2',
  },
  {
    id: 'family-25',
    german: 'Erziehung',
    turkish: 'Eğitim/Yetiştirme/Terbiye',
    article: 'die',
    partOfSpeech: 'noun',
    emoji: '📚',
    synonyms: ['Bildung', 'Aufzucht'],
    collocations: ['eine strenge Erziehung', 'die Erziehung der Kinder', 'antiautoritäre Erziehung'],
    exampleSentence: 'Die Erziehung von Kindern ist eine der wichtigsten und zugleich schwierigsten Aufgaben der Eltern.',
    exampleTranslation: 'Çocukların yetiştirilmesi ebeveynlerin en önemli ve aynı zamanda en zor görevlerinden biridir.',
    category: 'family',
    level: 'B2',
  },
  {
    id: 'family-26',
    german: 'Schwiegermutter',
    turkish: 'Kayınvalide',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Schwiegermütter',
    emoji: '👩‍🦳',
    antonyms: ['Schwiegervater'],
    collocations: ['meine Schwiegermutter', 'die Schwiegermutter besuchen', 'sich mit der Schwiegermutter verstehen'],
    exampleSentence: 'Meine Schwiegermutter kommt am Wochenende zu Besuch und bleibt eine ganze Woche.',
    exampleTranslation: 'Kayınvalidem hafta sonu ziyarete geliyor ve bir hafta kalacak.',
    category: 'family',
    level: 'B2',
  },
  {
    id: 'family-27',
    german: 'Schwiegervater',
    turkish: 'Kayınpeder',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Schwiegerväter',
    emoji: '👨‍🦳',
    antonyms: ['Schwiegermutter'],
    collocations: ['mein Schwiegervater', 'den Schwiegervater kennenlernen', 'mit dem Schwiegervater reden'],
    exampleSentence: 'Mein Schwiegervater ist ein erfahrener Handwerker und hilft uns oft bei Renovierungen.',
    exampleTranslation: 'Kayınpederim deneyimli bir zanaatkardır ve bize tadilatlarda sık sık yardım eder.',
    category: 'family',
    level: 'B2',
  },
  {
    id: 'family-28',
    german: 'Verwandtschaft',
    turkish: 'Akrabalık/Akrabalar',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Verwandtschaften',
    emoji: '👨‍👩‍👧‍👦',
    synonyms: ['Verwandte', 'Angehörige'],
    collocations: ['die ganze Verwandtschaft', 'entfernte Verwandtschaft', 'die Verwandtschaft einladen'],
    exampleSentence: 'Zu Feiertagen trifft sich die gesamte Verwandtschaft bei meinen Großeltern.',
    exampleTranslation: 'Bayramlarda tüm akrabalar büyükanne ve büyükbabamda bir araya gelir.',
    category: 'family',
    level: 'B2',
  },
  {
    id: 'family-29',
    german: 'alleinerziehend',
    turkish: 'tek ebeveynli/yalnız yetiştiren',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '👨‍👧',
    collocations: ['alleinerziehende Mutter', 'alleinerziehender Vater', 'alleinerziehend sein'],
    exampleSentence: 'Als alleinerziehende Mutter muss sie Beruf und Kindererziehung unter einen Hut bringen.',
    exampleTranslation: 'Tek ebeveyn bir anne olarak iş ve çocuk yetiştirmeyi bir arada yürütmek zorunda.',
    category: 'family',
    level: 'B2',
  },
  {
    id: 'family-30',
    german: 'Zusammenleben',
    turkish: 'Birlikte yaşam',
    article: 'das',
    partOfSpeech: 'noun',
    emoji: '🏠',
    synonyms: ['Zusammenwohnen', 'Lebensgemeinschaft'],
    collocations: ['das Zusammenleben gestalten', 'friedliches Zusammenleben', 'das Zusammenleben regeln'],
    exampleSentence: 'Das Zusammenleben mit einem Partner erfordert Kompromissbereitschaft und gegenseitigen Respekt.',
    exampleTranslation: 'Bir partnerle birlikte yaşam uzlaşma isteği ve karşılıklı saygı gerektirir.',
    category: 'family',
    level: 'B2',
  },
];
