import { VocabularyWord } from '@/lib/types';

export const foodWords: VocabularyWord[] = [
  {
    id: 'food-1',
    german: 'Brot',
    turkish: 'Ekmek',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Brote',
    synonyms: ['Laib', 'Brotlaib'],
    collocations: ['Brot backen', 'frisches Brot', 'Brot schneiden'],
    emoji: '🍞',
    exampleSentence: 'Ich kaufe frisches Brot.',
    exampleTranslation: 'Taze ekmek alıyorum.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-2',
    german: 'Butter',
    turkish: 'Tereyağı',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Margarine'],
    collocations: ['Butter aufs Brot streichen', 'mit Butter kochen', 'weiche Butter'],
    emoji: '🧈',
    exampleSentence: 'Die Butter ist im Kühlschrank.',
    exampleTranslation: 'Tereyağı buzdolabında.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-3',
    german: 'Käse',
    turkish: 'Peynir',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Käse',
    collocations: ['Käse reiben', 'ein Stück Käse', 'Brot mit Käse'],
    emoji: '🧀',
    exampleSentence: 'Ich esse gern Käse.',
    exampleTranslation: 'Peynir yemeyi severim.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-4',
    german: 'Milch',
    turkish: 'Süt',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['ein Glas Milch', 'frische Milch', 'Milch trinken'],
    emoji: '🥛',
    exampleSentence: 'Trinkst du Milch zum Frühstück?',
    exampleTranslation: 'Kahvaltıda süt içer misin?',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-5',
    german: 'Wasser',
    turkish: 'Su',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Wasser',
    collocations: ['ein Glas Wasser', 'stilles Wasser', 'Wasser mit Kohlensäure'],
    emoji: '💧',
    exampleSentence: 'Kann ich ein Glas Wasser haben?',
    exampleTranslation: 'Bir bardak su alabilir miyim?',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-6',
    german: 'Kaffee',
    turkish: 'Kahve',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Kaffees',
    synonyms: ['Mokka'],
    collocations: ['Kaffee trinken', 'eine Tasse Kaffee', 'Kaffee kochen'],
    emoji: '☕',
    exampleSentence: 'Ich trinke morgens Kaffee.',
    exampleTranslation: 'Sabahları kahve içerim.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-7',
    german: 'Tee',
    turkish: 'Çay',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Tees',
    collocations: ['Tee kochen', 'eine Tasse Tee', 'schwarzer Tee'],
    emoji: '🍵',
    exampleSentence: 'Möchten Sie Tee oder Kaffee?',
    exampleTranslation: 'Çay mı kahve mi istersiniz?',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-8',
    german: 'Bier',
    turkish: 'Bira',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Biere',
    collocations: ['ein Bier bestellen', 'Bier vom Fass', 'ein kühles Bier'],
    emoji: '🍺',
    exampleSentence: 'Ein Bier, bitte!',
    exampleTranslation: 'Bir bira, lütfen!',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-9',
    german: 'Fleisch',
    turkish: 'Et',
    article: 'das',
    partOfSpeech: 'noun',
    antonyms: ['Gemüse'],
    collocations: ['Fleisch braten', 'frisches Fleisch', 'Fleisch essen'],
    emoji: '🥩',
    exampleSentence: 'Ich esse kein Fleisch.',
    exampleTranslation: 'Et yemiyorum.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-10',
    german: 'Fisch',
    turkish: 'Balık',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Fische',
    collocations: ['Fisch braten', 'frischer Fisch', 'gegrillter Fisch'],
    emoji: '🐟',
    exampleSentence: 'Der Fisch ist sehr frisch.',
    exampleTranslation: 'Balık çok taze.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-11',
    german: 'Reis',
    turkish: 'Pirinç/Pilav',
    article: 'der',
    partOfSpeech: 'noun',
    collocations: ['Reis kochen', 'Reis mit Gemüse', 'eine Portion Reis'],
    emoji: '🍚',
    exampleSentence: 'Reis mit Gemüse schmeckt gut.',
    exampleTranslation: 'Sebzeli pilav güzel.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-12',
    german: 'Kartoffel',
    turkish: 'Patates',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Kartoffeln',
    synonyms: ['Erdapfel'],
    collocations: ['Kartoffeln schälen', 'Kartoffeln kochen', 'Bratkartoffeln'],
    emoji: '🥔',
    exampleSentence: 'Kartoffeln sind in Deutschland sehr beliebt.',
    exampleTranslation: 'Patates Almanya\'da çok popüler.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-13',
    german: 'Tomate',
    turkish: 'Domates',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Tomaten',
    synonyms: ['Paradeiser'],
    collocations: ['Tomaten schneiden', 'reife Tomaten', 'Tomatensoße'],
    emoji: '🍅',
    exampleSentence: 'Die Tomaten sind rot und reif.',
    exampleTranslation: 'Domatesler kırmızı ve olgun.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-14',
    german: 'Salat',
    turkish: 'Salata',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Salate',
    collocations: ['einen Salat machen', 'gemischter Salat', 'Salat bestellen'],
    emoji: '🥗',
    exampleSentence: 'Ich möchte einen Salat bestellen.',
    exampleTranslation: 'Bir salata sipariş etmek istiyorum.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-15',
    german: 'Obst',
    turkish: 'Meyve',
    article: 'das',
    partOfSpeech: 'noun',
    synonyms: ['Früchte'],
    antonyms: ['Gemüse'],
    collocations: ['frisches Obst', 'Obst essen', 'Obst und Gemüse'],
    emoji: '🍎',
    exampleSentence: 'Obst ist gesund.',
    exampleTranslation: 'Meyve sağlıklıdır.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-16',
    german: 'Apfel',
    turkish: 'Elma',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Äpfel',
    collocations: ['einen Apfel essen', 'Apfelkuchen', 'ein roter Apfel'],
    emoji: '🍏',
    exampleSentence: 'Ich esse jeden Tag einen Apfel.',
    exampleTranslation: 'Her gün bir elma yerim.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-17',
    german: 'Kuchen',
    turkish: 'Pasta/Kek',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Kuchen',
    synonyms: ['Torte', 'Gebäck'],
    collocations: ['Kuchen backen', 'ein Stück Kuchen', 'Kuchen essen'],
    emoji: '🍰',
    exampleSentence: 'Der Kuchen schmeckt lecker.',
    exampleTranslation: 'Pasta çok lezzetli.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-18',
    german: 'Ei',
    turkish: 'Yumurta',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Eier',
    collocations: ['ein Ei kochen', 'Spiegelei', 'Rührei'],
    emoji: '🥚',
    exampleSentence: 'Zum Frühstück esse ich zwei Eier.',
    exampleTranslation: 'Kahvaltıda iki yumurta yerim.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-19',
    german: 'Suppe',
    turkish: 'Çorba',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Suppen',
    synonyms: ['Brühe', 'Eintopf'],
    collocations: ['Suppe kochen', 'eine heiße Suppe', 'Suppe löffeln'],
    emoji: '🍲',
    exampleSentence: 'Die Suppe ist heiß.',
    exampleTranslation: 'Çorba sıcak.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-20',
    german: 'Gemüse',
    turkish: 'Sebze',
    article: 'das',
    partOfSpeech: 'noun',
    antonyms: ['Obst'],
    collocations: ['frisches Gemüse', 'Gemüse schneiden', 'Obst und Gemüse'],
    emoji: '🥦',
    exampleSentence: 'Gemüse ist sehr gesund.',
    exampleTranslation: 'Sebze çok sağlıklı.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-21',
    german: 'Zucker',
    turkish: 'Şeker',
    article: 'der',
    partOfSpeech: 'noun',
    antonyms: ['Salz'],
    collocations: ['Zucker in den Tee tun', 'ohne Zucker', 'ein Löffel Zucker'],
    emoji: '🍬',
    exampleSentence: 'Nehmen Sie Zucker in den Tee?',
    exampleTranslation: 'Çaya şeker alır mısınız?',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-22',
    german: 'Salz',
    turkish: 'Tuz',
    article: 'das',
    partOfSpeech: 'noun',
    antonyms: ['Zucker'],
    collocations: ['Salz und Pfeffer', 'eine Prise Salz', 'Salz streuen'],
    emoji: '🧂',
    exampleSentence: 'Kannst du mir das Salz geben?',
    exampleTranslation: 'Bana tuzu verir misin?',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-23',
    german: 'Schokolade',
    turkish: 'Çikolata',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Schokoladen',
    collocations: ['eine Tafel Schokolade', 'heiße Schokolade', 'dunkle Schokolade'],
    emoji: '🍫',
    exampleSentence: 'Ich liebe Schokolade!',
    exampleTranslation: 'Çikolatayı seviyorum!',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-24',
    german: 'Nudeln',
    turkish: 'Makarna',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    synonyms: ['Pasta', 'Spaghetti'],
    collocations: ['Nudeln kochen', 'Nudeln mit Soße', 'Nudeln al dente'],
    emoji: '🍝',
    exampleSentence: 'Nudeln mit Soße sind lecker.',
    exampleTranslation: 'Soslu makarna lezzetli.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-25',
    german: 'Eis',
    turkish: 'Dondurma',
    article: 'das',
    partOfSpeech: 'noun',
    collocations: ['ein Eis essen', 'eine Kugel Eis', 'Eis am Stiel'],
    emoji: '🍦',
    exampleSentence: 'Im Sommer esse ich gern Eis.',
    exampleTranslation: 'Yazın dondurma yemeyi severim.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-26',
    german: 'Zutaten',
    turkish: 'Malzemeler',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    synonyms: ['Bestandteile', 'Ingredienzien'],
    collocations: ['die Zutaten vorbereiten', 'frische Zutaten verwenden', 'alle Zutaten vermischen'],
    emoji: '🧾',
    exampleSentence: 'Für dieses Rezept brauchen wir nur wenige Zutaten.',
    exampleTranslation: 'Bu tarif için sadece birkaç malzemeye ihtiyacımız var.',
    category: 'food',
    level: 'B2',
    tags: ['cooking', 'preparation'],
  },
  {
    id: 'food-27',
    german: 'Rezept',
    turkish: 'Tarif',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Rezepte',
    synonyms: ['Kochanleitung', 'Zubereitungsanleitung'],
    collocations: ['ein Rezept ausprobieren', 'ein Rezept nachkochen', 'das Rezept befolgen'],
    emoji: '📖',
    exampleSentence: 'Das Rezept stammt von meiner Großmutter und wird seit Generationen weitergegeben.',
    exampleTranslation: 'Tarif büyükannemden geliyor ve nesillerdir aktarılıyor.',
    category: 'food',
    level: 'B2',
    tags: ['cooking', 'tradition'],
  },
  {
    id: 'food-28',
    german: 'würzen',
    turkish: 'baharatlamak',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['abschmecken', 'verfeinern'],
    collocations: ['das Essen würzen', 'mit Pfeffer würzen', 'nach Geschmack würzen'],
    emoji: '🌶️',
    exampleSentence: 'Man sollte das Gericht erst am Ende mit frischen Kräutern würzen.',
    exampleTranslation: 'Yemeği ancak sonunda taze otlarla baharatlamalısınız.',
    category: 'food',
    level: 'B2',
    tags: ['cooking', 'seasoning'],
  },
  {
    id: 'food-29',
    german: 'Beilage',
    turkish: 'Garnitür/Yan yemek',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Beilagen',
    synonyms: ['Zuspeise', 'Nebengericht'],
    collocations: ['als Beilage servieren', 'eine Beilage wählen', 'Reis als Beilage'],
    emoji: '🥗',
    exampleSentence: 'Als Beilage empfehle ich Ihnen gebratenes Gemüse oder Kartoffelpüree.',
    exampleTranslation: 'Garnitür olarak size kızarmış sebze veya patates püresi öneriyorum.',
    category: 'food',
    level: 'B2',
    tags: ['restaurant', 'dining'],
  },
  {
    id: 'food-30',
    german: 'Vorspeise',
    turkish: 'Başlangıç/Meze',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Vorspeisen',
    synonyms: ['Appetithappen', 'Starter'],
    antonyms: ['Nachspeise', 'Hauptgericht'],
    collocations: ['eine Vorspeise bestellen', 'als Vorspeise nehmen', 'eine kalte Vorspeise'],
    emoji: '🥄',
    exampleSentence: 'Als Vorspeise nehme ich die Kürbissuppe mit gerösteten Kernen.',
    exampleTranslation: 'Başlangıç olarak kavrulmuş çekirdekli balkabağı çorbasını alacağım.',
    category: 'food',
    level: 'B2',
    tags: ['restaurant', 'dining'],
  },
  {
    id: 'food-31',
    german: 'Nachspeise',
    turkish: 'Tatlı',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Nachspeisen',
    synonyms: ['Dessert', 'Nachtisch'],
    antonyms: ['Vorspeise'],
    collocations: ['eine Nachspeise bestellen', 'als Nachspeise essen', 'die Nachspeise genießen'],
    emoji: '🍮',
    exampleSentence: 'Die Nachspeise war ein hausgemachtes Tiramisu mit frischen Beeren.',
    exampleTranslation: 'Tatlı, taze meyvelerin eşlik ettiği ev yapımı bir tiramisuydu.',
    category: 'food',
    level: 'B2',
    tags: ['restaurant', 'dessert'],
  },
  {
    id: 'food-32',
    german: 'braten',
    turkish: 'kızartmak',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['anbraten', 'rösten'],
    antonyms: ['kochen', 'dämpfen'],
    collocations: ['in der Pfanne braten', 'das Fleisch braten', 'scharf anbraten'],
    emoji: '🍳',
    exampleSentence: 'Braten Sie das Fleisch bei starker Hitze scharf an, damit es eine Kruste bekommt.',
    exampleTranslation: 'Eti kabuk oluşması için yüksek ateşte kızartın.',
    category: 'food',
    level: 'B2',
    tags: ['cooking', 'technique'],
  },
  {
    id: 'food-33',
    german: 'kochen',
    turkish: 'pişirmek/kaynatmak',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['zubereiten', 'garen', 'sieden'],
    antonyms: ['braten', 'backen'],
    collocations: ['das Wasser kochen', 'das Essen kochen', 'nach Rezept kochen'],
    emoji: '🍲',
    exampleSentence: 'Wenn man Nudeln kocht, sollte man reichlich gesalzenes Wasser verwenden.',
    exampleTranslation: 'Makarna pişirirken bol tuzlu su kullanmalısınız.',
    category: 'food',
    level: 'B2',
    tags: ['cooking', 'technique'],
  },
  {
    id: 'food-34',
    german: 'Ernährung',
    turkish: 'Beslenme',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Nahrung', 'Kost', 'Diät'],
    collocations: ['eine gesunde Ernährung', 'auf die Ernährung achten', 'ausgewogene Ernährung'],
    emoji: '🥦',
    exampleSentence: 'Eine ausgewogene Ernährung ist die Grundlage für ein gesundes Leben.',
    exampleTranslation: 'Dengeli beslenme, sağlıklı bir yaşamın temelidir.',
    category: 'food',
    level: 'B2',
    tags: ['health', 'nutrition'],
  },
  {
    id: 'food-35',
    german: 'Geschmack',
    turkish: 'Tat/Lezzet',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Geschmäcker',
    synonyms: ['Aroma', 'Würze'],
    collocations: ['einen guten Geschmack haben', 'der Geschmack ist intensiv', 'Geschmackssache'],
    emoji: '👅',
    exampleSentence: 'Der intensive Geschmack dieser Soße kommt von den langsam gekochten Tomaten.',
    exampleTranslation: 'Bu sosun yoğun lezzeti yavaş pişirilmiş domateslerden geliyor.',
    category: 'food',
    level: 'B2',
    tags: ['taste', 'sensation'],
  },
];
