import { VocabularyWord } from '@/lib/types';

export const foodWords: VocabularyWord[] = [
  {
    id: 'food-1',
    german: 'Brot',
    turkish: 'Ekmek',
    english: 'Bread',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Brote',
    synonyms: ['Laib', 'Brotlaib'],
    collocations: ['Brot backen', 'frisches Brot', 'Brot schneiden'],
    emoji: '🍞',
    exampleSentence: 'Ich kaufe frisches Brot.',
    exampleTranslation: 'Taze ekmek alıyorum.',
    exampleTranslationEn: 'I buy fresh bread.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-2',
    german: 'Butter',
    turkish: 'Tereyağı',
    english: 'Butter',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Margarine'],
    collocations: ['Butter aufs Brot streichen', 'mit Butter kochen', 'weiche Butter'],
    emoji: '🧈',
    exampleSentence: 'Die Butter ist im Kühlschrank.',
    exampleTranslation: 'Tereyağı buzdolabında.',
    exampleTranslationEn: 'The butter is in the fridge.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-3',
    german: 'Käse',
    turkish: 'Peynir',
    english: 'Cheese',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Käse',
    collocations: ['Käse reiben', 'ein Stück Käse', 'Brot mit Käse'],
    emoji: '🧀',
    exampleSentence: 'Ich esse gern Käse.',
    exampleTranslation: 'Peynir yemeyi severim.',
    exampleTranslationEn: 'I like to eat cheese.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-4',
    german: 'Milch',
    turkish: 'Süt',
    english: 'Milk',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['ein Glas Milch', 'frische Milch', 'Milch trinken'],
    emoji: '🥛',
    exampleSentence: 'Trinkst du Milch zum Frühstück?',
    exampleTranslation: 'Kahvaltıda süt içer misin?',
    exampleTranslationEn: 'Do you drink milk for breakfast?',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-5',
    german: 'Wasser',
    turkish: 'Su',
    english: 'Water',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Wasser',
    collocations: ['ein Glas Wasser', 'stilles Wasser', 'Wasser mit Kohlensäure'],
    emoji: '💧',
    exampleSentence: 'Kann ich ein Glas Wasser haben?',
    exampleTranslation: 'Bir bardak su alabilir miyim?',
    exampleTranslationEn: 'Can I have a glass of water?',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-6',
    german: 'Kaffee',
    turkish: 'Kahve',
    english: 'Coffee',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Kaffees',
    synonyms: ['Mokka'],
    collocations: ['Kaffee trinken', 'eine Tasse Kaffee', 'Kaffee kochen'],
    emoji: '☕',
    exampleSentence: 'Ich trinke morgens Kaffee.',
    exampleTranslation: 'Sabahları kahve içerim.',
    exampleTranslationEn: 'I drink coffee in the morning.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-7',
    german: 'Tee',
    turkish: 'Çay',
    english: 'Tea',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Tees',
    collocations: ['Tee kochen', 'eine Tasse Tee', 'schwarzer Tee'],
    emoji: '🍵',
    exampleSentence: 'Möchten Sie Tee oder Kaffee?',
    exampleTranslation: 'Çay mı kahve mi istersiniz?',
    exampleTranslationEn: 'Would you like tea or coffee?',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-8',
    german: 'Bier',
    turkish: 'Bira',
    english: 'Beer',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Biere',
    collocations: ['ein Bier bestellen', 'Bier vom Fass', 'ein kühles Bier'],
    emoji: '🍺',
    exampleSentence: 'Ein Bier, bitte!',
    exampleTranslation: 'Bir bira, lütfen!',
    exampleTranslationEn: 'A beer, please!',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-9',
    german: 'Fleisch',
    turkish: 'Et',
    english: 'Meat',
    article: 'das',
    partOfSpeech: 'noun',
    antonyms: ['Gemüse'],
    collocations: ['Fleisch braten', 'frisches Fleisch', 'Fleisch essen'],
    emoji: '🥩',
    exampleSentence: 'Ich esse kein Fleisch.',
    exampleTranslation: 'Et yemiyorum.',
    exampleTranslationEn: 'I do not eat meat.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-10',
    german: 'Fisch',
    turkish: 'Balık',
    english: 'Fish',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Fische',
    collocations: ['Fisch braten', 'frischer Fisch', 'gegrillter Fisch'],
    emoji: '🐟',
    exampleSentence: 'Der Fisch ist sehr frisch.',
    exampleTranslation: 'Balık çok taze.',
    exampleTranslationEn: 'The fish is very fresh.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-11',
    german: 'Reis',
    turkish: 'Pirinç/Pilav',
    english: 'Rice',
    article: 'der',
    partOfSpeech: 'noun',
    collocations: ['Reis kochen', 'Reis mit Gemüse', 'eine Portion Reis'],
    emoji: '🍚',
    exampleSentence: 'Reis mit Gemüse schmeckt gut.',
    exampleTranslation: 'Sebzeli pilav güzel.',
    exampleTranslationEn: 'Rice with vegetables tastes good.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-12',
    german: 'Kartoffel',
    turkish: 'Patates',
    english: 'Potato',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Kartoffeln',
    synonyms: ['Erdapfel'],
    collocations: ['Kartoffeln schälen', 'Kartoffeln kochen', 'Bratkartoffeln'],
    emoji: '🥔',
    exampleSentence: 'Kartoffeln sind in Deutschland sehr beliebt.',
    exampleTranslation: 'Patates Almanya\'da çok popüler.',
    exampleTranslationEn: 'Potatoes are very popular in Germany.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-13',
    german: 'Tomate',
    turkish: 'Domates',
    english: 'Tomato',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Tomaten',
    synonyms: ['Paradeiser'],
    collocations: ['Tomaten schneiden', 'reife Tomaten', 'Tomatensoße'],
    emoji: '🍅',
    exampleSentence: 'Die Tomaten sind rot und reif.',
    exampleTranslation: 'Domatesler kırmızı ve olgun.',
    exampleTranslationEn: 'The tomatoes are red and ripe.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-14',
    german: 'Salat',
    turkish: 'Salata',
    english: 'Salad',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Salate',
    collocations: ['einen Salat machen', 'gemischter Salat', 'Salat bestellen'],
    emoji: '🥗',
    exampleSentence: 'Ich möchte einen Salat bestellen.',
    exampleTranslation: 'Bir salata sipariş etmek istiyorum.',
    exampleTranslationEn: 'I would like to order a salad.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-15',
    german: 'Obst',
    turkish: 'Meyve',
    english: 'Fruit',
    article: 'das',
    partOfSpeech: 'noun',
    synonyms: ['Früchte'],
    antonyms: ['Gemüse'],
    collocations: ['frisches Obst', 'Obst essen', 'Obst und Gemüse'],
    emoji: '🍎',
    exampleSentence: 'Obst ist gesund.',
    exampleTranslation: 'Meyve sağlıklıdır.',
    exampleTranslationEn: 'Fruit is healthy.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-16',
    german: 'Apfel',
    turkish: 'Elma',
    english: 'Apple',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Äpfel',
    collocations: ['einen Apfel essen', 'Apfelkuchen', 'ein roter Apfel'],
    emoji: '🍏',
    exampleSentence: 'Ich esse jeden Tag einen Apfel.',
    exampleTranslation: 'Her gün bir elma yerim.',
    exampleTranslationEn: 'I eat an apple every day.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-17',
    german: 'Kuchen',
    turkish: 'Pasta/Kek',
    english: 'Cake',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Kuchen',
    synonyms: ['Torte', 'Gebäck'],
    collocations: ['Kuchen backen', 'ein Stück Kuchen', 'Kuchen essen'],
    emoji: '🍰',
    exampleSentence: 'Der Kuchen schmeckt lecker.',
    exampleTranslation: 'Pasta çok lezzetli.',
    exampleTranslationEn: 'The cake tastes delicious.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-18',
    german: 'Ei',
    turkish: 'Yumurta',
    english: 'Egg',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Eier',
    collocations: ['ein Ei kochen', 'Spiegelei', 'Rührei'],
    emoji: '🥚',
    exampleSentence: 'Zum Frühstück esse ich zwei Eier.',
    exampleTranslation: 'Kahvaltıda iki yumurta yerim.',
    exampleTranslationEn: 'For breakfast I eat two eggs.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-19',
    german: 'Suppe',
    turkish: 'Çorba',
    english: 'Soup',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Suppen',
    synonyms: ['Brühe', 'Eintopf'],
    collocations: ['Suppe kochen', 'eine heiße Suppe', 'Suppe löffeln'],
    emoji: '🍲',
    exampleSentence: 'Die Suppe ist heiß.',
    exampleTranslation: 'Çorba sıcak.',
    exampleTranslationEn: 'The soup is hot.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-20',
    german: 'Gemüse',
    turkish: 'Sebze',
    english: 'Vegetables',
    article: 'das',
    partOfSpeech: 'noun',
    antonyms: ['Obst'],
    collocations: ['frisches Gemüse', 'Gemüse schneiden', 'Obst und Gemüse'],
    emoji: '🥦',
    exampleSentence: 'Gemüse ist sehr gesund.',
    exampleTranslation: 'Sebze çok sağlıklı.',
    exampleTranslationEn: 'Vegetables are very healthy.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-21',
    german: 'Zucker',
    turkish: 'Şeker',
    english: 'Sugar',
    article: 'der',
    partOfSpeech: 'noun',
    antonyms: ['Salz'],
    collocations: ['Zucker in den Tee tun', 'ohne Zucker', 'ein Löffel Zucker'],
    emoji: '🍬',
    exampleSentence: 'Nehmen Sie Zucker in den Tee?',
    exampleTranslation: 'Çaya şeker alır mısınız?',
    exampleTranslationEn: 'Do you take sugar in your tea?',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-22',
    german: 'Salz',
    turkish: 'Tuz',
    english: 'Salt',
    article: 'das',
    partOfSpeech: 'noun',
    antonyms: ['Zucker'],
    collocations: ['Salz und Pfeffer', 'eine Prise Salz', 'Salz streuen'],
    emoji: '🧂',
    exampleSentence: 'Kannst du mir das Salz geben?',
    exampleTranslation: 'Bana tuzu verir misin?',
    exampleTranslationEn: 'Can you pass me the salt?',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-23',
    german: 'Schokolade',
    turkish: 'Çikolata',
    english: 'Chocolate',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Schokoladen',
    collocations: ['eine Tafel Schokolade', 'heiße Schokolade', 'dunkle Schokolade'],
    emoji: '🍫',
    exampleSentence: 'Ich liebe Schokolade!',
    exampleTranslation: 'Çikolatayı seviyorum!',
    exampleTranslationEn: 'I love chocolate!',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-24',
    german: 'Nudeln',
    turkish: 'Makarna',
    english: 'Noodles / Pasta',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    synonyms: ['Pasta', 'Spaghetti'],
    collocations: ['Nudeln kochen', 'Nudeln mit Soße', 'Nudeln al dente'],
    emoji: '🍝',
    exampleSentence: 'Nudeln mit Soße sind lecker.',
    exampleTranslation: 'Soslu makarna lezzetli.',
    exampleTranslationEn: 'Noodles with sauce are delicious.',
    category: 'food',
    level: 'A1',
  },
  {
    id: 'food-25',
    german: 'Eis',
    turkish: 'Dondurma',
    english: 'Ice cream',
    article: 'das',
    partOfSpeech: 'noun',
    collocations: ['ein Eis essen', 'eine Kugel Eis', 'Eis am Stiel'],
    emoji: '🍦',
    exampleSentence: 'Im Sommer esse ich gern Eis.',
    exampleTranslation: 'Yazın dondurma yemeyi severim.',
    exampleTranslationEn: 'In summer I like to eat ice cream.',
    category: 'food',
    level: 'A1',
  },
  // B1 - Cooking, recipes, nutrition
  {
    id: 'food-b1-1',
    german: 'die Zutat',
    turkish: 'malzeme',
    english: 'ingredient',
    article: 'die',
    plural: 'Zutaten',
    partOfSpeech: 'noun',
    exampleSentence: 'Für diesen Kuchen braucht man nur wenige Zutaten.',
    exampleTranslation: 'Bu kek için sadece birkaç malzeme gerekiyor.',
    exampleTranslationEn: 'You only need a few ingredients for this cake.',
    category: 'food',
    level: 'B1',
    tags: ['cooking', 'recipe'],
  },
  {
    id: 'food-b1-2',
    german: 'zubereiten',
    turkish: 'hazırlamak',
    english: 'to prepare (food)',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Ich bereite das Abendessen für meine Familie zu.',
    exampleTranslation: 'Ailem için akşam yemeğini hazırlıyorum.',
    exampleTranslationEn: 'I am preparing dinner for my family.',
    category: 'food',
    level: 'B1',
    tags: ['cooking', 'preparation'],
  },
  {
    id: 'food-b1-3',
    german: 'die Ernährung',
    turkish: 'beslenme',
    english: 'nutrition / diet',
    article: 'die',
    partOfSpeech: 'noun',
    exampleSentence: 'Eine gesunde Ernährung ist sehr wichtig.',
    exampleTranslation: 'Sağlıklı beslenme çok önemlidir.',
    exampleTranslationEn: 'A healthy diet is very important.',
    category: 'food',
    level: 'B1',
    tags: ['health', 'nutrition'],
  },
  {
    id: 'food-b1-4',
    german: 'das Gericht',
    turkish: 'yemek',
    english: 'dish / meal',
    article: 'das',
    plural: 'Gerichte',
    partOfSpeech: 'noun',
    exampleSentence: 'Dieses Gericht ist eine Spezialität der Region.',
    exampleTranslation: 'Bu yemek bölgenin bir spesiyalitesidir.',
    exampleTranslationEn: 'This dish is a specialty of the region.',
    category: 'food',
    level: 'B1',
    tags: ['restaurant', 'cooking'],
  },
  {
    id: 'food-b1-5',
    german: 'die Portion',
    turkish: 'porsiyon',
    english: 'portion / serving',
    article: 'die',
    plural: 'Portionen',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Portionen in diesem Restaurant sind sehr groß.',
    exampleTranslation: 'Bu restoranda porsiyonlar çok büyük.',
    exampleTranslationEn: 'The portions in this restaurant are very large.',
    category: 'food',
    level: 'B1',
    tags: ['restaurant', 'quantity'],
  },
  {
    id: 'food-b1-6',
    german: 'schmecken',
    turkish: 'tadı olmak / tatmak',
    english: 'to taste',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Die Suppe schmeckt nach Knoblauch.',
    exampleTranslation: 'Çorba sarımsak tadında.',
    exampleTranslationEn: 'The soup tastes of garlic.',
    category: 'food',
    level: 'B1',
    tags: ['taste', 'cooking'],
  },
  {
    id: 'food-b1-7',
    german: 'die Pfanne',
    turkish: 'tava',
    english: 'pan / frying pan',
    article: 'die',
    plural: 'Pfannen',
    partOfSpeech: 'noun',
    exampleSentence: 'Brate die Zwiebeln in der Pfanne an.',
    exampleTranslation: 'Soğanları tavada kızart.',
    exampleTranslationEn: 'Fry the onions in the pan.',
    category: 'food',
    level: 'B1',
    tags: ['cooking', 'kitchen'],
  },
  {
    id: 'food-b1-8',
    german: 'vegetarisch',
    turkish: 'vejetaryen',
    english: 'vegetarian',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Haben Sie auch vegetarische Gerichte?',
    exampleTranslation: 'Vejetaryen yemekleriniz de var mı?',
    exampleTranslationEn: 'Do you also have vegetarian dishes?',
    category: 'food',
    level: 'B1',
    tags: ['diet', 'restaurant'],
  },
  {
    id: 'food-b1-9',
    german: 'backen',
    turkish: 'fırında pişirmek',
    english: 'to bake',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Am Wochenende backe ich gerne Brot.',
    exampleTranslation: 'Hafta sonları ekmek pişirmeyi severim.',
    exampleTranslationEn: 'On weekends I like to bake bread.',
    category: 'food',
    level: 'B1',
    tags: ['cooking', 'baking'],
  },
  {
    id: 'food-b1-10',
    german: 'die Soße',
    turkish: 'sos',
    english: 'sauce',
    article: 'die',
    plural: 'Soßen',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Soße wird aus frischen Tomaten gemacht.',
    exampleTranslation: 'Sos taze domateslerden yapılır.',
    exampleTranslationEn: 'The sauce is made from fresh tomatoes.',
    category: 'food',
    level: 'B1',
    tags: ['cooking', 'recipe'],
  },
  {
    id: 'food-26',
    german: 'Zutaten',
    turkish: 'Malzemeler',
    english: 'Ingredients',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    synonyms: ['Bestandteile', 'Ingredienzien'],
    collocations: ['die Zutaten vorbereiten', 'frische Zutaten verwenden', 'alle Zutaten vermischen'],
    emoji: '🧾',
    exampleSentence: 'Für dieses Rezept brauchen wir nur wenige Zutaten.',
    exampleTranslation: 'Bu tarif için sadece birkaç malzemeye ihtiyacımız var.',
    exampleTranslationEn: 'For this recipe we only need a few ingredients.',
    category: 'food',
    level: 'B2',
    tags: ['cooking', 'preparation'],
  },
  {
    id: 'food-27',
    german: 'Rezept',
    turkish: 'Tarif',
    english: 'Recipe',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Rezepte',
    synonyms: ['Kochanleitung', 'Zubereitungsanleitung'],
    collocations: ['ein Rezept ausprobieren', 'ein Rezept nachkochen', 'das Rezept befolgen'],
    emoji: '📖',
    exampleSentence: 'Das Rezept stammt von meiner Großmutter und wird seit Generationen weitergegeben.',
    exampleTranslation: 'Tarif büyükannemden geliyor ve nesillerdir aktarılıyor.',
    exampleTranslationEn: 'The recipe comes from my grandmother and has been passed down for generations.',
    category: 'food',
    level: 'B2',
    tags: ['cooking', 'tradition'],
  },
  {
    id: 'food-28',
    german: 'würzen',
    turkish: 'baharatlamak',
    english: 'To season',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['abschmecken', 'verfeinern'],
    collocations: ['das Essen würzen', 'mit Pfeffer würzen', 'nach Geschmack würzen'],
    emoji: '🌶️',
    exampleSentence: 'Man sollte das Gericht erst am Ende mit frischen Kräutern würzen.',
    exampleTranslation: 'Yemeği ancak sonunda taze otlarla baharatlamalısınız.',
    exampleTranslationEn: 'You should only season the dish with fresh herbs at the end.',
    category: 'food',
    level: 'B2',
    tags: ['cooking', 'seasoning'],
  },
  {
    id: 'food-29',
    german: 'Beilage',
    turkish: 'Garnitür/Yan yemek',
    english: 'Side dish',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Beilagen',
    synonyms: ['Zuspeise', 'Nebengericht'],
    collocations: ['als Beilage servieren', 'eine Beilage wählen', 'Reis als Beilage'],
    emoji: '🥗',
    exampleSentence: 'Als Beilage empfehle ich Ihnen gebratenes Gemüse oder Kartoffelpüree.',
    exampleTranslation: 'Garnitür olarak size kızarmış sebze veya patates püresi öneriyorum.',
    exampleTranslationEn: 'As a side dish, I recommend roasted vegetables or mashed potatoes.',
    category: 'food',
    level: 'B2',
    tags: ['restaurant', 'dining'],
  },
  {
    id: 'food-30',
    german: 'Vorspeise',
    turkish: 'Başlangıç/Meze',
    english: 'Appetizer/Starter',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Vorspeisen',
    synonyms: ['Appetithappen', 'Starter'],
    antonyms: ['Nachspeise', 'Hauptgericht'],
    collocations: ['eine Vorspeise bestellen', 'als Vorspeise nehmen', 'eine kalte Vorspeise'],
    emoji: '🥄',
    exampleSentence: 'Als Vorspeise nehme ich die Kürbissuppe mit gerösteten Kernen.',
    exampleTranslation: 'Başlangıç olarak kavrulmuş çekirdekli balkabağı çorbasını alacağım.',
    exampleTranslationEn: 'As a starter, I will have the pumpkin soup with roasted seeds.',
    category: 'food',
    level: 'B2',
    tags: ['restaurant', 'dining'],
  },
  {
    id: 'food-31',
    german: 'Nachspeise',
    turkish: 'Tatlı',
    english: 'Dessert',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Nachspeisen',
    synonyms: ['Dessert', 'Nachtisch'],
    antonyms: ['Vorspeise'],
    collocations: ['eine Nachspeise bestellen', 'als Nachspeise essen', 'die Nachspeise genießen'],
    emoji: '🍮',
    exampleSentence: 'Die Nachspeise war ein hausgemachtes Tiramisu mit frischen Beeren.',
    exampleTranslation: 'Tatlı, taze meyvelerin eşlik ettiği ev yapımı bir tiramisuydu.',
    exampleTranslationEn: 'The dessert was a homemade tiramisu with fresh berries.',
    category: 'food',
    level: 'B2',
    tags: ['restaurant', 'dessert'],
  },
  {
    id: 'food-32',
    german: 'braten',
    turkish: 'kızartmak',
    english: 'To fry/To roast',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['anbraten', 'rösten'],
    antonyms: ['kochen', 'dämpfen'],
    collocations: ['in der Pfanne braten', 'das Fleisch braten', 'scharf anbraten'],
    emoji: '🍳',
    exampleSentence: 'Braten Sie das Fleisch bei starker Hitze scharf an, damit es eine Kruste bekommt.',
    exampleTranslation: 'Eti kabuk oluşması için yüksek ateşte kızartın.',
    exampleTranslationEn: 'Sear the meat at high heat so that it gets a crust.',
    category: 'food',
    level: 'B2',
    tags: ['cooking', 'technique'],
  },
  {
    id: 'food-33',
    german: 'kochen',
    turkish: 'pişirmek/kaynatmak',
    english: 'To cook/To boil',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['zubereiten', 'garen', 'sieden'],
    antonyms: ['braten', 'backen'],
    collocations: ['das Wasser kochen', 'das Essen kochen', 'nach Rezept kochen'],
    emoji: '🍲',
    exampleSentence: 'Wenn man Nudeln kocht, sollte man reichlich gesalzenes Wasser verwenden.',
    exampleTranslation: 'Makarna pişirirken bol tuzlu su kullanmalısınız.',
    exampleTranslationEn: 'When cooking pasta, you should use plenty of salted water.',
    category: 'food',
    level: 'B2',
    tags: ['cooking', 'technique'],
  },
  {
    id: 'food-34',
    german: 'Ernährung',
    turkish: 'Beslenme',
    english: 'Nutrition/Diet',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Nahrung', 'Kost', 'Diät'],
    collocations: ['eine gesunde Ernährung', 'auf die Ernährung achten', 'ausgewogene Ernährung'],
    emoji: '🥦',
    exampleSentence: 'Eine ausgewogene Ernährung ist die Grundlage für ein gesundes Leben.',
    exampleTranslation: 'Dengeli beslenme, sağlıklı bir yaşamın temelidir.',
    exampleTranslationEn: 'A balanced diet is the foundation for a healthy life.',
    category: 'food',
    level: 'B2',
    tags: ['health', 'nutrition'],
  },
  {
    id: 'food-35',
    german: 'Geschmack',
    turkish: 'Tat/Lezzet',
    english: 'Taste/Flavor',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Geschmäcker',
    synonyms: ['Aroma', 'Würze'],
    collocations: ['einen guten Geschmack haben', 'der Geschmack ist intensiv', 'Geschmackssache'],
    emoji: '👅',
    exampleSentence: 'Der intensive Geschmack dieser Soße kommt von den langsam gekochten Tomaten.',
    exampleTranslation: 'Bu sosun yoğun lezzeti yavaş pişirilmiş domateslerden geliyor.',
    exampleTranslationEn: 'The intense flavor of this sauce comes from the slowly cooked tomatoes.',
    category: 'food',
    level: 'B2',
    tags: ['taste', 'sensation'],
  },
];
