import { VocabularyWord } from '@/lib/types';

export const foodWords: VocabularyWord[] = [
  { id: 'food-1', german: 'Brot', turkish: 'Ekmek', article: 'das', partOfSpeech: 'noun', plural: 'Brote', exampleSentence: 'Ich kaufe frisches Brot.', exampleTranslation: 'Taze ekmek alıyorum.', category: 'food', level: 'A1' },
  { id: 'food-2', german: 'Butter', turkish: 'Tereyağı', article: 'die', partOfSpeech: 'noun', exampleSentence: 'Die Butter ist im Kühlschrank.', exampleTranslation: 'Tereyağı buzdolabında.', category: 'food', level: 'A1' },
  { id: 'food-3', german: 'Käse', turkish: 'Peynir', article: 'der', partOfSpeech: 'noun', exampleSentence: 'Ich esse gern Käse.', exampleTranslation: 'Peynir yemeyi severim.', category: 'food', level: 'A1' },
  { id: 'food-4', german: 'Milch', turkish: 'Süt', article: 'die', partOfSpeech: 'noun', exampleSentence: 'Trinkst du Milch zum Frühstück?', exampleTranslation: 'Kahvaltıda süt içer misin?', category: 'food', level: 'A1' },
  { id: 'food-5', german: 'Wasser', turkish: 'Su', article: 'das', partOfSpeech: 'noun', exampleSentence: 'Kann ich ein Glas Wasser haben?', exampleTranslation: 'Bir bardak su alabilir miyim?', category: 'food', level: 'A1' },
  { id: 'food-6', german: 'Kaffee', turkish: 'Kahve', article: 'der', partOfSpeech: 'noun', exampleSentence: 'Ich trinke morgens Kaffee.', exampleTranslation: 'Sabahları kahve içerim.', category: 'food', level: 'A1' },
  { id: 'food-7', german: 'Tee', turkish: 'Çay', article: 'der', partOfSpeech: 'noun', exampleSentence: 'Möchten Sie Tee oder Kaffee?', exampleTranslation: 'Çay mı kahve mi istersiniz?', category: 'food', level: 'A1' },
  { id: 'food-8', german: 'Bier', turkish: 'Bira', article: 'das', partOfSpeech: 'noun', plural: 'Biere', exampleSentence: 'Ein Bier, bitte!', exampleTranslation: 'Bir bira, lütfen!', category: 'food', level: 'A1' },
  { id: 'food-9', german: 'Fleisch', turkish: 'Et', article: 'das', partOfSpeech: 'noun', exampleSentence: 'Ich esse kein Fleisch.', exampleTranslation: 'Et yemiyorum.', category: 'food', level: 'A1' },
  { id: 'food-10', german: 'Fisch', turkish: 'Balık', article: 'der', partOfSpeech: 'noun', plural: 'Fische', exampleSentence: 'Der Fisch ist sehr frisch.', exampleTranslation: 'Balık çok taze.', category: 'food', level: 'A1' },
  { id: 'food-11', german: 'Reis', turkish: 'Pirinç/Pilav', article: 'der', partOfSpeech: 'noun', exampleSentence: 'Reis mit Gemüse schmeckt gut.', exampleTranslation: 'Sebzeli pilav güzel.', category: 'food', level: 'A1' },
  { id: 'food-12', german: 'Kartoffel', turkish: 'Patates', article: 'die', partOfSpeech: 'noun', plural: 'Kartoffeln', exampleSentence: 'Kartoffeln sind in Deutschland sehr beliebt.', exampleTranslation: 'Patates Almanya\'da çok popüler.', category: 'food', level: 'A1' },
  { id: 'food-13', german: 'Tomate', turkish: 'Domates', article: 'die', partOfSpeech: 'noun', plural: 'Tomaten', exampleSentence: 'Die Tomaten sind rot und reif.', exampleTranslation: 'Domatesler kırmızı ve olgun.', category: 'food', level: 'A1' },
  { id: 'food-14', german: 'Salat', turkish: 'Salata', article: 'der', partOfSpeech: 'noun', plural: 'Salate', exampleSentence: 'Ich möchte einen Salat bestellen.', exampleTranslation: 'Bir salata sipariş etmek istiyorum.', category: 'food', level: 'A1' },
  { id: 'food-15', german: 'Obst', turkish: 'Meyve', article: 'das', partOfSpeech: 'noun', exampleSentence: 'Obst ist gesund.', exampleTranslation: 'Meyve sağlıklıdır.', category: 'food', level: 'A1' },
  { id: 'food-16', german: 'Apfel', turkish: 'Elma', article: 'der', partOfSpeech: 'noun', plural: 'Äpfel', exampleSentence: 'Ich esse jeden Tag einen Apfel.', exampleTranslation: 'Her gün bir elma yerim.', category: 'food', level: 'A1' },
  { id: 'food-17', german: 'Kuchen', turkish: 'Pasta/Kek', article: 'der', partOfSpeech: 'noun', exampleSentence: 'Der Kuchen schmeckt lecker.', exampleTranslation: 'Pasta çok lezzetli.', category: 'food', level: 'A1' },
  { id: 'food-18', german: 'Ei', turkish: 'Yumurta', article: 'das', partOfSpeech: 'noun', plural: 'Eier', exampleSentence: 'Zum Frühstück esse ich zwei Eier.', exampleTranslation: 'Kahvaltıda iki yumurta yerim.', category: 'food', level: 'A1' },
  { id: 'food-19', german: 'Suppe', turkish: 'Çorba', article: 'die', partOfSpeech: 'noun', plural: 'Suppen', exampleSentence: 'Die Suppe ist heiß.', exampleTranslation: 'Çorba sıcak.', category: 'food', level: 'A1' },
  { id: 'food-20', german: 'Gemüse', turkish: 'Sebze', article: 'das', partOfSpeech: 'noun', exampleSentence: 'Gemüse ist sehr gesund.', exampleTranslation: 'Sebze çok sağlıklı.', category: 'food', level: 'A1' },
  { id: 'food-21', german: 'Zucker', turkish: 'Şeker', article: 'der', partOfSpeech: 'noun', exampleSentence: 'Nehmen Sie Zucker in den Tee?', exampleTranslation: 'Çaya şeker alır mısınız?', category: 'food', level: 'A1' },
  { id: 'food-22', german: 'Salz', turkish: 'Tuz', article: 'das', partOfSpeech: 'noun', exampleSentence: 'Kannst du mir das Salz geben?', exampleTranslation: 'Bana tuzu verir misin?', category: 'food', level: 'A1' },
  { id: 'food-23', german: 'Schokolade', turkish: 'Çikolata', article: 'die', partOfSpeech: 'noun', exampleSentence: 'Ich liebe Schokolade!', exampleTranslation: 'Çikolatayı seviyorum!', category: 'food', level: 'A1' },
  { id: 'food-24', german: 'Nudeln', turkish: 'Makarna', article: 'die (pl)', partOfSpeech: 'noun', exampleSentence: 'Nudeln mit Soße sind lecker.', exampleTranslation: 'Soslu makarna lezzetli.', category: 'food', level: 'A1' },
  { id: 'food-25', german: 'Eis', turkish: 'Dondurma', article: 'das', partOfSpeech: 'noun', exampleSentence: 'Im Sommer esse ich gern Eis.', exampleTranslation: 'Yazın dondurma yemeyi severim.', category: 'food', level: 'A1' },
];
