import { VocabularyWord } from '@/lib/types';

export const greetingsWords: VocabularyWord[] = [
  {
    id: 'greetings-1',
    german: 'Hallo',
    turkish: 'Merhaba',
    english: 'Hello',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Hi', 'Hey', 'Grüß dich'],
    collocations: ['Hallo zusammen!', 'Hallo, wie geht\'s?', 'Na, hallo!'],
    emoji: '👋',
    exampleSentence: 'Hallo, wie geht es dir?',
    exampleTranslation: 'Merhaba, nasılsın?',
    exampleTranslationEn: 'Hello, how are you?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-2',
    german: 'Guten Morgen',
    turkish: 'Günaydın',
    english: 'Good morning',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Morgen!', 'Einen schönen guten Morgen'],
    collocations: ['Guten Morgen allerseits!', 'Guten Morgen zusammen!'],
    emoji: '🌅',
    exampleSentence: 'Guten Morgen! Haben Sie gut geschlafen?',
    exampleTranslation: 'Günaydın! İyi uyudunuz mu?',
    exampleTranslationEn: 'Good morning! Did you sleep well?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-3',
    german: 'Guten Tag',
    turkish: 'İyi günler',
    english: 'Good day',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Tag!', 'Grüß Gott'],
    collocations: ['Guten Tag, was kann ich für Sie tun?', 'Einen schönen guten Tag!'],
    emoji: '☀️',
    exampleSentence: 'Guten Tag, Herr Müller!',
    exampleTranslation: 'İyi günler, Bay Müller!',
    exampleTranslationEn: 'Good day, Mr. Müller!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-4',
    german: 'Guten Abend',
    turkish: 'İyi akşamlar',
    english: 'Good evening',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['N\'Abend!', 'Einen schönen guten Abend'],
    collocations: ['Guten Abend, meine Damen und Herren!', 'Guten Abend zusammen!'],
    emoji: '🌆',
    exampleSentence: 'Guten Abend, willkommen im Restaurant.',
    exampleTranslation: 'İyi akşamlar, restorana hoş geldiniz.',
    exampleTranslationEn: 'Good evening, welcome to the restaurant.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-5',
    german: 'Gute Nacht',
    turkish: 'İyi geceler',
    english: 'Good night',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Nacht!', 'Schlaf gut'],
    collocations: ['Gute Nacht und süße Träume!', 'Gute Nacht, schlaf schön!'],
    emoji: '🌙',
    exampleSentence: 'Gute Nacht, schlaf gut!',
    exampleTranslation: 'İyi geceler, iyi uykular!',
    exampleTranslationEn: 'Good night, sleep well!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-6',
    german: 'Auf Wiedersehen',
    turkish: 'Hoşça kalın',
    english: 'Goodbye',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Wiedersehen!', 'Auf Wiederschauen', 'Leben Sie wohl'],
    collocations: ['Auf Wiedersehen und alles Gute!', 'Auf Wiedersehen, bis zum nächsten Mal!'],
    emoji: '🫡',
    exampleSentence: 'Auf Wiedersehen, bis morgen!',
    exampleTranslation: 'Hoşça kalın, yarına kadar!',
    exampleTranslationEn: 'Goodbye, see you tomorrow!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-7',
    german: 'Tschüss',
    turkish: 'Güle güle',
    english: 'Bye',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Ciao', 'Tschau', 'Bis dann'],
    collocations: ['Tschüss, mach\'s gut!', 'Tschüss, bis bald!'],
    emoji: '👋',
    exampleSentence: 'Tschüss, mach es gut!',
    exampleTranslation: 'Güle güle, kendine iyi bak!',
    exampleTranslationEn: 'Bye, take care!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-8',
    german: 'Willkommen',
    turkish: 'Hoş geldiniz',
    english: 'Welcome',
    article: null,
    partOfSpeech: 'phrase',
    collocations: ['Herzlich willkommen!', 'Willkommen zu Hause!', 'Willkommen bei uns!'],
    emoji: '🤗',
    exampleSentence: 'Herzlich willkommen in Deutschland!',
    exampleTranslation: 'Almanya\'ya hoş geldiniz!',
    exampleTranslationEn: 'Welcome to Germany!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-9',
    german: 'Bitte',
    turkish: 'Lütfen / Rica ederim',
    english: 'Please / You\'re welcome',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Bitte schön', 'Bitte sehr', 'Gern geschehen'],
    collocations: ['Bitte schön!', 'Ja, bitte!', 'Aber bitte!'],
    emoji: '🙏',
    exampleSentence: 'Bitte schön, hier ist Ihr Kaffee.',
    exampleTranslation: 'Buyurun, kahveniz burada.',
    exampleTranslationEn: 'Here you go, here is your coffee.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-10',
    german: 'Danke',
    turkish: 'Teşekkürler',
    english: 'Thank you',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Vielen Dank', 'Dankeschön', 'Danke sehr'],
    collocations: ['Danke für alles!', 'Danke, gleichfalls!', 'Nein, danke!'],
    emoji: '🙏',
    exampleSentence: 'Danke für deine Hilfe!',
    exampleTranslation: 'Yardımın için teşekkürler!',
    exampleTranslationEn: 'Thank you for your help!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-11',
    german: 'Entschuldigung',
    turkish: 'Özür dilerim / Affedersiniz',
    english: 'Excuse me / Sorry',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Entschuldigungen',
    synonyms: ['Verzeihung', 'Pardon', 'Tut mir leid'],
    collocations: ['Um Entschuldigung bitten', 'Entschuldigung annehmen', 'Entschuldigung, darf ich mal?'],
    emoji: '😔',
    exampleSentence: 'Entschuldigung, wo ist der Bahnhof?',
    exampleTranslation: 'Affedersiniz, tren istasyonu nerede?',
    exampleTranslationEn: 'Excuse me, where is the train station?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-12',
    german: 'Wie geht es Ihnen?',
    turkish: 'Nasılsınız?',
    english: 'How are you? (formal)',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Wie geht\'s?', 'Wie geht es dir?', 'Wie steht\'s?'],
    emoji: '❓',
    exampleSentence: 'Guten Tag! Wie geht es Ihnen?',
    exampleTranslation: 'İyi günler! Nasılsınız?',
    exampleTranslationEn: 'Good day! How are you?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-13',
    german: 'Mir geht es gut',
    turkish: 'İyiyim',
    english: 'I am fine',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Es geht mir gut', 'Mir geht\'s gut', 'Gut, danke'],
    antonyms: ['Mir geht es schlecht'],
    emoji: '😊',
    exampleSentence: 'Danke, mir geht es gut. Und Ihnen?',
    exampleTranslation: 'Teşekkürler, iyiyim. Ya siz?',
    exampleTranslationEn: 'Thank you, I am fine. And you?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-14',
    german: 'Ja',
    turkish: 'Evet',
    english: 'Yes',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Jawohl', 'Genau', 'Stimmt'],
    antonyms: ['Nein'],
    collocations: ['Ja, gerne!', 'Ja, bitte!', 'Ja, natürlich!'],
    emoji: '✅',
    exampleSentence: 'Ja, das stimmt.',
    exampleTranslation: 'Evet, bu doğru.',
    exampleTranslationEn: 'Yes, that is correct.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-15',
    german: 'Nein',
    turkish: 'Hayır',
    english: 'No',
    article: null,
    partOfSpeech: 'phrase',
    antonyms: ['Ja'],
    collocations: ['Nein, danke!', 'Nein, leider nicht.', 'Oh nein!'],
    emoji: '❌',
    exampleSentence: 'Nein, das möchte ich nicht.',
    exampleTranslation: 'Hayır, bunu istemiyorum.',
    exampleTranslationEn: 'No, I do not want that.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-16',
    german: 'Wie heißen Sie?',
    turkish: 'Adınız ne?',
    english: 'What is your name? (formal)',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Wie ist Ihr Name?', 'Wie heißt du?'],
    emoji: '🪪',
    exampleSentence: 'Wie heißen Sie? Ich heiße Anna.',
    exampleTranslation: 'Adınız ne? Benim adım Anna.',
    exampleTranslationEn: 'What is your name? My name is Anna.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-17',
    german: 'Ich heiße...',
    turkish: 'Benim adım...',
    english: 'My name is...',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Mein Name ist...', 'Ich bin...'],
    emoji: '🏷️',
    exampleSentence: 'Ich heiße Thomas. Freut mich!',
    exampleTranslation: 'Benim adım Thomas. Memnun oldum!',
    exampleTranslationEn: 'My name is Thomas. Nice to meet you!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-18',
    german: 'Woher kommen Sie?',
    turkish: 'Nerelisiniz?',
    english: 'Where are you from? (formal)',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Woher kommst du?', 'Wo kommen Sie her?'],
    emoji: '🌍',
    exampleSentence: 'Woher kommen Sie? Aus der Türkei?',
    exampleTranslation: 'Nerelisiniz? Türkiye\'den mi?',
    exampleTranslationEn: 'Where are you from? From Turkey?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-19',
    german: 'Freut mich',
    turkish: 'Memnun oldum',
    english: 'Nice to meet you',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Sehr erfreut', 'Angenehm'],
    collocations: ['Freut mich, Sie kennenzulernen!', 'Freut mich sehr!'],
    emoji: '🤝',
    exampleSentence: 'Freut mich, Sie kennenzulernen!',
    exampleTranslation: 'Tanıştığımıza memnun oldum!',
    exampleTranslationEn: 'Nice to meet you!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-20',
    german: 'Bis bald',
    turkish: 'Yakında görüşürüz',
    english: 'See you soon',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Bis dann', 'Bis später', 'Bis demnächst'],
    emoji: '🔜',
    exampleSentence: 'Bis bald! Pass auf dich auf!',
    exampleTranslation: 'Yakında görüşürüz! Kendine iyi bak!',
    exampleTranslationEn: 'See you soon! Take care of yourself!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-21',
    german: 'Es tut mir leid',
    turkish: 'Üzgünüm',
    english: 'I am sorry',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Entschuldigung', 'Tut mir leid', 'Verzeihung'],
    emoji: '😞',
    exampleSentence: 'Es tut mir leid, ich bin zu spät.',
    exampleTranslation: 'Üzgünüm, geç kaldım.',
    exampleTranslationEn: 'I am sorry, I am late.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-22',
    german: 'Kein Problem',
    turkish: 'Sorun değil',
    english: 'No problem',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Macht nichts', 'Nicht schlimm', 'Kein Ding'],
    emoji: '👍',
    exampleSentence: 'Kein Problem, das macht nichts!',
    exampleTranslation: 'Sorun değil, önemli değil!',
    exampleTranslationEn: 'No problem, it does not matter!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-23',
    german: 'Prost',
    turkish: 'Şerefe',
    english: 'Cheers',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Zum Wohl', 'Cheers'],
    collocations: ['Prost Neujahr!', 'Prost, auf uns!'],
    emoji: '🍻',
    exampleSentence: 'Prost! Auf unsere Freundschaft!',
    exampleTranslation: 'Şerefe! Arkadaşlığımıza!',
    exampleTranslationEn: 'Cheers! To our friendship!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-24',
    german: 'Gesundheit',
    turkish: 'Çok yaşa',
    english: 'Bless you / Health',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['Gesundheit ist das Wichtigste.', 'Bei guter Gesundheit sein'],
    emoji: '🤧',
    exampleSentence: 'Hatschi! - Gesundheit!',
    exampleTranslation: 'Hapşu! - Çok yaşa!',
    exampleTranslationEn: 'Achoo! - Bless you!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-25',
    german: 'Vielleicht',
    turkish: 'Belki',
    english: 'Maybe',
    article: null,
    partOfSpeech: 'adverb',
    synonyms: ['Möglicherweise', 'Eventuell', 'Womöglich'],
    antonyms: ['Bestimmt', 'Sicher', 'Auf jeden Fall'],
    collocations: ['Vielleicht morgen', 'Vielleicht klappt es', 'Ja, vielleicht'],
    emoji: '🤔',
    exampleSentence: 'Vielleicht komme ich morgen.',
    exampleTranslation: 'Belki yarın gelirim.',
    exampleTranslationEn: 'Maybe I will come tomorrow.',
    category: 'greetings',
    level: 'A1',
  },
  // B1 - Polite conversation, opinions, feelings
  {
    id: 'greetings-b1-1',
    german: 'meiner Meinung nach',
    turkish: 'bence / benim görüşüme göre',
    english: 'in my opinion',
    article: null,
    partOfSpeech: 'phrase',
    exampleSentence: 'Meiner Meinung nach sollten wir mehr Sport treiben.',
    exampleTranslation: 'Bence daha fazla spor yapmalıyız.',
    exampleTranslationEn: 'In my opinion, we should do more sport.',
    category: 'greetings',
    level: 'B1',
    tags: ['opinion', 'conversation'],
  },
  {
    id: 'greetings-b1-2',
    german: 'sich entschuldigen',
    turkish: 'özür dilemek',
    english: 'to apologize',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Er hat sich für sein Verhalten entschuldigt.',
    exampleTranslation: 'Davranışı için özür diledi.',
    exampleTranslationEn: 'He apologized for his behavior.',
    category: 'greetings',
    level: 'B1',
    tags: ['apology', 'politeness'],
  },
  {
    id: 'greetings-b1-3',
    german: 'sich freuen',
    turkish: 'sevinmek / memnun olmak',
    english: 'to be happy / to look forward to',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Ich freue mich auf das Wochenende.',
    exampleTranslation: 'Hafta sonunu dört gözle bekliyorum.',
    exampleTranslationEn: 'I am looking forward to the weekend.',
    category: 'greetings',
    level: 'B1',
    tags: ['feelings', 'emotion'],
  },
  {
    id: 'greetings-b1-4',
    german: 'einverstanden',
    turkish: 'kabul / razı',
    english: 'agreed / in agreement',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Sind Sie damit einverstanden?',
    exampleTranslation: 'Bunu kabul ediyor musunuz?',
    exampleTranslationEn: 'Do you agree with that?',
    category: 'greetings',
    level: 'B1',
    tags: ['agreement', 'conversation'],
  },
  {
    id: 'greetings-b1-5',
    german: 'sich beschweren',
    turkish: 'şikayet etmek',
    english: 'to complain',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Er hat sich über den Lärm beschwert.',
    exampleTranslation: 'Gürültüden şikayet etti.',
    exampleTranslationEn: 'He complained about the noise.',
    category: 'greetings',
    level: 'B1',
    tags: ['complaint', 'conversation'],
  },
  {
    id: 'greetings-b1-6',
    german: 'vorschlagen',
    turkish: 'önermek / teklif etmek',
    english: 'to suggest / to propose',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Ich schlage vor, dass wir morgen ins Kino gehen.',
    exampleTranslation: 'Yarın sinemaya gitmemizi öneriyorum.',
    exampleTranslationEn: 'I suggest that we go to the cinema tomorrow.',
    category: 'greetings',
    level: 'B1',
    tags: ['suggestion', 'conversation'],
  },
  {
    id: 'greetings-b1-7',
    german: 'sich unterhalten',
    turkish: 'sohbet etmek',
    english: 'to have a conversation / to chat',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Wir haben uns lange über Politik unterhalten.',
    exampleTranslation: 'Uzun süre siyaset hakkında sohbet ettik.',
    exampleTranslationEn: 'We had a long conversation about politics.',
    category: 'greetings',
    level: 'B1',
    tags: ['conversation', 'social'],
  },
  {
    id: 'greetings-b1-8',
    german: 'zustimmen',
    turkish: 'katılmak / onaylamak',
    english: 'to agree',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Ich stimme Ihnen vollkommen zu.',
    exampleTranslation: 'Size tamamen katılıyorum.',
    exampleTranslationEn: 'I completely agree with you.',
    category: 'greetings',
    level: 'B1',
    tags: ['agreement', 'opinion'],
  },
  {
    id: 'greetings-b1-9',
    german: 'ablehnen',
    turkish: 'reddetmek',
    english: 'to decline / to reject',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Er hat die Einladung höflich abgelehnt.',
    exampleTranslation: 'Daveti kibarca reddetti.',
    exampleTranslationEn: 'He politely declined the invitation.',
    category: 'greetings',
    level: 'B1',
    tags: ['refusal', 'politeness'],
  },
  {
    id: 'greetings-b1-10',
    german: 'sich Sorgen machen',
    turkish: 'endişelenmek / kaygılanmak',
    english: 'to worry',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Mach dir keine Sorgen, alles wird gut.',
    exampleTranslation: 'Endişelenme, her şey iyi olacak.',
    exampleTranslationEn: 'Do not worry, everything will be fine.',
    category: 'greetings',
    level: 'B1',
    tags: ['feelings', 'emotion'],
  },
];
