import { VocabularyWord } from '@/lib/types';

export const greetingsWords: VocabularyWord[] = [
  {
    id: 'greetings-1',
    german: 'Hallo',
    turkish: 'Merhaba',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Hi', 'Hey', 'Grüß dich'],
    collocations: ['Hallo zusammen!', 'Hallo, wie geht\'s?', 'Na, hallo!'],
    emoji: '👋',
    exampleSentence: 'Hallo, wie geht es dir?',
    exampleTranslation: 'Merhaba, nasılsın?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-2',
    german: 'Guten Morgen',
    turkish: 'Günaydın',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Morgen!', 'Einen schönen guten Morgen'],
    collocations: ['Guten Morgen allerseits!', 'Guten Morgen zusammen!'],
    emoji: '🌅',
    exampleSentence: 'Guten Morgen! Haben Sie gut geschlafen?',
    exampleTranslation: 'Günaydın! İyi uyudunuz mu?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-3',
    german: 'Guten Tag',
    turkish: 'İyi günler',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Tag!', 'Grüß Gott'],
    collocations: ['Guten Tag, was kann ich für Sie tun?', 'Einen schönen guten Tag!'],
    emoji: '☀️',
    exampleSentence: 'Guten Tag, Herr Müller!',
    exampleTranslation: 'İyi günler, Bay Müller!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-4',
    german: 'Guten Abend',
    turkish: 'İyi akşamlar',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['N\'Abend!', 'Einen schönen guten Abend'],
    collocations: ['Guten Abend, meine Damen und Herren!', 'Guten Abend zusammen!'],
    emoji: '🌆',
    exampleSentence: 'Guten Abend, willkommen im Restaurant.',
    exampleTranslation: 'İyi akşamlar, restorana hoş geldiniz.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-5',
    german: 'Gute Nacht',
    turkish: 'İyi geceler',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Nacht!', 'Schlaf gut'],
    collocations: ['Gute Nacht und süße Träume!', 'Gute Nacht, schlaf schön!'],
    emoji: '🌙',
    exampleSentence: 'Gute Nacht, schlaf gut!',
    exampleTranslation: 'İyi geceler, iyi uykular!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-6',
    german: 'Auf Wiedersehen',
    turkish: 'Hoşça kalın',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Wiedersehen!', 'Auf Wiederschauen', 'Leben Sie wohl'],
    collocations: ['Auf Wiedersehen und alles Gute!', 'Auf Wiedersehen, bis zum nächsten Mal!'],
    emoji: '🫡',
    exampleSentence: 'Auf Wiedersehen, bis morgen!',
    exampleTranslation: 'Hoşça kalın, yarına kadar!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-7',
    german: 'Tschüss',
    turkish: 'Güle güle',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Ciao', 'Tschau', 'Bis dann'],
    collocations: ['Tschüss, mach\'s gut!', 'Tschüss, bis bald!'],
    emoji: '👋',
    exampleSentence: 'Tschüss, mach es gut!',
    exampleTranslation: 'Güle güle, kendine iyi bak!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-8',
    german: 'Willkommen',
    turkish: 'Hoş geldiniz',
    article: null,
    partOfSpeech: 'phrase',
    collocations: ['Herzlich willkommen!', 'Willkommen zu Hause!', 'Willkommen bei uns!'],
    emoji: '🤗',
    exampleSentence: 'Herzlich willkommen in Deutschland!',
    exampleTranslation: 'Almanya\'ya hoş geldiniz!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-9',
    german: 'Bitte',
    turkish: 'Lütfen / Rica ederim',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Bitte schön', 'Bitte sehr', 'Gern geschehen'],
    collocations: ['Bitte schön!', 'Ja, bitte!', 'Aber bitte!'],
    emoji: '🙏',
    exampleSentence: 'Bitte schön, hier ist Ihr Kaffee.',
    exampleTranslation: 'Buyurun, kahveniz burada.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-10',
    german: 'Danke',
    turkish: 'Teşekkürler',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Vielen Dank', 'Dankeschön', 'Danke sehr'],
    collocations: ['Danke für alles!', 'Danke, gleichfalls!', 'Nein, danke!'],
    emoji: '🙏',
    exampleSentence: 'Danke für deine Hilfe!',
    exampleTranslation: 'Yardımın için teşekkürler!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-11',
    german: 'Entschuldigung',
    turkish: 'Özür dilerim / Affedersiniz',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Entschuldigungen',
    synonyms: ['Verzeihung', 'Pardon', 'Tut mir leid'],
    collocations: ['Um Entschuldigung bitten', 'Entschuldigung annehmen', 'Entschuldigung, darf ich mal?'],
    emoji: '😔',
    exampleSentence: 'Entschuldigung, wo ist der Bahnhof?',
    exampleTranslation: 'Affedersiniz, tren istasyonu nerede?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-12',
    german: 'Wie geht es Ihnen?',
    turkish: 'Nasılsınız?',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Wie geht\'s?', 'Wie geht es dir?', 'Wie steht\'s?'],
    emoji: '❓',
    exampleSentence: 'Guten Tag! Wie geht es Ihnen?',
    exampleTranslation: 'İyi günler! Nasılsınız?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-13',
    german: 'Mir geht es gut',
    turkish: 'İyiyim',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Es geht mir gut', 'Mir geht\'s gut', 'Gut, danke'],
    antonyms: ['Mir geht es schlecht'],
    emoji: '😊',
    exampleSentence: 'Danke, mir geht es gut. Und Ihnen?',
    exampleTranslation: 'Teşekkürler, iyiyim. Ya siz?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-14',
    german: 'Ja',
    turkish: 'Evet',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Jawohl', 'Genau', 'Stimmt'],
    antonyms: ['Nein'],
    collocations: ['Ja, gerne!', 'Ja, bitte!', 'Ja, natürlich!'],
    emoji: '✅',
    exampleSentence: 'Ja, das stimmt.',
    exampleTranslation: 'Evet, bu doğru.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-15',
    german: 'Nein',
    turkish: 'Hayır',
    article: null,
    partOfSpeech: 'phrase',
    antonyms: ['Ja'],
    collocations: ['Nein, danke!', 'Nein, leider nicht.', 'Oh nein!'],
    emoji: '❌',
    exampleSentence: 'Nein, das möchte ich nicht.',
    exampleTranslation: 'Hayır, bunu istemiyorum.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-16',
    german: 'Wie heißen Sie?',
    turkish: 'Adınız ne?',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Wie ist Ihr Name?', 'Wie heißt du?'],
    emoji: '🪪',
    exampleSentence: 'Wie heißen Sie? Ich heiße Anna.',
    exampleTranslation: 'Adınız ne? Benim adım Anna.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-17',
    german: 'Ich heiße...',
    turkish: 'Benim adım...',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Mein Name ist...', 'Ich bin...'],
    emoji: '🏷️',
    exampleSentence: 'Ich heiße Thomas. Freut mich!',
    exampleTranslation: 'Benim adım Thomas. Memnun oldum!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-18',
    german: 'Woher kommen Sie?',
    turkish: 'Nerelisiniz?',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Woher kommst du?', 'Wo kommen Sie her?'],
    emoji: '🌍',
    exampleSentence: 'Woher kommen Sie? Aus der Türkei?',
    exampleTranslation: 'Nerelisiniz? Türkiye\'den mi?',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-19',
    german: 'Freut mich',
    turkish: 'Memnun oldum',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Sehr erfreut', 'Angenehm'],
    collocations: ['Freut mich, Sie kennenzulernen!', 'Freut mich sehr!'],
    emoji: '🤝',
    exampleSentence: 'Freut mich, Sie kennenzulernen!',
    exampleTranslation: 'Tanıştığımıza memnun oldum!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-20',
    german: 'Bis bald',
    turkish: 'Yakında görüşürüz',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Bis dann', 'Bis später', 'Bis demnächst'],
    emoji: '🔜',
    exampleSentence: 'Bis bald! Pass auf dich auf!',
    exampleTranslation: 'Yakında görüşürüz! Kendine iyi bak!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-21',
    german: 'Es tut mir leid',
    turkish: 'Üzgünüm',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Entschuldigung', 'Tut mir leid', 'Verzeihung'],
    emoji: '😞',
    exampleSentence: 'Es tut mir leid, ich bin zu spät.',
    exampleTranslation: 'Üzgünüm, geç kaldım.',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-22',
    german: 'Kein Problem',
    turkish: 'Sorun değil',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Macht nichts', 'Nicht schlimm', 'Kein Ding'],
    emoji: '👍',
    exampleSentence: 'Kein Problem, das macht nichts!',
    exampleTranslation: 'Sorun değil, önemli değil!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-23',
    german: 'Prost',
    turkish: 'Şerefe',
    article: null,
    partOfSpeech: 'phrase',
    synonyms: ['Zum Wohl', 'Cheers'],
    collocations: ['Prost Neujahr!', 'Prost, auf uns!'],
    emoji: '🍻',
    exampleSentence: 'Prost! Auf unsere Freundschaft!',
    exampleTranslation: 'Şerefe! Arkadaşlığımıza!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-24',
    german: 'Gesundheit',
    turkish: 'Çok yaşa',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['Gesundheit ist das Wichtigste.', 'Bei guter Gesundheit sein'],
    emoji: '🤧',
    exampleSentence: 'Hatschi! - Gesundheit!',
    exampleTranslation: 'Hapşu! - Çok yaşa!',
    category: 'greetings',
    level: 'A1',
  },
  {
    id: 'greetings-25',
    german: 'Vielleicht',
    turkish: 'Belki',
    article: null,
    partOfSpeech: 'adverb',
    synonyms: ['Möglicherweise', 'Eventuell', 'Womöglich'],
    antonyms: ['Bestimmt', 'Sicher', 'Auf jeden Fall'],
    collocations: ['Vielleicht morgen', 'Vielleicht klappt es', 'Ja, vielleicht'],
    emoji: '🤔',
    exampleSentence: 'Vielleicht komme ich morgen.',
    exampleTranslation: 'Belki yarın gelirim.',
    category: 'greetings',
    level: 'A1',
  },
];
