import { VocabularyWord } from '@/lib/types';
export const homeWords: VocabularyWord[] = [
  {
    id: 'home-1',
    german: 'Haus',
    turkish: 'Ev',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Häuser',
    emoji: '🏠',
    synonyms: ['Gebäude'],
    collocations: ['ein Haus bauen', 'nach Hause gehen', 'zu Hause sein'],
    exampleSentence: 'Das Haus ist groß.',
    exampleTranslation: 'Ev büyük.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-2',
    german: 'Wohnung',
    turkish: 'Daire',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Wohnungen',
    emoji: '🏢',
    synonyms: ['Appartement'],
    collocations: ['eine Wohnung mieten', 'eine Wohnung suchen', 'in eine Wohnung einziehen'],
    exampleSentence: 'Die Wohnung hat drei Zimmer.',
    exampleTranslation: 'Dairenin üç odası var.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-3',
    german: 'Küche',
    turkish: 'Mutfak',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Küchen',
    emoji: '🍳',
    collocations: ['in der Küche kochen', 'die Küche aufräumen', 'eine neue Küche einbauen'],
    exampleSentence: 'Ich koche in der Küche.',
    exampleTranslation: 'Mutfakta yemek yapıyorum.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-4',
    german: 'Schlafzimmer',
    turkish: 'Yatak odası',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Schlafzimmer',
    emoji: '🛏️',
    collocations: ['ins Schlafzimmer gehen', 'im Schlafzimmer schlafen'],
    exampleSentence: 'Das Schlafzimmer ist gemütlich.',
    exampleTranslation: 'Yatak odası rahat.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-5',
    german: 'Bad',
    turkish: 'Banyo',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Bäder',
    emoji: '🚿',
    synonyms: ['Badezimmer'],
    collocations: ['ins Bad gehen', 'ein Bad nehmen', 'das Bad putzen'],
    exampleSentence: 'Das Bad ist sauber.',
    exampleTranslation: 'Banyo temiz.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-6',
    german: 'Tür',
    turkish: 'Kapı',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Türen',
    emoji: '🚪',
    collocations: ['die Tür öffnen', 'die Tür schließen', 'an die Tür klopfen'],
    exampleSentence: 'Bitte schließen Sie die Tür.',
    exampleTranslation: 'Lütfen kapıyı kapatın.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-7',
    german: 'Fenster',
    turkish: 'Pencere',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Fenster',
    emoji: '🪟',
    collocations: ['das Fenster öffnen', 'das Fenster schließen', 'aus dem Fenster schauen'],
    exampleSentence: 'Öffne das Fenster!',
    exampleTranslation: 'Pencereyi aç!',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-8',
    german: 'Tisch',
    turkish: 'Masa',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Tische',
    emoji: '🪑',
    collocations: ['am Tisch sitzen', 'den Tisch decken', 'auf dem Tisch liegen'],
    exampleSentence: 'Das Buch liegt auf dem Tisch.',
    exampleTranslation: 'Kitap masada.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-9',
    german: 'Stuhl',
    turkish: 'Sandalye',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Stühle',
    emoji: '💺',
    synonyms: ['Sitz'],
    collocations: ['auf dem Stuhl sitzen', 'den Stuhl rücken', 'sich auf den Stuhl setzen'],
    exampleSentence: 'Setz dich auf den Stuhl.',
    exampleTranslation: 'Sandalyeye otur.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-10',
    german: 'Bett',
    turkish: 'Yatak',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Betten',
    emoji: '🛌',
    collocations: ['ins Bett gehen', 'im Bett liegen', 'das Bett machen'],
    exampleSentence: 'Das Bett ist bequem.',
    exampleTranslation: 'Yatak rahat.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-11',
    german: 'Schrank',
    turkish: 'Dolap',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Schränke',
    emoji: '🗄️',
    synonyms: ['Kleiderschrank'],
    collocations: ['den Schrank öffnen', 'die Kleidung in den Schrank hängen', 'im Schrank suchen'],
    exampleSentence: 'Die Kleidung ist im Schrank.',
    exampleTranslation: 'Kıyafetler dolapta.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-12',
    german: 'Lampe',
    turkish: 'Lamba',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Lampen',
    emoji: '💡',
    synonyms: ['Leuchte'],
    collocations: ['die Lampe anmachen', 'die Lampe ausmachen', 'die Lampe einschalten'],
    exampleSentence: 'Mach die Lampe an!',
    exampleTranslation: 'Lambayı aç!',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-13',
    german: 'Kühlschrank',
    turkish: 'Buzdolabı',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Kühlschränke',
    emoji: '🧊',
    collocations: ['den Kühlschrank öffnen', 'im Kühlschrank aufbewahren', 'den Kühlschrank einräumen'],
    exampleSentence: 'Die Milch ist im Kühlschrank.',
    exampleTranslation: 'Süt buzdolabında.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-14',
    german: 'Garten',
    turkish: 'Bahçe',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Gärten',
    emoji: '🌿',
    collocations: ['im Garten arbeiten', 'im Garten spielen', 'den Garten pflegen'],
    exampleSentence: 'Die Kinder spielen im Garten.',
    exampleTranslation: 'Çocuklar bahçede oynuyor.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-15',
    german: 'Schlüssel',
    turkish: 'Anahtar',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Schlüssel',
    emoji: '🔑',
    collocations: ['den Schlüssel verlieren', 'den Schlüssel suchen', 'den Schlüssel abgeben'],
    exampleSentence: 'Wo ist mein Schlüssel?',
    exampleTranslation: 'Anahtarım nerede?',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-16',
    german: 'Einrichtung',
    turkish: 'Döşeme/Mobilya',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Einrichtungen',
    emoji: '🛋️',
    synonyms: ['Möbel', 'Ausstattung'],
    collocations: ['die Einrichtung planen', 'eine moderne Einrichtung', 'die Einrichtung wechseln'],
    exampleSentence: 'Die Einrichtung der neuen Wohnung hat uns mehrere Wochen gekostet.',
    exampleTranslation: 'Yeni dairenin döşenmesi bize birkaç hafta sürdü.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-17',
    german: 'Miete',
    turkish: 'Kira',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Mieten',
    emoji: '💸',
    synonyms: ['Mietpreis'],
    antonyms: ['Eigentum'],
    collocations: ['die Miete zahlen', 'die Miete erhöhen', 'eine günstige Miete'],
    exampleSentence: 'Die Miete in Großstädten steigt von Jahr zu Jahr und wird für viele unbezahlbar.',
    exampleTranslation: 'Büyük şehirlerde kira yıldan yıla artıyor ve birçokları için ödenemez hale geliyor.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-18',
    german: 'Vermieter',
    turkish: 'Ev sahibi',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Vermieter',
    emoji: '🏘️',
    antonyms: ['Mieter'],
    collocations: ['den Vermieter informieren', 'der Vermieter kündigt', 'mit dem Vermieter sprechen'],
    exampleSentence: 'Der Vermieter hat angekündigt, die Wohnung ab nächstem Monat zu renovieren.',
    exampleTranslation: 'Ev sahibi, daireyi gelecek aydan itibaren tadilata alacağını bildirdi.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-19',
    german: 'Umzug',
    turkish: 'Taşınma',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Umzüge',
    emoji: '📦',
    synonyms: ['Wohnungswechsel'],
    collocations: ['einen Umzug planen', 'beim Umzug helfen', 'der Umzug ist stressig'],
    exampleSentence: 'Der Umzug in die neue Stadt war aufregend, aber auch mit viel Stress verbunden.',
    exampleTranslation: 'Yeni şehre taşınmak heyecan vericiydi ama çok stresli de oldu.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-20',
    german: 'Strom',
    turkish: 'Elektrik',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '⚡',
    synonyms: ['Elektrizität', 'Energie'],
    collocations: ['Strom sparen', 'den Strom anmelden', 'Strom verbrauchen'],
    exampleSentence: 'Wir versuchen, weniger Strom zu verbrauchen, um die Umwelt zu schonen.',
    exampleTranslation: 'Çevreyi korumak için daha az elektrik tüketmeye çalışıyoruz.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-21',
    german: 'Heizung',
    turkish: 'Isıtma/Kalorifer',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Heizungen',
    emoji: '🔥',
    collocations: ['die Heizung anstellen', 'die Heizung aufdrehen', 'die Heizung ist kaputt'],
    exampleSentence: 'Im Winter muss die Heizung regelmäßig gewartet werden, damit sie effizient arbeitet.',
    exampleTranslation: 'Kışın kaloriferın verimli çalışması için düzenli bakım yapılmalıdır.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-22',
    german: 'Nachbarschaft',
    turkish: 'Mahalle/Komşuluk',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Nachbarschaften',
    emoji: '🏘️',
    synonyms: ['Umgebung', 'Viertel'],
    collocations: ['in der Nachbarschaft wohnen', 'eine ruhige Nachbarschaft', 'gute Nachbarschaft pflegen'],
    exampleSentence: 'In unserer Nachbarschaft gibt es viele Familien mit kleinen Kindern.',
    exampleTranslation: 'Mahallemizde küçük çocuklu birçok aile var.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-23',
    german: 'Renovierung',
    turkish: 'Tadilat',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Renovierungen',
    emoji: '🔨',
    synonyms: ['Sanierung', 'Modernisierung'],
    collocations: ['eine Renovierung durchführen', 'die Renovierung planen', 'nach der Renovierung'],
    exampleSentence: 'Die Renovierung des Badezimmers hat länger gedauert als ursprünglich geplant.',
    exampleTranslation: 'Banyo tadilatı başlangıçta planlanandan daha uzun sürdü.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-24',
    german: 'Eigentumswohnung',
    turkish: 'Mülk daire',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Eigentumswohnungen',
    emoji: '🏠',
    antonyms: ['Mietwohnung'],
    collocations: ['eine Eigentumswohnung kaufen', 'eine Eigentumswohnung besitzen', 'in einer Eigentumswohnung wohnen'],
    exampleSentence: 'Viele junge Leute können sich heutzutage keine Eigentumswohnung mehr leisten.',
    exampleTranslation: 'Günümüzde birçok genç artık mülk daire almaya gücü yetmiyor.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-25',
    german: 'Mietvertrag',
    turkish: 'Kira sözleşmesi',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Mietverträge',
    emoji: '📄',
    synonyms: ['Mietkontrakt'],
    collocations: ['einen Mietvertrag unterschreiben', 'den Mietvertrag kündigen', 'im Mietvertrag steht'],
    exampleSentence: 'Lesen Sie den Mietvertrag sorgfältig durch, bevor Sie ihn unterschreiben.',
    exampleTranslation: 'Kira sözleşmesini imzalamadan önce dikkatlice okuyun.',
    category: 'home',
    level: 'B2',
  },
];
