import { VocabularyWord } from '@/lib/types';
export const homeWords: VocabularyWord[] = [
  {
    id: 'home-1',
    german: 'Haus',
    turkish: 'Ev',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Häuser',
    emoji: '🏠',
    synonyms: ['Gebäude'],
    collocations: ['ein Haus bauen', 'nach Hause gehen', 'zu Hause sein'],
    exampleSentence: 'Das Haus ist groß.',
    exampleTranslation: 'Ev büyük.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-2',
    german: 'Wohnung',
    turkish: 'Daire',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Wohnungen',
    emoji: '🏢',
    synonyms: ['Appartement'],
    collocations: ['eine Wohnung mieten', 'eine Wohnung suchen', 'in eine Wohnung einziehen'],
    exampleSentence: 'Die Wohnung hat drei Zimmer.',
    exampleTranslation: 'Dairenin üç odası var.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-3',
    german: 'Küche',
    turkish: 'Mutfak',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Küchen',
    emoji: '🍳',
    collocations: ['in der Küche kochen', 'die Küche aufräumen', 'eine neue Küche einbauen'],
    exampleSentence: 'Ich koche in der Küche.',
    exampleTranslation: 'Mutfakta yemek yapıyorum.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-4',
    german: 'Schlafzimmer',
    turkish: 'Yatak odası',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Schlafzimmer',
    emoji: '🛏️',
    collocations: ['ins Schlafzimmer gehen', 'im Schlafzimmer schlafen'],
    exampleSentence: 'Das Schlafzimmer ist gemütlich.',
    exampleTranslation: 'Yatak odası rahat.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-5',
    german: 'Bad',
    turkish: 'Banyo',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Bäder',
    emoji: '🚿',
    synonyms: ['Badezimmer'],
    collocations: ['ins Bad gehen', 'ein Bad nehmen', 'das Bad putzen'],
    exampleSentence: 'Das Bad ist sauber.',
    exampleTranslation: 'Banyo temiz.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-6',
    german: 'Tür',
    turkish: 'Kapı',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Türen',
    emoji: '🚪',
    collocations: ['die Tür öffnen', 'die Tür schließen', 'an die Tür klopfen'],
    exampleSentence: 'Bitte schließen Sie die Tür.',
    exampleTranslation: 'Lütfen kapıyı kapatın.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-7',
    german: 'Fenster',
    turkish: 'Pencere',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Fenster',
    emoji: '🪟',
    collocations: ['das Fenster öffnen', 'das Fenster schließen', 'aus dem Fenster schauen'],
    exampleSentence: 'Öffne das Fenster!',
    exampleTranslation: 'Pencereyi aç!',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-8',
    german: 'Tisch',
    turkish: 'Masa',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Tische',
    emoji: '🪑',
    collocations: ['am Tisch sitzen', 'den Tisch decken', 'auf dem Tisch liegen'],
    exampleSentence: 'Das Buch liegt auf dem Tisch.',
    exampleTranslation: 'Kitap masada.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-9',
    german: 'Stuhl',
    turkish: 'Sandalye',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Stühle',
    emoji: '💺',
    synonyms: ['Sitz'],
    collocations: ['auf dem Stuhl sitzen', 'den Stuhl rücken', 'sich auf den Stuhl setzen'],
    exampleSentence: 'Setz dich auf den Stuhl.',
    exampleTranslation: 'Sandalyeye otur.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-10',
    german: 'Bett',
    turkish: 'Yatak',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Betten',
    emoji: '🛌',
    collocations: ['ins Bett gehen', 'im Bett liegen', 'das Bett machen'],
    exampleSentence: 'Das Bett ist bequem.',
    exampleTranslation: 'Yatak rahat.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-11',
    german: 'Schrank',
    turkish: 'Dolap',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Schränke',
    emoji: '🗄️',
    synonyms: ['Kleiderschrank'],
    collocations: ['den Schrank öffnen', 'die Kleidung in den Schrank hängen', 'im Schrank suchen'],
    exampleSentence: 'Die Kleidung ist im Schrank.',
    exampleTranslation: 'Kıyafetler dolapta.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-12',
    german: 'Lampe',
    turkish: 'Lamba',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Lampen',
    emoji: '💡',
    synonyms: ['Leuchte'],
    collocations: ['die Lampe anmachen', 'die Lampe ausmachen', 'die Lampe einschalten'],
    exampleSentence: 'Mach die Lampe an!',
    exampleTranslation: 'Lambayı aç!',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-13',
    german: 'Kühlschrank',
    turkish: 'Buzdolabı',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Kühlschränke',
    emoji: '🧊',
    collocations: ['den Kühlschrank öffnen', 'im Kühlschrank aufbewahren', 'den Kühlschrank einräumen'],
    exampleSentence: 'Die Milch ist im Kühlschrank.',
    exampleTranslation: 'Süt buzdolabında.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-14',
    german: 'Garten',
    turkish: 'Bahçe',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Gärten',
    emoji: '🌿',
    collocations: ['im Garten arbeiten', 'im Garten spielen', 'den Garten pflegen'],
    exampleSentence: 'Die Kinder spielen im Garten.',
    exampleTranslation: 'Çocuklar bahçede oynuyor.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-15',
    german: 'Schlüssel',
    turkish: 'Anahtar',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Schlüssel',
    emoji: '🔑',
    collocations: ['den Schlüssel verlieren', 'den Schlüssel suchen', 'den Schlüssel abgeben'],
    exampleSentence: 'Wo ist mein Schlüssel?',
    exampleTranslation: 'Anahtarım nerede?',
    category: 'home',
    level: 'A1',
  },
];
