import { VocabularyWord } from '@/lib/types';
export const homeWords: VocabularyWord[] = [
  {
    id: 'home-1',
    german: 'Haus',
    turkish: 'Ev',
    english: 'house',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Häuser',
    emoji: '🏠',
    synonyms: ['Gebäude'],
    collocations: ['ein Haus bauen', 'nach Hause gehen', 'zu Hause sein'],
    exampleSentence: 'Das Haus ist groß.',
    exampleTranslation: 'Ev büyük.',
    exampleTranslationEn: 'The house is big.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-2',
    german: 'Wohnung',
    turkish: 'Daire',
    english: 'apartment',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Wohnungen',
    emoji: '🏢',
    synonyms: ['Appartement'],
    collocations: ['eine Wohnung mieten', 'eine Wohnung suchen', 'in eine Wohnung einziehen'],
    exampleSentence: 'Die Wohnung hat drei Zimmer.',
    exampleTranslation: 'Dairenin üç odası var.',
    exampleTranslationEn: 'The apartment has three rooms.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-3',
    german: 'Küche',
    turkish: 'Mutfak',
    english: 'kitchen',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Küchen',
    emoji: '🍳',
    collocations: ['in der Küche kochen', 'die Küche aufräumen', 'eine neue Küche einbauen'],
    exampleSentence: 'Ich koche in der Küche.',
    exampleTranslation: 'Mutfakta yemek yapıyorum.',
    exampleTranslationEn: 'I cook in the kitchen.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-4',
    german: 'Schlafzimmer',
    turkish: 'Yatak odası',
    english: 'bedroom',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Schlafzimmer',
    emoji: '🛏️',
    collocations: ['ins Schlafzimmer gehen', 'im Schlafzimmer schlafen'],
    exampleSentence: 'Das Schlafzimmer ist gemütlich.',
    exampleTranslation: 'Yatak odası rahat.',
    exampleTranslationEn: 'The bedroom is cozy.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-5',
    german: 'Bad',
    turkish: 'Banyo',
    english: 'bathroom',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Bäder',
    emoji: '🚿',
    synonyms: ['Badezimmer'],
    collocations: ['ins Bad gehen', 'ein Bad nehmen', 'das Bad putzen'],
    exampleSentence: 'Das Bad ist sauber.',
    exampleTranslation: 'Banyo temiz.',
    exampleTranslationEn: 'The bathroom is clean.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-6',
    german: 'Tür',
    turkish: 'Kapı',
    english: 'door',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Türen',
    emoji: '🚪',
    collocations: ['die Tür öffnen', 'die Tür schließen', 'an die Tür klopfen'],
    exampleSentence: 'Bitte schließen Sie die Tür.',
    exampleTranslation: 'Lütfen kapıyı kapatın.',
    exampleTranslationEn: 'Please close the door.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-7',
    german: 'Fenster',
    turkish: 'Pencere',
    english: 'window',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Fenster',
    emoji: '🪟',
    collocations: ['das Fenster öffnen', 'das Fenster schließen', 'aus dem Fenster schauen'],
    exampleSentence: 'Öffne das Fenster!',
    exampleTranslation: 'Pencereyi aç!',
    exampleTranslationEn: 'Open the window!',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-8',
    german: 'Tisch',
    turkish: 'Masa',
    english: 'table',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Tische',
    emoji: '🪑',
    collocations: ['am Tisch sitzen', 'den Tisch decken', 'auf dem Tisch liegen'],
    exampleSentence: 'Das Buch liegt auf dem Tisch.',
    exampleTranslation: 'Kitap masada.',
    exampleTranslationEn: 'The book is on the table.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-9',
    german: 'Stuhl',
    turkish: 'Sandalye',
    english: 'chair',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Stühle',
    emoji: '💺',
    synonyms: ['Sitz'],
    collocations: ['auf dem Stuhl sitzen', 'den Stuhl rücken', 'sich auf den Stuhl setzen'],
    exampleSentence: 'Setz dich auf den Stuhl.',
    exampleTranslation: 'Sandalyeye otur.',
    exampleTranslationEn: 'Sit down on the chair.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-10',
    german: 'Bett',
    turkish: 'Yatak',
    english: 'bed',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Betten',
    emoji: '🛌',
    collocations: ['ins Bett gehen', 'im Bett liegen', 'das Bett machen'],
    exampleSentence: 'Das Bett ist bequem.',
    exampleTranslation: 'Yatak rahat.',
    exampleTranslationEn: 'The bed is comfortable.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-11',
    german: 'Schrank',
    turkish: 'Dolap',
    english: 'closet/wardrobe',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Schränke',
    emoji: '🗄️',
    synonyms: ['Kleiderschrank'],
    collocations: ['den Schrank öffnen', 'die Kleidung in den Schrank hängen', 'im Schrank suchen'],
    exampleSentence: 'Die Kleidung ist im Schrank.',
    exampleTranslation: 'Kıyafetler dolapta.',
    exampleTranslationEn: 'The clothes are in the closet.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-12',
    german: 'Lampe',
    turkish: 'Lamba',
    english: 'lamp',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Lampen',
    emoji: '💡',
    synonyms: ['Leuchte'],
    collocations: ['die Lampe anmachen', 'die Lampe ausmachen', 'die Lampe einschalten'],
    exampleSentence: 'Mach die Lampe an!',
    exampleTranslation: 'Lambayı aç!',
    exampleTranslationEn: 'Turn on the lamp!',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-13',
    german: 'Kühlschrank',
    turkish: 'Buzdolabı',
    english: 'refrigerator',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Kühlschränke',
    emoji: '🧊',
    collocations: ['den Kühlschrank öffnen', 'im Kühlschrank aufbewahren', 'den Kühlschrank einräumen'],
    exampleSentence: 'Die Milch ist im Kühlschrank.',
    exampleTranslation: 'Süt buzdolabında.',
    exampleTranslationEn: 'The milk is in the refrigerator.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-14',
    german: 'Garten',
    turkish: 'Bahçe',
    english: 'garden',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Gärten',
    emoji: '🌿',
    collocations: ['im Garten arbeiten', 'im Garten spielen', 'den Garten pflegen'],
    exampleSentence: 'Die Kinder spielen im Garten.',
    exampleTranslation: 'Çocuklar bahçede oynuyor.',
    exampleTranslationEn: 'The children are playing in the garden.',
    category: 'home',
    level: 'A1',
  },
  {
    id: 'home-15',
    german: 'Schlüssel',
    turkish: 'Anahtar',
    english: 'key',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Schlüssel',
    emoji: '🔑',
    collocations: ['den Schlüssel verlieren', 'den Schlüssel suchen', 'den Schlüssel abgeben'],
    exampleSentence: 'Wo ist mein Schlüssel?',
    exampleTranslation: 'Anahtarım nerede?',
    exampleTranslationEn: 'Where is my key?',
    category: 'home',
    level: 'A1',
  },
  // B1 - Furniture, household
  {
    id: 'home-b1-1',
    german: 'die Einrichtung',
    turkish: 'döşeme / mobilya',
    english: 'furnishing / interior',
    article: 'die',
    plural: 'Einrichtungen',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Einrichtung der Wohnung ist sehr modern.',
    exampleTranslation: 'Dairenin döşemesi çok modern.',
    exampleTranslationEn: 'The furnishing of the apartment is very modern.',
    category: 'home',
    level: 'B1',
    tags: ['furniture', 'interior'],
  },
  {
    id: 'home-b1-2',
    german: 'renovieren',
    turkish: 'tadilat yapmak / yenilemek',
    english: 'to renovate',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Wir möchten die Küche renovieren.',
    exampleTranslation: 'Mutfağı yenilemek istiyoruz.',
    exampleTranslationEn: 'We want to renovate the kitchen.',
    category: 'home',
    level: 'B1',
    tags: ['renovation', 'maintenance'],
  },
  {
    id: 'home-b1-3',
    german: 'der Umzug',
    turkish: 'taşınma',
    english: 'move / relocation',
    article: 'der',
    plural: 'Umzüge',
    partOfSpeech: 'noun',
    exampleSentence: 'Der Umzug in die neue Wohnung ist nächsten Monat.',
    exampleTranslation: 'Yeni daireye taşınma gelecek ay.',
    exampleTranslationEn: 'The move to the new apartment is next month.',
    category: 'home',
    level: 'B1',
    tags: ['moving', 'relocation'],
  },
  {
    id: 'home-b1-4',
    german: 'die Miete',
    turkish: 'kira',
    english: 'rent',
    article: 'die',
    plural: 'Mieten',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Miete für diese Wohnung beträgt 800 Euro.',
    exampleTranslation: 'Bu dairenin kirası 800 Euro.',
    exampleTranslationEn: 'The rent for this apartment is 800 euros.',
    category: 'home',
    level: 'B1',
    tags: ['rent', 'housing'],
  },
  {
    id: 'home-b1-5',
    german: 'das Regal',
    turkish: 'raf',
    english: 'shelf',
    article: 'das',
    plural: 'Regale',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Bücher stehen im Regal.',
    exampleTranslation: 'Kitaplar rafta duruyor.',
    exampleTranslationEn: 'The books are on the shelf.',
    category: 'home',
    level: 'B1',
    tags: ['furniture', 'storage'],
  },
  {
    id: 'home-b1-6',
    german: 'die Waschmaschine',
    turkish: 'çamaşır makinesi',
    english: 'washing machine',
    article: 'die',
    plural: 'Waschmaschinen',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Waschmaschine ist kaputt und muss repariert werden.',
    exampleTranslation: 'Çamaşır makinesi bozuldu ve tamir edilmesi gerekiyor.',
    exampleTranslationEn: 'The washing machine is broken and needs to be repaired.',
    category: 'home',
    level: 'B1',
    tags: ['appliance', 'household'],
  },
  {
    id: 'home-b1-7',
    german: 'der Vermieter',
    turkish: 'ev sahibi',
    english: 'landlord',
    article: 'der',
    plural: 'Vermieter',
    partOfSpeech: 'noun',
    exampleSentence: 'Der Vermieter kommt morgen, um die Heizung zu prüfen.',
    exampleTranslation: 'Ev sahibi yarın kalöriferi kontrol etmek için geliyor.',
    exampleTranslationEn: 'The landlord is coming tomorrow to check the heating.',
    category: 'home',
    level: 'B1',
    tags: ['housing', 'rental'],
  },
  {
    id: 'home-b1-8',
    german: 'einziehen',
    turkish: 'taşınmak (eve)',
    english: 'to move in',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Wir ziehen nächste Woche in die neue Wohnung ein.',
    exampleTranslation: 'Gelecek hafta yeni daireye taşınıyoruz.',
    exampleTranslationEn: 'We are moving into the new apartment next week.',
    category: 'home',
    level: 'B1',
    tags: ['moving', 'housing'],
  },
  {
    id: 'home-b1-9',
    german: 'der Staubsauger',
    turkish: 'elektrikli süpürge',
    english: 'vacuum cleaner',
    article: 'der',
    plural: 'Staubsauger',
    partOfSpeech: 'noun',
    exampleSentence: 'Ich muss den Staubsauger kaufen, weil der alte kaputt ist.',
    exampleTranslation: 'Eski bozulduğu için elektrikli süpürge almam gerekiyor.',
    exampleTranslationEn: 'I need to buy a vacuum cleaner because the old one is broken.',
    category: 'home',
    level: 'B1',
    tags: ['appliance', 'cleaning'],
  },
  {
    id: 'home-b1-10',
    german: 'die Nebenkosten',
    turkish: 'ek masraflar / yan giderler',
    english: 'utility costs / additional costs',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Nebenkosten für Wasser und Heizung sind im Preis enthalten.',
    exampleTranslation: 'Su ve ısınma için ek masraflar fiyata dahildir.',
    exampleTranslationEn: 'The utility costs for water and heating are included in the price.',
    category: 'home',
    level: 'B1',
    tags: ['costs', 'housing'],
  },
  {
    id: 'home-16',
    german: 'Einrichtung',
    turkish: 'Döşeme/Mobilya',
    english: 'furnishing/interior',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Einrichtungen',
    emoji: '🛋️',
    synonyms: ['Möbel', 'Ausstattung'],
    collocations: ['die Einrichtung planen', 'eine moderne Einrichtung', 'die Einrichtung wechseln'],
    exampleSentence: 'Die Einrichtung der neuen Wohnung hat uns mehrere Wochen gekostet.',
    exampleTranslation: 'Yeni dairenin döşenmesi bize birkaç hafta sürdü.',
    exampleTranslationEn: 'Furnishing the new apartment took us several weeks.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-17',
    german: 'Miete',
    turkish: 'Kira',
    english: 'rent',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Mieten',
    emoji: '💸',
    synonyms: ['Mietpreis'],
    antonyms: ['Eigentum'],
    collocations: ['die Miete zahlen', 'die Miete erhöhen', 'eine günstige Miete'],
    exampleSentence: 'Die Miete in Großstädten steigt von Jahr zu Jahr und wird für viele unbezahlbar.',
    exampleTranslation: 'Büyük şehirlerde kira yıldan yıla artıyor ve birçokları için ödenemez hale geliyor.',
    exampleTranslationEn: 'Rent in big cities rises year by year and becomes unaffordable for many.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-18',
    german: 'Vermieter',
    turkish: 'Ev sahibi',
    english: 'landlord',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Vermieter',
    emoji: '🏘️',
    antonyms: ['Mieter'],
    collocations: ['den Vermieter informieren', 'der Vermieter kündigt', 'mit dem Vermieter sprechen'],
    exampleSentence: 'Der Vermieter hat angekündigt, die Wohnung ab nächstem Monat zu renovieren.',
    exampleTranslation: 'Ev sahibi, daireyi gelecek aydan itibaren tadilata alacağını bildirdi.',
    exampleTranslationEn: 'The landlord announced that he will renovate the apartment starting next month.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-19',
    german: 'Umzug',
    turkish: 'Taşınma',
    english: 'move/relocation',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Umzüge',
    emoji: '📦',
    synonyms: ['Wohnungswechsel'],
    collocations: ['einen Umzug planen', 'beim Umzug helfen', 'der Umzug ist stressig'],
    exampleSentence: 'Der Umzug in die neue Stadt war aufregend, aber auch mit viel Stress verbunden.',
    exampleTranslation: 'Yeni şehre taşınmak heyecan vericiydi ama çok stresli de oldu.',
    exampleTranslationEn: 'The move to the new city was exciting, but also very stressful.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-20',
    german: 'Strom',
    turkish: 'Elektrik',
    english: 'electricity',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '⚡',
    synonyms: ['Elektrizität', 'Energie'],
    collocations: ['Strom sparen', 'den Strom anmelden', 'Strom verbrauchen'],
    exampleSentence: 'Wir versuchen, weniger Strom zu verbrauchen, um die Umwelt zu schonen.',
    exampleTranslation: 'Çevreyi korumak için daha az elektrik tüketmeye çalışıyoruz.',
    exampleTranslationEn: 'We try to use less electricity to protect the environment.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-21',
    german: 'Heizung',
    turkish: 'Isıtma/Kalorifer',
    english: 'heating',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Heizungen',
    emoji: '🔥',
    collocations: ['die Heizung anstellen', 'die Heizung aufdrehen', 'die Heizung ist kaputt'],
    exampleSentence: 'Im Winter muss die Heizung regelmäßig gewartet werden, damit sie effizient arbeitet.',
    exampleTranslation: 'Kışın kaloriferın verimli çalışması için düzenli bakım yapılmalıdır.',
    exampleTranslationEn: 'In winter, the heating must be regularly maintained so that it works efficiently.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-22',
    german: 'Nachbarschaft',
    turkish: 'Mahalle/Komşuluk',
    english: 'neighborhood',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Nachbarschaften',
    emoji: '🏘️',
    synonyms: ['Umgebung', 'Viertel'],
    collocations: ['in der Nachbarschaft wohnen', 'eine ruhige Nachbarschaft', 'gute Nachbarschaft pflegen'],
    exampleSentence: 'In unserer Nachbarschaft gibt es viele Familien mit kleinen Kindern.',
    exampleTranslation: 'Mahallemizde küçük çocuklu birçok aile var.',
    exampleTranslationEn: 'In our neighborhood there are many families with small children.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-23',
    german: 'Renovierung',
    turkish: 'Tadilat',
    english: 'renovation',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Renovierungen',
    emoji: '🔨',
    synonyms: ['Sanierung', 'Modernisierung'],
    collocations: ['eine Renovierung durchführen', 'die Renovierung planen', 'nach der Renovierung'],
    exampleSentence: 'Die Renovierung des Badezimmers hat länger gedauert als ursprünglich geplant.',
    exampleTranslation: 'Banyo tadilatı başlangıçta planlanandan daha uzun sürdü.',
    exampleTranslationEn: 'The renovation of the bathroom took longer than originally planned.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-24',
    german: 'Eigentumswohnung',
    turkish: 'Mülk daire',
    english: 'condominium',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Eigentumswohnungen',
    emoji: '🏠',
    antonyms: ['Mietwohnung'],
    collocations: ['eine Eigentumswohnung kaufen', 'eine Eigentumswohnung besitzen', 'in einer Eigentumswohnung wohnen'],
    exampleSentence: 'Viele junge Leute können sich heutzutage keine Eigentumswohnung mehr leisten.',
    exampleTranslation: 'Günümüzde birçok genç artık mülk daire almaya gücü yetmiyor.',
    exampleTranslationEn: 'Many young people nowadays can no longer afford a condominium.',
    category: 'home',
    level: 'B2',
  },
  {
    id: 'home-25',
    german: 'Mietvertrag',
    turkish: 'Kira sözleşmesi',
    english: 'lease agreement',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Mietverträge',
    emoji: '📄',
    synonyms: ['Mietkontrakt'],
    collocations: ['einen Mietvertrag unterschreiben', 'den Mietvertrag kündigen', 'im Mietvertrag steht'],
    exampleSentence: 'Lesen Sie den Mietvertrag sorgfältig durch, bevor Sie ihn unterschreiben.',
    exampleTranslation: 'Kira sözleşmesini imzalamadan önce dikkatlice okuyun.',
    exampleTranslationEn: 'Read the lease agreement carefully before you sign it.',
    category: 'home',
    level: 'B2',
  },
];
