import { VocabularyWord } from '@/lib/types';
export const natureWords: VocabularyWord[] = [
  {
    id: 'nature-1',
    german: 'Sonne',
    turkish: 'Güneş',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Sonnen',
    emoji: '☀️',
    antonyms: ['Mond'],
    collocations: ['die Sonne scheint', 'in der Sonne liegen', 'die Sonne geht auf'],
    exampleSentence: 'Die Sonne scheint.',
    exampleTranslation: 'Güneş parlıyor.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-2',
    german: 'Mond',
    turkish: 'Ay',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Monde',
    emoji: '🌙',
    antonyms: ['Sonne'],
    collocations: ['der Mond scheint', 'der Vollmond', 'bei Mondschein'],
    exampleSentence: 'Der Mond ist voll.',
    exampleTranslation: 'Ay dolunay.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-3',
    german: 'Regen',
    turkish: 'Yağmur',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '🌧️',
    synonyms: ['Niederschlag'],
    antonyms: ['Sonnenschein'],
    collocations: ['es regnet', 'im Regen stehen', 'starker Regen'],
    exampleSentence: 'Es gibt heute Regen.',
    exampleTranslation: 'Bugün yağmur var.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-4',
    german: 'Schnee',
    turkish: 'Kar',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '❄️',
    collocations: ['es schneit', 'Schnee fällt', 'im Schnee spielen'],
    exampleSentence: 'Im Winter fällt Schnee.',
    exampleTranslation: 'Kışın kar yağar.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-5',
    german: 'Wind',
    turkish: 'Rüzgar',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Winde',
    emoji: '💨',
    synonyms: ['Brise'],
    collocations: ['der Wind weht', 'starker Wind', 'gegen den Wind'],
    exampleSentence: 'Der Wind ist stark.',
    exampleTranslation: 'Rüzgar kuvvetli.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-6',
    german: 'Wetter',
    turkish: 'Hava durumu',
    article: 'das',
    partOfSpeech: 'noun',
    emoji: '🌤️',
    synonyms: ['Witterung'],
    collocations: ['schönes Wetter', 'schlechtes Wetter', 'das Wetter wird besser'],
    exampleSentence: 'Wie ist das Wetter heute?',
    exampleTranslation: 'Bugün hava nasıl?',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-7',
    german: 'warm',
    turkish: 'sıcak/ılık',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🔥',
    synonyms: ['heiß'],
    antonyms: ['kalt', 'kühl'],
    collocations: ['es ist warm', 'warm anziehen', 'eine warme Jacke'],
    exampleSentence: 'Es ist warm draußen.',
    exampleTranslation: 'Dışarısı sıcak.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-8',
    german: 'kalt',
    turkish: 'soğuk',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🥶',
    synonyms: ['kühl', 'frostig'],
    antonyms: ['warm', 'heiß'],
    collocations: ['es ist kalt', 'kaltes Wasser', 'mir ist kalt'],
    exampleSentence: 'Im Winter ist es kalt.',
    exampleTranslation: 'Kışın soğuk olur.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-9',
    german: 'Baum',
    turkish: 'Ağaç',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Bäume',
    emoji: '🌳',
    collocations: ['einen Baum pflanzen', 'auf einen Baum klettern', 'unter dem Baum sitzen'],
    exampleSentence: 'Der Baum ist sehr alt.',
    exampleTranslation: 'Ağaç çok yaşlı.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-10',
    german: 'Blume',
    turkish: 'Çiçek',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Blumen',
    emoji: '🌸',
    collocations: ['Blumen pflücken', 'Blumen gießen', 'einen Strauß Blumen schenken'],
    exampleSentence: 'Die Blumen sind schön.',
    exampleTranslation: 'Çiçekler güzel.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-11',
    german: 'Berg',
    turkish: 'Dağ',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Berge',
    emoji: '⛰️',
    synonyms: ['Gebirge'],
    antonyms: ['Tal'],
    collocations: ['auf den Berg steigen', 'in den Bergen wandern', 'ein hoher Berg'],
    exampleSentence: 'Wir wandern in den Bergen.',
    exampleTranslation: 'Dağlarda yürüyüş yapıyoruz.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-12',
    german: 'See',
    turkish: 'Göl',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Seen',
    emoji: '🏞️',
    collocations: ['am See spazieren', 'im See schwimmen', 'an den See fahren'],
    exampleSentence: 'Der See ist sehr tief.',
    exampleTranslation: 'Göl çok derin.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-13',
    german: 'Hund',
    turkish: 'Köpek',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Hunde',
    emoji: '🐕',
    antonyms: ['Katze'],
    collocations: ['den Hund ausführen', 'mit dem Hund spazieren gehen', 'der Hund bellt'],
    exampleSentence: 'Der Hund ist treu.',
    exampleTranslation: 'Köpek sadık.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-14',
    german: 'Katze',
    turkish: 'Kedi',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Katzen',
    emoji: '🐈',
    antonyms: ['Hund'],
    collocations: ['die Katze streicheln', 'die Katze füttern', 'die Katze schnurrt'],
    exampleSentence: 'Die Katze schläft auf dem Sofa.',
    exampleTranslation: 'Kedi kanepede uyuyor.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-15',
    german: 'Vogel',
    turkish: 'Kuş',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Vögel',
    emoji: '🐦',
    collocations: ['die Vögel singen', 'ein Vogel fliegt', 'die Vögel füttern'],
    exampleSentence: 'Die Vögel singen am Morgen.',
    exampleTranslation: 'Kuşlar sabah şarkı söyler.',
    category: 'nature',
    level: 'A1',
  },
];
