import { VocabularyWord } from '@/lib/types';
export const natureWords: VocabularyWord[] = [
  {
    id: 'nature-1',
    german: 'Sonne',
    turkish: 'Güneş',
    english: 'sun',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Sonnen',
    emoji: '☀️',
    antonyms: ['Mond'],
    collocations: ['die Sonne scheint', 'in der Sonne liegen', 'die Sonne geht auf'],
    exampleSentence: 'Die Sonne scheint.',
    exampleTranslation: 'Güneş parlıyor.',
    exampleTranslationEn: 'The sun is shining.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-2',
    german: 'Mond',
    turkish: 'Ay',
    english: 'moon',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Monde',
    emoji: '🌙',
    antonyms: ['Sonne'],
    collocations: ['der Mond scheint', 'der Vollmond', 'bei Mondschein'],
    exampleSentence: 'Der Mond ist voll.',
    exampleTranslation: 'Ay dolunay.',
    exampleTranslationEn: 'The moon is full.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-3',
    german: 'Regen',
    turkish: 'Yağmur',
    english: 'rain',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '🌧️',
    synonyms: ['Niederschlag'],
    antonyms: ['Sonnenschein'],
    collocations: ['es regnet', 'im Regen stehen', 'starker Regen'],
    exampleSentence: 'Es gibt heute Regen.',
    exampleTranslation: 'Bugün yağmur var.',
    exampleTranslationEn: 'There is rain today.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-4',
    german: 'Schnee',
    turkish: 'Kar',
    english: 'snow',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '❄️',
    collocations: ['es schneit', 'Schnee fällt', 'im Schnee spielen'],
    exampleSentence: 'Im Winter fällt Schnee.',
    exampleTranslation: 'Kışın kar yağar.',
    exampleTranslationEn: 'In winter snow falls.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-5',
    german: 'Wind',
    turkish: 'Rüzgar',
    english: 'wind',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Winde',
    emoji: '💨',
    synonyms: ['Brise'],
    collocations: ['der Wind weht', 'starker Wind', 'gegen den Wind'],
    exampleSentence: 'Der Wind ist stark.',
    exampleTranslation: 'Rüzgar kuvvetli.',
    exampleTranslationEn: 'The wind is strong.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-6',
    german: 'Wetter',
    turkish: 'Hava durumu',
    english: 'weather',
    article: 'das',
    partOfSpeech: 'noun',
    emoji: '🌤️',
    synonyms: ['Witterung'],
    collocations: ['schönes Wetter', 'schlechtes Wetter', 'das Wetter wird besser'],
    exampleSentence: 'Wie ist das Wetter heute?',
    exampleTranslation: 'Bugün hava nasıl?',
    exampleTranslationEn: 'How is the weather today?',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-7',
    german: 'warm',
    turkish: 'sıcak/ılık',
    english: 'warm',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🔥',
    synonyms: ['heiß'],
    antonyms: ['kalt', 'kühl'],
    collocations: ['es ist warm', 'warm anziehen', 'eine warme Jacke'],
    exampleSentence: 'Es ist warm draußen.',
    exampleTranslation: 'Dışarısı sıcak.',
    exampleTranslationEn: 'It is warm outside.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-8',
    german: 'kalt',
    turkish: 'soğuk',
    english: 'cold',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🥶',
    synonyms: ['kühl', 'frostig'],
    antonyms: ['warm', 'heiß'],
    collocations: ['es ist kalt', 'kaltes Wasser', 'mir ist kalt'],
    exampleSentence: 'Im Winter ist es kalt.',
    exampleTranslation: 'Kışın soğuk olur.',
    exampleTranslationEn: 'In winter it is cold.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-9',
    german: 'Baum',
    turkish: 'Ağaç',
    english: 'tree',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Bäume',
    emoji: '🌳',
    collocations: ['einen Baum pflanzen', 'auf einen Baum klettern', 'unter dem Baum sitzen'],
    exampleSentence: 'Der Baum ist sehr alt.',
    exampleTranslation: 'Ağaç çok yaşlı.',
    exampleTranslationEn: 'The tree is very old.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-10',
    german: 'Blume',
    turkish: 'Çiçek',
    english: 'flower',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Blumen',
    emoji: '🌸',
    collocations: ['Blumen pflücken', 'Blumen gießen', 'einen Strauß Blumen schenken'],
    exampleSentence: 'Die Blumen sind schön.',
    exampleTranslation: 'Çiçekler güzel.',
    exampleTranslationEn: 'The flowers are beautiful.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-11',
    german: 'Berg',
    turkish: 'Dağ',
    english: 'mountain',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Berge',
    emoji: '⛰️',
    synonyms: ['Gebirge'],
    antonyms: ['Tal'],
    collocations: ['auf den Berg steigen', 'in den Bergen wandern', 'ein hoher Berg'],
    exampleSentence: 'Wir wandern in den Bergen.',
    exampleTranslation: 'Dağlarda yürüyüş yapıyoruz.',
    exampleTranslationEn: 'We are hiking in the mountains.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-12',
    german: 'See',
    turkish: 'Göl',
    english: 'lake',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Seen',
    emoji: '🏞️',
    collocations: ['am See spazieren', 'im See schwimmen', 'an den See fahren'],
    exampleSentence: 'Der See ist sehr tief.',
    exampleTranslation: 'Göl çok derin.',
    exampleTranslationEn: 'The lake is very deep.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-13',
    german: 'Hund',
    turkish: 'Köpek',
    english: 'dog',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Hunde',
    emoji: '🐕',
    antonyms: ['Katze'],
    collocations: ['den Hund ausführen', 'mit dem Hund spazieren gehen', 'der Hund bellt'],
    exampleSentence: 'Der Hund ist treu.',
    exampleTranslation: 'Köpek sadık.',
    exampleTranslationEn: 'The dog is loyal.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-14',
    german: 'Katze',
    turkish: 'Kedi',
    english: 'cat',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Katzen',
    emoji: '🐈',
    antonyms: ['Hund'],
    collocations: ['die Katze streicheln', 'die Katze füttern', 'die Katze schnurrt'],
    exampleSentence: 'Die Katze schläft auf dem Sofa.',
    exampleTranslation: 'Kedi kanepede uyuyor.',
    exampleTranslationEn: 'The cat is sleeping on the sofa.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-15',
    german: 'Vogel',
    turkish: 'Kuş',
    english: 'bird',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Vögel',
    emoji: '🐦',
    collocations: ['die Vögel singen', 'ein Vogel fliegt', 'die Vögel füttern'],
    exampleSentence: 'Die Vögel singen am Morgen.',
    exampleTranslation: 'Kuşlar sabah şarkı söyler.',
    exampleTranslationEn: 'The birds sing in the morning.',
    category: 'nature',
    level: 'A1',
  },
  {
    id: 'nature-16',
    german: 'Umwelt',
    turkish: 'Çevre',
    english: 'environment',
    article: 'die',
    partOfSpeech: 'noun',
    emoji: '🌍',
    synonyms: ['Umgebung', 'Natur'],
    collocations: ['die Umwelt schützen', 'die Umwelt schonen', 'umweltfreundlich sein'],
    exampleSentence: 'Wir müssen die Umwelt schützen, damit auch zukünftige Generationen gut leben können.',
    exampleTranslation: 'Gelecek nesillerin de iyi yaşayabilmesi için çevreyi korumalıyız.',
    exampleTranslationEn: 'We must protect the environment so that future generations can also live well.',
    category: 'nature',
    level: 'B2',
  },
  {
    id: 'nature-17',
    german: 'Klimawandel',
    turkish: 'İklim değişikliği',
    english: 'climate change',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '🌡️',
    synonyms: ['Klimaveränderung', 'Erderwärmung'],
    collocations: ['den Klimawandel bekämpfen', 'die Folgen des Klimawandels', 'vom Klimawandel betroffen sein'],
    exampleSentence: 'Der Klimawandel ist eine der größten Herausforderungen unserer Zeit.',
    exampleTranslation: 'İklim değişikliği zamanımızın en büyük zorluklarından biridir.',
    exampleTranslationEn: 'Climate change is one of the greatest challenges of our time.',
    category: 'nature',
    level: 'B2',
  },
  {
    id: 'nature-18',
    german: 'Erdbeben',
    turkish: 'Deprem',
    english: 'earthquake',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Erdbeben',
    emoji: '🌋',
    synonyms: ['Beben', 'Erderschütterung'],
    collocations: ['ein Erdbeben erschüttert', 'ein starkes Erdbeben', 'das Erdbeben messen'],
    exampleSentence: 'Das schwere Erdbeben hat zahlreiche Gebäude zerstört und viele Menschen obdachlos gemacht.',
    exampleTranslation: 'Şiddetli deprem çok sayıda binayı yıktı ve birçok insanı evsiz bıraktı.',
    exampleTranslationEn: 'The severe earthquake destroyed numerous buildings and left many people homeless.',
    category: 'nature',
    level: 'B2',
  },
  {
    id: 'nature-19',
    german: 'Überschwemmung',
    turkish: 'Sel/Su baskını',
    english: 'flood',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Überschwemmungen',
    emoji: '🌊',
    synonyms: ['Hochwasser', 'Flut'],
    antonyms: ['Dürre'],
    collocations: ['eine Überschwemmung verursachen', 'von einer Überschwemmung betroffen sein', 'Überschwemmungen vorbeugen'],
    exampleSentence: 'Nach dem starken Regen kam es in mehreren Regionen zu schweren Überschwemmungen.',
    exampleTranslation: 'Şiddetli yağmurdan sonra birçok bölgede ağır sel baskınları yaşandı.',
    exampleTranslationEn: 'After the heavy rain, severe floods occurred in several regions.',
    category: 'nature',
    level: 'B2',
  },
  {
    id: 'nature-20',
    german: 'Nachhaltigkeit',
    turkish: 'Sürdürülebilirlik',
    english: 'sustainability',
    article: 'die',
    partOfSpeech: 'noun',
    emoji: '♻️',
    synonyms: ['Zukunftsfähigkeit'],
    collocations: ['auf Nachhaltigkeit achten', 'Nachhaltigkeit fördern', 'im Sinne der Nachhaltigkeit'],
    exampleSentence: 'Nachhaltigkeit spielt in der modernen Wirtschaft eine immer wichtigere Rolle.',
    exampleTranslation: 'Sürdürülebilirlik modern ekonomide giderek daha önemli bir rol oynamaktadır.',
    exampleTranslationEn: 'Sustainability plays an increasingly important role in the modern economy.',
    category: 'nature',
    level: 'B2',
  },
  {
    id: 'nature-21',
    german: 'Artenschutz',
    turkish: 'Tür koruma',
    english: 'species conservation',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '🐼',
    synonyms: ['Tierschutz', 'Naturschutz'],
    collocations: ['den Artenschutz unterstützen', 'Maßnahmen zum Artenschutz', 'Artenschutz betreiben'],
    exampleSentence: 'Der Artenschutz ist entscheidend, um die biologische Vielfalt auf unserem Planeten zu erhalten.',
    exampleTranslation: 'Tür koruma, gezegenimizde biyolojik çeşitliliği korumak için hayati önem taşımaktadır.',
    exampleTranslationEn: 'Species conservation is crucial to preserving the biological diversity on our planet.',
    category: 'nature',
    level: 'B2',
  },
  {
    id: 'nature-22',
    german: 'Luftverschmutzung',
    turkish: 'Hava kirliliği',
    english: 'air pollution',
    article: 'die',
    partOfSpeech: 'noun',
    emoji: '🏭',
    synonyms: ['Luftverunreinigung', 'Smog'],
    collocations: ['die Luftverschmutzung reduzieren', 'unter Luftverschmutzung leiden', 'hohe Luftverschmutzung'],
    exampleSentence: 'Die Luftverschmutzung in Großstädten führt zu ernsthaften Gesundheitsproblemen bei der Bevölkerung.',
    exampleTranslation: 'Büyük şehirlerdeki hava kirliliği nüfusta ciddi sağlık sorunlarına yol açmaktadır.',
    exampleTranslationEn: 'Air pollution in big cities leads to serious health problems among the population.',
    category: 'nature',
    level: 'B2',
  },
  {
    id: 'nature-23',
    german: 'Wiederaufforstung',
    turkish: 'Ağaçlandırma/Yeniden ormanlaştırma',
    english: 'reforestation',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Wiederaufforstungen',
    emoji: '🌲',
    synonyms: ['Aufforstung'],
    antonyms: ['Abholzung', 'Entwaldung'],
    collocations: ['Wiederaufforstung betreiben', 'ein Programm zur Wiederaufforstung', 'Wiederaufforstung fördern'],
    exampleSentence: 'Die Regierung hat ein umfangreiches Programm zur Wiederaufforstung der abgeholzten Gebiete gestartet.',
    exampleTranslation: 'Hükümet, kesilen alanların yeniden ağaçlandırılması için kapsamlı bir program başlattı.',
    exampleTranslationEn: 'The government launched a comprehensive reforestation program for the deforested areas.',
    category: 'nature',
    level: 'B2',
  },
  {
    id: 'nature-24',
    german: 'Dürre',
    turkish: 'Kuraklık',
    english: 'drought',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Dürren',
    emoji: '🏜️',
    synonyms: ['Trockenheit', 'Trockenperiode'],
    antonyms: ['Überschwemmung', 'Hochwasser'],
    collocations: ['unter einer Dürre leiden', 'eine langanhaltende Dürre', 'die Dürre überstehen'],
    exampleSentence: 'Die langanhaltende Dürre hat die Ernte in vielen Regionen erheblich beeinträchtigt.',
    exampleTranslation: 'Uzun süren kuraklık birçok bölgede hasadı önemli ölçüde olumsuz etkiledi.',
    exampleTranslationEn: 'The prolonged drought significantly affected the harvest in many regions.',
    category: 'nature',
    level: 'B2',
  },
  {
    id: 'nature-25',
    german: 'Gewitter',
    turkish: 'Fırtına/Gök gürültülü sağanak',
    english: 'thunderstorm',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Gewitter',
    emoji: '⛈️',
    synonyms: ['Unwetter', 'Donnerwetter'],
    collocations: ['ein Gewitter zieht auf', 'ein heftiges Gewitter', 'bei Gewitter Schutz suchen'],
    exampleSentence: 'Am Nachmittag zog ein heftiges Gewitter auf und es wurde vor Blitzschlag gewarnt.',
    exampleTranslation: 'Öğleden sonra şiddetli bir fırtına yaklaştı ve yıldırım düşmesine karşı uyarıda bulunuldu.',
    exampleTranslationEn: 'In the afternoon a severe thunderstorm approached and there was a warning about lightning strikes.',
    category: 'nature',
    level: 'B2',
  },
];
