import { VocabularyWord } from '@/lib/types';

export const numbersWords: VocabularyWord[] = [
  { id: 'numbers-1', german: 'eins', turkish: 'bir', english: 'one', article: null, partOfSpeech: 'noun', emoji: '1️⃣', collocations: ['eins zu eins', 'Nummer eins'], exampleSentence: 'Ich habe eins bekommen.', exampleTranslation: 'Bir tane aldım.', exampleTranslationEn: 'I got one.', category: 'numbers', level: 'A1' },
  { id: 'numbers-2', german: 'zwei', turkish: 'iki', english: 'two', article: null, partOfSpeech: 'noun', emoji: '2️⃣', collocations: ['zu zweit', 'in zwei Teile'], exampleSentence: 'Ich habe zwei Brüder.', exampleTranslation: 'İki erkek kardeşim var.', exampleTranslationEn: 'I have two brothers.', category: 'numbers', level: 'A1' },
  { id: 'numbers-3', german: 'drei', turkish: 'üç', english: 'three', article: null, partOfSpeech: 'noun', emoji: '3️⃣', collocations: ['alle guten Dinge sind drei', 'zu dritt'], exampleSentence: 'Es ist drei Uhr.', exampleTranslation: 'Saat üç.', exampleTranslationEn: 'It is three o\'clock.', category: 'numbers', level: 'A1' },
  { id: 'numbers-4', german: 'vier', turkish: 'dört', english: 'four', article: null, partOfSpeech: 'noun', emoji: '4️⃣', collocations: ['auf allen vieren', 'vier Jahreszeiten'], exampleSentence: 'Vier Jahreszeiten gibt es.', exampleTranslation: 'Dört mevsim var.', exampleTranslationEn: 'There are four seasons.', category: 'numbers', level: 'A1' },
  { id: 'numbers-5', german: 'fünf', turkish: 'beş', english: 'five', article: null, partOfSpeech: 'noun', emoji: '5️⃣', collocations: ['fünf Sinne', 'fünf vor zwölf'], exampleSentence: 'Ich habe fünf Finger an jeder Hand.', exampleTranslation: 'Her elimde beş parmak var.', exampleTranslationEn: 'I have five fingers on each hand.', category: 'numbers', level: 'A1' },
  { id: 'numbers-6', german: 'sechs', turkish: 'altı', english: 'six', article: null, partOfSpeech: 'noun', emoji: '6️⃣', collocations: ['um sechs Uhr', 'eine Sechs würfeln'], exampleSentence: 'Wir essen um sechs Uhr.', exampleTranslation: 'Saat altıda yemek yeriz.', exampleTranslationEn: 'We eat at six o\'clock.', category: 'numbers', level: 'A1' },
  { id: 'numbers-7', german: 'sieben', turkish: 'yedi', english: 'seven', article: null, partOfSpeech: 'noun', emoji: '7️⃣', collocations: ['sieben Tage die Woche', 'auf Wolke sieben'], exampleSentence: 'Eine Woche hat sieben Tage.', exampleTranslation: 'Bir hafta yedi gündür.', exampleTranslationEn: 'A week has seven days.', category: 'numbers', level: 'A1' },
  { id: 'numbers-8', german: 'acht', turkish: 'sekiz', english: 'eight', article: null, partOfSpeech: 'noun', emoji: '8️⃣', collocations: ['um acht Uhr', 'sich in Acht nehmen'], exampleSentence: 'Die Schule beginnt um acht.', exampleTranslation: 'Okul sekizde başlar.', exampleTranslationEn: 'School starts at eight.', category: 'numbers', level: 'A1' },
  { id: 'numbers-9', german: 'neun', turkish: 'dokuz', english: 'nine', article: null, partOfSpeech: 'noun', emoji: '9️⃣', exampleSentence: 'Neun ist meine Glückszahl.', exampleTranslation: 'Dokuz benim şanslı sayım.', exampleTranslationEn: 'Nine is my lucky number.', category: 'numbers', level: 'A1' },
  { id: 'numbers-10', german: 'zehn', turkish: 'on', english: 'ten', article: null, partOfSpeech: 'noun', emoji: '🔟', collocations: ['bis zehn zählen', 'die Top Ten'], exampleSentence: 'Ich zähle bis zehn.', exampleTranslation: 'Ona kadar sayıyorum.', exampleTranslationEn: 'I count to ten.', category: 'numbers', level: 'A1' },
  { id: 'numbers-11', german: 'zwanzig', turkish: 'yirmi', english: 'twenty', article: null, partOfSpeech: 'noun', emoji: '🔢', collocations: ['zwanzig Jahre alt', 'die goldenen Zwanziger'], exampleSentence: 'Ich bin zwanzig Jahre alt.', exampleTranslation: 'Yirmi yaşındayım.', exampleTranslationEn: 'I am twenty years old.', category: 'numbers', level: 'A1' },
  { id: 'numbers-12', german: 'hundert', turkish: 'yüz', english: 'hundred', article: null, partOfSpeech: 'noun', emoji: '💯', collocations: ['hundert Prozent', 'ein paar Hundert'], exampleSentence: 'Hundert Prozent richtig!', exampleTranslation: 'Yüzde yüz doğru!', exampleTranslationEn: 'One hundred percent correct!', category: 'numbers', level: 'A1' },
  { id: 'numbers-13', german: 'tausend', turkish: 'bin', english: 'thousand', article: null, partOfSpeech: 'noun', emoji: '🔢', collocations: ['tausend Dank', 'Tausende von Menschen'], exampleSentence: 'Es kostet tausend Euro.', exampleTranslation: 'Bin Euro tutuyor.', exampleTranslationEn: 'It costs a thousand euros.', category: 'numbers', level: 'A1' },
  { id: 'numbers-14', german: 'erste', turkish: 'birinci', english: 'first', article: null, partOfSpeech: 'adjective', emoji: '🥇', collocations: ['der erste Eindruck', 'zum ersten Mal', 'an erster Stelle'], exampleSentence: 'Das ist mein erstes Auto.', exampleTranslation: 'Bu benim ilk arabam.', exampleTranslationEn: 'This is my first car.', category: 'numbers', level: 'A1' },
  { id: 'numbers-15', german: 'zweite', turkish: 'ikinci', english: 'second', article: null, partOfSpeech: 'adjective', emoji: '🥈', collocations: ['die zweite Chance', 'zum zweiten Mal', 'aus zweiter Hand'], exampleSentence: 'Die zweite Straße links.', exampleTranslation: 'İkinci sokak solda.', exampleTranslationEn: 'The second street on the left.', category: 'numbers', level: 'A1' },
  { id: 'numbers-16', german: 'halb', turkish: 'yarım', english: 'half', article: null, partOfSpeech: 'adjective', emoji: '➗', synonyms: ['zur Hälfte'], antonyms: ['ganz', 'doppelt'], collocations: ['halb so viel', 'halb drei', 'eine halbe Stunde'], exampleSentence: 'Es ist halb drei.', exampleTranslation: 'Saat iki buçuk.', exampleTranslationEn: 'It is half past two.', category: 'numbers', level: 'A1' },
  { id: 'numbers-17', german: 'Viertel', turkish: 'çeyrek', english: 'quarter', article: 'das', partOfSpeech: 'noun', emoji: '¼', collocations: ['Viertel nach', 'Viertel vor', 'ein Viertel der Bevölkerung'], exampleSentence: 'Es ist Viertel nach vier.', exampleTranslation: 'Saat dördü çeyrek geçiyor.', exampleTranslationEn: 'It is a quarter past four.', category: 'numbers', level: 'A1' },
  { id: 'numbers-18', german: 'doppelt', turkish: 'çift/iki kat', english: 'double', article: null, partOfSpeech: 'adjective', emoji: '✖️', antonyms: ['halb', 'einfach'], collocations: ['doppelt so viel', 'doppelte Portion', 'doppelt gemoppelt'], exampleSentence: 'Ich nehme die doppelte Portion.', exampleTranslation: 'İki kat porsiyon alıyorum.', exampleTranslationEn: 'I will take the double portion.', category: 'numbers', level: 'A1' },
  // B1 - Percentages, statistics, math
  {
    id: 'numbers-b1-1',
    german: 'das Prozent',
    turkish: 'yüzde',
    english: 'percent',
    article: 'das',
    plural: 'Prozent',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Preise sind um zehn Prozent gestiegen.',
    exampleTranslation: 'Fiyatlar yüzde on arttı.',
    exampleTranslationEn: 'Prices have risen by ten percent.',
    category: 'numbers',
    level: 'B1',
    tags: ['math', 'statistics'],
  },
  {
    id: 'numbers-b1-2',
    german: 'berechnen',
    turkish: 'hesaplamak',
    english: 'to calculate',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Können Sie bitte die Gesamtkosten berechnen?',
    exampleTranslation: 'Toplam maliyeti hesaplayabilir misiniz lütfen?',
    exampleTranslationEn: 'Can you please calculate the total costs?',
    category: 'numbers',
    level: 'B1',
    tags: ['math', 'calculation'],
  },
  {
    id: 'numbers-b1-3',
    german: 'die Hälfte',
    turkish: 'yarısı',
    english: 'half',
    article: 'die',
    plural: 'Hälften',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Hälfte der Studenten hat die Prüfung bestanden.',
    exampleTranslation: 'Öğrencilerin yarısı sınavı geçti.',
    exampleTranslationEn: 'Half of the students passed the exam.',
    category: 'numbers',
    level: 'B1',
    tags: ['math', 'quantity'],
  },
  {
    id: 'numbers-b1-4',
    german: 'das Drittel',
    turkish: 'üçte bir',
    english: 'third (fraction)',
    article: 'das',
    plural: 'Drittel',
    partOfSpeech: 'noun',
    exampleSentence: 'Ein Drittel der Bevölkerung lebt in der Stadt.',
    exampleTranslation: 'Nüfusun üçte biri şehirde yaşıyor.',
    exampleTranslationEn: 'A third of the population lives in the city.',
    category: 'numbers',
    level: 'B1',
    tags: ['math', 'fraction'],
  },
  {
    id: 'numbers-b1-5',
    german: 'die Statistik',
    turkish: 'istatistik',
    english: 'statistics',
    article: 'die',
    plural: 'Statistiken',
    partOfSpeech: 'noun',
    exampleSentence: 'Laut Statistik fahren immer mehr Leute mit dem Fahrrad.',
    exampleTranslation: 'İstatistiklere göre giderek daha fazla insan bisiklet kullanıyor.',
    exampleTranslationEn: 'According to statistics, more and more people ride bicycles.',
    category: 'numbers',
    level: 'B1',
    tags: ['data', 'statistics'],
  },
  {
    id: 'numbers-b1-6',
    german: 'ungefähr',
    turkish: 'yaklaşık / aşağı yukarı',
    english: 'approximately',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Es dauert ungefähr zwei Stunden.',
    exampleTranslation: 'Yaklaşık iki saat sürer.',
    exampleTranslationEn: 'It takes approximately two hours.',
    category: 'numbers',
    level: 'B1',
    tags: ['approximation', 'quantity'],
  },
  {
    id: 'numbers-b1-7',
    german: 'die Mehrheit',
    turkish: 'çoğunluk',
    english: 'majority',
    article: 'die',
    plural: 'Mehrheiten',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Mehrheit der Teilnehmer war zufrieden.',
    exampleTranslation: 'Katılımcıların çoğunluğu memnundu.',
    exampleTranslationEn: 'The majority of participants were satisfied.',
    category: 'numbers',
    level: 'B1',
    tags: ['quantity', 'statistics'],
  },
  {
    id: 'numbers-b1-8',
    german: 'steigen',
    turkish: 'artmak / yükselmek',
    english: 'to rise / to increase',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Die Temperaturen steigen im Sommer auf über 30 Grad.',
    exampleTranslation: 'Yazın sıcaklıklar 30 derecenin üzerine çıkar.',
    exampleTranslationEn: 'Temperatures rise above 30 degrees in summer.',
    category: 'numbers',
    level: 'B1',
    tags: ['increase', 'statistics'],
  },
  {
    id: 'numbers-b1-9',
    german: 'sinken',
    turkish: 'azalmak / düşmek',
    english: 'to decrease / to drop',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Die Arbeitslosigkeit ist in den letzten Jahren gesunken.',
    exampleTranslation: 'Son yıllarda işsizlik azaldı.',
    exampleTranslationEn: 'Unemployment has decreased in recent years.',
    category: 'numbers',
    level: 'B1',
    tags: ['decrease', 'statistics'],
  },
  {
    id: 'numbers-b1-10',
    german: 'der Durchschnitt',
    turkish: 'ortalama',
    english: 'average',
    article: 'der',
    partOfSpeech: 'noun',
    exampleSentence: 'Im Durchschnitt arbeiten die Deutschen 38 Stunden pro Woche.',
    exampleTranslation: 'Almanlar ortalama haftada 38 saat çalışır.',
    exampleTranslationEn: 'On average, Germans work 38 hours per week.',
    category: 'numbers',
    level: 'B1',
    tags: ['math', 'statistics'],
  },
];
