import { VocabularyWord } from '@/lib/types';

export const numbersWords: VocabularyWord[] = [
  { id: 'numbers-1', german: 'eins', turkish: 'bir', article: null, partOfSpeech: 'noun', emoji: '1️⃣', collocations: ['eins zu eins', 'Nummer eins'], exampleSentence: 'Ich habe eins bekommen.', exampleTranslation: 'Bir tane aldım.', category: 'numbers', level: 'A1' },
  { id: 'numbers-2', german: 'zwei', turkish: 'iki', article: null, partOfSpeech: 'noun', emoji: '2️⃣', collocations: ['zu zweit', 'in zwei Teile'], exampleSentence: 'Ich habe zwei Brüder.', exampleTranslation: 'İki erkek kardeşim var.', category: 'numbers', level: 'A1' },
  { id: 'numbers-3', german: 'drei', turkish: 'üç', article: null, partOfSpeech: 'noun', emoji: '3️⃣', collocations: ['alle guten Dinge sind drei', 'zu dritt'], exampleSentence: 'Es ist drei Uhr.', exampleTranslation: 'Saat üç.', category: 'numbers', level: 'A1' },
  { id: 'numbers-4', german: 'vier', turkish: 'dört', article: null, partOfSpeech: 'noun', emoji: '4️⃣', collocations: ['auf allen vieren', 'vier Jahreszeiten'], exampleSentence: 'Vier Jahreszeiten gibt es.', exampleTranslation: 'Dört mevsim var.', category: 'numbers', level: 'A1' },
  { id: 'numbers-5', german: 'fünf', turkish: 'beş', article: null, partOfSpeech: 'noun', emoji: '5️⃣', collocations: ['fünf Sinne', 'fünf vor zwölf'], exampleSentence: 'Ich habe fünf Finger an jeder Hand.', exampleTranslation: 'Her elimde beş parmak var.', category: 'numbers', level: 'A1' },
  { id: 'numbers-6', german: 'sechs', turkish: 'altı', article: null, partOfSpeech: 'noun', emoji: '6️⃣', collocations: ['um sechs Uhr', 'eine Sechs würfeln'], exampleSentence: 'Wir essen um sechs Uhr.', exampleTranslation: 'Saat altıda yemek yeriz.', category: 'numbers', level: 'A1' },
  { id: 'numbers-7', german: 'sieben', turkish: 'yedi', article: null, partOfSpeech: 'noun', emoji: '7️⃣', collocations: ['sieben Tage die Woche', 'auf Wolke sieben'], exampleSentence: 'Eine Woche hat sieben Tage.', exampleTranslation: 'Bir hafta yedi gündür.', category: 'numbers', level: 'A1' },
  { id: 'numbers-8', german: 'acht', turkish: 'sekiz', article: null, partOfSpeech: 'noun', emoji: '8️⃣', collocations: ['um acht Uhr', 'sich in Acht nehmen'], exampleSentence: 'Die Schule beginnt um acht.', exampleTranslation: 'Okul sekizde başlar.', category: 'numbers', level: 'A1' },
  { id: 'numbers-9', german: 'neun', turkish: 'dokuz', article: null, partOfSpeech: 'noun', emoji: '9️⃣', exampleSentence: 'Neun ist meine Glückszahl.', exampleTranslation: 'Dokuz benim şanslı sayım.', category: 'numbers', level: 'A1' },
  { id: 'numbers-10', german: 'zehn', turkish: 'on', article: null, partOfSpeech: 'noun', emoji: '🔟', collocations: ['bis zehn zählen', 'die Top Ten'], exampleSentence: 'Ich zähle bis zehn.', exampleTranslation: 'Ona kadar sayıyorum.', category: 'numbers', level: 'A1' },
  { id: 'numbers-11', german: 'zwanzig', turkish: 'yirmi', article: null, partOfSpeech: 'noun', emoji: '🔢', collocations: ['zwanzig Jahre alt', 'die goldenen Zwanziger'], exampleSentence: 'Ich bin zwanzig Jahre alt.', exampleTranslation: 'Yirmi yaşındayım.', category: 'numbers', level: 'A1' },
  { id: 'numbers-12', german: 'hundert', turkish: 'yüz', article: null, partOfSpeech: 'noun', emoji: '💯', collocations: ['hundert Prozent', 'ein paar Hundert'], exampleSentence: 'Hundert Prozent richtig!', exampleTranslation: 'Yüzde yüz doğru!', category: 'numbers', level: 'A1' },
  { id: 'numbers-13', german: 'tausend', turkish: 'bin', article: null, partOfSpeech: 'noun', emoji: '🔢', collocations: ['tausend Dank', 'Tausende von Menschen'], exampleSentence: 'Es kostet tausend Euro.', exampleTranslation: 'Bin Euro tutuyor.', category: 'numbers', level: 'A1' },
  { id: 'numbers-14', german: 'erste', turkish: 'birinci', article: null, partOfSpeech: 'adjective', emoji: '🥇', collocations: ['der erste Eindruck', 'zum ersten Mal', 'an erster Stelle'], exampleSentence: 'Das ist mein erstes Auto.', exampleTranslation: 'Bu benim ilk arabam.', category: 'numbers', level: 'A1' },
  { id: 'numbers-15', german: 'zweite', turkish: 'ikinci', article: null, partOfSpeech: 'adjective', emoji: '🥈', collocations: ['die zweite Chance', 'zum zweiten Mal', 'aus zweiter Hand'], exampleSentence: 'Die zweite Straße links.', exampleTranslation: 'İkinci sokak solda.', category: 'numbers', level: 'A1' },
  { id: 'numbers-16', german: 'halb', turkish: 'yarım', article: null, partOfSpeech: 'adjective', emoji: '➗', synonyms: ['zur Hälfte'], antonyms: ['ganz', 'doppelt'], collocations: ['halb so viel', 'halb drei', 'eine halbe Stunde'], exampleSentence: 'Es ist halb drei.', exampleTranslation: 'Saat iki buçuk.', category: 'numbers', level: 'A1' },
  { id: 'numbers-17', german: 'Viertel', turkish: 'çeyrek', article: 'das', partOfSpeech: 'noun', emoji: '¼', collocations: ['Viertel nach', 'Viertel vor', 'ein Viertel der Bevölkerung'], exampleSentence: 'Es ist Viertel nach vier.', exampleTranslation: 'Saat dördü çeyrek geçiyor.', category: 'numbers', level: 'A1' },
  { id: 'numbers-18', german: 'doppelt', turkish: 'çift/iki kat', article: null, partOfSpeech: 'adjective', emoji: '✖️', antonyms: ['halb', 'einfach'], collocations: ['doppelt so viel', 'doppelte Portion', 'doppelt gemoppelt'], exampleSentence: 'Ich nehme die doppelte Portion.', exampleTranslation: 'İki kat porsiyon alıyorum.', category: 'numbers', level: 'A1' },
];
