import { VocabularyWord } from '@/lib/types';
export const shoppingWords: VocabularyWord[] = [
  {
    id: 'shopping-1',
    german: 'Geschäft',
    turkish: 'Dükkan/Mağaza',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Geschäfte',
    emoji: '🏪',
    synonyms: ['Laden', 'Shop'],
    collocations: ['ein Geschäft eröffnen', 'ins Geschäft gehen', 'das Geschäft schließt'],
    exampleSentence: 'Das Geschäft öffnet um 9 Uhr.',
    exampleTranslation: 'Mağaza saat 9\'da açılır.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-2',
    german: 'Supermarkt',
    turkish: 'Süpermarket',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Supermärkte',
    emoji: '🛒',
    synonyms: ['Einkaufsmarkt', 'Lebensmittelgeschäft'],
    collocations: ['im Supermarkt einkaufen', 'zum Supermarkt gehen', 'der Supermarkt hat geöffnet'],
    exampleSentence: 'Ich gehe zum Supermarkt.',
    exampleTranslation: 'Süpermarkete gidiyorum.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-3',
    german: 'Preis',
    turkish: 'Fiyat',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Preise',
    emoji: '🏷️',
    synonyms: ['Kosten', 'Betrag'],
    collocations: ['den Preis fragen', 'einen guten Preis machen', 'der Preis steigt'],
    exampleSentence: 'Was ist der Preis?',
    exampleTranslation: 'Fiyat ne?',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-4',
    german: 'Geld',
    turkish: 'Para',
    article: 'das',
    partOfSpeech: 'noun',
    emoji: '💵',
    synonyms: ['Bargeld', 'Kohle'],
    collocations: ['Geld ausgeben', 'Geld sparen', 'Geld abheben'],
    exampleSentence: 'Ich habe kein Geld dabei.',
    exampleTranslation: 'Yanımda param yok.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-5',
    german: 'teuer',
    turkish: 'pahalı',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '💎',
    synonyms: ['kostspielig', 'hochpreisig'],
    antonyms: ['billig', 'günstig', 'preiswert'],
    collocations: ['zu teuer sein', 'sehr teuer', 'das ist mir zu teuer'],
    exampleSentence: 'Das ist zu teuer.',
    exampleTranslation: 'Bu çok pahalı.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-6',
    german: 'billig',
    turkish: 'ucuz',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🪙',
    synonyms: ['günstig', 'preiswert'],
    antonyms: ['teuer', 'kostspielig'],
    collocations: ['sehr billig', 'billig einkaufen', 'billig und gut'],
    exampleSentence: 'Hier ist alles billig.',
    exampleTranslation: 'Burada her şey ucuz.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-7',
    german: 'kaufen',
    turkish: 'satın almak',
    article: null,
    partOfSpeech: 'verb',
    emoji: '🛍️',
    synonyms: ['erwerben', 'anschaffen'],
    antonyms: ['verkaufen'],
    collocations: ['etwas kaufen', 'online kaufen', 'günstig kaufen'],
    exampleSentence: 'Ich möchte ein Buch kaufen.',
    exampleTranslation: 'Bir kitap almak istiyorum.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-8',
    german: 'bezahlen',
    turkish: 'ödemek',
    article: null,
    partOfSpeech: 'verb',
    emoji: '💳',
    synonyms: ['zahlen', 'begleichen'],
    collocations: ['mit Karte bezahlen', 'bar bezahlen', 'die Rechnung bezahlen'],
    exampleSentence: 'Kann ich mit Karte bezahlen?',
    exampleTranslation: 'Kartla ödeyebilir miyim?',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-9',
    german: 'Kleidung',
    turkish: 'Giysi/Kıyafet',
    article: 'die',
    partOfSpeech: 'noun',
    emoji: '👗',
    synonyms: ['Klamotten', 'Bekleidung'],
    collocations: ['Kleidung kaufen', 'neue Kleidung tragen', 'warme Kleidung anziehen'],
    exampleSentence: 'Ich brauche neue Kleidung.',
    exampleTranslation: 'Yeni kıyafetlere ihtiyacım var.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-10',
    german: 'Größe',
    turkish: 'Beden',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Größen',
    emoji: '📏',
    collocations: ['welche Größe', 'die richtige Größe', 'eine Größe größer'],
    exampleSentence: 'Welche Größe haben Sie?',
    exampleTranslation: 'Bedeniniz ne?',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-11',
    german: 'Kasse',
    turkish: 'Kasa',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Kassen',
    emoji: '🧾',
    collocations: ['an der Kasse bezahlen', 'zur Kasse gehen', 'die Kasse ist geschlossen'],
    exampleSentence: 'Bitte gehen Sie zur Kasse.',
    exampleTranslation: 'Lütfen kasaya gidin.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-12',
    german: 'Angebot',
    turkish: 'İndirim/Teklif',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Angebote',
    emoji: '🔖',
    synonyms: ['Sonderangebot', 'Aktion'],
    collocations: ['ein Angebot machen', 'im Angebot sein', 'ein gutes Angebot'],
    exampleSentence: 'Das Angebot ist sehr gut.',
    exampleTranslation: 'İndirim çok iyi.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-13',
    german: 'Schuhe',
    turkish: 'Ayakkabılar',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    emoji: '👟',
    collocations: ['Schuhe anprobieren', 'neue Schuhe kaufen', 'bequeme Schuhe tragen'],
    exampleSentence: 'Die Schuhe sind schön.',
    exampleTranslation: 'Ayakkabılar güzel.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-14',
    german: 'Tasche',
    turkish: 'Çanta',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Taschen',
    emoji: '👜',
    synonyms: ['Beutel', 'Tüte'],
    collocations: ['eine Tasche tragen', 'die Tasche packen', 'eine Tasche kaufen'],
    exampleSentence: 'Die Tasche kostet 50 Euro.',
    exampleTranslation: 'Çanta 50 Euro.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-15',
    german: 'Euro',
    turkish: 'Euro',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Euro',
    emoji: '💶',
    collocations: ['fünf Euro kosten', 'in Euro bezahlen', 'Euro wechseln'],
    exampleSentence: 'Das kostet fünf Euro.',
    exampleTranslation: 'Bu beş Euro tutuyor.',
    category: 'shopping',
    level: 'A2',
  },
  {
    id: 'shopping-16',
    german: 'Rechnung',
    turkish: 'Fatura/Hesap',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Rechnungen',
    emoji: '🧾',
    synonyms: ['Faktura', 'Zahlungsaufforderung'],
    collocations: ['die Rechnung bezahlen', 'eine Rechnung ausstellen', 'die Rechnung prüfen'],
    exampleSentence: 'Könnten Sie mir bitte die Rechnung per E-Mail zuschicken, damit ich sie für die Steuererklärung verwenden kann?',
    exampleTranslation: 'Vergi beyannamesi için kullanabilmem için faturayı bana e-posta ile gönderebilir misiniz?',
    category: 'shopping',
    level: 'B2',
  },
  {
    id: 'shopping-17',
    german: 'Umtausch',
    turkish: 'Değişim/Ürün değişimi',
    article: 'der',
    partOfSpeech: 'noun',
    emoji: '🔄',
    synonyms: ['Austausch', 'Tausch'],
    antonyms: ['Kauf'],
    collocations: ['einen Umtausch vornehmen', 'Umtausch ausgeschlossen', 'das Recht auf Umtausch'],
    exampleSentence: 'Der Umtausch ist innerhalb von 14 Tagen möglich, sofern die Ware unbenutzt ist.',
    exampleTranslation: 'Ürün kullanılmamış olduğu sürece 14 gün içinde değişim yapılabilir.',
    category: 'shopping',
    level: 'B2',
  },
  {
    id: 'shopping-18',
    german: 'Garantie',
    turkish: 'Garanti',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Garantien',
    emoji: '🛡️',
    synonyms: ['Gewährleistung', 'Zusicherung'],
    collocations: ['unter Garantie stehen', 'die Garantie erlischt', 'eine Garantie geben'],
    exampleSentence: 'Die Garantie für dieses Gerät beträgt zwei Jahre ab dem Kaufdatum.',
    exampleTranslation: 'Bu cihazın garantisi satın alma tarihinden itibaren iki yıldır.',
    category: 'shopping',
    level: 'B2',
  },
  {
    id: 'shopping-19',
    german: 'Quittung',
    turkish: 'Makbuz/Fiş',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Quittungen',
    emoji: '🧾',
    synonyms: ['Beleg', 'Kassenbon'],
    collocations: ['eine Quittung ausstellen', 'die Quittung aufbewahren', 'eine Quittung verlangen'],
    exampleSentence: 'Bitte bewahren Sie die Quittung auf, falls Sie die Ware umtauschen möchten.',
    exampleTranslation: 'Ürünü değiştirmek isterseniz lütfen makbuzu saklayın.',
    category: 'shopping',
    level: 'B2',
  },
  {
    id: 'shopping-20',
    german: 'Rabatt',
    turkish: 'İndirim/İskonto',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Rabatte',
    emoji: '💸',
    synonyms: ['Nachlass', 'Ermäßigung', 'Preisnachlass'],
    collocations: ['einen Rabatt gewähren', 'Rabatt bekommen', 'einen Rabatt von 20 Prozent'],
    exampleSentence: 'Bei einem Einkauf über 100 Euro erhalten Sie automatisch einen Rabatt von zehn Prozent.',
    exampleTranslation: '100 Euro üzeri alışverişlerde otomatik olarak yüzde on indirim alırsınız.',
    category: 'shopping',
    level: 'B2',
  },
  {
    id: 'shopping-21',
    german: 'Lieferung',
    turkish: 'Teslimat',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Lieferungen',
    emoji: '📦',
    synonyms: ['Zustellung', 'Versand'],
    collocations: ['eine Lieferung erhalten', 'die Lieferung verzögert sich', 'kostenlose Lieferung'],
    exampleSentence: 'Die Lieferung erfolgt in der Regel innerhalb von drei bis fünf Werktagen.',
    exampleTranslation: 'Teslimat genellikle üç ila beş iş günü içinde gerçekleşir.',
    category: 'shopping',
    level: 'B2',
  },
  {
    id: 'shopping-22',
    german: 'Bestellung',
    turkish: 'Sipariş',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Bestellungen',
    emoji: '📝',
    synonyms: ['Auftrag', 'Order'],
    collocations: ['eine Bestellung aufgeben', 'die Bestellung stornieren', 'die Bestellung verfolgen'],
    exampleSentence: 'Sie können den Status Ihrer Bestellung jederzeit online überprüfen.',
    exampleTranslation: 'Siparişinizin durumunu istediğiniz zaman çevrimiçi olarak kontrol edebilirsiniz.',
    category: 'shopping',
    level: 'B2',
  },
  {
    id: 'shopping-23',
    german: 'Reklamation',
    turkish: 'Şikayet/İtiraz',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Reklamationen',
    emoji: '📢',
    synonyms: ['Beschwerde', 'Beanstandung'],
    collocations: ['eine Reklamation einreichen', 'die Reklamation bearbeiten', 'Grund zur Reklamation'],
    exampleSentence: 'Aufgrund des beschädigten Produkts hat der Kunde eine Reklamation eingereicht.',
    exampleTranslation: 'Hasarlı ürün nedeniyle müşteri bir şikayet başvurusu yaptı.',
    category: 'shopping',
    level: 'B2',
  },
  {
    id: 'shopping-24',
    german: 'Verpackung',
    turkish: 'Ambalaj/Paketleme',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Verpackungen',
    emoji: '📦',
    synonyms: ['Umverpackung', 'Hülle'],
    collocations: ['die Verpackung öffnen', 'umweltfreundliche Verpackung', 'in der Originalverpackung'],
    exampleSentence: 'Immer mehr Unternehmen setzen auf umweltfreundliche Verpackungen aus recyceltem Material.',
    exampleTranslation: 'Giderek daha fazla şirket geri dönüştürülmüş malzemeden çevre dostu ambalajlar kullanıyor.',
    category: 'shopping',
    level: 'B2',
  },
  {
    id: 'shopping-25',
    german: 'Mehrwertsteuer',
    turkish: 'Katma değer vergisi (KDV)',
    article: 'die',
    partOfSpeech: 'noun',
    emoji: '🏛️',
    synonyms: ['MwSt.', 'Umsatzsteuer'],
    collocations: ['inklusive Mehrwertsteuer', 'die Mehrwertsteuer ausweisen', 'die Mehrwertsteuer berechnen'],
    exampleSentence: 'Alle angegebenen Preise verstehen sich inklusive der gesetzlichen Mehrwertsteuer.',
    exampleTranslation: 'Belirtilen tüm fiyatlar yasal katma değer vergisi dahildir.',
    category: 'shopping',
    level: 'B2',
  },
];
