import { VocabularyWord } from '@/lib/types';

export const technologyWords: VocabularyWord[] = [
  {
    id: 'technology-1',
    german: 'der Computer',
    turkish: 'Bilgisayar',
    english: 'Computer',
    article: 'der',
    plural: 'Computer',
    partOfSpeech: 'noun',
    synonyms: ['Rechner', 'PC'],
    collocations: ['am Computer arbeiten', 'den Computer einschalten'],
    emoji: '💻',
    exampleSentence: 'Ich arbeite den ganzen Tag am Computer.',
    exampleTranslation: 'Bütün gün bilgisayarda çalışıyorum.',
    exampleTranslationEn: 'I work on the computer all day.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-2',
    german: 'das Handy',
    turkish: 'Cep telefonu',
    english: 'Mobile phone',
    article: 'das',
    plural: 'Handys',
    partOfSpeech: 'noun',
    synonyms: ['Smartphone', 'Mobiltelefon'],
    collocations: ['das Handy laden', 'auf dem Handy spielen'],
    emoji: '📱',
    exampleSentence: 'Wo ist mein Handy?',
    exampleTranslation: 'Cep telefonum nerede?',
    exampleTranslationEn: 'Where is my mobile phone?',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-3',
    german: 'das Internet',
    turkish: 'İnternet',
    english: 'Internet',
    article: 'das',
    partOfSpeech: 'noun',
    synonyms: ['Netz', 'Web'],
    collocations: ['im Internet surfen', 'im Internet suchen'],
    emoji: '🌐',
    exampleSentence: 'Hast du Zugang zum Internet?',
    exampleTranslation: 'İnternete erişimin var mı?',
    exampleTranslationEn: 'Do you have access to the internet?',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-4',
    german: 'die E-Mail',
    turkish: 'E-posta',
    english: 'Email',
    article: 'die',
    plural: 'E-Mails',
    partOfSpeech: 'noun',
    synonyms: ['Mail', 'elektronische Post'],
    collocations: ['eine E-Mail schreiben', 'eine E-Mail senden'],
    emoji: '📧',
    exampleSentence: 'Ich habe dir eine E-Mail geschickt.',
    exampleTranslation: 'Sana bir e-posta gönderdim.',
    exampleTranslationEn: 'I sent you an email.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-5',
    german: 'das Foto',
    turkish: 'Fotoğraf',
    english: 'Photo',
    article: 'das',
    plural: 'Fotos',
    partOfSpeech: 'noun',
    synonyms: ['Bild', 'Aufnahme'],
    collocations: ['ein Foto machen', 'ein Foto schießen'],
    emoji: '📷',
    exampleSentence: 'Kann ich ein Foto machen?',
    exampleTranslation: 'Bir fotoğraf çekebilir miyim?',
    exampleTranslationEn: 'Can I take a photo?',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-6',
    german: 'das Passwort',
    turkish: 'Şifre',
    english: 'Password',
    article: 'das',
    plural: 'Passwörter',
    partOfSpeech: 'noun',
    synonyms: ['Kennwort', 'Code'],
    collocations: ['das Passwort eingeben', 'das Passwort ändern'],
    emoji: '🔑',
    exampleSentence: 'Ich habe mein Passwort vergessen.',
    exampleTranslation: 'Şifremi unuttum.',
    exampleTranslationEn: 'I forgot my password.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-7',
    german: 'herunterladen',
    turkish: 'İndirmek',
    english: 'To download',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['downloaden', 'runterladen'],
    collocations: ['eine App herunterladen', 'eine Datei herunterladen'],
    emoji: '⬇️',
    exampleSentence: 'Ich muss die App herunterladen.',
    exampleTranslation: 'Uygulamayı indirmem gerekiyor.',
    exampleTranslationEn: 'I need to download the app.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-8',
    german: 'der Bildschirm',
    turkish: 'Ekran',
    english: 'Screen',
    article: 'der',
    plural: 'Bildschirme',
    partOfSpeech: 'noun',
    synonyms: ['Monitor', 'Display'],
    collocations: ['auf den Bildschirm schauen', 'der große Bildschirm'],
    emoji: '🖥️',
    exampleSentence: 'Der Bildschirm ist zu hell.',
    exampleTranslation: 'Ekran çok parlak.',
    exampleTranslationEn: 'The screen is too bright.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-9',
    german: 'die Tastatur',
    turkish: 'Klavye',
    english: 'Keyboard',
    article: 'die',
    plural: 'Tastaturen',
    partOfSpeech: 'noun',
    synonyms: ['Keyboard'],
    collocations: ['auf der Tastatur tippen', 'die Tastatur reinigen'],
    emoji: '⌨️',
    exampleSentence: 'Die Tastatur funktioniert nicht richtig.',
    exampleTranslation: 'Klavye düzgün çalışmıyor.',
    exampleTranslationEn: 'The keyboard is not working properly.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-10',
    german: 'die Webseite',
    turkish: 'Web sitesi',
    english: 'Website',
    article: 'die',
    plural: 'Webseiten',
    partOfSpeech: 'noun',
    synonyms: ['Internetseite', 'Homepage'],
    collocations: ['eine Webseite besuchen', 'eine Webseite erstellen'],
    emoji: '🌐',
    exampleSentence: 'Besuchen Sie unsere Webseite für mehr Informationen.',
    exampleTranslation: 'Daha fazla bilgi için web sitemizi ziyaret edin.',
    exampleTranslationEn: 'Visit our website for more information.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-11',
    german: 'die Datenbank',
    turkish: 'Veritabanı',
    english: 'Database',
    article: 'die',
    plural: 'Datenbanken',
    partOfSpeech: 'noun',
    synonyms: ['Datenspeicher'],
    collocations: ['eine Datenbank erstellen', 'in der Datenbank suchen'],
    emoji: '🗄️',
    exampleSentence: 'Alle Kundeninformationen sind in der Datenbank gespeichert.',
    exampleTranslation: 'Tüm müşteri bilgileri veritabanında kayıtlı.',
    exampleTranslationEn: 'All customer information is stored in the database.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-12',
    german: 'die Anwendung',
    turkish: 'Uygulama',
    english: 'Application',
    article: 'die',
    plural: 'Anwendungen',
    partOfSpeech: 'noun',
    synonyms: ['App', 'Programm', 'Software'],
    collocations: ['eine Anwendung installieren', 'eine mobile Anwendung'],
    emoji: '📲',
    exampleSentence: 'Diese Anwendung erleichtert die tägliche Arbeit.',
    exampleTranslation: 'Bu uygulama günlük işleri kolaylaştırıyor.',
    exampleTranslationEn: 'This application makes daily work easier.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-13',
    german: 'die Datensicherheit',
    turkish: 'Veri güvenliği',
    english: 'Data security',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Datenschutz', 'IT-Sicherheit'],
    collocations: ['die Datensicherheit gewährleisten', 'Datensicherheit im Internet'],
    emoji: '🔒',
    exampleSentence: 'Datensicherheit ist im digitalen Zeitalter besonders wichtig.',
    exampleTranslation: 'Veri güvenliği dijital çağda özellikle önemli.',
    exampleTranslationEn: 'Data security is especially important in the digital age.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-14',
    german: 'die Künstliche Intelligenz',
    turkish: 'Yapay zeka',
    english: 'Artificial Intelligence',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['KI', 'AI'],
    collocations: ['Künstliche Intelligenz einsetzen', 'Fortschritte in der KI'],
    emoji: '🤖',
    exampleSentence: 'Künstliche Intelligenz verändert unsere Arbeitswelt.',
    exampleTranslation: 'Yapay zeka iş dünyamızı değiştiriyor.',
    exampleTranslationEn: 'Artificial intelligence is changing our working world.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-15',
    german: 'die Digitalisierung',
    turkish: 'Dijitalleşme',
    english: 'Digitalization',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['digitale Transformation'],
    collocations: ['die Digitalisierung vorantreiben', 'Chancen der Digitalisierung'],
    emoji: '💡',
    exampleSentence: 'Die Digitalisierung betrifft alle Lebensbereiche.',
    exampleTranslation: 'Dijitalleşme hayatın her alanını etkiliyor.',
    exampleTranslationEn: 'Digitalization affects all areas of life.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-16',
    german: 'die Verschlüsselung',
    turkish: 'Şifreleme',
    english: 'Encryption',
    article: 'die',
    plural: 'Verschlüsselungen',
    partOfSpeech: 'noun',
    synonyms: ['Kodierung', 'Chiffrierung'],
    collocations: ['Ende-zu-Ende-Verschlüsselung', 'Daten verschlüsseln'],
    emoji: '🔐',
    exampleSentence: 'Eine starke Verschlüsselung schützt unsere Daten.',
    exampleTranslation: 'Güçlü bir şifreleme verilerimizi korur.',
    exampleTranslationEn: 'Strong encryption protects our data.',
    category: 'technology',
    level: 'B2',
  },
];
