import { VocabularyWord } from '@/lib/types';

export const technologyWords: VocabularyWord[] = [
  {
    id: 'technology-1',
    german: 'der Computer',
    turkish: 'Bilgisayar',
    english: 'Computer',
    article: 'der',
    plural: 'Computer',
    partOfSpeech: 'noun',
    synonyms: ['Rechner', 'PC'],
    collocations: ['am Computer arbeiten', 'den Computer einschalten'],
    emoji: '💻',
    exampleSentence: 'Ich arbeite den ganzen Tag am Computer.',
    exampleTranslation: 'Bütün gün bilgisayarda çalışıyorum.',
    exampleTranslationEn: 'I work on the computer all day.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-2',
    german: 'das Handy',
    turkish: 'Cep telefonu',
    english: 'Mobile phone',
    article: 'das',
    plural: 'Handys',
    partOfSpeech: 'noun',
    synonyms: ['Smartphone', 'Mobiltelefon'],
    collocations: ['das Handy laden', 'auf dem Handy spielen'],
    emoji: '📱',
    exampleSentence: 'Wo ist mein Handy?',
    exampleTranslation: 'Cep telefonum nerede?',
    exampleTranslationEn: 'Where is my mobile phone?',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-3',
    german: 'das Internet',
    turkish: 'İnternet',
    english: 'Internet',
    article: 'das',
    partOfSpeech: 'noun',
    synonyms: ['Netz', 'Web'],
    collocations: ['im Internet surfen', 'im Internet suchen'],
    emoji: '🌐',
    exampleSentence: 'Hast du Zugang zum Internet?',
    exampleTranslation: 'İnternete erişimin var mı?',
    exampleTranslationEn: 'Do you have access to the internet?',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-4',
    german: 'die E-Mail',
    turkish: 'E-posta',
    english: 'Email',
    article: 'die',
    plural: 'E-Mails',
    partOfSpeech: 'noun',
    synonyms: ['Mail', 'elektronische Post'],
    collocations: ['eine E-Mail schreiben', 'eine E-Mail senden'],
    emoji: '📧',
    exampleSentence: 'Ich habe dir eine E-Mail geschickt.',
    exampleTranslation: 'Sana bir e-posta gönderdim.',
    exampleTranslationEn: 'I sent you an email.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-5',
    german: 'das Foto',
    turkish: 'Fotoğraf',
    english: 'Photo',
    article: 'das',
    plural: 'Fotos',
    partOfSpeech: 'noun',
    synonyms: ['Bild', 'Aufnahme'],
    collocations: ['ein Foto machen', 'ein Foto schießen'],
    emoji: '📷',
    exampleSentence: 'Kann ich ein Foto machen?',
    exampleTranslation: 'Bir fotoğraf çekebilir miyim?',
    exampleTranslationEn: 'Can I take a photo?',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-6',
    german: 'das Passwort',
    turkish: 'Şifre',
    english: 'Password',
    article: 'das',
    plural: 'Passwörter',
    partOfSpeech: 'noun',
    synonyms: ['Kennwort', 'Code'],
    collocations: ['das Passwort eingeben', 'das Passwort ändern'],
    emoji: '🔑',
    exampleSentence: 'Ich habe mein Passwort vergessen.',
    exampleTranslation: 'Şifremi unuttum.',
    exampleTranslationEn: 'I forgot my password.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-7',
    german: 'herunterladen',
    turkish: 'İndirmek',
    english: 'To download',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['downloaden', 'runterladen'],
    collocations: ['eine App herunterladen', 'eine Datei herunterladen'],
    emoji: '⬇️',
    exampleSentence: 'Ich muss die App herunterladen.',
    exampleTranslation: 'Uygulamayı indirmem gerekiyor.',
    exampleTranslationEn: 'I need to download the app.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-8',
    german: 'der Bildschirm',
    turkish: 'Ekran',
    english: 'Screen',
    article: 'der',
    plural: 'Bildschirme',
    partOfSpeech: 'noun',
    synonyms: ['Monitor', 'Display'],
    collocations: ['auf den Bildschirm schauen', 'der große Bildschirm'],
    emoji: '🖥️',
    exampleSentence: 'Der Bildschirm ist zu hell.',
    exampleTranslation: 'Ekran çok parlak.',
    exampleTranslationEn: 'The screen is too bright.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-9',
    german: 'die Tastatur',
    turkish: 'Klavye',
    english: 'Keyboard',
    article: 'die',
    plural: 'Tastaturen',
    partOfSpeech: 'noun',
    synonyms: ['Keyboard'],
    collocations: ['auf der Tastatur tippen', 'die Tastatur reinigen'],
    emoji: '⌨️',
    exampleSentence: 'Die Tastatur funktioniert nicht richtig.',
    exampleTranslation: 'Klavye düzgün çalışmıyor.',
    exampleTranslationEn: 'The keyboard is not working properly.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-10',
    german: 'die Webseite',
    turkish: 'Web sitesi',
    english: 'Website',
    article: 'die',
    plural: 'Webseiten',
    partOfSpeech: 'noun',
    synonyms: ['Internetseite', 'Homepage'],
    collocations: ['eine Webseite besuchen', 'eine Webseite erstellen'],
    emoji: '🌐',
    exampleSentence: 'Besuchen Sie unsere Webseite für mehr Informationen.',
    exampleTranslation: 'Daha fazla bilgi için web sitemizi ziyaret edin.',
    exampleTranslationEn: 'Visit our website for more information.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-11',
    german: 'die Datenbank',
    turkish: 'Veritabanı',
    english: 'Database',
    article: 'die',
    plural: 'Datenbanken',
    partOfSpeech: 'noun',
    synonyms: ['Datenspeicher'],
    collocations: ['eine Datenbank erstellen', 'in der Datenbank suchen'],
    emoji: '🗄️',
    exampleSentence: 'Alle Kundeninformationen sind in der Datenbank gespeichert.',
    exampleTranslation: 'Tüm müşteri bilgileri veritabanında kayıtlı.',
    exampleTranslationEn: 'All customer information is stored in the database.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-12',
    german: 'die Anwendung',
    turkish: 'Uygulama',
    english: 'Application',
    article: 'die',
    plural: 'Anwendungen',
    partOfSpeech: 'noun',
    synonyms: ['App', 'Programm', 'Software'],
    collocations: ['eine Anwendung installieren', 'eine mobile Anwendung'],
    emoji: '📲',
    exampleSentence: 'Diese Anwendung erleichtert die tägliche Arbeit.',
    exampleTranslation: 'Bu uygulama günlük işleri kolaylaştırıyor.',
    exampleTranslationEn: 'This application makes daily work easier.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-13',
    german: 'die Datensicherheit',
    turkish: 'Veri güvenliği',
    english: 'Data security',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Datenschutz', 'IT-Sicherheit'],
    collocations: ['die Datensicherheit gewährleisten', 'Datensicherheit im Internet'],
    emoji: '🔒',
    exampleSentence: 'Datensicherheit ist im digitalen Zeitalter besonders wichtig.',
    exampleTranslation: 'Veri güvenliği dijital çağda özellikle önemli.',
    exampleTranslationEn: 'Data security is especially important in the digital age.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-14',
    german: 'die Künstliche Intelligenz',
    turkish: 'Yapay zeka',
    english: 'Artificial Intelligence',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['KI', 'AI'],
    collocations: ['Künstliche Intelligenz einsetzen', 'Fortschritte in der KI'],
    emoji: '🤖',
    exampleSentence: 'Künstliche Intelligenz verändert unsere Arbeitswelt.',
    exampleTranslation: 'Yapay zeka iş dünyamızı değiştiriyor.',
    exampleTranslationEn: 'Artificial intelligence is changing our working world.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-15',
    german: 'die Digitalisierung',
    turkish: 'Dijitalleşme',
    english: 'Digitalization',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['digitale Transformation'],
    collocations: ['die Digitalisierung vorantreiben', 'Chancen der Digitalisierung'],
    emoji: '💡',
    exampleSentence: 'Die Digitalisierung betrifft alle Lebensbereiche.',
    exampleTranslation: 'Dijitalleşme hayatın her alanını etkiliyor.',
    exampleTranslationEn: 'Digitalization affects all areas of life.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-16',
    german: 'die Verschlüsselung',
    turkish: 'Şifreleme',
    english: 'Encryption',
    article: 'die',
    plural: 'Verschlüsselungen',
    partOfSpeech: 'noun',
    synonyms: ['Kodierung', 'Chiffrierung'],
    collocations: ['Ende-zu-Ende-Verschlüsselung', 'Daten verschlüsseln'],
    emoji: '🔐',
    exampleSentence: 'Eine starke Verschlüsselung schützt unsere Daten.',
    exampleTranslation: 'Güçlü bir şifreleme verilerimizi korur.',
    exampleTranslationEn: 'Strong encryption protects our data.',
    category: 'technology',
    level: 'B2',
  },
  // === NEW WORDS START HERE ===
  // A1 words (technology-17 to technology-36)
  {
    id: 'technology-17',
    german: 'das Telefon',
    turkish: 'Telefon',
    english: 'Telephone',
    article: 'das',
    plural: 'Telefone',
    partOfSpeech: 'noun',
    synonyms: ['Fernsprechapparat'],
    collocations: ['das Telefon klingelt', 'ans Telefon gehen'],
    emoji: '📞',
    exampleSentence: 'Das Telefon klingelt.',
    exampleTranslation: 'Telefon çalıyor.',
    exampleTranslationEn: 'The telephone is ringing.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-18',
    german: 'das Fernsehen',
    turkish: 'Televizyon',
    english: 'Television',
    article: 'das',
    partOfSpeech: 'noun',
    synonyms: ['TV'],
    collocations: ['fernsehen', 'im Fernsehen kommen'],
    emoji: '📺',
    exampleSentence: 'Abends sehe ich gern fern.',
    exampleTranslation: 'Akşamları televizyon izlemeyi seviyorum.',
    exampleTranslationEn: 'I like to watch television in the evening.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-19',
    german: 'das Radio',
    turkish: 'Radyo',
    english: 'Radio',
    article: 'das',
    plural: 'Radios',
    partOfSpeech: 'noun',
    synonyms: ['Rundfunk'],
    collocations: ['Radio hören', 'im Radio laufen'],
    emoji: '📻',
    exampleSentence: 'Ich höre morgens immer Radio.',
    exampleTranslation: 'Sabahları hep radyo dinlerim.',
    exampleTranslationEn: 'I always listen to the radio in the morning.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-20',
    german: 'die Kamera',
    turkish: 'Kamera',
    english: 'Camera',
    article: 'die',
    plural: 'Kameras',
    partOfSpeech: 'noun',
    synonyms: ['Fotoapparat'],
    collocations: ['die Kamera einschalten', 'mit der Kamera fotografieren'],
    emoji: '📸',
    exampleSentence: 'Ich habe eine neue Kamera gekauft.',
    exampleTranslation: 'Yeni bir kamera aldım.',
    exampleTranslationEn: 'I bought a new camera.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-21',
    german: 'anrufen',
    turkish: 'Aramak (telefon)',
    english: 'To call',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['telefonieren', 'anklingeln'],
    collocations: ['jemanden anrufen', 'später anrufen'],
    emoji: '📞',
    exampleSentence: 'Ich rufe dich morgen an.',
    exampleTranslation: 'Seni yarın ararım.',
    exampleTranslationEn: 'I will call you tomorrow.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-22',
    german: 'die Nummer',
    turkish: 'Numara',
    english: 'Number',
    article: 'die',
    plural: 'Nummern',
    partOfSpeech: 'noun',
    synonyms: ['Telefonnummer'],
    collocations: ['die Nummer wählen', 'eine Nummer eingeben'],
    emoji: '🔢',
    exampleSentence: 'Was ist deine Telefonnummer?',
    exampleTranslation: 'Telefon numaran ne?',
    exampleTranslationEn: 'What is your phone number?',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-23',
    german: 'die Nachricht',
    turkish: 'Mesaj',
    english: 'Message',
    article: 'die',
    plural: 'Nachrichten',
    partOfSpeech: 'noun',
    synonyms: ['Mitteilung', 'SMS'],
    collocations: ['eine Nachricht schreiben', 'eine Nachricht bekommen'],
    emoji: '💬',
    exampleSentence: 'Ich habe eine Nachricht von Maria bekommen.',
    exampleTranslation: "Maria'dan bir mesaj aldım.",
    exampleTranslationEn: 'I got a message from Maria.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-24',
    german: 'das Video',
    turkish: 'Video',
    english: 'Video',
    article: 'das',
    plural: 'Videos',
    partOfSpeech: 'noun',
    synonyms: ['Film', 'Clip'],
    collocations: ['ein Video ansehen', 'ein Video drehen'],
    emoji: '🎬',
    exampleSentence: 'Ich schaue gern Videos im Internet.',
    exampleTranslation: 'İnternette video izlemeyi seviyorum.',
    exampleTranslationEn: 'I like watching videos on the internet.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-25',
    german: 'die Musik',
    turkish: 'Müzik',
    english: 'Music',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: [],
    collocations: ['Musik hören', 'Musik herunterladen'],
    emoji: '🎵',
    exampleSentence: 'Ich höre Musik auf meinem Handy.',
    exampleTranslation: 'Telefonumda müzik dinliyorum.',
    exampleTranslationEn: 'I listen to music on my phone.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-26',
    german: 'das Spiel',
    turkish: 'Oyun',
    english: 'Game',
    article: 'das',
    plural: 'Spiele',
    partOfSpeech: 'noun',
    synonyms: ['Computerspiel', 'Game'],
    collocations: ['ein Spiel spielen', 'ein Spiel herunterladen'],
    emoji: '🎮',
    exampleSentence: 'Dieses Spiel ist sehr beliebt.',
    exampleTranslation: 'Bu oyun çok popüler.',
    exampleTranslationEn: 'This game is very popular.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-27',
    german: 'schreiben',
    turkish: 'Yazmak',
    english: 'To write',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['tippen', 'verfassen'],
    collocations: ['eine Nachricht schreiben', 'eine E-Mail schreiben'],
    emoji: '✍️',
    exampleSentence: 'Ich schreibe eine E-Mail an meinen Chef.',
    exampleTranslation: 'Patronuma bir e-posta yazıyorum.',
    exampleTranslationEn: 'I am writing an email to my boss.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-28',
    german: 'suchen',
    turkish: 'Aramak',
    english: 'To search',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['googeln', 'nachschlagen'],
    collocations: ['im Internet suchen', 'etwas suchen'],
    emoji: '🔍',
    exampleSentence: 'Ich suche die Adresse im Internet.',
    exampleTranslation: 'Adresi internette arıyorum.',
    exampleTranslationEn: 'I am searching for the address on the internet.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-29',
    german: 'der Fernseher',
    turkish: 'Televizyon (cihaz)',
    english: 'TV set',
    article: 'der',
    plural: 'Fernseher',
    partOfSpeech: 'noun',
    synonyms: ['TV-Gerät', 'Fernsehgerät'],
    collocations: ['den Fernseher einschalten', 'vor dem Fernseher sitzen'],
    emoji: '📺',
    exampleSentence: 'Der Fernseher ist kaputt.',
    exampleTranslation: 'Televizyon bozuk.',
    exampleTranslationEn: 'The TV is broken.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-30',
    german: 'schicken',
    turkish: 'Göndermek',
    english: 'To send',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['senden', 'verschicken'],
    collocations: ['eine Nachricht schicken', 'ein Foto schicken'],
    emoji: '📤',
    exampleSentence: 'Kannst du mir das Foto schicken?',
    exampleTranslation: 'Bana fotoğrafı gönderebilir misin?',
    exampleTranslationEn: 'Can you send me the photo?',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-31',
    german: 'die Lampe',
    turkish: 'Lamba',
    english: 'Lamp',
    article: 'die',
    plural: 'Lampen',
    partOfSpeech: 'noun',
    synonyms: ['Leuchte', 'Licht'],
    collocations: ['die Lampe einschalten', 'die Lampe ausschalten'],
    emoji: '💡',
    exampleSentence: 'Mach bitte die Lampe an.',
    exampleTranslation: 'Lütfen lambayı aç.',
    exampleTranslationEn: 'Please turn on the lamp.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-32',
    german: 'die Uhr',
    turkish: 'Saat',
    english: 'Clock / Watch',
    article: 'die',
    plural: 'Uhren',
    partOfSpeech: 'noun',
    synonyms: ['Armbanduhr', 'Smartwatch'],
    collocations: ['die Uhr stellen', 'auf die Uhr schauen'],
    emoji: '⌚',
    exampleSentence: 'Meine Uhr zeigt die falsche Zeit.',
    exampleTranslation: 'Saatim yanlış zamanı gösteriyor.',
    exampleTranslationEn: 'My watch shows the wrong time.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-33',
    german: 'laut',
    turkish: 'Yüksek sesli',
    english: 'Loud',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['geräuschvoll'],
    collocations: ['laut stellen', 'zu laut sein'],
    emoji: '🔊',
    exampleSentence: 'Die Musik ist zu laut.',
    exampleTranslation: 'Müzik çok yüksek.',
    exampleTranslationEn: 'The music is too loud.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-34',
    german: 'leise',
    turkish: 'Sessiz / Kısık',
    english: 'Quiet',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['ruhig', 'still'],
    collocations: ['leise stellen', 'leise sprechen'],
    emoji: '🔈',
    exampleSentence: 'Bitte mach das Radio leiser.',
    exampleTranslation: 'Lütfen radyoyu kıs.',
    exampleTranslationEn: 'Please turn the radio down.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-35',
    german: 'kaputt',
    turkish: 'Bozuk',
    english: 'Broken',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['defekt', 'beschädigt'],
    collocations: ['kaputt gehen', 'kaputt machen'],
    emoji: '💔',
    exampleSentence: 'Mein Handy ist kaputt.',
    exampleTranslation: 'Telefonum bozuk.',
    exampleTranslationEn: 'My phone is broken.',
    category: 'technology',
    level: 'A1',
  },
  {
    id: 'technology-36',
    german: 'neu',
    turkish: 'Yeni',
    english: 'New',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['brandneu', 'aktuell'],
    collocations: ['ein neues Handy', 'ganz neu'],
    emoji: '✨',
    exampleSentence: 'Ich habe ein neues Handy.',
    exampleTranslation: 'Yeni bir telefonum var.',
    exampleTranslationEn: 'I have a new phone.',
    category: 'technology',
    level: 'A1',
  },
  // A2 words (technology-37 to technology-56)
  {
    id: 'technology-37',
    german: 'der Drucker',
    turkish: 'Yazıcı',
    english: 'Printer',
    article: 'der',
    plural: 'Drucker',
    partOfSpeech: 'noun',
    synonyms: ['Printer'],
    collocations: ['den Drucker anschließen', 'etwas ausdrucken'],
    emoji: '🖨️',
    exampleSentence: 'Der Drucker hat kein Papier mehr.',
    exampleTranslation: 'Yazıcıda kağıt kalmadı.',
    exampleTranslationEn: 'The printer is out of paper.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-38',
    german: 'die Maus',
    turkish: 'Fare (bilgisayar)',
    english: 'Mouse',
    article: 'die',
    plural: 'Mäuse',
    partOfSpeech: 'noun',
    synonyms: ['Computermaus'],
    collocations: ['mit der Maus klicken', 'die Maus bewegen'],
    emoji: '🖱️',
    exampleSentence: 'Klicken Sie mit der Maus auf den Button.',
    exampleTranslation: 'Fare ile butona tıklayın.',
    exampleTranslationEn: 'Click on the button with the mouse.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-39',
    german: 'das Kabel',
    turkish: 'Kablo',
    english: 'Cable',
    article: 'das',
    plural: 'Kabel',
    partOfSpeech: 'noun',
    synonyms: ['Leitung', 'Ladekabel'],
    collocations: ['das Kabel anschließen', 'ein USB-Kabel'],
    emoji: '🔌',
    exampleSentence: 'Wo ist das Ladekabel für mein Handy?',
    exampleTranslation: 'Telefonumun şarj kablosu nerede?',
    exampleTranslationEn: 'Where is the charging cable for my phone?',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-40',
    german: 'der Lautsprecher',
    turkish: 'Hoparlör',
    english: 'Speaker',
    article: 'der',
    plural: 'Lautsprecher',
    partOfSpeech: 'noun',
    synonyms: ['Box', 'Speaker'],
    collocations: ['den Lautsprecher einschalten', 'über Lautsprecher hören'],
    emoji: '🔊',
    exampleSentence: 'Der Lautsprecher ist sehr laut.',
    exampleTranslation: 'Hoparlör çok yüksek sesli.',
    exampleTranslationEn: 'The speaker is very loud.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-41',
    german: 'drucken',
    turkish: 'Yazdırmak',
    english: 'To print',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['ausdrucken'],
    collocations: ['ein Dokument drucken', 'in Farbe drucken'],
    emoji: '🖨️',
    exampleSentence: 'Kannst du das Dokument bitte drucken?',
    exampleTranslation: 'Belgeyi yazdırabilir misin lütfen?',
    exampleTranslationEn: 'Can you please print the document?',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-42',
    german: 'speichern',
    turkish: 'Kaydetmek',
    english: 'To save',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['abspeichern', 'sichern'],
    collocations: ['eine Datei speichern', 'Daten speichern'],
    emoji: '💾',
    exampleSentence: 'Vergiss nicht, die Datei zu speichern.',
    exampleTranslation: 'Dosyayı kaydetmeyi unutma.',
    exampleTranslationEn: 'Do not forget to save the file.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-43',
    german: 'löschen',
    turkish: 'Silmek',
    english: 'To delete',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['entfernen', 'beseitigen'],
    collocations: ['eine Datei löschen', 'eine Nachricht löschen'],
    emoji: '🗑️',
    exampleSentence: 'Ich habe die alte Datei gelöscht.',
    exampleTranslation: 'Eski dosyayı sildim.',
    exampleTranslationEn: 'I deleted the old file.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-44',
    german: 'klicken',
    turkish: 'Tıklamak',
    english: 'To click',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['anklicken', 'drücken'],
    collocations: ['auf einen Link klicken', 'doppelt klicken'],
    emoji: '🖱️',
    exampleSentence: 'Klicken Sie auf den Link.',
    exampleTranslation: 'Linke tıklayın.',
    exampleTranslationEn: 'Click on the link.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-45',
    german: 'das Programm',
    turkish: 'Program',
    english: 'Program',
    article: 'das',
    plural: 'Programme',
    partOfSpeech: 'noun',
    synonyms: ['Software', 'Anwendung'],
    collocations: ['ein Programm starten', 'ein Programm installieren'],
    emoji: '💿',
    exampleSentence: 'Welches Programm benutzt du dafür?',
    exampleTranslation: 'Bunun için hangi programı kullanıyorsun?',
    exampleTranslationEn: 'Which program do you use for that?',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-46',
    german: 'die Datei',
    turkish: 'Dosya',
    english: 'File',
    article: 'die',
    plural: 'Dateien',
    partOfSpeech: 'noun',
    synonyms: ['Dokument'],
    collocations: ['eine Datei öffnen', 'eine Datei anhängen'],
    emoji: '📄',
    exampleSentence: 'Die Datei ist zu groß für die E-Mail.',
    exampleTranslation: 'Dosya e-posta için çok büyük.',
    exampleTranslationEn: 'The file is too large for the email.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-47',
    german: 'das WLAN',
    turkish: 'Kablosuz internet',
    english: 'WiFi',
    article: 'das',
    partOfSpeech: 'noun',
    synonyms: ['WiFi', 'drahtloses Netzwerk'],
    collocations: ['sich mit dem WLAN verbinden', 'das WLAN-Passwort'],
    emoji: '📶',
    exampleSentence: 'Wie ist das WLAN-Passwort?',
    exampleTranslation: 'WiFi şifresi ne?',
    exampleTranslationEn: 'What is the WiFi password?',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-48',
    german: 'online',
    turkish: 'Çevrimiçi',
    english: 'Online',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['im Internet', 'im Netz'],
    collocations: ['online sein', 'online bestellen'],
    emoji: '🟢',
    exampleSentence: 'Du kannst das Ticket online kaufen.',
    exampleTranslation: 'Bileti çevrimiçi satın alabilirsin.',
    exampleTranslationEn: 'You can buy the ticket online.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-49',
    german: 'das Tablet',
    turkish: 'Tablet',
    english: 'Tablet',
    article: 'das',
    plural: 'Tablets',
    partOfSpeech: 'noun',
    synonyms: ['Tablet-Computer'],
    collocations: ['auf dem Tablet lesen', 'ein Tablet benutzen'],
    emoji: '📱',
    exampleSentence: 'Ich lese Bücher auf meinem Tablet.',
    exampleTranslation: 'Tabletimde kitap okuyorum.',
    exampleTranslationEn: 'I read books on my tablet.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-50',
    german: 'der Kopfhörer',
    turkish: 'Kulaklık',
    english: 'Headphones',
    article: 'der',
    plural: 'Kopfhörer',
    partOfSpeech: 'noun',
    synonyms: ['Ohrhörer', 'Headset'],
    collocations: ['Kopfhörer aufsetzen', 'kabellose Kopfhörer'],
    emoji: '🎧',
    exampleSentence: 'Ich brauche meine Kopfhörer für den Zug.',
    exampleTranslation: 'Tren için kulaklıklarıma ihtiyacım var.',
    exampleTranslationEn: 'I need my headphones for the train.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-51',
    german: 'anmachen',
    turkish: 'Açmak (cihaz)',
    english: 'To turn on',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['einschalten', 'aktivieren'],
    collocations: ['das Licht anmachen', 'den Computer anmachen'],
    emoji: '🔛',
    exampleSentence: 'Mach bitte den Computer an.',
    exampleTranslation: 'Lütfen bilgisayarı aç.',
    exampleTranslationEn: 'Please turn on the computer.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-52',
    german: 'ausmachen',
    turkish: 'Kapatmak (cihaz)',
    english: 'To turn off',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['ausschalten', 'abschalten'],
    collocations: ['den Fernseher ausmachen', 'das Handy ausmachen'],
    emoji: '📴',
    exampleSentence: 'Mach bitte den Fernseher aus.',
    exampleTranslation: 'Lütfen televizyonu kapat.',
    exampleTranslationEn: 'Please turn off the TV.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-53',
    german: 'laden',
    turkish: 'Şarj etmek',
    english: 'To charge',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['aufladen'],
    collocations: ['das Handy laden', 'den Akku laden'],
    emoji: '🔋',
    exampleSentence: 'Ich muss mein Handy laden.',
    exampleTranslation: 'Telefonumu şarj etmem gerekiyor.',
    exampleTranslationEn: 'I need to charge my phone.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-54',
    german: 'der Akku',
    turkish: 'Batarya',
    english: 'Battery',
    article: 'der',
    plural: 'Akkus',
    partOfSpeech: 'noun',
    synonyms: ['Batterie'],
    collocations: ['der Akku ist leer', 'den Akku laden'],
    emoji: '🔋',
    exampleSentence: 'Mein Akku ist fast leer.',
    exampleTranslation: 'Bataryam neredeyse bitti.',
    exampleTranslationEn: 'My battery is almost empty.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-55',
    german: 'die App',
    turkish: 'Uygulama',
    english: 'App',
    article: 'die',
    plural: 'Apps',
    partOfSpeech: 'noun',
    synonyms: ['Anwendung', 'Applikation'],
    collocations: ['eine App installieren', 'eine App öffnen'],
    emoji: '📱',
    exampleSentence: 'Diese App ist sehr nützlich.',
    exampleTranslation: 'Bu uygulama çok faydalı.',
    exampleTranslationEn: 'This app is very useful.',
    category: 'technology',
    level: 'A2',
  },
  {
    id: 'technology-56',
    german: 'der USB-Stick',
    turkish: 'USB bellek',
    english: 'USB stick',
    article: 'der',
    plural: 'USB-Sticks',
    partOfSpeech: 'noun',
    synonyms: ['Speicherstick', 'USB-Speicher'],
    collocations: ['auf dem USB-Stick speichern', 'den USB-Stick einstecken'],
    emoji: '💾',
    exampleSentence: 'Hast du einen USB-Stick dabei?',
    exampleTranslation: 'Yanında USB bellek var mı?',
    exampleTranslationEn: 'Do you have a USB stick with you?',
    category: 'technology',
    level: 'A2',
  },
  // B1 words (technology-57 to technology-78)
  {
    id: 'technology-57',
    german: 'die Suchmaschine',
    turkish: 'Arama motoru',
    english: 'Search engine',
    article: 'die',
    plural: 'Suchmaschinen',
    partOfSpeech: 'noun',
    synonyms: ['Internetsuchmaschine'],
    collocations: ['eine Suchmaschine benutzen', 'in der Suchmaschine eingeben'],
    emoji: '🔍',
    exampleSentence: 'Google ist die bekannteste Suchmaschine.',
    exampleTranslation: 'Google en bilinen arama motorudur.',
    exampleTranslationEn: 'Google is the most well-known search engine.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-58',
    german: 'das soziale Netzwerk',
    turkish: 'Sosyal ağ',
    english: 'Social network',
    article: 'das',
    plural: 'soziale Netzwerke',
    partOfSpeech: 'noun',
    synonyms: ['Social Media', 'soziale Medien'],
    collocations: ['in sozialen Netzwerken aktiv sein', 'ein Profil erstellen'],
    emoji: '👥',
    exampleSentence: 'Viele junge Menschen nutzen soziale Netzwerke täglich.',
    exampleTranslation: 'Birçok genç sosyal ağları günlük olarak kullanıyor.',
    exampleTranslationEn: 'Many young people use social networks daily.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-59',
    german: 'der Blog',
    turkish: 'Blog',
    english: 'Blog',
    article: 'der',
    plural: 'Blogs',
    partOfSpeech: 'noun',
    synonyms: ['Weblog', 'Onlinetagebuch'],
    collocations: ['einen Blog schreiben', 'einen Blog lesen'],
    emoji: '📝',
    exampleSentence: 'Sie schreibt einen Blog über Reisen.',
    exampleTranslation: 'Seyahat hakkında bir blog yazıyor.',
    exampleTranslationEn: 'She writes a blog about travel.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-60',
    german: 'der Virus',
    turkish: 'Virüs',
    english: 'Virus',
    article: 'der',
    plural: 'Viren',
    partOfSpeech: 'noun',
    synonyms: ['Computervirus', 'Schadsoftware'],
    collocations: ['einen Virus haben', 'vor Viren schützen'],
    emoji: '🦠',
    exampleSentence: 'Mein Computer hat einen Virus.',
    exampleTranslation: 'Bilgisayarıma virüs bulaştı.',
    exampleTranslationEn: 'My computer has a virus.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-61',
    german: 'installieren',
    turkish: 'Kurmak / Yüklemek',
    english: 'To install',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['einrichten', 'aufspielen'],
    collocations: ['eine Software installieren', 'ein Update installieren'],
    emoji: '⚙️',
    exampleSentence: 'Ich muss ein neues Programm installieren.',
    exampleTranslation: 'Yeni bir program kurmam gerekiyor.',
    exampleTranslationEn: 'I need to install a new program.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-62',
    german: 'aktualisieren',
    turkish: 'Güncellemek',
    english: 'To update',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['updaten', 'auf den neuesten Stand bringen'],
    collocations: ['die Software aktualisieren', 'das System aktualisieren'],
    emoji: '🔄',
    exampleSentence: 'Du solltest dein Betriebssystem regelmäßig aktualisieren.',
    exampleTranslation: 'İşletim sistemini düzenli olarak güncellemelisin.',
    exampleTranslationEn: 'You should update your operating system regularly.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-63',
    german: 'die Verbindung',
    turkish: 'Bağlantı',
    english: 'Connection',
    article: 'die',
    plural: 'Verbindungen',
    partOfSpeech: 'noun',
    synonyms: ['Anschluss', 'Anbindung'],
    collocations: ['die Internetverbindung', 'eine stabile Verbindung'],
    emoji: '🔗',
    exampleSentence: 'Die Internetverbindung ist heute sehr langsam.',
    exampleTranslation: 'İnternet bağlantısı bugün çok yavaş.',
    exampleTranslationEn: 'The internet connection is very slow today.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-64',
    german: 'hochladen',
    turkish: 'Yüklemek (internete)',
    english: 'To upload',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['uploaden'],
    collocations: ['ein Foto hochladen', 'eine Datei hochladen'],
    emoji: '⬆️',
    exampleSentence: 'Ich lade die Fotos auf die Webseite hoch.',
    exampleTranslation: 'Fotoğrafları web sitesine yüklüyorum.',
    exampleTranslationEn: 'I am uploading the photos to the website.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-65',
    german: 'der Speicher',
    turkish: 'Bellek / Depolama',
    english: 'Memory / Storage',
    article: 'der',
    plural: 'Speicher',
    partOfSpeech: 'noun',
    synonyms: ['Arbeitsspeicher', 'Festplatte'],
    collocations: ['der Speicher ist voll', 'mehr Speicher brauchen'],
    emoji: '💽',
    exampleSentence: 'Mein Handy hat nicht genug Speicher.',
    exampleTranslation: 'Telefonumda yeterli bellek yok.',
    exampleTranslationEn: 'My phone does not have enough storage.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-66',
    german: 'das Netzwerk',
    turkish: 'Ağ',
    english: 'Network',
    article: 'das',
    plural: 'Netzwerke',
    partOfSpeech: 'noun',
    synonyms: ['Netz'],
    collocations: ['ein Netzwerk einrichten', 'sich mit einem Netzwerk verbinden'],
    emoji: '🌐',
    exampleSentence: 'Das Netzwerk in unserem Büro ist sehr schnell.',
    exampleTranslation: 'Ofisimizdeki ağ çok hızlı.',
    exampleTranslationEn: 'The network in our office is very fast.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-67',
    german: 'der Onlineshop',
    turkish: 'İnternet mağazası',
    english: 'Online shop',
    article: 'der',
    plural: 'Onlineshops',
    partOfSpeech: 'noun',
    synonyms: ['Webshop', 'Internetshop'],
    collocations: ['im Onlineshop bestellen', 'einen Onlineshop betreiben'],
    emoji: '🛒',
    exampleSentence: 'Ich bestelle oft Kleidung im Onlineshop.',
    exampleTranslation: 'Sık sık internet mağazasından kıyafet sipariş ediyorum.',
    exampleTranslationEn: 'I often order clothes from online shops.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-68',
    german: 'die Festplatte',
    turkish: 'Sabit disk',
    english: 'Hard drive',
    article: 'die',
    plural: 'Festplatten',
    partOfSpeech: 'noun',
    synonyms: ['Harddisk', 'HDD', 'SSD'],
    collocations: ['die Festplatte formatieren', 'eine externe Festplatte'],
    emoji: '💿',
    exampleSentence: 'Die Festplatte meines Computers ist fast voll.',
    exampleTranslation: 'Bilgisayarımın sabit diski neredeyse dolu.',
    exampleTranslationEn: 'My computer hard drive is almost full.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-69',
    german: 'kabellos',
    turkish: 'Kablosuz',
    english: 'Wireless',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['drahtlos', 'wireless'],
    collocations: ['kabellose Kopfhörer', 'kabelloses Laden'],
    emoji: '📡',
    exampleSentence: 'Ich bevorzuge kabellose Kopfhörer.',
    exampleTranslation: 'Kablosuz kulaklıkları tercih ediyorum.',
    exampleTranslationEn: 'I prefer wireless headphones.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-70',
    german: 'der Bildschirmschoner',
    turkish: 'Ekran koruyucu',
    english: 'Screen saver',
    article: 'der',
    plural: 'Bildschirmschoner',
    partOfSpeech: 'noun',
    synonyms: ['Screensaver'],
    collocations: ['den Bildschirmschoner einstellen', 'ein schöner Bildschirmschoner'],
    emoji: '🖥️',
    exampleSentence: 'Mein Bildschirmschoner zeigt schöne Naturbilder.',
    exampleTranslation: 'Ekran koruyucum güzel doğa resimleri gösteriyor.',
    exampleTranslationEn: 'My screen saver shows beautiful nature pictures.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-71',
    german: 'die Cloud',
    turkish: 'Bulut (depolama)',
    english: 'Cloud',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Cloud-Speicher', 'Online-Speicher'],
    collocations: ['in der Cloud speichern', 'Cloud-Dienste nutzen'],
    emoji: '☁️',
    exampleSentence: 'Ich speichere meine Fotos in der Cloud.',
    exampleTranslation: 'Fotoğraflarımı bulutta saklıyorum.',
    exampleTranslationEn: 'I store my photos in the cloud.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-72',
    german: 'das Betriebssystem',
    turkish: 'İşletim sistemi',
    english: 'Operating system',
    article: 'das',
    plural: 'Betriebssysteme',
    partOfSpeech: 'noun',
    synonyms: ['OS'],
    collocations: ['das Betriebssystem aktualisieren', 'ein neues Betriebssystem'],
    emoji: '🖥️',
    exampleSentence: 'Welches Betriebssystem benutzt du?',
    exampleTranslation: 'Hangi işletim sistemini kullanıyorsun?',
    exampleTranslationEn: 'Which operating system do you use?',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-73',
    german: 'der Touchscreen',
    turkish: 'Dokunmatik ekran',
    english: 'Touchscreen',
    article: 'der',
    plural: 'Touchscreens',
    partOfSpeech: 'noun',
    synonyms: ['Berührungsbildschirm'],
    collocations: ['den Touchscreen berühren', 'über den Touchscreen wischen'],
    emoji: '👆',
    exampleSentence: 'Der Touchscreen reagiert nicht mehr.',
    exampleTranslation: 'Dokunmatik ekran artık tepki vermiyor.',
    exampleTranslationEn: 'The touchscreen is no longer responding.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-74',
    german: 'die Videokonferenz',
    turkish: 'Video konferans',
    english: 'Video conference',
    article: 'die',
    plural: 'Videokonferenzen',
    partOfSpeech: 'noun',
    synonyms: ['Videocall', 'Onlinemeeting'],
    collocations: ['an einer Videokonferenz teilnehmen', 'eine Videokonferenz starten'],
    emoji: '🎥',
    exampleSentence: 'Wir haben jeden Montag eine Videokonferenz.',
    exampleTranslation: 'Her pazartesi bir video konferansımız var.',
    exampleTranslationEn: 'We have a video conference every Monday.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-75',
    german: 'der Spam',
    turkish: 'İstenmeyen posta',
    english: 'Spam',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Junk-Mail', 'unerwünschte Werbung'],
    collocations: ['Spam-Filter', 'Spam-Nachrichten löschen'],
    emoji: '📧',
    exampleSentence: 'Mein Postfach ist voller Spam.',
    exampleTranslation: 'Posta kutum istenmeyen postalarla dolu.',
    exampleTranslationEn: 'My inbox is full of spam.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-76',
    german: 'digital',
    turkish: 'Dijital',
    english: 'Digital',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['elektronisch', 'virtuell'],
    collocations: ['digitale Medien', 'digitale Welt'],
    emoji: '💻',
    exampleSentence: 'Wir leben in einer digitalen Welt.',
    exampleTranslation: 'Dijital bir dünyada yaşıyoruz.',
    exampleTranslationEn: 'We live in a digital world.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-77',
    german: 'das Streaming',
    turkish: 'Yayın akışı',
    english: 'Streaming',
    article: 'das',
    partOfSpeech: 'noun',
    synonyms: ['Live-Streaming', 'Onlinestreaming'],
    collocations: ['Musik streamen', 'einen Streaming-Dienst nutzen'],
    emoji: '▶️',
    exampleSentence: 'Streaming-Dienste werden immer beliebter.',
    exampleTranslation: 'Yayın akışı hizmetleri giderek daha popüler oluyor.',
    exampleTranslationEn: 'Streaming services are becoming increasingly popular.',
    category: 'technology',
    level: 'B1',
  },
  {
    id: 'technology-78',
    german: 'der Empfang',
    turkish: 'Çekim / Sinyal',
    english: 'Reception / Signal',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Signal', 'Netzempfang'],
    collocations: ['keinen Empfang haben', 'schlechter Empfang'],
    emoji: '📶',
    exampleSentence: 'Hier habe ich keinen Empfang.',
    exampleTranslation: 'Burada çekim yok.',
    exampleTranslationEn: 'I have no reception here.',
    category: 'technology',
    level: 'B1',
  },
  // B2 words (technology-79 to technology-100)
  {
    id: 'technology-79',
    german: 'die Benutzeroberfläche',
    turkish: 'Kullanıcı arayüzü',
    english: 'User interface',
    article: 'die',
    plural: 'Benutzeroberflächen',
    partOfSpeech: 'noun',
    synonyms: ['Interface', 'Oberfläche', 'UI'],
    collocations: ['eine intuitive Benutzeroberfläche', 'die Benutzeroberfläche gestalten'],
    emoji: '🖥️',
    exampleSentence: 'Die Benutzeroberfläche dieser App ist sehr benutzerfreundlich.',
    exampleTranslation: 'Bu uygulamanın kullanıcı arayüzü çok kullanıcı dostu.',
    exampleTranslationEn: 'The user interface of this app is very user-friendly.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-80',
    german: 'die Barrierefreiheit',
    turkish: 'Erişilebilirlik',
    english: 'Accessibility',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Zugänglichkeit'],
    collocations: ['digitale Barrierefreiheit', 'Barrierefreiheit gewährleisten'],
    emoji: '♿',
    exampleSentence: 'Barrierefreiheit im Internet ist ein wichtiges Thema.',
    exampleTranslation: 'İnternette erişilebilirlik önemli bir konudur.',
    exampleTranslationEn: 'Accessibility on the internet is an important topic.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-81',
    german: 'das Rechenzentrum',
    turkish: 'Veri merkezi',
    english: 'Data center',
    article: 'das',
    plural: 'Rechenzentren',
    partOfSpeech: 'noun',
    synonyms: ['Datenzentrum', 'Serverraum'],
    collocations: ['ein Rechenzentrum betreiben', 'im Rechenzentrum gespeichert'],
    emoji: '🏢',
    exampleSentence: 'Das Rechenzentrum verbraucht sehr viel Energie.',
    exampleTranslation: 'Veri merkezi çok fazla enerji tüketiyor.',
    exampleTranslationEn: 'The data center consumes a lot of energy.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-82',
    german: 'der Algorithmus',
    turkish: 'Algoritma',
    english: 'Algorithm',
    article: 'der',
    plural: 'Algorithmen',
    partOfSpeech: 'noun',
    synonyms: ['Rechenvorschrift', 'Berechnungsverfahren'],
    collocations: ['einen Algorithmus entwickeln', 'der Algorithmus entscheidet'],
    emoji: '🧮',
    exampleSentence: 'Der Algorithmus bestimmt, welche Inhalte du siehst.',
    exampleTranslation: 'Algoritma hangi içerikleri gördüğünü belirler.',
    exampleTranslationEn: 'The algorithm determines which content you see.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-83',
    german: 'die Automatisierung',
    turkish: 'Otomasyon',
    english: 'Automation',
    article: 'die',
    plural: 'Automatisierungen',
    partOfSpeech: 'noun',
    synonyms: ['Automation'],
    collocations: ['Prozesse automatisieren', 'Automatisierung der Produktion'],
    emoji: '⚙️',
    exampleSentence: 'Die Automatisierung hat viele Arbeitsplätze verändert.',
    exampleTranslation: 'Otomasyon birçok iş yerini değiştirdi.',
    exampleTranslationEn: 'Automation has changed many workplaces.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-84',
    german: 'die Cyberkriminalität',
    turkish: 'Siber suç',
    english: 'Cybercrime',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Internetkriminalität', 'Computerkriminalität'],
    collocations: ['Cyberkriminalität bekämpfen', 'Opfer von Cyberkriminalität'],
    emoji: '🕵️',
    exampleSentence: 'Cyberkriminalität nimmt weltweit zu.',
    exampleTranslation: 'Siber suç dünya genelinde artıyor.',
    exampleTranslationEn: 'Cybercrime is increasing worldwide.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-85',
    german: 'der Datenschutz',
    turkish: 'Veri koruma',
    english: 'Data protection',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Privatsphäre', 'Datensicherheit'],
    collocations: ['den Datenschutz einhalten', 'Datenschutzrichtlinien'],
    emoji: '🛡️',
    exampleSentence: 'Der Datenschutz ist in Europa sehr streng.',
    exampleTranslation: "Avrupa'da veri koruma çok katıdır.",
    exampleTranslationEn: 'Data protection is very strict in Europe.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-86',
    german: 'hacken',
    turkish: 'Hacklemek',
    english: 'To hack',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['eindringen', 'knacken'],
    collocations: ['ein System hacken', 'ein Konto hacken'],
    emoji: '👨‍💻',
    exampleSentence: 'Jemand hat mein E-Mail-Konto gehackt.',
    exampleTranslation: 'Birisi e-posta hesabımı hackledi.',
    exampleTranslationEn: 'Someone hacked my email account.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-87',
    german: 'die Programmierung',
    turkish: 'Programlama',
    english: 'Programming',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Softwareentwicklung', 'Coding'],
    collocations: ['Programmierung lernen', 'objektorientierte Programmierung'],
    emoji: '👨‍💻',
    exampleSentence: 'Programmierung ist eine wichtige Fähigkeit in der modernen Arbeitswelt.',
    exampleTranslation: 'Programlama modern iş dünyasında önemli bir beceridir.',
    exampleTranslationEn: 'Programming is an important skill in the modern working world.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-88',
    german: 'die Schnittstelle',
    turkish: 'Arayüz / Arabirim',
    english: 'Interface',
    article: 'die',
    plural: 'Schnittstellen',
    partOfSpeech: 'noun',
    synonyms: ['Interface', 'API'],
    collocations: ['eine Schnittstelle programmieren', 'über eine Schnittstelle verbinden'],
    emoji: '🔌',
    exampleSentence: 'Die Schnittstelle zwischen den beiden Systemen funktioniert nicht.',
    exampleTranslation: 'İki sistem arasındaki arabirim çalışmıyor.',
    exampleTranslationEn: 'The interface between the two systems is not working.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-89',
    german: 'die Vernetzung',
    turkish: 'Ağ oluşturma',
    english: 'Networking / Interconnection',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Verbindung', 'Verknüpfung'],
    collocations: ['globale Vernetzung', 'die Vernetzung von Geräten'],
    emoji: '🌍',
    exampleSentence: 'Die globale Vernetzung hat die Kommunikation revolutioniert.',
    exampleTranslation: 'Küresel ağ oluşturma iletişimde devrim yarattı.',
    exampleTranslationEn: 'Global networking has revolutionized communication.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-90',
    german: 'das Start-up',
    turkish: 'Girişim / Start-up',
    english: 'Start-up',
    article: 'das',
    plural: 'Start-ups',
    partOfSpeech: 'noun',
    synonyms: ['Jungunternehmen', 'Gründung'],
    collocations: ['ein Start-up gründen', 'in ein Start-up investieren'],
    emoji: '🚀',
    exampleSentence: 'Berlin ist bekannt für seine Technologie-Start-ups.',
    exampleTranslation: 'Berlin teknoloji girişimleriyle tanınır.',
    exampleTranslationEn: 'Berlin is known for its technology start-ups.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-91',
    german: 'die Medienkompetenz',
    turkish: 'Medya okuryazarlığı',
    english: 'Media literacy',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Medienbildung'],
    collocations: ['Medienkompetenz fördern', 'Medienkompetenz vermitteln'],
    emoji: '📚',
    exampleSentence: 'Medienkompetenz sollte in der Schule unterrichtet werden.',
    exampleTranslation: 'Medya okuryazarlığı okulda öğretilmelidir.',
    exampleTranslationEn: 'Media literacy should be taught in school.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-92',
    german: 'die virtuelle Realität',
    turkish: 'Sanal gerçeklik',
    english: 'Virtual reality',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['VR'],
    collocations: ['virtuelle Realität erleben', 'VR-Brille tragen'],
    emoji: '🥽',
    exampleSentence: 'Virtuelle Realität wird in der Medizin immer häufiger eingesetzt.',
    exampleTranslation: 'Sanal gerçeklik tıpta giderek daha sık kullanılıyor.',
    exampleTranslationEn: 'Virtual reality is being used more and more in medicine.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-93',
    german: 'die Robotik',
    turkish: 'Robotik',
    english: 'Robotics',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Robotertechnik'],
    collocations: ['Fortschritte in der Robotik', 'Robotik in der Industrie'],
    emoji: '🤖',
    exampleSentence: 'Die Robotik hat in den letzten Jahren große Fortschritte gemacht.',
    exampleTranslation: 'Robotik son yıllarda büyük ilerlemeler kaydetti.',
    exampleTranslationEn: 'Robotics has made great progress in recent years.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-94',
    german: 'der Influencer',
    turkish: 'Fenomen / Etkileyici',
    english: 'Influencer',
    article: 'der',
    plural: 'Influencer',
    partOfSpeech: 'noun',
    synonyms: ['Meinungsmacher', 'Internetberühmtheit'],
    collocations: ['ein bekannter Influencer', 'Influencer-Marketing'],
    emoji: '📸',
    exampleSentence: 'Viele Jugendliche folgen Influencern in den sozialen Medien.',
    exampleTranslation: 'Birçok genç sosyal medyada fenomenleri takip ediyor.',
    exampleTranslationEn: 'Many young people follow influencers on social media.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-95',
    german: 'die Desinformation',
    turkish: 'Dezenformasyon',
    english: 'Disinformation',
    article: 'die',
    plural: 'Desinformationen',
    partOfSpeech: 'noun',
    synonyms: ['Falschinformation', 'Fake News'],
    collocations: ['Desinformation verbreiten', 'gegen Desinformation vorgehen'],
    emoji: '🚫',
    exampleSentence: 'Desinformation im Internet ist ein wachsendes Problem.',
    exampleTranslation: 'İnternette dezenformasyon büyüyen bir sorundur.',
    exampleTranslationEn: 'Disinformation on the internet is a growing problem.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-96',
    german: 'nachhaltig',
    turkish: 'Sürdürülebilir',
    english: 'Sustainable',
    article: null,
    partOfSpeech: 'adjective',
    synonyms: ['zukunftsfähig', 'umweltbewusst'],
    collocations: ['nachhaltige Technologie', 'nachhaltig handeln'],
    emoji: '♻️',
    exampleSentence: 'Nachhaltige Technologien sind für die Zukunft entscheidend.',
    exampleTranslation: 'Sürdürülebilir teknolojiler gelecek için belirleyicidir.',
    exampleTranslationEn: 'Sustainable technologies are crucial for the future.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-97',
    german: 'die Drohne',
    turkish: 'Drone',
    english: 'Drone',
    article: 'die',
    plural: 'Drohnen',
    partOfSpeech: 'noun',
    synonyms: ['unbemanntes Flugobjekt', 'Flugdrohne'],
    collocations: ['eine Drohne fliegen', 'mit einer Drohne filmen'],
    emoji: '🛸',
    exampleSentence: 'Drohnen werden auch für die Paketlieferung getestet.',
    exampleTranslation: 'Dronelar paket teslimatı için de test ediliyor.',
    exampleTranslationEn: 'Drones are also being tested for package delivery.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-98',
    german: 'der 3D-Drucker',
    turkish: '3D yazıcı',
    english: '3D printer',
    article: 'der',
    plural: '3D-Drucker',
    partOfSpeech: 'noun',
    synonyms: ['3D-Printer'],
    collocations: ['mit dem 3D-Drucker herstellen', 'einen 3D-Drucker benutzen'],
    emoji: '🖨️',
    exampleSentence: 'Mit einem 3D-Drucker kann man Ersatzteile selbst herstellen.',
    exampleTranslation: 'Bir 3D yazıcı ile yedek parçaları kendiniz üretebilirsiniz.',
    exampleTranslationEn: 'With a 3D printer you can produce spare parts yourself.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-99',
    german: 'die Spracherkennung',
    turkish: 'Ses tanıma',
    english: 'Voice recognition',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Sprachsteuerung', 'Stimmerkennung'],
    collocations: ['Spracherkennung nutzen', 'automatische Spracherkennung'],
    emoji: '🗣️',
    exampleSentence: 'Die Spracherkennung meines Handys funktioniert sehr gut.',
    exampleTranslation: 'Telefonumun ses tanıma özelliği çok iyi çalışıyor.',
    exampleTranslationEn: 'The voice recognition on my phone works very well.',
    category: 'technology',
    level: 'B2',
  },
  {
    id: 'technology-100',
    german: 'die Blockchain',
    turkish: 'Blok zinciri',
    english: 'Blockchain',
    article: 'die',
    plural: 'Blockchains',
    partOfSpeech: 'noun',
    synonyms: ['Blockkette'],
    collocations: ['Blockchain-Technologie', 'auf der Blockchain basieren'],
    emoji: '🔗',
    exampleSentence: 'Die Blockchain-Technologie hat das Potenzial, viele Branchen zu verändern.',
    exampleTranslation: 'Blok zinciri teknolojisi birçok sektörü değiştirme potansiyeline sahiptir.',
    exampleTranslationEn: 'Blockchain technology has the potential to change many industries.',
    category: 'technology',
    level: 'B2',
  },
];
