import { VocabularyWord } from '@/lib/types';

export const timeWords: VocabularyWord[] = [
  { id: 'time-1', german: 'Uhr', turkish: 'Saat', english: 'clock/o\'clock', article: 'die', partOfSpeech: 'noun', plural: 'Uhren', emoji: '🕐', collocations: ['um drei Uhr', 'Wie viel Uhr ist es?', 'rund um die Uhr'], exampleSentence: 'Es ist drei Uhr.', exampleTranslation: 'Saat üç.', exampleTranslationEn: 'It is three o\'clock.', category: 'time', level: 'A1' },
  { id: 'time-2', german: 'Stunde', turkish: 'Saat (süre)', english: 'hour', article: 'die', partOfSpeech: 'noun', plural: 'Stunden', emoji: '⏳', collocations: ['eine halbe Stunde', 'pro Stunde', 'zur vollen Stunde'], exampleSentence: 'Der Film dauert zwei Stunden.', exampleTranslation: 'Film iki saat sürüyor.', exampleTranslationEn: 'The film lasts two hours.', category: 'time', level: 'A1' },
  { id: 'time-3', german: 'Minute', turkish: 'Dakika', english: 'minute', article: 'die', partOfSpeech: 'noun', plural: 'Minuten', emoji: '⏱️', collocations: ['in letzter Minute', 'fünf Minuten zu spät', 'eine Minute Geduld'], exampleSentence: 'Warte fünf Minuten!', exampleTranslation: 'Beş dakika bekle!', exampleTranslationEn: 'Wait five minutes!', category: 'time', level: 'A1' },
  { id: 'time-4', german: 'Tag', turkish: 'Gün', english: 'day', article: 'der', partOfSpeech: 'noun', plural: 'Tage', emoji: '📅', antonyms: ['Nacht'], collocations: ['den ganzen Tag', 'Tag für Tag', 'guten Tag'], exampleSentence: 'Heute ist ein schöner Tag.', exampleTranslation: 'Bugün güzel bir gün.', exampleTranslationEn: 'Today is a beautiful day.', category: 'time', level: 'A1' },
  { id: 'time-5', german: 'Woche', turkish: 'Hafta', english: 'week', article: 'die', partOfSpeech: 'noun', plural: 'Wochen', emoji: '🗓️', collocations: ['nächste Woche', 'unter der Woche', 'einmal pro Woche'], exampleSentence: 'Nächste Woche habe ich Urlaub.', exampleTranslation: 'Gelecek hafta tatilim var.', exampleTranslationEn: 'Next week I have vacation.', category: 'time', level: 'A1' },
  { id: 'time-6', german: 'Monat', turkish: 'Ay', english: 'month', article: 'der', partOfSpeech: 'noun', plural: 'Monate', emoji: '📆', collocations: ['letzten Monat', 'pro Monat', 'im nächsten Monat'], exampleSentence: 'Welcher Monat ist jetzt?', exampleTranslation: 'Şimdi hangi ay?', exampleTranslationEn: 'Which month is it now?', category: 'time', level: 'A1' },
  { id: 'time-7', german: 'Jahr', turkish: 'Yıl', english: 'year', article: 'das', partOfSpeech: 'noun', plural: 'Jahre', emoji: '🎆', collocations: ['letztes Jahr', 'im Laufe des Jahres', 'Jahr für Jahr'], exampleSentence: 'Ich lerne seit einem Jahr Deutsch.', exampleTranslation: 'Bir yıldır Almanca öğreniyorum.', exampleTranslationEn: 'I have been learning German for a year.', category: 'time', level: 'A1' },
  { id: 'time-8', german: 'Morgen', turkish: 'Sabah', english: 'morning', article: 'der', partOfSpeech: 'noun', plural: 'Morgen', emoji: '🌅', antonyms: ['Abend'], collocations: ['am frühen Morgen', 'guten Morgen', 'heute Morgen'], exampleSentence: 'Am Morgen trinke ich Kaffee.', exampleTranslation: 'Sabahleyin kahve içerim.', exampleTranslationEn: 'In the morning I drink coffee.', category: 'time', level: 'A1' },
  { id: 'time-9', german: 'Abend', turkish: 'Akşam', english: 'evening', article: 'der', partOfSpeech: 'noun', plural: 'Abende', emoji: '🌇', antonyms: ['Morgen'], collocations: ['guten Abend', 'am Abend', 'heute Abend'], exampleSentence: 'Am Abend lese ich ein Buch.', exampleTranslation: 'Akşamları kitap okurum.', exampleTranslationEn: 'In the evening I read a book.', category: 'time', level: 'A1' },
  { id: 'time-10', german: 'Nacht', turkish: 'Gece', english: 'night', article: 'die', partOfSpeech: 'noun', plural: 'Nächte', emoji: '🌙', antonyms: ['Tag'], collocations: ['gute Nacht', 'in der Nacht', 'über Nacht'], exampleSentence: 'In der Nacht schlafe ich.', exampleTranslation: 'Geceleri uyurum.', exampleTranslationEn: 'At night I sleep.', category: 'time', level: 'A1' },
  { id: 'time-11', german: 'Montag', turkish: 'Pazartesi', english: 'Monday', article: 'der', partOfSpeech: 'noun', plural: 'Montage', emoji: '📌', collocations: ['am Montag', 'jeden Montag', 'montags'], exampleSentence: 'Am Montag beginnt die Arbeit.', exampleTranslation: 'Pazartesi iş başlar.', exampleTranslationEn: 'On Monday work begins.', category: 'time', level: 'A1' },
  { id: 'time-12', german: 'heute', turkish: 'bugün', english: 'today', article: null, partOfSpeech: 'adverb', emoji: '📍', antonyms: ['gestern', 'morgen'], collocations: ['heute Morgen', 'heute Abend', 'von heute an'], exampleSentence: 'Heute ist Mittwoch.', exampleTranslation: 'Bugün Çarşamba.', exampleTranslationEn: 'Today is Wednesday.', category: 'time', level: 'A1' },
  { id: 'time-13', german: 'gestern', turkish: 'dün', english: 'yesterday', article: null, partOfSpeech: 'adverb', emoji: '⬅️', antonyms: ['morgen', 'heute'], collocations: ['gestern Abend', 'gestern Morgen', 'seit gestern'], exampleSentence: 'Gestern war ich müde.', exampleTranslation: 'Dün yorgundum.', exampleTranslationEn: 'Yesterday I was tired.', category: 'time', level: 'A1' },
  { id: 'time-14', german: 'morgen', turkish: 'yarın', english: 'tomorrow', article: null, partOfSpeech: 'adverb', emoji: '➡️', antonyms: ['gestern', 'heute'], collocations: ['morgen früh', 'bis morgen', 'morgen Abend'], exampleSentence: 'Morgen gehe ich einkaufen.', exampleTranslation: 'Yarın alışverişe gideceğim.', exampleTranslationEn: 'Tomorrow I will go shopping.', category: 'time', level: 'A1' },
  { id: 'time-15', german: 'jetzt', turkish: 'şimdi', english: 'now', article: null, partOfSpeech: 'adverb', emoji: '⏺️', synonyms: ['nun', 'gerade'], antonyms: ['später', 'vorher'], collocations: ['jetzt sofort', 'bis jetzt', 'von jetzt an'], exampleSentence: 'Ich bin jetzt zu Hause.', exampleTranslation: 'Şimdi evdeyim.', exampleTranslationEn: 'I am at home now.', category: 'time', level: 'A1' },
  { id: 'time-16', german: 'immer', turkish: 'her zaman', english: 'always', article: null, partOfSpeech: 'adverb', emoji: '♾️', synonyms: ['stets'], antonyms: ['nie', 'niemals'], collocations: ['immer wieder', 'für immer', 'immer noch'], exampleSentence: 'Er kommt immer pünktlich.', exampleTranslation: 'Her zaman zamanında gelir.', exampleTranslationEn: 'He always comes on time.', category: 'time', level: 'A1' },
  { id: 'time-17', german: 'nie', turkish: 'hiçbir zaman', english: 'never', article: null, partOfSpeech: 'adverb', emoji: '🚫', synonyms: ['niemals'], antonyms: ['immer', 'stets'], collocations: ['nie wieder', 'nie und nimmer', 'fast nie'], exampleSentence: 'Ich war nie in Japan.', exampleTranslation: 'Hiçbir zaman Japonya\'da bulunmadım.', exampleTranslationEn: 'I have never been to Japan.', category: 'time', level: 'A1' },
  { id: 'time-18', german: 'manchmal', turkish: 'bazen', english: 'sometimes', article: null, partOfSpeech: 'adverb', emoji: '🔀', synonyms: ['ab und zu', 'gelegentlich'], collocations: ['manchmal auch', 'nur manchmal'], exampleSentence: 'Manchmal gehe ich joggen.', exampleTranslation: 'Bazen koşuya çıkarım.', exampleTranslationEn: 'Sometimes I go jogging.', category: 'time', level: 'A1' },
  { id: 'time-19', german: 'oft', turkish: 'sık sık', english: 'often', article: null, partOfSpeech: 'adverb', emoji: '🔁', synonyms: ['häufig'], antonyms: ['selten'], collocations: ['wie oft', 'so oft wie möglich', 'ziemlich oft'], exampleSentence: 'Ich gehe oft ins Kino.', exampleTranslation: 'Sık sık sinemaya giderim.', exampleTranslationEn: 'I often go to the cinema.', category: 'time', level: 'A1' },
  { id: 'time-20', german: 'früh', turkish: 'erken', english: 'early', article: null, partOfSpeech: 'adjective', emoji: '🌄', antonyms: ['spät'], collocations: ['früh aufstehen', 'früh am Morgen', 'zu früh'], exampleSentence: 'Ich stehe früh auf.', exampleTranslation: 'Erken kalkarım.', exampleTranslationEn: 'I get up early.', category: 'time', level: 'A1' },
];
