import { VocabularyWord } from '@/lib/types';

export const timeWords: VocabularyWord[] = [
  { id: 'time-1', german: 'Uhr', turkish: 'Saat', english: 'clock/o\'clock', article: 'die', partOfSpeech: 'noun', plural: 'Uhren', emoji: '🕐', collocations: ['um drei Uhr', 'Wie viel Uhr ist es?', 'rund um die Uhr'], exampleSentence: 'Es ist drei Uhr.', exampleTranslation: 'Saat üç.', exampleTranslationEn: 'It is three o\'clock.', category: 'time', level: 'A1' },
  { id: 'time-2', german: 'Stunde', turkish: 'Saat (süre)', english: 'hour', article: 'die', partOfSpeech: 'noun', plural: 'Stunden', emoji: '⏳', collocations: ['eine halbe Stunde', 'pro Stunde', 'zur vollen Stunde'], exampleSentence: 'Der Film dauert zwei Stunden.', exampleTranslation: 'Film iki saat sürüyor.', exampleTranslationEn: 'The film lasts two hours.', category: 'time', level: 'A1' },
  { id: 'time-3', german: 'Minute', turkish: 'Dakika', english: 'minute', article: 'die', partOfSpeech: 'noun', plural: 'Minuten', emoji: '⏱️', collocations: ['in letzter Minute', 'fünf Minuten zu spät', 'eine Minute Geduld'], exampleSentence: 'Warte fünf Minuten!', exampleTranslation: 'Beş dakika bekle!', exampleTranslationEn: 'Wait five minutes!', category: 'time', level: 'A1' },
  { id: 'time-4', german: 'Tag', turkish: 'Gün', english: 'day', article: 'der', partOfSpeech: 'noun', plural: 'Tage', emoji: '📅', antonyms: ['Nacht'], collocations: ['den ganzen Tag', 'Tag für Tag', 'guten Tag'], exampleSentence: 'Heute ist ein schöner Tag.', exampleTranslation: 'Bugün güzel bir gün.', exampleTranslationEn: 'Today is a beautiful day.', category: 'time', level: 'A1' },
  { id: 'time-5', german: 'Woche', turkish: 'Hafta', english: 'week', article: 'die', partOfSpeech: 'noun', plural: 'Wochen', emoji: '🗓️', collocations: ['nächste Woche', 'unter der Woche', 'einmal pro Woche'], exampleSentence: 'Nächste Woche habe ich Urlaub.', exampleTranslation: 'Gelecek hafta tatilim var.', exampleTranslationEn: 'Next week I have vacation.', category: 'time', level: 'A1' },
  { id: 'time-6', german: 'Monat', turkish: 'Ay', english: 'month', article: 'der', partOfSpeech: 'noun', plural: 'Monate', emoji: '📆', collocations: ['letzten Monat', 'pro Monat', 'im nächsten Monat'], exampleSentence: 'Welcher Monat ist jetzt?', exampleTranslation: 'Şimdi hangi ay?', exampleTranslationEn: 'Which month is it now?', category: 'time', level: 'A1' },
  { id: 'time-7', german: 'Jahr', turkish: 'Yıl', english: 'year', article: 'das', partOfSpeech: 'noun', plural: 'Jahre', emoji: '🎆', collocations: ['letztes Jahr', 'im Laufe des Jahres', 'Jahr für Jahr'], exampleSentence: 'Ich lerne seit einem Jahr Deutsch.', exampleTranslation: 'Bir yıldır Almanca öğreniyorum.', exampleTranslationEn: 'I have been learning German for a year.', category: 'time', level: 'A1' },
  { id: 'time-8', german: 'Morgen', turkish: 'Sabah', english: 'morning', article: 'der', partOfSpeech: 'noun', plural: 'Morgen', emoji: '🌅', antonyms: ['Abend'], collocations: ['am frühen Morgen', 'guten Morgen', 'heute Morgen'], exampleSentence: 'Am Morgen trinke ich Kaffee.', exampleTranslation: 'Sabahleyin kahve içerim.', exampleTranslationEn: 'In the morning I drink coffee.', category: 'time', level: 'A1' },
  { id: 'time-9', german: 'Abend', turkish: 'Akşam', english: 'evening', article: 'der', partOfSpeech: 'noun', plural: 'Abende', emoji: '🌇', antonyms: ['Morgen'], collocations: ['guten Abend', 'am Abend', 'heute Abend'], exampleSentence: 'Am Abend lese ich ein Buch.', exampleTranslation: 'Akşamları kitap okurum.', exampleTranslationEn: 'In the evening I read a book.', category: 'time', level: 'A1' },
  { id: 'time-10', german: 'Nacht', turkish: 'Gece', english: 'night', article: 'die', partOfSpeech: 'noun', plural: 'Nächte', emoji: '🌙', antonyms: ['Tag'], collocations: ['gute Nacht', 'in der Nacht', 'über Nacht'], exampleSentence: 'In der Nacht schlafe ich.', exampleTranslation: 'Geceleri uyurum.', exampleTranslationEn: 'At night I sleep.', category: 'time', level: 'A1' },
  { id: 'time-11', german: 'Montag', turkish: 'Pazartesi', english: 'Monday', article: 'der', partOfSpeech: 'noun', plural: 'Montage', emoji: '📌', collocations: ['am Montag', 'jeden Montag', 'montags'], exampleSentence: 'Am Montag beginnt die Arbeit.', exampleTranslation: 'Pazartesi iş başlar.', exampleTranslationEn: 'On Monday work begins.', category: 'time', level: 'A1' },
  { id: 'time-12', german: 'heute', turkish: 'bugün', english: 'today', article: null, partOfSpeech: 'adverb', emoji: '📍', antonyms: ['gestern', 'morgen'], collocations: ['heute Morgen', 'heute Abend', 'von heute an'], exampleSentence: 'Heute ist Mittwoch.', exampleTranslation: 'Bugün Çarşamba.', exampleTranslationEn: 'Today is Wednesday.', category: 'time', level: 'A1' },
  { id: 'time-13', german: 'gestern', turkish: 'dün', english: 'yesterday', article: null, partOfSpeech: 'adverb', emoji: '⬅️', antonyms: ['morgen', 'heute'], collocations: ['gestern Abend', 'gestern Morgen', 'seit gestern'], exampleSentence: 'Gestern war ich müde.', exampleTranslation: 'Dün yorgundum.', exampleTranslationEn: 'Yesterday I was tired.', category: 'time', level: 'A1' },
  { id: 'time-14', german: 'morgen', turkish: 'yarın', english: 'tomorrow', article: null, partOfSpeech: 'adverb', emoji: '➡️', antonyms: ['gestern', 'heute'], collocations: ['morgen früh', 'bis morgen', 'morgen Abend'], exampleSentence: 'Morgen gehe ich einkaufen.', exampleTranslation: 'Yarın alışverişe gideceğim.', exampleTranslationEn: 'Tomorrow I will go shopping.', category: 'time', level: 'A1' },
  { id: 'time-15', german: 'jetzt', turkish: 'şimdi', english: 'now', article: null, partOfSpeech: 'adverb', emoji: '⏺️', synonyms: ['nun', 'gerade'], antonyms: ['später', 'vorher'], collocations: ['jetzt sofort', 'bis jetzt', 'von jetzt an'], exampleSentence: 'Ich bin jetzt zu Hause.', exampleTranslation: 'Şimdi evdeyim.', exampleTranslationEn: 'I am at home now.', category: 'time', level: 'A1' },
  { id: 'time-16', german: 'immer', turkish: 'her zaman', english: 'always', article: null, partOfSpeech: 'adverb', emoji: '♾️', synonyms: ['stets'], antonyms: ['nie', 'niemals'], collocations: ['immer wieder', 'für immer', 'immer noch'], exampleSentence: 'Er kommt immer pünktlich.', exampleTranslation: 'Her zaman zamanında gelir.', exampleTranslationEn: 'He always comes on time.', category: 'time', level: 'A1' },
  { id: 'time-17', german: 'nie', turkish: 'hiçbir zaman', english: 'never', article: null, partOfSpeech: 'adverb', emoji: '🚫', synonyms: ['niemals'], antonyms: ['immer', 'stets'], collocations: ['nie wieder', 'nie und nimmer', 'fast nie'], exampleSentence: 'Ich war nie in Japan.', exampleTranslation: 'Hiçbir zaman Japonya\'da bulunmadım.', exampleTranslationEn: 'I have never been to Japan.', category: 'time', level: 'A1' },
  { id: 'time-18', german: 'manchmal', turkish: 'bazen', english: 'sometimes', article: null, partOfSpeech: 'adverb', emoji: '🔀', synonyms: ['ab und zu', 'gelegentlich'], collocations: ['manchmal auch', 'nur manchmal'], exampleSentence: 'Manchmal gehe ich joggen.', exampleTranslation: 'Bazen koşuya çıkarım.', exampleTranslationEn: 'Sometimes I go jogging.', category: 'time', level: 'A1' },
  { id: 'time-19', german: 'oft', turkish: 'sık sık', english: 'often', article: null, partOfSpeech: 'adverb', emoji: '🔁', synonyms: ['häufig'], antonyms: ['selten'], collocations: ['wie oft', 'so oft wie möglich', 'ziemlich oft'], exampleSentence: 'Ich gehe oft ins Kino.', exampleTranslation: 'Sık sık sinemaya giderim.', exampleTranslationEn: 'I often go to the cinema.', category: 'time', level: 'A1' },
  { id: 'time-20', german: 'früh', turkish: 'erken', english: 'early', article: null, partOfSpeech: 'adjective', emoji: '🌄', antonyms: ['spät'], collocations: ['früh aufstehen', 'früh am Morgen', 'zu früh'], exampleSentence: 'Ich stehe früh auf.', exampleTranslation: 'Erken kalkarım.', exampleTranslationEn: 'I get up early.', category: 'time', level: 'A1' },
  // B1 - Scheduling, frequency
  {
    id: 'time-b1-1',
    german: 'der Termin',
    turkish: 'randevu',
    english: 'appointment',
    article: 'der',
    plural: 'Termine',
    partOfSpeech: 'noun',
    exampleSentence: 'Ich muss einen Termin beim Arzt vereinbaren.',
    exampleTranslation: 'Doktorda bir randevu almam gerekiyor.',
    exampleTranslationEn: 'I need to make an appointment with the doctor.',
    category: 'time',
    level: 'B1',
    tags: ['scheduling', 'planning'],
  },
  {
    id: 'time-b1-2',
    german: 'regelmäßig',
    turkish: 'düzenli olarak',
    english: 'regularly',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Er geht regelmäßig ins Fitnessstudio.',
    exampleTranslation: 'Düzenli olarak spor salonuna gider.',
    exampleTranslationEn: 'He goes to the gym regularly.',
    category: 'time',
    level: 'B1',
    tags: ['frequency', 'routine'],
  },
  {
    id: 'time-b1-3',
    german: 'gelegentlich',
    turkish: 'ara sıra / zaman zaman',
    english: 'occasionally',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Gelegentlich gehe ich ins Theater.',
    exampleTranslation: 'Ara sıra tiyatroya giderim.',
    exampleTranslationEn: 'Occasionally I go to the theater.',
    category: 'time',
    level: 'B1',
    tags: ['frequency', 'occasional'],
  },
  {
    id: 'time-b1-4',
    german: 'der Zeitraum',
    turkish: 'süre / dönem',
    english: 'period of time',
    article: 'der',
    plural: 'Zeiträume',
    partOfSpeech: 'noun',
    exampleSentence: 'In diesem Zeitraum hat sich viel verändert.',
    exampleTranslation: 'Bu süre zarfında çok şey değişti.',
    exampleTranslationEn: 'A lot has changed in this period of time.',
    category: 'time',
    level: 'B1',
    tags: ['duration', 'planning'],
  },
  {
    id: 'time-b1-5',
    german: 'verschieben',
    turkish: 'ertelemek',
    english: 'to postpone / to reschedule',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Wir müssen den Termin auf nächste Woche verschieben.',
    exampleTranslation: 'Randevuyu gelecek haftaya ertelememiz gerekiyor.',
    exampleTranslationEn: 'We need to postpone the appointment to next week.',
    category: 'time',
    level: 'B1',
    tags: ['scheduling', 'change'],
  },
  {
    id: 'time-b1-6',
    german: 'pünktlich',
    turkish: 'dakik / zamanında',
    english: 'punctual / on time',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Bitte seien Sie pünktlich zum Unterricht.',
    exampleTranslation: 'Lütfen derse zamanında gelin.',
    exampleTranslationEn: 'Please be on time for class.',
    category: 'time',
    level: 'B1',
    tags: ['punctuality', 'scheduling'],
  },
  {
    id: 'time-b1-7',
    german: 'dauern',
    turkish: 'sürmek',
    english: 'to last / to take (time)',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Die Besprechung dauert ungefähr eine Stunde.',
    exampleTranslation: 'Toplantı yaklaşık bir saat sürüyor.',
    exampleTranslationEn: 'The meeting lasts about one hour.',
    category: 'time',
    level: 'B1',
    tags: ['duration', 'time'],
  },
  {
    id: 'time-b1-8',
    german: 'die Frist',
    turkish: 'son tarih / süre',
    english: 'deadline / time limit',
    article: 'die',
    plural: 'Fristen',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Frist für die Bewerbung endet am Freitag.',
    exampleTranslation: 'Başvuru için son tarih Cuma günü bitiyor.',
    exampleTranslationEn: 'The deadline for the application ends on Friday.',
    category: 'time',
    level: 'B1',
    tags: ['deadline', 'scheduling'],
  },
  {
    id: 'time-b1-9',
    german: 'inzwischen',
    turkish: 'bu arada / artık',
    english: 'meanwhile / in the meantime',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Inzwischen hat er eine neue Stelle gefunden.',
    exampleTranslation: 'Bu arada yeni bir iş buldu.',
    exampleTranslationEn: 'In the meantime, he found a new job.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'sequence'],
  },
  {
    id: 'time-b1-10',
    german: 'vorher',
    turkish: 'önceden / daha önce',
    english: 'before / beforehand',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Bitte ruf mich vorher an.',
    exampleTranslation: 'Lütfen önceden beni ara.',
    exampleTranslationEn: 'Please call me beforehand.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'sequence'],
  },
  // B2 - Advanced time concepts, temporal expressions
  {
    id: 'time-b2-1',
    german: 'die Frist',
    turkish: 'son tarih / vade',
    english: 'deadline',
    article: 'die',
    plural: 'Fristen',
    partOfSpeech: 'noun',
    exampleSentence: 'Wenn Sie die Frist versäumen, müssen Sie mit Konsequenzen rechnen.',
    exampleTranslation: 'Son tarihi kaçırırsanız, sonuçlarıyla yüzleşmeniz gerekir.',
    exampleTranslationEn: 'If you miss the deadline, you must face the consequences.',
    category: 'time',
    level: 'B2',
    tags: ['deadline', 'formal'],
  },
  {
    id: 'time-b2-2',
    german: 'der Zeitraum',
    turkish: 'zaman dilimi / dönem',
    english: 'time period',
    article: 'der',
    plural: 'Zeiträume',
    partOfSpeech: 'noun',
    exampleSentence: 'Der Zeitraum zwischen Bewerbung und Einstellung beträgt oft mehrere Wochen.',
    exampleTranslation: 'Başvuru ile işe alım arasındaki zaman dilimi genellikle birkaç haftadır.',
    exampleTranslationEn: 'The time period between application and hiring is often several weeks.',
    category: 'time',
    level: 'B2',
    tags: ['duration', 'planning'],
  },
  {
    id: 'time-b2-3',
    german: 'vorübergehend',
    turkish: 'geçici',
    english: 'temporary',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Die Straße ist wegen Bauarbeiten vorübergehend gesperrt.',
    exampleTranslation: 'Yol inşaat çalışmaları nedeniyle geçici olarak kapatıldı.',
    exampleTranslationEn: 'The road is temporarily closed due to construction work.',
    category: 'time',
    level: 'B2',
    tags: ['temporary', 'duration'],
  },
  {
    id: 'time-b2-4',
    german: 'gleichzeitig',
    turkish: 'eş zamanlı / aynı anda',
    english: 'simultaneous',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Es ist schwierig, gleichzeitig zu arbeiten und zu studieren.',
    exampleTranslation: 'Aynı anda hem çalışmak hem de okumak zordur.',
    exampleTranslationEn: 'It is difficult to work and study simultaneously.',
    category: 'time',
    level: 'B2',
    tags: ['simultaneous', 'multitasking'],
  },
  {
    id: 'time-b2-5',
    german: 'inzwischen',
    turkish: 'bu arada / bu sırada',
    english: 'meanwhile',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Die Technologie hat sich inzwischen rasant weiterentwickelt.',
    exampleTranslation: 'Teknoloji bu arada hızla ilerledi.',
    exampleTranslationEn: 'Technology has meanwhile advanced rapidly.',
    category: 'time',
    level: 'B2',
    tags: ['meanwhile', 'progression'],
  },
  {
    id: 'time-b2-6',
    german: 'die Dauer',
    turkish: 'süre',
    english: 'duration',
    article: 'die',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Dauer des Visumsverfahrens hängt vom jeweiligen Land ab.',
    exampleTranslation: 'Vize işlemlerinin süresi ilgili ülkeye bağlıdır.',
    exampleTranslationEn: 'The duration of the visa process depends on the respective country.',
    category: 'time',
    level: 'B2',
    tags: ['duration', 'formal'],
  },
  {
    id: 'time-b2-7',
    german: 'allmählich',
    turkish: 'yavaş yavaş / giderek',
    english: 'gradually',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Die Situation hat sich allmählich verbessert.',
    exampleTranslation: 'Durum yavaş yavaş iyileşti.',
    exampleTranslationEn: 'The situation has gradually improved.',
    category: 'time',
    level: 'B2',
    tags: ['gradual', 'progression'],
  },
  {
    id: 'time-b2-8',
    german: 'heutzutage',
    turkish: 'günümüzde / bugünlerde',
    english: 'nowadays',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Heutzutage ist es üblich, von zu Hause aus zu arbeiten.',
    exampleTranslation: 'Günümüzde evden çalışmak yaygın hale geldi.',
    exampleTranslationEn: 'Nowadays it is common to work from home.',
    category: 'time',
    level: 'B2',
    tags: ['modern', 'present'],
  },
  {
    id: 'time-b2-9',
    german: 'die Epoche',
    turkish: 'çağ / dönem',
    english: 'epoch',
    article: 'die',
    plural: 'Epochen',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Romantik war eine bedeutende Epoche der deutschen Literatur.',
    exampleTranslation: 'Romantizm, Alman edebiyatının önemli bir dönemiydi.',
    exampleTranslationEn: 'Romanticism was a significant epoch of German literature.',
    category: 'time',
    level: 'B2',
    tags: ['history', 'era'],
  },
  {
    id: 'time-b2-10',
    german: 'der Zeitgenosse',
    turkish: 'çağdaş (kişi)',
    english: 'contemporary',
    article: 'der',
    plural: 'Zeitgenossen',
    partOfSpeech: 'noun',
    exampleSentence: 'Goethe und Schiller waren Zeitgenossen und enge Freunde.',
    exampleTranslation: 'Goethe ve Schiller çağdaştı ve yakın arkadaştılar.',
    exampleTranslationEn: 'Goethe and Schiller were contemporaries and close friends.',
    category: 'time',
    level: 'B2',
    tags: ['history', 'person'],
  },
];
