import { VocabularyWord } from '@/lib/types';

export const timeWords: VocabularyWord[] = [
  { id: 'time-1', german: 'Uhr', turkish: 'Saat', english: 'clock/o\'clock', article: 'die', partOfSpeech: 'noun', plural: 'Uhren', emoji: '🕐', collocations: ['um drei Uhr', 'Wie viel Uhr ist es?', 'rund um die Uhr'], exampleSentence: 'Es ist drei Uhr.', exampleTranslation: 'Saat üç.', exampleTranslationEn: 'It is three o\'clock.', category: 'time', level: 'A1' },
  { id: 'time-2', german: 'Stunde', turkish: 'Saat (süre)', english: 'hour', article: 'die', partOfSpeech: 'noun', plural: 'Stunden', emoji: '⏳', collocations: ['eine halbe Stunde', 'pro Stunde', 'zur vollen Stunde'], exampleSentence: 'Der Film dauert zwei Stunden.', exampleTranslation: 'Film iki saat sürüyor.', exampleTranslationEn: 'The film lasts two hours.', category: 'time', level: 'A1' },
  { id: 'time-3', german: 'Minute', turkish: 'Dakika', english: 'minute', article: 'die', partOfSpeech: 'noun', plural: 'Minuten', emoji: '⏱️', collocations: ['in letzter Minute', 'fünf Minuten zu spät', 'eine Minute Geduld'], exampleSentence: 'Warte fünf Minuten!', exampleTranslation: 'Beş dakika bekle!', exampleTranslationEn: 'Wait five minutes!', category: 'time', level: 'A1' },
  { id: 'time-4', german: 'Tag', turkish: 'Gün', english: 'day', article: 'der', partOfSpeech: 'noun', plural: 'Tage', emoji: '📅', antonyms: ['Nacht'], collocations: ['den ganzen Tag', 'Tag für Tag', 'guten Tag'], exampleSentence: 'Heute ist ein schöner Tag.', exampleTranslation: 'Bugün güzel bir gün.', exampleTranslationEn: 'Today is a beautiful day.', category: 'time', level: 'A1' },
  { id: 'time-5', german: 'Woche', turkish: 'Hafta', english: 'week', article: 'die', partOfSpeech: 'noun', plural: 'Wochen', emoji: '🗓️', collocations: ['nächste Woche', 'unter der Woche', 'einmal pro Woche'], exampleSentence: 'Nächste Woche habe ich Urlaub.', exampleTranslation: 'Gelecek hafta tatilim var.', exampleTranslationEn: 'Next week I have vacation.', category: 'time', level: 'A1' },
  { id: 'time-6', german: 'Monat', turkish: 'Ay', english: 'month', article: 'der', partOfSpeech: 'noun', plural: 'Monate', emoji: '📆', collocations: ['letzten Monat', 'pro Monat', 'im nächsten Monat'], exampleSentence: 'Welcher Monat ist jetzt?', exampleTranslation: 'Şimdi hangi ay?', exampleTranslationEn: 'Which month is it now?', category: 'time', level: 'A1' },
  { id: 'time-7', german: 'Jahr', turkish: 'Yıl', english: 'year', article: 'das', partOfSpeech: 'noun', plural: 'Jahre', emoji: '🎆', collocations: ['letztes Jahr', 'im Laufe des Jahres', 'Jahr für Jahr'], exampleSentence: 'Ich lerne seit einem Jahr Deutsch.', exampleTranslation: 'Bir yıldır Almanca öğreniyorum.', exampleTranslationEn: 'I have been learning German for a year.', category: 'time', level: 'A1' },
  { id: 'time-8', german: 'Morgen', turkish: 'Sabah', english: 'morning', article: 'der', partOfSpeech: 'noun', plural: 'Morgen', emoji: '🌅', antonyms: ['Abend'], collocations: ['am frühen Morgen', 'guten Morgen', 'heute Morgen'], exampleSentence: 'Am Morgen trinke ich Kaffee.', exampleTranslation: 'Sabahleyin kahve içerim.', exampleTranslationEn: 'In the morning I drink coffee.', category: 'time', level: 'A1' },
  { id: 'time-9', german: 'Abend', turkish: 'Akşam', english: 'evening', article: 'der', partOfSpeech: 'noun', plural: 'Abende', emoji: '🌇', antonyms: ['Morgen'], collocations: ['guten Abend', 'am Abend', 'heute Abend'], exampleSentence: 'Am Abend lese ich ein Buch.', exampleTranslation: 'Akşamları kitap okurum.', exampleTranslationEn: 'In the evening I read a book.', category: 'time', level: 'A1' },
  { id: 'time-10', german: 'Nacht', turkish: 'Gece', english: 'night', article: 'die', partOfSpeech: 'noun', plural: 'Nächte', emoji: '🌙', antonyms: ['Tag'], collocations: ['gute Nacht', 'in der Nacht', 'über Nacht'], exampleSentence: 'In der Nacht schlafe ich.', exampleTranslation: 'Geceleri uyurum.', exampleTranslationEn: 'At night I sleep.', category: 'time', level: 'A1' },
  { id: 'time-11', german: 'Montag', turkish: 'Pazartesi', english: 'Monday', article: 'der', partOfSpeech: 'noun', plural: 'Montage', emoji: '📌', collocations: ['am Montag', 'jeden Montag', 'montags'], exampleSentence: 'Am Montag beginnt die Arbeit.', exampleTranslation: 'Pazartesi iş başlar.', exampleTranslationEn: 'On Monday work begins.', category: 'time', level: 'A1' },
  { id: 'time-12', german: 'heute', turkish: 'bugün', english: 'today', article: null, partOfSpeech: 'adverb', emoji: '📍', antonyms: ['gestern', 'morgen'], collocations: ['heute Morgen', 'heute Abend', 'von heute an'], exampleSentence: 'Heute ist Mittwoch.', exampleTranslation: 'Bugün Çarşamba.', exampleTranslationEn: 'Today is Wednesday.', category: 'time', level: 'A1' },
  { id: 'time-13', german: 'gestern', turkish: 'dün', english: 'yesterday', article: null, partOfSpeech: 'adverb', emoji: '⬅️', antonyms: ['morgen', 'heute'], collocations: ['gestern Abend', 'gestern Morgen', 'seit gestern'], exampleSentence: 'Gestern war ich müde.', exampleTranslation: 'Dün yorgundum.', exampleTranslationEn: 'Yesterday I was tired.', category: 'time', level: 'A1' },
  { id: 'time-14', german: 'morgen', turkish: 'yarın', english: 'tomorrow', article: null, partOfSpeech: 'adverb', emoji: '➡️', antonyms: ['gestern', 'heute'], collocations: ['morgen früh', 'bis morgen', 'morgen Abend'], exampleSentence: 'Morgen gehe ich einkaufen.', exampleTranslation: 'Yarın alışverişe gideceğim.', exampleTranslationEn: 'Tomorrow I will go shopping.', category: 'time', level: 'A1' },
  { id: 'time-15', german: 'jetzt', turkish: 'şimdi', english: 'now', article: null, partOfSpeech: 'adverb', emoji: '⏺️', synonyms: ['nun', 'gerade'], antonyms: ['später', 'vorher'], collocations: ['jetzt sofort', 'bis jetzt', 'von jetzt an'], exampleSentence: 'Ich bin jetzt zu Hause.', exampleTranslation: 'Şimdi evdeyim.', exampleTranslationEn: 'I am at home now.', category: 'time', level: 'A1' },
  { id: 'time-16', german: 'immer', turkish: 'her zaman', english: 'always', article: null, partOfSpeech: 'adverb', emoji: '♾️', synonyms: ['stets'], antonyms: ['nie', 'niemals'], collocations: ['immer wieder', 'für immer', 'immer noch'], exampleSentence: 'Er kommt immer pünktlich.', exampleTranslation: 'Her zaman zamanında gelir.', exampleTranslationEn: 'He always comes on time.', category: 'time', level: 'A1' },
  { id: 'time-17', german: 'nie', turkish: 'hiçbir zaman', english: 'never', article: null, partOfSpeech: 'adverb', emoji: '🚫', synonyms: ['niemals'], antonyms: ['immer', 'stets'], collocations: ['nie wieder', 'nie und nimmer', 'fast nie'], exampleSentence: 'Ich war nie in Japan.', exampleTranslation: 'Hiçbir zaman Japonya\'da bulunmadım.', exampleTranslationEn: 'I have never been to Japan.', category: 'time', level: 'A1' },
  { id: 'time-18', german: 'manchmal', turkish: 'bazen', english: 'sometimes', article: null, partOfSpeech: 'adverb', emoji: '🔀', synonyms: ['ab und zu', 'gelegentlich'], collocations: ['manchmal auch', 'nur manchmal'], exampleSentence: 'Manchmal gehe ich joggen.', exampleTranslation: 'Bazen koşuya çıkarım.', exampleTranslationEn: 'Sometimes I go jogging.', category: 'time', level: 'A1' },
  { id: 'time-19', german: 'oft', turkish: 'sık sık', english: 'often', article: null, partOfSpeech: 'adverb', emoji: '🔁', synonyms: ['häufig'], antonyms: ['selten'], collocations: ['wie oft', 'so oft wie möglich', 'ziemlich oft'], exampleSentence: 'Ich gehe oft ins Kino.', exampleTranslation: 'Sık sık sinemaya giderim.', exampleTranslationEn: 'I often go to the cinema.', category: 'time', level: 'A1' },
  { id: 'time-20', german: 'früh', turkish: 'erken', english: 'early', article: null, partOfSpeech: 'adjective', emoji: '🌄', antonyms: ['spät'], collocations: ['früh aufstehen', 'früh am Morgen', 'zu früh'], exampleSentence: 'Ich stehe früh auf.', exampleTranslation: 'Erken kalkarım.', exampleTranslationEn: 'I get up early.', category: 'time', level: 'A1' },
  // A1 - Additional basic time words
  { id: 'time-21', german: 'Dienstag', turkish: 'Salı', english: 'Tuesday', article: 'der', partOfSpeech: 'noun', plural: 'Dienstage', emoji: '📅', collocations: ['am Dienstag', 'jeden Dienstag', 'dienstags'], exampleSentence: 'Am Dienstag habe ich einen Kurs.', exampleTranslation: 'Salı günü bir kursum var.', exampleTranslationEn: 'On Tuesday I have a course.', category: 'time', level: 'A1' },
  { id: 'time-22', german: 'Mittwoch', turkish: 'Çarşamba', english: 'Wednesday', article: 'der', partOfSpeech: 'noun', plural: 'Mittwoche', emoji: '📅', collocations: ['am Mittwoch', 'jeden Mittwoch', 'mittwochs'], exampleSentence: 'Mittwoch ist die Mitte der Woche.', exampleTranslation: 'Çarşamba haftanın ortasıdır.', exampleTranslationEn: 'Wednesday is the middle of the week.', category: 'time', level: 'A1' },
  { id: 'time-23', german: 'Donnerstag', turkish: 'Perşembe', english: 'Thursday', article: 'der', partOfSpeech: 'noun', plural: 'Donnerstage', emoji: '📅', collocations: ['am Donnerstag', 'jeden Donnerstag', 'donnerstags'], exampleSentence: 'Am Donnerstag gehe ich zum Sport.', exampleTranslation: 'Perşembe günü spora giderim.', exampleTranslationEn: 'On Thursday I go to sports.', category: 'time', level: 'A1' },
  { id: 'time-24', german: 'Freitag', turkish: 'Cuma', english: 'Friday', article: 'der', partOfSpeech: 'noun', plural: 'Freitage', emoji: '🎉', collocations: ['am Freitag', 'jeden Freitag', 'freitags'], exampleSentence: 'Am Freitag ist das Wochenende nah.', exampleTranslation: 'Cuma günü hafta sonu yakındır.', exampleTranslationEn: 'On Friday the weekend is near.', category: 'time', level: 'A1' },
  { id: 'time-25', german: 'Samstag', turkish: 'Cumartesi', english: 'Saturday', article: 'der', partOfSpeech: 'noun', plural: 'Samstage', emoji: '🛒', synonyms: ['Sonnabend'], collocations: ['am Samstag', 'jeden Samstag', 'samstags'], exampleSentence: 'Am Samstag gehe ich einkaufen.', exampleTranslation: 'Cumartesi alışverişe giderim.', exampleTranslationEn: 'On Saturday I go shopping.', category: 'time', level: 'A1' },
  { id: 'time-26', german: 'Sonntag', turkish: 'Pazar', english: 'Sunday', article: 'der', partOfSpeech: 'noun', plural: 'Sonntage', emoji: '☀️', collocations: ['am Sonntag', 'jeden Sonntag', 'sonntags'], exampleSentence: 'Am Sonntag ruhen wir uns aus.', exampleTranslation: 'Pazar günü dinleniriz.', exampleTranslationEn: 'On Sunday we rest.', category: 'time', level: 'A1' },
  { id: 'time-27', german: 'spät', turkish: 'geç', english: 'late', article: null, partOfSpeech: 'adjective', emoji: '🌃', antonyms: ['früh'], collocations: ['zu spät kommen', 'es ist spät', 'spät abends'], exampleSentence: 'Es ist schon spät.', exampleTranslation: 'Çoktan geç oldu.', exampleTranslationEn: 'It is already late.', category: 'time', level: 'A1' },
  { id: 'time-28', german: 'Wochenende', turkish: 'hafta sonu', english: 'weekend', article: 'das', partOfSpeech: 'noun', plural: 'Wochenenden', emoji: '🎊', collocations: ['am Wochenende', 'schönes Wochenende', 'langes Wochenende'], exampleSentence: 'Am Wochenende schlafe ich lange.', exampleTranslation: 'Hafta sonunda uzun uyurum.', exampleTranslationEn: 'On the weekend I sleep in.', category: 'time', level: 'A1' },
  { id: 'time-29', german: 'Mittag', turkish: 'öğle', english: 'noon/midday', article: 'der', partOfSpeech: 'noun', plural: 'Mittage', emoji: '☀️', collocations: ['am Mittag', 'zu Mittag essen', 'gegen Mittag'], exampleSentence: 'Um Mittag essen wir zusammen.', exampleTranslation: 'Öğleyin birlikte yemek yeriz.', exampleTranslationEn: 'At noon we eat together.', category: 'time', level: 'A1' },
  { id: 'time-30', german: 'Sekunde', turkish: 'saniye', english: 'second', article: 'die', partOfSpeech: 'noun', plural: 'Sekunden', emoji: '⏱️', collocations: ['eine Sekunde bitte', 'in Sekundenschnelle', 'jede Sekunde'], exampleSentence: 'Warte eine Sekunde!', exampleTranslation: 'Bir saniye bekle!', exampleTranslationEn: 'Wait a second!', category: 'time', level: 'A1' },
  // A2 - Months, seasons, dates, schedule basics
  { id: 'time-31', german: 'Januar', turkish: 'Ocak', english: 'January', article: 'der', partOfSpeech: 'noun', emoji: '❄️', collocations: ['im Januar', 'Anfang Januar', 'Ende Januar'], exampleSentence: 'Im Januar ist es sehr kalt.', exampleTranslation: 'Ocak ayında hava çok soğuktur.', exampleTranslationEn: 'In January it is very cold.', category: 'time', level: 'A2' },
  { id: 'time-32', german: 'Februar', turkish: 'Şubat', english: 'February', article: 'der', partOfSpeech: 'noun', emoji: '💕', collocations: ['im Februar', 'Anfang Februar', 'Mitte Februar'], exampleSentence: 'Im Februar feiern wir Valentinstag.', exampleTranslation: 'Şubat ayında Sevgililer Günü\'nü kutlarız.', exampleTranslationEn: 'In February we celebrate Valentine\'s Day.', category: 'time', level: 'A2' },
  { id: 'time-33', german: 'März', turkish: 'Mart', english: 'March', article: 'der', partOfSpeech: 'noun', emoji: '🌱', collocations: ['im März', 'Anfang März', 'Ende März'], exampleSentence: 'Im März beginnt der Frühling.', exampleTranslation: 'Mart ayında bahar başlar.', exampleTranslationEn: 'In March spring begins.', category: 'time', level: 'A2' },
  { id: 'time-34', german: 'April', turkish: 'Nisan', english: 'April', article: 'der', partOfSpeech: 'noun', emoji: '🌧️', collocations: ['im April', 'Anfang April', 'April, April!'], exampleSentence: 'Der April macht, was er will.', exampleTranslation: 'Nisan ayı istediğini yapar.', exampleTranslationEn: 'April does what it wants.', category: 'time', level: 'A2' },
  { id: 'time-35', german: 'Mai', turkish: 'Mayıs', english: 'May', article: 'der', partOfSpeech: 'noun', emoji: '🌸', collocations: ['im Mai', 'Anfang Mai', 'der erste Mai'], exampleSentence: 'Im Mai blühen die Blumen.', exampleTranslation: 'Mayıs ayında çiçekler açar.', exampleTranslationEn: 'In May the flowers bloom.', category: 'time', level: 'A2' },
  { id: 'time-36', german: 'Juni', turkish: 'Haziran', english: 'June', article: 'der', partOfSpeech: 'noun', emoji: '☀️', collocations: ['im Juni', 'Anfang Juni', 'Ende Juni'], exampleSentence: 'Im Juni beginnen die Sommerferien.', exampleTranslation: 'Haziran ayında yaz tatili başlar.', exampleTranslationEn: 'In June the summer holidays begin.', category: 'time', level: 'A2' },
  { id: 'time-37', german: 'Juli', turkish: 'Temmuz', english: 'July', article: 'der', partOfSpeech: 'noun', emoji: '🏖️', collocations: ['im Juli', 'Anfang Juli', 'Mitte Juli'], exampleSentence: 'Im Juli fahren wir in den Urlaub.', exampleTranslation: 'Temmuz ayında tatile gideriz.', exampleTranslationEn: 'In July we go on vacation.', category: 'time', level: 'A2' },
  { id: 'time-38', german: 'August', turkish: 'Ağustos', english: 'August', article: 'der', partOfSpeech: 'noun', emoji: '🌻', collocations: ['im August', 'Anfang August', 'Ende August'], exampleSentence: 'Im August ist es am heißesten.', exampleTranslation: 'Ağustos ayında hava en sıcaktır.', exampleTranslationEn: 'In August it is the hottest.', category: 'time', level: 'A2' },
  { id: 'time-39', german: 'September', turkish: 'Eylül', english: 'September', article: 'der', partOfSpeech: 'noun', emoji: '🍂', collocations: ['im September', 'Anfang September', 'Ende September'], exampleSentence: 'Im September beginnt die Schule wieder.', exampleTranslation: 'Eylül ayında okul tekrar başlar.', exampleTranslationEn: 'In September school starts again.', category: 'time', level: 'A2' },
  { id: 'time-40', german: 'Oktober', turkish: 'Ekim', english: 'October', article: 'der', partOfSpeech: 'noun', emoji: '🎃', collocations: ['im Oktober', 'Anfang Oktober', 'Ende Oktober'], exampleSentence: 'Im Oktober ist das Oktoberfest.', exampleTranslation: 'Ekim ayında Oktoberfest vardır.', exampleTranslationEn: 'In October there is the Oktoberfest.', category: 'time', level: 'A2' },
  { id: 'time-41', german: 'November', turkish: 'Kasım', english: 'November', article: 'der', partOfSpeech: 'noun', emoji: '🍁', collocations: ['im November', 'Anfang November', 'Ende November'], exampleSentence: 'Im November wird es früh dunkel.', exampleTranslation: 'Kasım ayında erken karanlık olur.', exampleTranslationEn: 'In November it gets dark early.', category: 'time', level: 'A2' },
  { id: 'time-42', german: 'Dezember', turkish: 'Aralık', english: 'December', article: 'der', partOfSpeech: 'noun', emoji: '🎄', collocations: ['im Dezember', 'Anfang Dezember', 'Ende Dezember'], exampleSentence: 'Im Dezember feiern wir Weihnachten.', exampleTranslation: 'Aralık ayında Noel kutlarız.', exampleTranslationEn: 'In December we celebrate Christmas.', category: 'time', level: 'A2' },
  { id: 'time-43', german: 'Frühling', turkish: 'ilkbahar', english: 'spring', article: 'der', partOfSpeech: 'noun', plural: 'Frühlinge', emoji: '🌷', synonyms: ['Frühjahr'], collocations: ['im Frühling', 'Frühlingsanfang', 'Frühlingsblumen'], exampleSentence: 'Im Frühling werden die Tage länger.', exampleTranslation: 'İlkbaharda günler uzar.', exampleTranslationEn: 'In spring the days get longer.', category: 'time', level: 'A2' },
  { id: 'time-44', german: 'Sommer', turkish: 'yaz', english: 'summer', article: 'der', partOfSpeech: 'noun', plural: 'Sommer', emoji: '☀️', antonyms: ['Winter'], collocations: ['im Sommer', 'Sommerferien', 'letzten Sommer'], exampleSentence: 'Im Sommer gehen wir schwimmen.', exampleTranslation: 'Yazın yüzmeye gideriz.', exampleTranslationEn: 'In summer we go swimming.', category: 'time', level: 'A2' },
  { id: 'time-45', german: 'Herbst', turkish: 'sonbahar', english: 'autumn/fall', article: 'der', partOfSpeech: 'noun', plural: 'Herbste', emoji: '🍂', collocations: ['im Herbst', 'Herbstanfang', 'Herbstferien'], exampleSentence: 'Im Herbst fallen die Blätter.', exampleTranslation: 'Sonbaharda yapraklar düşer.', exampleTranslationEn: 'In autumn the leaves fall.', category: 'time', level: 'A2' },
  { id: 'time-46', german: 'Winter', turkish: 'kış', english: 'winter', article: 'der', partOfSpeech: 'noun', plural: 'Winter', emoji: '⛄', antonyms: ['Sommer'], collocations: ['im Winter', 'Winteranfang', 'Winterferien'], exampleSentence: 'Im Winter schneit es oft.', exampleTranslation: 'Kışın sık sık kar yağar.', exampleTranslationEn: 'In winter it often snows.', category: 'time', level: 'A2' },
  { id: 'time-47', german: 'Datum', turkish: 'tarih', english: 'date', article: 'das', partOfSpeech: 'noun', plural: 'Daten', emoji: '📅', collocations: ['welches Datum', 'das heutige Datum', 'Datum und Uhrzeit'], exampleSentence: 'Welches Datum haben wir heute?', exampleTranslation: 'Bugün tarih ne?', exampleTranslationEn: 'What date is it today?', category: 'time', level: 'A2' },
  { id: 'time-48', german: 'Kalender', turkish: 'takvim', english: 'calendar', article: 'der', partOfSpeech: 'noun', plural: 'Kalender', emoji: '🗓️', collocations: ['im Kalender', 'den Kalender prüfen', 'Kalender eintragen'], exampleSentence: 'Ich schaue in meinen Kalender.', exampleTranslation: 'Takvimime bakıyorum.', exampleTranslationEn: 'I look at my calendar.', category: 'time', level: 'A2' },
  { id: 'time-49', german: 'Geburtstag', turkish: 'doğum günü', english: 'birthday', article: 'der', partOfSpeech: 'noun', plural: 'Geburtstage', emoji: '🎂', collocations: ['alles Gute zum Geburtstag', 'Geburtstag feiern', 'am Geburtstag'], exampleSentence: 'Mein Geburtstag ist im Mai.', exampleTranslation: 'Doğum günüm Mayıs ayında.', exampleTranslationEn: 'My birthday is in May.', category: 'time', level: 'A2' },
  { id: 'time-50', german: 'Feiertag', turkish: 'resmi tatil', english: 'public holiday', article: 'der', partOfSpeech: 'noun', plural: 'Feiertage', emoji: '🎉', collocations: ['gesetzlicher Feiertag', 'an Feiertagen', 'schöne Feiertage'], exampleSentence: 'Am Feiertag bleiben die Geschäfte geschlossen.', exampleTranslation: 'Resmi tatilde dükkanlar kapalı kalır.', exampleTranslationEn: 'On public holidays the shops stay closed.', category: 'time', level: 'A2' },
  { id: 'time-51', german: 'Ferien', turkish: 'tatil', english: 'holidays/vacation', article: 'die (pl)', partOfSpeech: 'noun', emoji: '✈️', collocations: ['in den Ferien', 'Sommerferien', 'Ferien haben'], exampleSentence: 'In den Ferien fahren wir ans Meer.', exampleTranslation: 'Tatilde denize gideriz.', exampleTranslationEn: 'During the holidays we go to the sea.', category: 'time', level: 'A2' },
  { id: 'time-52', german: 'bald', turkish: 'yakında', english: 'soon', article: null, partOfSpeech: 'adverb', emoji: '⏩', collocations: ['bis bald', 'bald darauf', 'so bald wie möglich'], exampleSentence: 'Der Bus kommt bald.', exampleTranslation: 'Otobüs yakında gelecek.', exampleTranslationEn: 'The bus is coming soon.', category: 'time', level: 'A2' },
  { id: 'time-53', german: 'später', turkish: 'sonra / daha sonra', english: 'later', article: null, partOfSpeech: 'adverb', emoji: '⏭️', antonyms: ['früher', 'vorher'], collocations: ['bis später', 'etwas später', 'früher oder später'], exampleSentence: 'Ich rufe dich später an.', exampleTranslation: 'Seni sonra ararım.', exampleTranslationEn: 'I will call you later.', category: 'time', level: 'A2' },
  { id: 'time-54', german: 'Viertel', turkish: 'çeyrek', english: 'quarter', article: 'das', partOfSpeech: 'noun', plural: 'Viertel', emoji: '🕐', collocations: ['Viertel vor', 'Viertel nach', 'eine Viertelstunde'], exampleSentence: 'Es ist Viertel nach drei.', exampleTranslation: 'Saat üçü çeyrek geçiyor.', exampleTranslationEn: 'It is a quarter past three.', category: 'time', level: 'A2' },
  { id: 'time-55', german: 'halb', turkish: 'yarım / buçuk', english: 'half', article: null, partOfSpeech: 'adjective', emoji: '🕧', collocations: ['halb drei', 'eine halbe Stunde', 'halb so viel'], exampleSentence: 'Wir treffen uns um halb vier.', exampleTranslation: 'Üç buçukta buluşuyoruz.', exampleTranslationEn: 'We meet at half past three.', category: 'time', level: 'A2' },
  // B1 - Scheduling, frequency
  {
    id: 'time-b1-1',
    german: 'der Termin',
    turkish: 'randevu',
    english: 'appointment',
    article: 'der',
    plural: 'Termine',
    partOfSpeech: 'noun',
    exampleSentence: 'Ich muss einen Termin beim Arzt vereinbaren.',
    exampleTranslation: 'Doktorda bir randevu almam gerekiyor.',
    exampleTranslationEn: 'I need to make an appointment with the doctor.',
    category: 'time',
    level: 'B1',
    tags: ['scheduling', 'planning'],
  },
  {
    id: 'time-b1-2',
    german: 'regelmäßig',
    turkish: 'düzenli olarak',
    english: 'regularly',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Er geht regelmäßig ins Fitnessstudio.',
    exampleTranslation: 'Düzenli olarak spor salonuna gider.',
    exampleTranslationEn: 'He goes to the gym regularly.',
    category: 'time',
    level: 'B1',
    tags: ['frequency', 'routine'],
  },
  {
    id: 'time-b1-3',
    german: 'gelegentlich',
    turkish: 'ara sıra / zaman zaman',
    english: 'occasionally',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Gelegentlich gehe ich ins Theater.',
    exampleTranslation: 'Ara sıra tiyatroya giderim.',
    exampleTranslationEn: 'Occasionally I go to the theater.',
    category: 'time',
    level: 'B1',
    tags: ['frequency', 'occasional'],
  },
  {
    id: 'time-b1-4',
    german: 'der Zeitraum',
    turkish: 'süre / dönem',
    english: 'period of time',
    article: 'der',
    plural: 'Zeiträume',
    partOfSpeech: 'noun',
    exampleSentence: 'In diesem Zeitraum hat sich viel verändert.',
    exampleTranslation: 'Bu süre zarfında çok şey değişti.',
    exampleTranslationEn: 'A lot has changed in this period of time.',
    category: 'time',
    level: 'B1',
    tags: ['duration', 'planning'],
  },
  {
    id: 'time-b1-5',
    german: 'verschieben',
    turkish: 'ertelemek',
    english: 'to postpone / to reschedule',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Wir müssen den Termin auf nächste Woche verschieben.',
    exampleTranslation: 'Randevuyu gelecek haftaya ertelememiz gerekiyor.',
    exampleTranslationEn: 'We need to postpone the appointment to next week.',
    category: 'time',
    level: 'B1',
    tags: ['scheduling', 'change'],
  },
  {
    id: 'time-b1-6',
    german: 'pünktlich',
    turkish: 'dakik / zamanında',
    english: 'punctual / on time',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Bitte seien Sie pünktlich zum Unterricht.',
    exampleTranslation: 'Lütfen derse zamanında gelin.',
    exampleTranslationEn: 'Please be on time for class.',
    category: 'time',
    level: 'B1',
    tags: ['punctuality', 'scheduling'],
  },
  {
    id: 'time-b1-7',
    german: 'dauern',
    turkish: 'sürmek',
    english: 'to last / to take (time)',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Die Besprechung dauert ungefähr eine Stunde.',
    exampleTranslation: 'Toplantı yaklaşık bir saat sürüyor.',
    exampleTranslationEn: 'The meeting lasts about one hour.',
    category: 'time',
    level: 'B1',
    tags: ['duration', 'time'],
  },
  {
    id: 'time-b1-8',
    german: 'die Frist',
    turkish: 'son tarih / süre',
    english: 'deadline / time limit',
    article: 'die',
    plural: 'Fristen',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Frist für die Bewerbung endet am Freitag.',
    exampleTranslation: 'Başvuru için son tarih Cuma günü bitiyor.',
    exampleTranslationEn: 'The deadline for the application ends on Friday.',
    category: 'time',
    level: 'B1',
    tags: ['deadline', 'scheduling'],
  },
  {
    id: 'time-b1-9',
    german: 'inzwischen',
    turkish: 'bu arada / artık',
    english: 'meanwhile / in the meantime',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Inzwischen hat er eine neue Stelle gefunden.',
    exampleTranslation: 'Bu arada yeni bir iş buldu.',
    exampleTranslationEn: 'In the meantime, he found a new job.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'sequence'],
  },
  {
    id: 'time-b1-10',
    german: 'vorher',
    turkish: 'önceden / daha önce',
    english: 'before / beforehand',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Bitte ruf mich vorher an.',
    exampleTranslation: 'Lütfen önceden beni ara.',
    exampleTranslationEn: 'Please call me beforehand.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'sequence'],
  },
  // B1 - Additional scheduling, time expressions
  {
    id: 'time-b1-11',
    german: 'Zeitplan',
    turkish: 'zaman çizelgesi / program',
    english: 'schedule / timetable',
    article: 'der',
    plural: 'Zeitpläne',
    partOfSpeech: 'noun',
    emoji: '📋',
    collocations: ['den Zeitplan einhalten', 'nach Zeitplan', 'einen Zeitplan erstellen'],
    exampleSentence: 'Wir liegen gut im Zeitplan.',
    exampleTranslation: 'Programa göre iyi gidiyoruz.',
    exampleTranslationEn: 'We are on schedule.',
    category: 'time',
    level: 'B1',
    tags: ['scheduling', 'planning'],
  },
  {
    id: 'time-b1-12',
    german: 'Verspätung',
    turkish: 'gecikme / rötar',
    english: 'delay',
    article: 'die',
    plural: 'Verspätungen',
    partOfSpeech: 'noun',
    emoji: '⏰',
    collocations: ['Verspätung haben', 'mit Verspätung', 'ohne Verspätung'],
    exampleSentence: 'Der Zug hat zwanzig Minuten Verspätung.',
    exampleTranslation: 'Tren yirmi dakika gecikmiş.',
    exampleTranslationEn: 'The train is twenty minutes late.',
    category: 'time',
    level: 'B1',
    tags: ['delay', 'transport'],
  },
  {
    id: 'time-b1-13',
    german: 'Zeitpunkt',
    turkish: 'an / zaman',
    english: 'point in time / moment',
    article: 'der',
    plural: 'Zeitpunkte',
    partOfSpeech: 'noun',
    emoji: '📌',
    collocations: ['zum richtigen Zeitpunkt', 'zu diesem Zeitpunkt', 'der genaue Zeitpunkt'],
    exampleSentence: 'Das ist nicht der richtige Zeitpunkt dafür.',
    exampleTranslation: 'Bunun için doğru an değil.',
    exampleTranslationEn: 'This is not the right time for that.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'moment'],
  },
  {
    id: 'time-b1-14',
    german: 'nachher',
    turkish: 'sonra / daha sonra',
    english: 'afterwards / later',
    article: null,
    partOfSpeech: 'adverb',
    emoji: '⏭️',
    synonyms: ['danach', 'anschließend'],
    antonyms: ['vorher'],
    collocations: ['bis nachher', 'kurz nachher', 'gleich nachher'],
    exampleSentence: 'Wir gehen nachher ins Kino.',
    exampleTranslation: 'Sonra sinemaya gideceğiz.',
    exampleTranslationEn: 'We will go to the cinema afterwards.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'sequence'],
  },
  {
    id: 'time-b1-15',
    german: 'solange',
    turkish: 'sürece / olduğu müddetçe',
    english: 'as long as',
    article: null,
    partOfSpeech: 'conjunction',
    emoji: '⏳',
    collocations: ['solange wie', 'solange es dauert', 'solange ich kann'],
    exampleSentence: 'Solange es regnet, bleiben wir drinnen.',
    exampleTranslation: 'Yağmur yağdığı sürece içeride kalırız.',
    exampleTranslationEn: 'As long as it rains, we stay inside.',
    category: 'time',
    level: 'B1',
    tags: ['conjunction', 'duration'],
  },
  {
    id: 'time-b1-16',
    german: 'Jahreszeit',
    turkish: 'mevsim',
    english: 'season',
    article: 'die',
    plural: 'Jahreszeiten',
    partOfSpeech: 'noun',
    emoji: '🍃',
    collocations: ['vier Jahreszeiten', 'die schönste Jahreszeit', 'je nach Jahreszeit'],
    exampleSentence: 'Welche Jahreszeit magst du am liebsten?',
    exampleTranslation: 'En çok hangi mevsimi seviyorsun?',
    exampleTranslationEn: 'Which season do you like the most?',
    category: 'time',
    level: 'B1',
    tags: ['seasons', 'time'],
  },
  {
    id: 'time-b1-17',
    german: 'Vergangenheit',
    turkish: 'geçmiş',
    english: 'past',
    article: 'die',
    partOfSpeech: 'noun',
    emoji: '⏪',
    antonyms: ['Zukunft', 'Gegenwart'],
    collocations: ['in der Vergangenheit', 'der Vergangenheit angehören', 'aus der Vergangenheit'],
    exampleSentence: 'In der Vergangenheit war alles anders.',
    exampleTranslation: 'Geçmişte her şey farklıydı.',
    exampleTranslationEn: 'In the past everything was different.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'past'],
  },
  {
    id: 'time-b1-18',
    german: 'Zukunft',
    turkish: 'gelecek',
    english: 'future',
    article: 'die',
    partOfSpeech: 'noun',
    emoji: '🔮',
    antonyms: ['Vergangenheit'],
    collocations: ['in Zukunft', 'die nahe Zukunft', 'Zukunftspläne'],
    exampleSentence: 'In Zukunft möchte ich im Ausland leben.',
    exampleTranslation: 'Gelecekte yurt dışında yaşamak istiyorum.',
    exampleTranslationEn: 'In the future I would like to live abroad.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'future'],
  },
  {
    id: 'time-b1-19',
    german: 'Gegenwart',
    turkish: 'şimdiki zaman / bugün',
    english: 'present',
    article: 'die',
    partOfSpeech: 'noun',
    emoji: '⏺️',
    antonyms: ['Vergangenheit', 'Zukunft'],
    collocations: ['in der Gegenwart', 'die Gegenwart genießen'],
    exampleSentence: 'Man sollte in der Gegenwart leben.',
    exampleTranslation: 'İnsan şimdiki zamanda yaşamalı.',
    exampleTranslationEn: 'One should live in the present.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'present'],
  },
  {
    id: 'time-b1-20',
    german: 'Jahrzehnt',
    turkish: 'on yıl',
    english: 'decade',
    article: 'das',
    plural: 'Jahrzehnte',
    partOfSpeech: 'noun',
    emoji: '🔟',
    collocations: ['im letzten Jahrzehnt', 'über Jahrzehnte', 'ein ganzes Jahrzehnt'],
    exampleSentence: 'Im letzten Jahrzehnt hat sich viel verändert.',
    exampleTranslation: 'Son on yılda çok şey değişti.',
    exampleTranslationEn: 'A lot has changed in the last decade.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'period'],
  },
  {
    id: 'time-b1-21',
    german: 'Wecker',
    turkish: 'çalar saat',
    english: 'alarm clock',
    article: 'der',
    plural: 'Wecker',
    partOfSpeech: 'noun',
    emoji: '⏰',
    collocations: ['den Wecker stellen', 'der Wecker klingelt', 'den Wecker ausschalten'],
    exampleSentence: 'Ich stelle meinen Wecker auf sechs Uhr.',
    exampleTranslation: 'Çalar saatimi altıya kuruyorum.',
    exampleTranslationEn: 'I set my alarm clock for six o\'clock.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'daily routine'],
  },
  {
    id: 'time-b1-22',
    german: 'Countdown',
    turkish: 'geri sayım',
    english: 'countdown',
    article: 'der',
    plural: 'Countdowns',
    partOfSpeech: 'noun',
    emoji: '⏳',
    collocations: ['der Countdown läuft', 'Countdown starten', 'den Countdown beginnen'],
    exampleSentence: 'Der Countdown bis Silvester hat begonnen.',
    exampleTranslation: 'Yılbaşına geri sayım başladı.',
    exampleTranslationEn: 'The countdown to New Year\'s Eve has started.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'event'],
  },
  {
    id: 'time-b1-23',
    german: 'Eile',
    turkish: 'acele',
    english: 'hurry / rush',
    article: 'die',
    partOfSpeech: 'noun',
    emoji: '🏃',
    collocations: ['in Eile sein', 'keine Eile', 'Eile haben'],
    exampleSentence: 'Ich bin in Eile, der Termin ist um zehn.',
    exampleTranslation: 'Acelemiz var, randevu saat onda.',
    exampleTranslationEn: 'I am in a hurry, the appointment is at ten.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'urgency'],
  },
  {
    id: 'time-b1-24',
    german: 'Stundenplan',
    turkish: 'ders programı',
    english: 'timetable / class schedule',
    article: 'der',
    plural: 'Stundenpläne',
    partOfSpeech: 'noun',
    emoji: '📋',
    collocations: ['den Stundenplan anschauen', 'im Stundenplan', 'Stundenplan ändern'],
    exampleSentence: 'Der neue Stundenplan beginnt nächste Woche.',
    exampleTranslation: 'Yeni ders programı gelecek hafta başlıyor.',
    exampleTranslationEn: 'The new timetable starts next week.',
    category: 'time',
    level: 'B1',
    tags: ['scheduling', 'school'],
  },
  {
    id: 'time-b1-25',
    german: 'Moment',
    turkish: 'an / kısa süre',
    english: 'moment',
    article: 'der',
    plural: 'Momente',
    partOfSpeech: 'noun',
    emoji: '✨',
    synonyms: ['Augenblick'],
    collocations: ['einen Moment bitte', 'im Moment', 'im richtigen Moment'],
    exampleSentence: 'Einen Moment bitte, ich komme gleich.',
    exampleTranslation: 'Bir an lütfen, hemen geliyorum.',
    exampleTranslationEn: 'One moment please, I am coming right away.',
    category: 'time',
    level: 'B1',
    tags: ['time', 'instant'],
  },
  // B2 - Advanced time concepts, temporal expressions
  {
    id: 'time-b2-1',
    german: 'die Frist',
    turkish: 'son tarih / vade',
    english: 'deadline',
    article: 'die',
    plural: 'Fristen',
    partOfSpeech: 'noun',
    exampleSentence: 'Wenn Sie die Frist versäumen, müssen Sie mit Konsequenzen rechnen.',
    exampleTranslation: 'Son tarihi kaçırırsanız, sonuçlarıyla yüzleşmeniz gerekir.',
    exampleTranslationEn: 'If you miss the deadline, you must face the consequences.',
    category: 'time',
    level: 'B2',
    tags: ['deadline', 'formal'],
  },
  {
    id: 'time-b2-2',
    german: 'der Zeitraum',
    turkish: 'zaman dilimi / dönem',
    english: 'time period',
    article: 'der',
    plural: 'Zeiträume',
    partOfSpeech: 'noun',
    exampleSentence: 'Der Zeitraum zwischen Bewerbung und Einstellung beträgt oft mehrere Wochen.',
    exampleTranslation: 'Başvuru ile işe alım arasındaki zaman dilimi genellikle birkaç haftadır.',
    exampleTranslationEn: 'The time period between application and hiring is often several weeks.',
    category: 'time',
    level: 'B2',
    tags: ['duration', 'planning'],
  },
  {
    id: 'time-b2-3',
    german: 'vorübergehend',
    turkish: 'geçici',
    english: 'temporary',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Die Straße ist wegen Bauarbeiten vorübergehend gesperrt.',
    exampleTranslation: 'Yol inşaat çalışmaları nedeniyle geçici olarak kapatıldı.',
    exampleTranslationEn: 'The road is temporarily closed due to construction work.',
    category: 'time',
    level: 'B2',
    tags: ['temporary', 'duration'],
  },
  {
    id: 'time-b2-4',
    german: 'gleichzeitig',
    turkish: 'eş zamanlı / aynı anda',
    english: 'simultaneous',
    article: null,
    partOfSpeech: 'adjective',
    exampleSentence: 'Es ist schwierig, gleichzeitig zu arbeiten und zu studieren.',
    exampleTranslation: 'Aynı anda hem çalışmak hem de okumak zordur.',
    exampleTranslationEn: 'It is difficult to work and study simultaneously.',
    category: 'time',
    level: 'B2',
    tags: ['simultaneous', 'multitasking'],
  },
  {
    id: 'time-b2-5',
    german: 'inzwischen',
    turkish: 'bu arada / bu sırada',
    english: 'meanwhile',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Die Technologie hat sich inzwischen rasant weiterentwickelt.',
    exampleTranslation: 'Teknoloji bu arada hızla ilerledi.',
    exampleTranslationEn: 'Technology has meanwhile advanced rapidly.',
    category: 'time',
    level: 'B2',
    tags: ['meanwhile', 'progression'],
  },
  {
    id: 'time-b2-6',
    german: 'die Dauer',
    turkish: 'süre',
    english: 'duration',
    article: 'die',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Dauer des Visumsverfahrens hängt vom jeweiligen Land ab.',
    exampleTranslation: 'Vize işlemlerinin süresi ilgili ülkeye bağlıdır.',
    exampleTranslationEn: 'The duration of the visa process depends on the respective country.',
    category: 'time',
    level: 'B2',
    tags: ['duration', 'formal'],
  },
  {
    id: 'time-b2-7',
    german: 'allmählich',
    turkish: 'yavaş yavaş / giderek',
    english: 'gradually',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Die Situation hat sich allmählich verbessert.',
    exampleTranslation: 'Durum yavaş yavaş iyileşti.',
    exampleTranslationEn: 'The situation has gradually improved.',
    category: 'time',
    level: 'B2',
    tags: ['gradual', 'progression'],
  },
  {
    id: 'time-b2-8',
    german: 'heutzutage',
    turkish: 'günümüzde / bugünlerde',
    english: 'nowadays',
    article: null,
    partOfSpeech: 'adverb',
    exampleSentence: 'Heutzutage ist es üblich, von zu Hause aus zu arbeiten.',
    exampleTranslation: 'Günümüzde evden çalışmak yaygın hale geldi.',
    exampleTranslationEn: 'Nowadays it is common to work from home.',
    category: 'time',
    level: 'B2',
    tags: ['modern', 'present'],
  },
  {
    id: 'time-b2-9',
    german: 'die Epoche',
    turkish: 'çağ / dönem',
    english: 'epoch',
    article: 'die',
    plural: 'Epochen',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Romantik war eine bedeutende Epoche der deutschen Literatur.',
    exampleTranslation: 'Romantizm, Alman edebiyatının önemli bir dönemiydi.',
    exampleTranslationEn: 'Romanticism was a significant epoch of German literature.',
    category: 'time',
    level: 'B2',
    tags: ['history', 'era'],
  },
  {
    id: 'time-b2-10',
    german: 'der Zeitgenosse',
    turkish: 'çağdaş (kişi)',
    english: 'contemporary',
    article: 'der',
    plural: 'Zeitgenossen',
    partOfSpeech: 'noun',
    exampleSentence: 'Goethe und Schiller waren Zeitgenossen und enge Freunde.',
    exampleTranslation: 'Goethe ve Schiller çağdaştı ve yakın arkadaştılar.',
    exampleTranslationEn: 'Goethe and Schiller were contemporaries and close friends.',
    category: 'time',
    level: 'B2',
    tags: ['history', 'person'],
  },
  // B2 - Additional advanced time concepts
  {
    id: 'time-b2-11',
    german: 'Zeitspanne',
    turkish: 'zaman aralığı',
    english: 'time span',
    article: 'die',
    plural: 'Zeitspannen',
    partOfSpeech: 'noun',
    emoji: '📏',
    collocations: ['eine kurze Zeitspanne', 'in dieser Zeitspanne', 'eine lange Zeitspanne'],
    exampleSentence: 'In einer so kurzen Zeitspanne kann man das nicht schaffen.',
    exampleTranslation: 'Bu kadar kısa bir zaman aralığında bunu başaramazsınız.',
    exampleTranslationEn: 'You cannot manage that in such a short time span.',
    category: 'time',
    level: 'B2',
    tags: ['duration', 'formal'],
  },
  {
    id: 'time-b2-12',
    german: 'befristet',
    turkish: 'süreli / belirli süreli',
    english: 'temporary / fixed-term',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '📝',
    antonyms: ['unbefristet'],
    collocations: ['befristeter Vertrag', 'befristete Stelle', 'zeitlich befristet'],
    exampleSentence: 'Sein Arbeitsvertrag ist auf zwei Jahre befristet.',
    exampleTranslation: 'İş sözleşmesi iki yıl sürelidir.',
    exampleTranslationEn: 'His employment contract is limited to two years.',
    category: 'time',
    level: 'B2',
    tags: ['contract', 'work'],
  },
  {
    id: 'time-b2-13',
    german: 'Zeitverschiebung',
    turkish: 'saat farkı',
    english: 'time difference / jet lag',
    article: 'die',
    plural: 'Zeitverschiebungen',
    partOfSpeech: 'noun',
    emoji: '🌍',
    collocations: ['die Zeitverschiebung beachten', 'wegen der Zeitverschiebung', 'trotz Zeitverschiebung'],
    exampleSentence: 'Die Zeitverschiebung zwischen Berlin und Tokio beträgt acht Stunden.',
    exampleTranslation: 'Berlin ve Tokyo arasındaki saat farkı sekiz saattir.',
    exampleTranslationEn: 'The time difference between Berlin and Tokyo is eight hours.',
    category: 'time',
    level: 'B2',
    tags: ['travel', 'time zones'],
  },
  {
    id: 'time-b2-14',
    german: 'vorläufig',
    turkish: 'geçici olarak / şimdilik',
    english: 'provisional / for the time being',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '⏸️',
    synonyms: ['vorübergehend', 'einstweilen'],
    collocations: ['vorläufige Ergebnisse', 'vorläufig geschlossen', 'ein vorläufiger Plan'],
    exampleSentence: 'Die vorläufigen Ergebnisse werden morgen veröffentlicht.',
    exampleTranslation: 'Geçici sonuçlar yarın yayınlanacak.',
    exampleTranslationEn: 'The provisional results will be published tomorrow.',
    category: 'time',
    level: 'B2',
    tags: ['temporary', 'formal'],
  },
  {
    id: 'time-b2-15',
    german: 'stets',
    turkish: 'her zaman / daima',
    english: 'always / constantly',
    article: null,
    partOfSpeech: 'adverb',
    emoji: '🔄',
    synonyms: ['immer', 'ständig'],
    collocations: ['stets bemüht', 'stets freundlich', 'stets pünktlich'],
    exampleSentence: 'Sie war stets eine zuverlässige Mitarbeiterin.',
    exampleTranslation: 'O her zaman güvenilir bir çalışan olmuştur.',
    exampleTranslationEn: 'She was always a reliable employee.',
    category: 'time',
    level: 'B2',
    tags: ['frequency', 'formal'],
  },
  {
    id: 'time-b2-16',
    german: 'Jahrhundert',
    turkish: 'yüzyıl',
    english: 'century',
    article: 'das',
    plural: 'Jahrhunderte',
    partOfSpeech: 'noun',
    emoji: '🏛️',
    collocations: ['im 21. Jahrhundert', 'Jahrhunderte lang', 'die Wende des Jahrhunderts'],
    exampleSentence: 'Im 20. Jahrhundert gab es zwei Weltkriege.',
    exampleTranslation: '20. yüzyılda iki dünya savaşı oldu.',
    exampleTranslationEn: 'In the 20th century there were two world wars.',
    category: 'time',
    level: 'B2',
    tags: ['history', 'period'],
  },
  {
    id: 'time-b2-17',
    german: 'Jahrtausend',
    turkish: 'bin yıl / milenyum',
    english: 'millennium',
    article: 'das',
    plural: 'Jahrtausende',
    partOfSpeech: 'noun',
    emoji: '🌐',
    collocations: ['das neue Jahrtausend', 'seit Jahrtausenden', 'Jahrtausendwende'],
    exampleSentence: 'Seit Jahrtausenden leben Menschen an diesem Fluss.',
    exampleTranslation: 'Binlerce yıldır insanlar bu nehrin kenarında yaşıyor.',
    exampleTranslationEn: 'For millennia people have lived along this river.',
    category: 'time',
    level: 'B2',
    tags: ['history', 'period'],
  },
  {
    id: 'time-b2-18',
    german: 'zeitgenössisch',
    turkish: 'çağdaş',
    english: 'contemporary',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🎨',
    collocations: ['zeitgenössische Kunst', 'zeitgenössische Literatur', 'zeitgenössische Musik'],
    exampleSentence: 'Das Museum zeigt zeitgenössische Kunst aus Europa.',
    exampleTranslation: 'Müze Avrupa\'dan çağdaş sanat sergiliyor.',
    exampleTranslationEn: 'The museum shows contemporary art from Europe.',
    category: 'time',
    level: 'B2',
    tags: ['art', 'modern'],
  },
  {
    id: 'time-b2-19',
    german: 'verzögern',
    turkish: 'geciktirmek / ertelemek',
    english: 'to delay',
    article: null,
    partOfSpeech: 'verb',
    emoji: '🐌',
    synonyms: ['hinauszögern', 'aufschieben'],
    collocations: ['den Prozess verzögern', 'sich verzögern', 'unnötig verzögern'],
    exampleSentence: 'Der Streik hat die Lieferung um drei Tage verzögert.',
    exampleTranslation: 'Grev teslimatı üç gün geciktirdi.',
    exampleTranslationEn: 'The strike delayed the delivery by three days.',
    category: 'time',
    level: 'B2',
    tags: ['delay', 'action'],
  },
  {
    id: 'time-b2-20',
    german: 'Fälligkeitsdatum',
    turkish: 'vade tarihi / son ödeme tarihi',
    english: 'due date',
    article: 'das',
    plural: 'Fälligkeitsdaten',
    partOfSpeech: 'noun',
    emoji: '📅',
    collocations: ['das Fälligkeitsdatum einhalten', 'vor dem Fälligkeitsdatum', 'nach dem Fälligkeitsdatum'],
    exampleSentence: 'Das Fälligkeitsdatum für die Rechnung ist der 15. März.',
    exampleTranslation: 'Faturanın vade tarihi 15 Mart.',
    exampleTranslationEn: 'The due date for the invoice is March 15th.',
    category: 'time',
    level: 'B2',
    tags: ['deadline', 'finance'],
  },
  {
    id: 'time-b2-21',
    german: 'unverzüglich',
    turkish: 'derhal / gecikmeksizin',
    english: 'immediately / without delay',
    article: null,
    partOfSpeech: 'adverb',
    emoji: '⚡',
    synonyms: ['sofort', 'umgehend'],
    collocations: ['unverzüglich handeln', 'unverzüglich melden', 'unverzüglich antworten'],
    exampleSentence: 'Bitte melden Sie sich unverzüglich bei der Verwaltung.',
    exampleTranslation: 'Lütfen derhal yönetime başvurun.',
    exampleTranslationEn: 'Please report to the administration immediately.',
    category: 'time',
    level: 'B2',
    tags: ['urgency', 'formal'],
  },
  {
    id: 'time-b2-22',
    german: 'ehemalig',
    turkish: 'eski / önceki',
    english: 'former',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🔙',
    collocations: ['ehemaliger Präsident', 'ehemalige Schüler', 'ehemalige Kollegen'],
    exampleSentence: 'Der ehemalige Bürgermeister lebt jetzt im Ausland.',
    exampleTranslation: 'Eski belediye başkanı şimdi yurt dışında yaşıyor.',
    exampleTranslationEn: 'The former mayor now lives abroad.',
    category: 'time',
    level: 'B2',
    tags: ['past', 'description'],
  },
  {
    id: 'time-b2-23',
    german: 'künftig',
    turkish: 'gelecekteki / bundan sonraki',
    english: 'future / from now on',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🔜',
    synonyms: ['zukünftig'],
    collocations: ['künftige Generationen', 'künftig vermeiden', 'der künftige Präsident'],
    exampleSentence: 'Künftig sollen alle Dokumente digital eingereicht werden.',
    exampleTranslation: 'Bundan sonra tüm belgeler dijital olarak sunulmalıdır.',
    exampleTranslationEn: 'From now on all documents should be submitted digitally.',
    category: 'time',
    level: 'B2',
    tags: ['future', 'formal'],
  },
  {
    id: 'time-b2-24',
    german: 'Zeitwende',
    turkish: 'dönüm noktası / çağ değişimi',
    english: 'turning point / change of era',
    article: 'die',
    plural: 'Zeitwenden',
    partOfSpeech: 'noun',
    emoji: '🔄',
    collocations: ['eine Zeitwende erleben', 'vor der Zeitwende', 'nach der Zeitwende'],
    exampleSentence: 'Die Digitalisierung markiert eine Zeitwende in der Arbeitswelt.',
    exampleTranslation: 'Dijitalleşme, iş dünyasında bir dönüm noktasını işaret ediyor.',
    exampleTranslationEn: 'Digitalization marks a turning point in the working world.',
    category: 'time',
    level: 'B2',
    tags: ['history', 'change'],
  },
  {
    id: 'time-b2-25',
    german: 'langfristig',
    turkish: 'uzun vadeli',
    english: 'long-term',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '📈',
    antonyms: ['kurzfristig'],
    collocations: ['langfristig planen', 'langfristige Ziele', 'langfristig denken'],
    exampleSentence: 'Wir brauchen eine langfristige Strategie für das Unternehmen.',
    exampleTranslation: 'Şirket için uzun vadeli bir stratejiye ihtiyacımız var.',
    exampleTranslationEn: 'We need a long-term strategy for the company.',
    category: 'time',
    level: 'B2',
    tags: ['planning', 'business'],
  },
];
