import { VocabularyWord } from '@/lib/types';

export const transportWords: VocabularyWord[] = [
  {
    id: 'transport-1',
    german: 'das Auto',
    turkish: 'Araba',
    english: 'Car',
    article: 'das',
    plural: 'Autos',
    partOfSpeech: 'noun',
    synonyms: ['Wagen', 'Fahrzeug', 'PKW'],
    collocations: ['Auto fahren', 'ein Auto kaufen'],
    emoji: '🚗',
    exampleSentence: 'Ich fahre mit dem Auto zur Arbeit.',
    exampleTranslation: 'İşe arabayla gidiyorum.',
    exampleTranslationEn: 'I drive to work by car.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-2',
    german: 'der Bus',
    turkish: 'Otobüs',
    english: 'Bus',
    article: 'der',
    plural: 'Busse',
    partOfSpeech: 'noun',
    synonyms: ['Linienbus', 'Reisebus'],
    collocations: ['den Bus nehmen', 'auf den Bus warten'],
    emoji: '🚌',
    exampleSentence: 'Der Bus kommt in fünf Minuten.',
    exampleTranslation: 'Otobüs beş dakika içinde gelecek.',
    exampleTranslationEn: 'The bus comes in five minutes.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-3',
    german: 'der Zug',
    turkish: 'Tren',
    english: 'Train',
    article: 'der',
    plural: 'Züge',
    partOfSpeech: 'noun',
    synonyms: ['Eisenbahn', 'Bahn'],
    collocations: ['mit dem Zug fahren', 'den Zug nehmen'],
    emoji: '🚂',
    exampleSentence: 'Der Zug nach Berlin fährt um 10 Uhr.',
    exampleTranslation: 'Berlin treni saat 10\'da kalkıyor.',
    exampleTranslationEn: 'The train to Berlin departs at 10 o\'clock.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-4',
    german: 'das Fahrrad',
    turkish: 'Bisiklet',
    english: 'Bicycle',
    article: 'das',
    plural: 'Fahrräder',
    partOfSpeech: 'noun',
    synonyms: ['Rad', 'Bike'],
    collocations: ['Fahrrad fahren', 'mit dem Fahrrad'],
    emoji: '🚲',
    exampleSentence: 'Ich fahre gerne Fahrrad.',
    exampleTranslation: 'Bisiklet sürmeyi seviyorum.',
    exampleTranslationEn: 'I like to ride a bicycle.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-5',
    german: 'das Flugzeug',
    turkish: 'Uçak',
    english: 'Airplane',
    article: 'das',
    plural: 'Flugzeuge',
    partOfSpeech: 'noun',
    synonyms: ['Flieger', 'Maschine'],
    collocations: ['mit dem Flugzeug fliegen', 'das Flugzeug landet'],
    emoji: '✈️',
    exampleSentence: 'Das Flugzeug startet in einer Stunde.',
    exampleTranslation: 'Uçak bir saat içinde kalkıyor.',
    exampleTranslationEn: 'The airplane departs in one hour.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-6',
    german: 'die Straßenbahn',
    turkish: 'Tramvay',
    english: 'Tram',
    article: 'die',
    plural: 'Straßenbahnen',
    partOfSpeech: 'noun',
    synonyms: ['Tram'],
    collocations: ['mit der Straßenbahn fahren', 'die Straßenbahn nehmen'],
    emoji: '🚃',
    exampleSentence: 'Die Straßenbahn fährt alle zehn Minuten.',
    exampleTranslation: 'Tramvay her on dakikada bir geliyor.',
    exampleTranslationEn: 'The tram runs every ten minutes.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-7',
    german: 'die U-Bahn',
    turkish: 'Metro',
    english: 'Subway',
    article: 'die',
    plural: 'U-Bahnen',
    partOfSpeech: 'noun',
    synonyms: ['Metro', 'Untergrundbahn'],
    collocations: ['mit der U-Bahn fahren', 'die U-Bahn nehmen'],
    emoji: '🚇',
    exampleSentence: 'Die U-Bahn ist schneller als der Bus.',
    exampleTranslation: 'Metro otobüsten daha hızlı.',
    exampleTranslationEn: 'The subway is faster than the bus.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-8',
    german: 'der Führerschein',
    turkish: 'Ehliyet',
    english: 'Driver\'s license',
    article: 'der',
    plural: 'Führerscheine',
    partOfSpeech: 'noun',
    synonyms: ['Fahrerlaubnis'],
    collocations: ['den Führerschein machen', 'den Führerschein verlieren'],
    emoji: '🪪',
    exampleSentence: 'Ich habe meinen Führerschein mit 18 gemacht.',
    exampleTranslation: '18 yaşında ehliyetimi aldım.',
    exampleTranslationEn: 'I got my driver\'s license at 18.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-9',
    german: 'die Fahrkarte',
    turkish: 'Bilet',
    english: 'Ticket',
    article: 'die',
    plural: 'Fahrkarten',
    partOfSpeech: 'noun',
    synonyms: ['Ticket', 'Fahrschein'],
    collocations: ['eine Fahrkarte kaufen', 'die Fahrkarte zeigen'],
    emoji: '🎫',
    exampleSentence: 'Wo kann ich eine Fahrkarte kaufen?',
    exampleTranslation: 'Nereden bilet alabilirim?',
    exampleTranslationEn: 'Where can I buy a ticket?',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-10',
    german: 'die Haltestelle',
    turkish: 'Durak',
    english: 'Stop (bus/tram)',
    article: 'die',
    plural: 'Haltestellen',
    partOfSpeech: 'noun',
    synonyms: ['Station'],
    collocations: ['an der Haltestelle warten', 'die nächste Haltestelle'],
    emoji: '🚏',
    exampleSentence: 'Die Haltestelle ist gleich um die Ecke.',
    exampleTranslation: 'Durak hemen köşede.',
    exampleTranslationEn: 'The stop is just around the corner.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-11',
    german: 'der Stau',
    turkish: 'Trafik sıkışıklığı',
    english: 'Traffic jam',
    article: 'der',
    plural: 'Staus',
    partOfSpeech: 'noun',
    synonyms: ['Verkehrsstau'],
    collocations: ['im Stau stehen', 'einen Stau umfahren'],
    emoji: '🚗',
    exampleSentence: 'Ich stehe seit einer Stunde im Stau.',
    exampleTranslation: 'Bir saattir trafikte bekliyorum.',
    exampleTranslationEn: 'I have been stuck in a traffic jam for an hour.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-12',
    german: 'umsteigen',
    turkish: 'Aktarma yapmak',
    english: 'To transfer / change',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['wechseln'],
    collocations: ['in Berlin umsteigen', 'einmal umsteigen'],
    emoji: '🔄',
    exampleSentence: 'Sie müssen in München umsteigen.',
    exampleTranslation: 'Münih\'te aktarma yapmanız gerekiyor.',
    exampleTranslationEn: 'You need to transfer in Munich.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-13',
    german: 'die Verspätung',
    turkish: 'Gecikme / Rötar',
    english: 'Delay',
    article: 'die',
    plural: 'Verspätungen',
    partOfSpeech: 'noun',
    synonyms: ['Verzögerung'],
    collocations: ['Verspätung haben', 'mit Verspätung ankommen'],
    emoji: '⏰',
    exampleSentence: 'Der Zug hat zwanzig Minuten Verspätung.',
    exampleTranslation: 'Trenin yirmi dakika rötarı var.',
    exampleTranslationEn: 'The train has a twenty-minute delay.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-14',
    german: 'die Autobahn',
    turkish: 'Otoyol',
    english: 'Highway / Motorway',
    article: 'die',
    plural: 'Autobahnen',
    partOfSpeech: 'noun',
    synonyms: ['Schnellstraße'],
    collocations: ['auf der Autobahn fahren', 'die Autobahn nehmen'],
    emoji: '🛣️',
    exampleSentence: 'Auf der deutschen Autobahn gibt es kein Tempolimit.',
    exampleTranslation: 'Alman otoyollarında hız sınırı yok.',
    exampleTranslationEn: 'There is no speed limit on the German highway.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-15',
    german: 'die Infrastruktur',
    turkish: 'Altyapı',
    english: 'Infrastructure',
    article: 'die',
    plural: 'Infrastrukturen',
    partOfSpeech: 'noun',
    synonyms: ['Verkehrsnetz'],
    collocations: ['die Infrastruktur ausbauen', 'öffentliche Infrastruktur'],
    emoji: '🏗️',
    exampleSentence: 'Die Infrastruktur in Deutschland ist gut ausgebaut.',
    exampleTranslation: 'Almanya\'daki altyapı iyi gelişmiş.',
    exampleTranslationEn: 'The infrastructure in Germany is well developed.',
    category: 'transport',
    level: 'B2',
  },
  {
    id: 'transport-16',
    german: 'die Verkehrswende',
    turkish: 'Ulaşım dönüşümü',
    english: 'Transport transition',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Mobilitätswende'],
    collocations: ['die Verkehrswende vorantreiben', 'nachhaltige Verkehrswende'],
    emoji: '🌱',
    exampleSentence: 'Die Verkehrswende ist ein wichtiges Thema in der Politik.',
    exampleTranslation: 'Ulaşım dönüşümü siyasette önemli bir konu.',
    exampleTranslationEn: 'The transport transition is an important political topic.',
    category: 'transport',
    level: 'B2',
  },
  {
    id: 'transport-17',
    german: 'das Taxi',
    turkish: 'Taksi',
    english: 'Taxi',
    article: 'das',
    plural: 'Taxis',
    partOfSpeech: 'noun',
    collocations: ['ein Taxi rufen', 'mit dem Taxi fahren'],
    emoji: '🚕',
    exampleSentence: 'Sollen wir ein Taxi rufen?',
    exampleTranslation: 'Taksi çağıralım mı?',
    exampleTranslationEn: 'Shall we call a taxi?',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-18',
    german: 'das Schiff',
    turkish: 'Gemi',
    english: 'Ship',
    article: 'das',
    plural: 'Schiffe',
    partOfSpeech: 'noun',
    synonyms: ['Boot', 'Dampfer'],
    collocations: ['mit dem Schiff fahren', 'ein großes Schiff'],
    emoji: '🚢',
    exampleSentence: 'Das Schiff fährt nach Griechenland.',
    exampleTranslation: 'Gemi Yunanistan\'a gidiyor.',
    exampleTranslationEn: 'The ship goes to Greece.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-19',
    german: 'das Motorrad',
    turkish: 'Motosiklet',
    english: 'Motorcycle',
    article: 'das',
    plural: 'Motorräder',
    partOfSpeech: 'noun',
    synonyms: ['Moped', 'Maschine'],
    collocations: ['Motorrad fahren', 'ein schnelles Motorrad'],
    emoji: '🏍️',
    exampleSentence: 'Er fährt gern Motorrad.',
    exampleTranslation: 'Motosiklet sürmeyi seviyor.',
    exampleTranslationEn: 'He likes to ride a motorcycle.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-20',
    german: 'der Bahnhof',
    turkish: 'Tren istasyonu',
    english: 'Train station',
    article: 'der',
    plural: 'Bahnhöfe',
    partOfSpeech: 'noun',
    synonyms: ['Station'],
    collocations: ['zum Bahnhof fahren', 'am Bahnhof ankommen'],
    emoji: '🚉',
    exampleSentence: 'Wie komme ich zum Bahnhof?',
    exampleTranslation: 'Tren istasyonuna nasıl gidebilirim?',
    exampleTranslationEn: 'How do I get to the train station?',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-21',
    german: 'der Flughafen',
    turkish: 'Havalimanı',
    english: 'Airport',
    article: 'der',
    plural: 'Flughäfen',
    partOfSpeech: 'noun',
    collocations: ['zum Flughafen fahren', 'am Flughafen ankommen'],
    emoji: '🛫',
    exampleSentence: 'Der Flughafen ist weit vom Stadtzentrum.',
    exampleTranslation: 'Havalimanı şehir merkezinden uzak.',
    exampleTranslationEn: 'The airport is far from the city center.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-22',
    german: 'der Hafen',
    turkish: 'Liman',
    english: 'Port / Harbor',
    article: 'der',
    plural: 'Häfen',
    partOfSpeech: 'noun',
    collocations: ['im Hafen anlegen', 'ein großer Hafen'],
    emoji: '⚓',
    exampleSentence: 'Das Schiff liegt im Hafen.',
    exampleTranslation: 'Gemi limanda.',
    exampleTranslationEn: 'The ship is in the port.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-23',
    german: 'der Hubschrauber',
    turkish: 'Helikopter',
    english: 'Helicopter',
    article: 'der',
    plural: 'Hubschrauber',
    partOfSpeech: 'noun',
    synonyms: ['Helikopter'],
    collocations: ['mit dem Hubschrauber fliegen', 'der Rettungshubschrauber'],
    emoji: '🚁',
    exampleSentence: 'Der Hubschrauber landete auf dem Dach.',
    exampleTranslation: 'Helikopter çatıya indi.',
    exampleTranslationEn: 'The helicopter landed on the roof.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-24',
    german: 'der Roller',
    turkish: 'Skuter',
    english: 'Scooter',
    article: 'der',
    plural: 'Roller',
    partOfSpeech: 'noun',
    synonyms: ['E-Roller', 'Tretroller'],
    collocations: ['Roller fahren', 'einen E-Roller mieten'],
    emoji: '🛴',
    exampleSentence: 'In der Stadt fahre ich oft mit dem Roller.',
    exampleTranslation: 'Şehirde sık sık skuterle gidiyorum.',
    exampleTranslationEn: 'In the city I often ride a scooter.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-25',
    german: 'die S-Bahn',
    turkish: 'Banliyö treni',
    english: 'Suburban train',
    article: 'die',
    plural: 'S-Bahnen',
    partOfSpeech: 'noun',
    collocations: ['mit der S-Bahn fahren', 'die S-Bahn nehmen'],
    emoji: '🚆',
    exampleSentence: 'Die S-Bahn fährt zum Flughafen.',
    exampleTranslation: 'Banliyö treni havalimanına gidiyor.',
    exampleTranslationEn: 'The suburban train goes to the airport.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-26',
    german: 'die Fähre',
    turkish: 'Feribot',
    english: 'Ferry',
    article: 'die',
    plural: 'Fähren',
    partOfSpeech: 'noun',
    collocations: ['mit der Fähre fahren', 'die Fähre nehmen'],
    emoji: '⛴️',
    exampleSentence: 'Die Fähre fährt alle zwei Stunden.',
    exampleTranslation: 'Feribot her iki saatte bir kalkar.',
    exampleTranslationEn: 'The ferry departs every two hours.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-27',
    german: 'der LKW',
    turkish: 'Kamyon',
    english: 'Truck',
    article: 'der',
    plural: 'LKWs',
    partOfSpeech: 'noun',
    synonyms: ['Lastwagen', 'Lastkraftwagen'],
    collocations: ['LKW fahren', 'ein großer LKW'],
    emoji: '🚚',
    exampleSentence: 'Der LKW blockiert die Straße.',
    exampleTranslation: 'Kamyon yolu tıkıyor.',
    exampleTranslationEn: 'The truck is blocking the road.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-28',
    german: 'der Krankenwagen',
    turkish: 'Ambulans',
    english: 'Ambulance',
    article: 'der',
    plural: 'Krankenwagen',
    partOfSpeech: 'noun',
    synonyms: ['Rettungswagen'],
    collocations: ['den Krankenwagen rufen', 'der Krankenwagen kommt'],
    emoji: '🚑',
    exampleSentence: 'Ruft sofort einen Krankenwagen!',
    exampleTranslation: 'Hemen bir ambulans çağırın!',
    exampleTranslationEn: 'Call an ambulance immediately!',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-29',
    german: 'das Feuerwehrauto',
    turkish: 'İtfaiye aracı',
    english: 'Fire truck',
    article: 'das',
    plural: 'Feuerwehrautos',
    partOfSpeech: 'noun',
    collocations: ['das Feuerwehrauto kommt', 'mit Sirene'],
    emoji: '🚒',
    exampleSentence: 'Das Feuerwehrauto fährt mit Sirene.',
    exampleTranslation: 'İtfaiye aracı sirenle gidiyor.',
    exampleTranslationEn: 'The fire truck drives with a siren.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-30',
    german: 'der Parkplatz',
    turkish: 'Otopark',
    english: 'Parking lot',
    article: 'der',
    plural: 'Parkplätze',
    partOfSpeech: 'noun',
    collocations: ['einen Parkplatz suchen', 'einen Parkplatz finden'],
    emoji: '🅿️',
    exampleSentence: 'Ich suche einen Parkplatz.',
    exampleTranslation: 'Otopark arıyorum.',
    exampleTranslationEn: 'I am looking for a parking spot.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-31',
    german: 'die Ampel',
    turkish: 'Trafik lambası',
    english: 'Traffic light',
    article: 'die',
    plural: 'Ampeln',
    partOfSpeech: 'noun',
    collocations: ['die Ampel ist rot', 'bei Grün über die Ampel gehen'],
    emoji: '🚦',
    exampleSentence: 'Die Ampel ist rot, wir müssen warten.',
    exampleTranslation: 'Trafik lambası kırmızı, beklememiz lazım.',
    exampleTranslationEn: 'The traffic light is red, we have to wait.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-32',
    german: 'der Zebrastreifen',
    turkish: 'Yaya geçidi',
    english: 'Crosswalk / Pedestrian crossing',
    article: 'der',
    plural: 'Zebrastreifen',
    partOfSpeech: 'noun',
    collocations: ['am Zebrastreifen warten', 'über den Zebrastreifen gehen'],
    emoji: '🚶',
    exampleSentence: 'Bitte benutze den Zebrastreifen.',
    exampleTranslation: 'Lütfen yaya geçidini kullan.',
    exampleTranslationEn: 'Please use the crosswalk.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-33',
    german: 'die Kreuzung',
    turkish: 'Kavşak',
    english: 'Intersection / Crossroads',
    article: 'die',
    plural: 'Kreuzungen',
    partOfSpeech: 'noun',
    collocations: ['an der Kreuzung abbiegen', 'eine gefährliche Kreuzung'],
    emoji: '🔀',
    exampleSentence: 'An der nächsten Kreuzung biegen Sie rechts ab.',
    exampleTranslation: 'Bir sonraki kavşaktan sağa dönün.',
    exampleTranslationEn: 'Turn right at the next intersection.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-34',
    german: 'der Gehweg',
    turkish: 'Kaldırım',
    english: 'Sidewalk',
    article: 'der',
    plural: 'Gehwege',
    partOfSpeech: 'noun',
    synonyms: ['Bürgersteig'],
    collocations: ['auf dem Gehweg gehen', 'den Gehweg benutzen'],
    emoji: '🚶‍♀️',
    exampleSentence: 'Bitte gehen Sie auf dem Gehweg.',
    exampleTranslation: 'Lütfen kaldırımda yürüyün.',
    exampleTranslationEn: 'Please walk on the sidewalk.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-35',
    german: 'der Fahrradweg',
    turkish: 'Bisiklet yolu',
    english: 'Bicycle path',
    article: 'der',
    plural: 'Fahrradwege',
    partOfSpeech: 'noun',
    synonyms: ['Radweg'],
    collocations: ['auf dem Fahrradweg fahren', 'einen Fahrradweg benutzen'],
    emoji: '🚴',
    exampleSentence: 'Berlin hat viele Fahrradwege.',
    exampleTranslation: 'Berlin\'de çok bisiklet yolu var.',
    exampleTranslationEn: 'Berlin has many bicycle paths.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-36',
    german: 'der Strafzettel',
    turkish: 'Trafik cezası',
    english: 'Parking ticket / Fine',
    article: 'der',
    plural: 'Strafzettel',
    partOfSpeech: 'noun',
    synonyms: ['Bußgeld'],
    collocations: ['einen Strafzettel bekommen', 'einen Strafzettel bezahlen'],
    emoji: '📝',
    exampleSentence: 'Ich habe einen Strafzettel bekommen.',
    exampleTranslation: 'Trafik cezası aldım.',
    exampleTranslationEn: 'I got a parking ticket.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-37',
    german: 'der Reifen',
    turkish: 'Lastik',
    english: 'Tire',
    article: 'der',
    plural: 'Reifen',
    partOfSpeech: 'noun',
    collocations: ['einen Reifen wechseln', 'platter Reifen'],
    emoji: '🛞',
    exampleSentence: 'Der Reifen ist platt.',
    exampleTranslation: 'Lastik patlamış.',
    exampleTranslationEn: 'The tire is flat.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-38',
    german: 'der Motor',
    turkish: 'Motor',
    english: 'Engine',
    article: 'der',
    plural: 'Motoren',
    partOfSpeech: 'noun',
    collocations: ['den Motor starten', 'der Motor läuft'],
    emoji: '🔧',
    exampleSentence: 'Der Motor springt nicht an.',
    exampleTranslation: 'Motor çalışmıyor.',
    exampleTranslationEn: 'The engine won\'t start.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-39',
    german: 'das Benzin',
    turkish: 'Benzin',
    english: 'Gasoline / Petrol',
    article: 'das',
    partOfSpeech: 'noun',
    synonyms: ['Sprit', 'Treibstoff'],
    collocations: ['Benzin tanken', 'Benzin sparen'],
    emoji: '⛽',
    exampleSentence: 'Wir müssen Benzin tanken.',
    exampleTranslation: 'Benzin almamız lazım.',
    exampleTranslationEn: 'We need to get gasoline.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-40',
    german: 'die Tankstelle',
    turkish: 'Benzin istasyonu',
    english: 'Gas station',
    article: 'die',
    plural: 'Tankstellen',
    partOfSpeech: 'noun',
    collocations: ['an der Tankstelle', 'die nächste Tankstelle'],
    emoji: '⛽',
    exampleSentence: 'Wo ist die nächste Tankstelle?',
    exampleTranslation: 'En yakın benzin istasyonu nerede?',
    exampleTranslationEn: 'Where is the nearest gas station?',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-41',
    german: 'abbiegen',
    turkish: 'Dönmek',
    english: 'To turn',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['links abbiegen', 'rechts abbiegen'],
    emoji: '↩️',
    exampleSentence: 'Biegen Sie an der Ampel links ab.',
    exampleTranslation: 'Trafik lambasından sola dönün.',
    exampleTranslationEn: 'Turn left at the traffic light.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-42',
    german: 'parken',
    turkish: 'Park etmek',
    english: 'To park',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['das Auto parken', 'hier darf man nicht parken'],
    emoji: '🅿️',
    exampleSentence: 'Hier darf man nicht parken.',
    exampleTranslation: 'Buraya park etmek yasak.',
    exampleTranslationEn: 'You are not allowed to park here.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-43',
    german: 'anhalten',
    turkish: 'Durmak',
    english: 'To stop',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['stoppen'],
    collocations: ['den Bus anhalten', 'an der Haltestelle anhalten'],
    emoji: '🛑',
    exampleSentence: 'Der Bus hält an der nächsten Haltestelle an.',
    exampleTranslation: 'Otobüs bir sonraki durakta duracak.',
    exampleTranslationEn: 'The bus stops at the next stop.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-44',
    german: 'überholen',
    turkish: 'Sollama yapmak',
    english: 'To overtake',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['ein Auto überholen', 'nicht überholen'],
    emoji: '🏎️',
    exampleSentence: 'Hier darf man nicht überholen.',
    exampleTranslation: 'Burada sollama yapmak yasak.',
    exampleTranslationEn: 'You must not overtake here.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-45',
    german: 'bremsen',
    turkish: 'Fren yapmak',
    english: 'To brake',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['stark bremsen', 'rechtzeitig bremsen'],
    emoji: '🛑',
    exampleSentence: 'Er musste plötzlich bremsen.',
    exampleTranslation: 'Aniden fren yapmak zorunda kaldı.',
    exampleTranslationEn: 'He had to brake suddenly.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-46',
    german: 'tanken',
    turkish: 'Yakıt almak',
    english: 'To refuel',
    article: null,
    partOfSpeech: 'verb',
    collocations: ['Benzin tanken', 'volltanken'],
    emoji: '⛽',
    exampleSentence: 'Wir müssen noch tanken.',
    exampleTranslation: 'Yakıt almamız lazım.',
    exampleTranslationEn: 'We still need to refuel.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-47',
    german: 'die Geschwindigkeit',
    turkish: 'Hız',
    english: 'Speed',
    article: 'die',
    plural: 'Geschwindigkeiten',
    partOfSpeech: 'noun',
    synonyms: ['Tempo'],
    collocations: ['die Geschwindigkeit erhöhen', 'hohe Geschwindigkeit'],
    emoji: '💨',
    exampleSentence: 'Die Geschwindigkeit ist hier auf 50 km/h begrenzt.',
    exampleTranslation: 'Burada hız 50 km/s ile sınırlı.',
    exampleTranslationEn: 'The speed is limited to 50 km/h here.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-48',
    german: 'das Tempolimit',
    turkish: 'Hız sınırı',
    english: 'Speed limit',
    article: 'das',
    plural: 'Tempolimits',
    partOfSpeech: 'noun',
    synonyms: ['Geschwindigkeitsbegrenzung'],
    collocations: ['das Tempolimit einhalten', 'ein Tempolimit von 130'],
    emoji: '🚫',
    exampleSentence: 'In Deutschland gibt es kein allgemeines Tempolimit.',
    exampleTranslation: 'Almanya\'da genel bir hız sınırı yok.',
    exampleTranslationEn: 'In Germany there is no general speed limit.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-49',
    german: 'die Umleitung',
    turkish: 'Dolambaçlı yol / Sapma',
    english: 'Detour / Diversion',
    article: 'die',
    plural: 'Umleitungen',
    partOfSpeech: 'noun',
    collocations: ['eine Umleitung folgen', 'Umleitung wegen Baustelle'],
    emoji: '🔄',
    exampleSentence: 'Wegen der Baustelle gibt es eine Umleitung.',
    exampleTranslation: 'İnşaat yüzünden sapma var.',
    exampleTranslationEn: 'There is a detour because of the construction site.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-50',
    german: 'der Unfall',
    turkish: 'Kaza',
    english: 'Accident',
    article: 'der',
    plural: 'Unfälle',
    partOfSpeech: 'noun',
    synonyms: ['Zusammenstoß', 'Crash'],
    collocations: ['einen Unfall haben', 'einen Unfall verursachen'],
    emoji: '💥',
    exampleSentence: 'Auf der Autobahn gab es einen Unfall.',
    exampleTranslation: 'Otoyolda bir kaza oldu.',
    exampleTranslationEn: 'There was an accident on the highway.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-51',
    german: 'der Sicherheitsgurt',
    turkish: 'Emniyet kemeri',
    english: 'Seatbelt',
    article: 'der',
    plural: 'Sicherheitsgurte',
    partOfSpeech: 'noun',
    collocations: ['den Sicherheitsgurt anlegen', 'den Gurt anschnallen'],
    emoji: '🔒',
    exampleSentence: 'Bitte legen Sie den Sicherheitsgurt an.',
    exampleTranslation: 'Lütfen emniyet kemerinizi takın.',
    exampleTranslationEn: 'Please fasten your seatbelt.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-52',
    german: 'der Verkehr',
    turkish: 'Trafik',
    english: 'Traffic',
    article: 'der',
    partOfSpeech: 'noun',
    collocations: ['im Verkehr', 'starker Verkehr'],
    emoji: '🚗',
    exampleSentence: 'Der Verkehr ist heute besonders stark.',
    exampleTranslation: 'Bugün trafik özellikle yoğun.',
    exampleTranslationEn: 'Traffic is especially heavy today.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-53',
    german: 'der Fußgänger',
    turkish: 'Yaya',
    english: 'Pedestrian',
    article: 'der',
    plural: 'Fußgänger',
    partOfSpeech: 'noun',
    collocations: ['Fußgänger haben Vorrang', 'als Fußgänger unterwegs'],
    emoji: '🚶',
    exampleSentence: 'Fußgänger haben hier Vorrang.',
    exampleTranslation: 'Burada yayalar öncelikli.',
    exampleTranslationEn: 'Pedestrians have priority here.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-54',
    german: 'der Passagier',
    turkish: 'Yolcu',
    english: 'Passenger',
    article: 'der',
    plural: 'Passagiere',
    partOfSpeech: 'noun',
    synonyms: ['Fahrgast', 'Reisende'],
    collocations: ['die Passagiere einsteigen', 'ein Passagierflugzeug'],
    emoji: '🧳',
    exampleSentence: 'Alle Passagiere bitte einsteigen.',
    exampleTranslation: 'Tüm yolcular lütfen binin.',
    exampleTranslationEn: 'All passengers please board.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-55',
    german: 'der Fahrer',
    turkish: 'Sürücü',
    english: 'Driver',
    article: 'der',
    plural: 'Fahrer',
    partOfSpeech: 'noun',
    synonyms: ['Chauffeur'],
    collocations: ['der Busfahrer', 'der Taxifahrer'],
    emoji: '🧑‍✈️',
    exampleSentence: 'Der Fahrer war sehr freundlich.',
    exampleTranslation: 'Sürücü çok nazikti.',
    exampleTranslationEn: 'The driver was very friendly.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-56',
    german: 'das Gleis',
    turkish: 'Peron / Ray',
    english: 'Track / Platform',
    article: 'das',
    plural: 'Gleise',
    partOfSpeech: 'noun',
    collocations: ['auf Gleis 3', 'das richtige Gleis finden'],
    emoji: '🛤️',
    exampleSentence: 'Der Zug fährt von Gleis 5 ab.',
    exampleTranslation: 'Tren 5. perondan kalkıyor.',
    exampleTranslationEn: 'The train departs from platform 5.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-57',
    german: 'einsteigen',
    turkish: 'Binmek',
    english: 'To board / Get on',
    article: null,
    partOfSpeech: 'verb',
    antonyms: ['aussteigen'],
    collocations: ['in den Zug einsteigen', 'bitte einsteigen'],
    emoji: '🚪',
    exampleSentence: 'Bitte steigen Sie ein!',
    exampleTranslation: 'Lütfen binin!',
    exampleTranslationEn: 'Please board!',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-58',
    german: 'aussteigen',
    turkish: 'İnmek',
    english: 'To get off',
    article: null,
    partOfSpeech: 'verb',
    antonyms: ['einsteigen'],
    collocations: ['aus dem Bus aussteigen', 'an der nächsten Haltestelle aussteigen'],
    emoji: '🚪',
    exampleSentence: 'Ich steige an der nächsten Haltestelle aus.',
    exampleTranslation: 'Bir sonraki durakta iniyorum.',
    exampleTranslationEn: 'I get off at the next stop.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-59',
    german: 'ankommen',
    turkish: 'Varmak',
    english: 'To arrive',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['eintreffen'],
    antonyms: ['abfahren'],
    collocations: ['pünktlich ankommen', 'am Ziel ankommen'],
    emoji: '📍',
    exampleSentence: 'Wann kommen wir an?',
    exampleTranslation: 'Ne zaman varacağız?',
    exampleTranslationEn: 'When do we arrive?',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-60',
    german: 'abfahren',
    turkish: 'Hareket etmek',
    english: 'To depart',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['losfahren'],
    antonyms: ['ankommen'],
    collocations: ['der Zug fährt ab', 'um 10 Uhr abfahren'],
    emoji: '🚀',
    exampleSentence: 'Der Zug fährt um 8 Uhr ab.',
    exampleTranslation: 'Tren saat 8\'de hareket ediyor.',
    exampleTranslationEn: 'The train departs at 8 o\'clock.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-61',
    german: 'landen',
    turkish: 'İnmek (uçak)',
    english: 'To land',
    article: null,
    partOfSpeech: 'verb',
    antonyms: ['starten', 'abheben'],
    collocations: ['das Flugzeug landet', 'sicher landen'],
    emoji: '🛬',
    exampleSentence: 'Das Flugzeug wird in 20 Minuten landen.',
    exampleTranslation: 'Uçak 20 dakika içinde inecek.',
    exampleTranslationEn: 'The airplane will land in 20 minutes.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-62',
    german: 'starten',
    turkish: 'Kalkmak (uçak)',
    english: 'To take off',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['abheben'],
    antonyms: ['landen'],
    collocations: ['das Flugzeug startet', 'der Flug startet'],
    emoji: '🛫',
    exampleSentence: 'Das Flugzeug startet pünktlich.',
    exampleTranslation: 'Uçak zamanında kalkıyor.',
    exampleTranslationEn: 'The airplane takes off on time.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-63',
    german: 'der Fahrplan',
    turkish: 'Tarife / Sefer programı',
    english: 'Timetable / Schedule',
    article: 'der',
    plural: 'Fahrpläne',
    partOfSpeech: 'noun',
    collocations: ['den Fahrplan prüfen', 'laut Fahrplan'],
    emoji: '📅',
    exampleSentence: 'Laut Fahrplan kommt der Bus um 14:30.',
    exampleTranslation: 'Tarife göre otobüs 14:30\'da gelecek.',
    exampleTranslationEn: 'According to the timetable the bus comes at 14:30.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-64',
    german: 'die Abfahrt',
    turkish: 'Kalkış',
    english: 'Departure',
    article: 'die',
    plural: 'Abfahrten',
    partOfSpeech: 'noun',
    antonyms: ['Ankunft'],
    collocations: ['die Abfahrt verzögert sich', 'planmäßige Abfahrt'],
    emoji: '🚏',
    exampleSentence: 'Die Abfahrt verzögert sich um 10 Minuten.',
    exampleTranslation: 'Kalkış 10 dakika gecikiyor.',
    exampleTranslationEn: 'The departure is delayed by 10 minutes.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-65',
    german: 'die Ankunft',
    turkish: 'Varış',
    english: 'Arrival',
    article: 'die',
    plural: 'Ankünfte',
    partOfSpeech: 'noun',
    antonyms: ['Abfahrt'],
    collocations: ['die Ankunft des Zuges', 'planmäßige Ankunft'],
    emoji: '📍',
    exampleSentence: 'Die Ankunft ist für 16 Uhr geplant.',
    exampleTranslation: 'Varış saat 16 için planlandı.',
    exampleTranslationEn: 'The arrival is planned for 4 PM.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-66',
    german: 'die Richtung',
    turkish: 'Yön',
    english: 'Direction',
    article: 'die',
    plural: 'Richtungen',
    partOfSpeech: 'noun',
    collocations: ['in Richtung Berlin', 'die richtige Richtung'],
    emoji: '➡️',
    exampleSentence: 'Fahren Sie in Richtung Stadtzentrum.',
    exampleTranslation: 'Şehir merkezi yönüne gidin.',
    exampleTranslationEn: 'Drive in the direction of the city center.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-67',
    german: 'die Brücke',
    turkish: 'Köprü',
    english: 'Bridge',
    article: 'die',
    plural: 'Brücken',
    partOfSpeech: 'noun',
    collocations: ['über die Brücke fahren', 'eine Brücke bauen'],
    emoji: '🌉',
    exampleSentence: 'Fahren Sie über die Brücke.',
    exampleTranslation: 'Köprüden geçin.',
    exampleTranslationEn: 'Drive over the bridge.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-68',
    german: 'der Tunnel',
    turkish: 'Tünel',
    english: 'Tunnel',
    article: 'der',
    plural: 'Tunnel',
    partOfSpeech: 'noun',
    collocations: ['durch den Tunnel fahren', 'ein langer Tunnel'],
    emoji: '🚇',
    exampleSentence: 'Der Tunnel ist drei Kilometer lang.',
    exampleTranslation: 'Tünel üç kilometre uzunluğunda.',
    exampleTranslationEn: 'The tunnel is three kilometers long.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-69',
    german: 'die Einbahnstraße',
    turkish: 'Tek yönlü yol',
    english: 'One-way street',
    article: 'die',
    plural: 'Einbahnstraßen',
    partOfSpeech: 'noun',
    collocations: ['eine Einbahnstraße befahren', 'Achtung, Einbahnstraße!'],
    emoji: '⬆️',
    exampleSentence: 'Das ist eine Einbahnstraße.',
    exampleTranslation: 'Burası tek yönlü yol.',
    exampleTranslationEn: 'This is a one-way street.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-70',
    german: 'der Kreisverkehr',
    turkish: 'Dönel kavşak',
    english: 'Roundabout',
    article: 'der',
    plural: 'Kreisverkehre',
    partOfSpeech: 'noun',
    collocations: ['im Kreisverkehr', 'den Kreisverkehr nehmen'],
    emoji: '🔄',
    exampleSentence: 'Nehmen Sie die zweite Ausfahrt im Kreisverkehr.',
    exampleTranslation: 'Dönel kavşakta ikinci çıkışı alın.',
    exampleTranslationEn: 'Take the second exit at the roundabout.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-71',
    german: 'die Werkstatt',
    turkish: 'Tamirhane',
    english: 'Workshop / Garage',
    article: 'die',
    plural: 'Werkstätten',
    partOfSpeech: 'noun',
    synonyms: ['Autowerkstatt'],
    collocations: ['das Auto in die Werkstatt bringen', 'in der Werkstatt'],
    emoji: '🔧',
    exampleSentence: 'Mein Auto ist in der Werkstatt.',
    exampleTranslation: 'Arabam tamirhanede.',
    exampleTranslationEn: 'My car is in the workshop.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-72',
    german: 'die Panne',
    turkish: 'Arıza',
    english: 'Breakdown',
    article: 'die',
    plural: 'Pannen',
    partOfSpeech: 'noun',
    collocations: ['eine Panne haben', 'Pannenhilfe'],
    emoji: '🔋',
    exampleSentence: 'Wir hatten eine Panne auf der Autobahn.',
    exampleTranslation: 'Otoyolda arıza yaptık.',
    exampleTranslationEn: 'We had a breakdown on the highway.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-73',
    german: 'der Spiegel',
    turkish: 'Ayna',
    english: 'Mirror',
    article: 'der',
    plural: 'Spiegel',
    partOfSpeech: 'noun',
    synonyms: ['Rückspiegel', 'Seitenspiegel'],
    collocations: ['in den Spiegel schauen', 'der Rückspiegel'],
    emoji: '🪞',
    exampleSentence: 'Schau in den Rückspiegel, bevor du abbiegst.',
    exampleTranslation: 'Dönmeden önce dikiz aynasına bak.',
    exampleTranslationEn: 'Look in the rearview mirror before you turn.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-74',
    german: 'die Bremse',
    turkish: 'Fren',
    english: 'Brake',
    article: 'die',
    plural: 'Bremsen',
    partOfSpeech: 'noun',
    synonyms: ['Handbremse'],
    collocations: ['auf die Bremse treten', 'die Bremse lösen'],
    emoji: '🛑',
    exampleSentence: 'Tritt auf die Bremse!',
    exampleTranslation: 'Frene bas!',
    exampleTranslationEn: 'Step on the brake!',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-75',
    german: 'der Steuermann',
    turkish: 'Kaptan / Dümenci',
    english: 'Helmsman',
    article: 'der',
    plural: 'Steuermänner',
    partOfSpeech: 'noun',
    synonyms: ['Kapitän'],
    collocations: ['der Steuermann lenkt das Schiff'],
    emoji: '🧑‍✈️',
    exampleSentence: 'Der Steuermann lenkte das Schiff sicher durch den Sturm.',
    exampleTranslation: 'Kaptan gemiyi fırtınada güvenle yönetti.',
    exampleTranslationEn: 'The helmsman steered the ship safely through the storm.',
    category: 'transport',
    level: 'B2',
  },
  {
    id: 'transport-76',
    german: 'das Navi',
    turkish: 'Navigasyon',
    english: 'GPS / Sat nav',
    article: 'das',
    plural: 'Navis',
    partOfSpeech: 'noun',
    synonyms: ['Navigationssystem'],
    collocations: ['das Navi einschalten', 'dem Navi folgen'],
    emoji: '📱',
    exampleSentence: 'Stell das Navi ein, ich kenne den Weg nicht.',
    exampleTranslation: 'Navigasyonu aç, yolu bilmiyorum.',
    exampleTranslationEn: 'Set up the GPS, I don\'t know the way.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-77',
    german: 'die Versicherung',
    turkish: 'Sigorta',
    english: 'Insurance',
    article: 'die',
    plural: 'Versicherungen',
    partOfSpeech: 'noun',
    synonyms: ['KFZ-Versicherung'],
    collocations: ['eine Versicherung abschließen', 'die Autoversicherung'],
    emoji: '📋',
    exampleSentence: 'Hast du eine Autoversicherung?',
    exampleTranslation: 'Araba sigortanız var mı?',
    exampleTranslationEn: 'Do you have car insurance?',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-78',
    german: 'der Schalter',
    turkish: 'Gişe / Bilet gişesi',
    english: 'Counter / Ticket office',
    article: 'der',
    plural: 'Schalter',
    partOfSpeech: 'noun',
    collocations: ['am Schalter kaufen', 'der Fahrkartenschalter'],
    emoji: '🎫',
    exampleSentence: 'Fahrkarten gibt es am Schalter.',
    exampleTranslation: 'Biletler gişede satılıyor.',
    exampleTranslationEn: 'Tickets are available at the counter.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-79',
    german: 'die Monatskarte',
    turkish: 'Aylık bilet',
    english: 'Monthly pass',
    article: 'die',
    plural: 'Monatskarten',
    partOfSpeech: 'noun',
    collocations: ['eine Monatskarte kaufen', 'die Monatskarte gilt'],
    emoji: '🎫',
    exampleSentence: 'Eine Monatskarte ist günstiger.',
    exampleTranslation: 'Aylık bilet daha uygun.',
    exampleTranslationEn: 'A monthly pass is cheaper.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-80',
    german: 'das Elektroauto',
    turkish: 'Elektrikli araba',
    english: 'Electric car',
    article: 'das',
    plural: 'Elektroautos',
    partOfSpeech: 'noun',
    synonyms: ['E-Auto'],
    collocations: ['ein Elektroauto fahren', 'das Elektroauto laden'],
    emoji: '🔌',
    exampleSentence: 'Elektroautos werden immer beliebter.',
    exampleTranslation: 'Elektrikli arabalar giderek daha popüler.',
    exampleTranslationEn: 'Electric cars are becoming more and more popular.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-81',
    german: 'die Ladestation',
    turkish: 'Şarj istasyonu',
    english: 'Charging station',
    article: 'die',
    plural: 'Ladestationen',
    partOfSpeech: 'noun',
    collocations: ['eine Ladestation finden', 'an der Ladestation laden'],
    emoji: '🔋',
    exampleSentence: 'Wo ist die nächste Ladestation?',
    exampleTranslation: 'En yakın şarj istasyonu nerede?',
    exampleTranslationEn: 'Where is the nearest charging station?',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-82',
    german: 'der Anhänger',
    turkish: 'Römork',
    english: 'Trailer',
    article: 'der',
    plural: 'Anhänger',
    partOfSpeech: 'noun',
    collocations: ['einen Anhänger ziehen', 'mit Anhänger fahren'],
    emoji: '🚛',
    exampleSentence: 'Er fährt mit einem Anhänger.',
    exampleTranslation: 'Römorkla gidiyor.',
    exampleTranslationEn: 'He is driving with a trailer.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-83',
    german: 'der Stau',
    turkish: 'Trafik sıkışıklığı',
    english: 'Traffic jam',
    article: 'der',
    plural: 'Staus',
    partOfSpeech: 'noun',
    collocations: ['im Stau stecken', 'Stau melden'],
    emoji: '🚗',
    exampleSentence: 'Wir stecken im Stau fest.',
    exampleTranslation: 'Trafikte sıkıştık.',
    exampleTranslationEn: 'We are stuck in a traffic jam.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-84',
    german: 'die Maut',
    turkish: 'Gişe ücreti',
    english: 'Toll',
    article: 'die',
    plural: 'Mauten',
    partOfSpeech: 'noun',
    collocations: ['Maut bezahlen', 'die Mautstation'],
    emoji: '💶',
    exampleSentence: 'In Österreich muss man Maut bezahlen.',
    exampleTranslation: 'Avusturya\'da gişe ücreti ödenmeli.',
    exampleTranslationEn: 'In Austria you have to pay a toll.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-85',
    german: 'die Baustelle',
    turkish: 'Şantiye / Yol çalışması',
    english: 'Construction site',
    article: 'die',
    plural: 'Baustellen',
    partOfSpeech: 'noun',
    collocations: ['Achtung Baustelle', 'eine Baustelle umfahren'],
    emoji: '🚧',
    exampleSentence: 'Vorsicht, Baustelle auf der Autobahn!',
    exampleTranslation: 'Dikkat, otoyolda yol çalışması!',
    exampleTranslationEn: 'Careful, construction site on the highway!',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-86',
    german: 'das Verkehrsschild',
    turkish: 'Trafik işareti',
    english: 'Traffic sign',
    article: 'das',
    plural: 'Verkehrsschilder',
    partOfSpeech: 'noun',
    collocations: ['ein Verkehrsschild beachten', 'Verkehrsschilder lesen'],
    emoji: '🪧',
    exampleSentence: 'Beachte die Verkehrsschilder!',
    exampleTranslation: 'Trafik işaretlerine dikkat et!',
    exampleTranslationEn: 'Pay attention to the traffic signs!',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-87',
    german: 'der Radfahrer',
    turkish: 'Bisikletçi',
    english: 'Cyclist',
    article: 'der',
    plural: 'Radfahrer',
    partOfSpeech: 'noun',
    synonyms: ['Fahrradfahrer'],
    collocations: ['Vorsicht vor Radfahrern', 'als Radfahrer unterwegs'],
    emoji: '🚴',
    exampleSentence: 'In Amsterdam gibt es viele Radfahrer.',
    exampleTranslation: 'Amsterdam\'da çok bisikletçi var.',
    exampleTranslationEn: 'There are many cyclists in Amsterdam.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-88',
    german: 'die Mitfahrgelegenheit',
    turkish: 'Araç paylaşımı',
    english: 'Ride share / Carpool',
    article: 'die',
    plural: 'Mitfahrgelegenheiten',
    partOfSpeech: 'noun',
    collocations: ['eine Mitfahrgelegenheit suchen', 'eine Mitfahrgelegenheit anbieten'],
    emoji: '🤝',
    exampleSentence: 'Ich suche eine Mitfahrgelegenheit nach München.',
    exampleTranslation: 'Münih\'e araç paylaşımı arıyorum.',
    exampleTranslationEn: 'I am looking for a ride share to Munich.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-89',
    german: 'der Kofferraum',
    turkish: 'Bagaj',
    english: 'Trunk / Boot',
    article: 'der',
    plural: 'Kofferräume',
    partOfSpeech: 'noun',
    collocations: ['den Kofferraum öffnen', 'im Kofferraum verstauen'],
    emoji: '🧳',
    exampleSentence: 'Der Koffer passt nicht in den Kofferraum.',
    exampleTranslation: 'Bavul bagaja sığmıyor.',
    exampleTranslationEn: 'The suitcase doesn\'t fit in the trunk.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-90',
    german: 'der Scheibenwischer',
    turkish: 'Silecek',
    english: 'Windshield wiper',
    article: 'der',
    plural: 'Scheibenwischer',
    partOfSpeech: 'noun',
    collocations: ['die Scheibenwischer einschalten', 'neue Scheibenwischer'],
    emoji: '🌧️',
    exampleSentence: 'Schalte die Scheibenwischer ein, es regnet.',
    exampleTranslation: 'Silecekleri aç, yağmur yağıyor.',
    exampleTranslationEn: 'Turn on the windshield wipers, it\'s raining.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-91',
    german: 'die Fahrspur',
    turkish: 'Şerit',
    english: 'Lane',
    article: 'die',
    plural: 'Fahrspuren',
    partOfSpeech: 'noun',
    collocations: ['die Fahrspur wechseln', 'auf der rechten Fahrspur'],
    emoji: '🛣️',
    exampleSentence: 'Wechseln Sie die Fahrspur nicht ohne zu blinken.',
    exampleTranslation: 'Sinyal vermeden şerit değiştirmeyin.',
    exampleTranslationEn: 'Don\'t change lanes without signaling.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-92',
    german: 'der Blinker',
    turkish: 'Sinyal lambası',
    english: 'Turn signal / Indicator',
    article: 'der',
    plural: 'Blinker',
    partOfSpeech: 'noun',
    collocations: ['den Blinker setzen', 'den Blinker vergessen'],
    emoji: '💡',
    exampleSentence: 'Vergiss nicht den Blinker zu setzen!',
    exampleTranslation: 'Sinyal vermeyi unutma!',
    exampleTranslationEn: 'Don\'t forget to use the turn signal!',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-93',
    german: 'der Kindersitz',
    turkish: 'Çocuk koltuğu',
    english: 'Child seat',
    article: 'der',
    plural: 'Kindersitze',
    partOfSpeech: 'noun',
    collocations: ['einen Kindersitz benutzen', 'Kindersitzpflicht'],
    emoji: '👶',
    exampleSentence: 'Im Auto braucht das Kind einen Kindersitz.',
    exampleTranslation: 'Çocuğun arabada çocuk koltuğuna ihtiyacı var.',
    exampleTranslationEn: 'The child needs a child seat in the car.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-94',
    german: 'die Ausfahrt',
    turkish: 'Çıkış',
    english: 'Exit (highway)',
    article: 'die',
    plural: 'Ausfahrten',
    partOfSpeech: 'noun',
    antonyms: ['Einfahrt'],
    collocations: ['die nächste Ausfahrt nehmen', 'Ausfahrt verpassen'],
    emoji: '🔚',
    exampleSentence: 'Nehmen Sie die nächste Ausfahrt.',
    exampleTranslation: 'Bir sonraki çıkışı alın.',
    exampleTranslationEn: 'Take the next exit.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-95',
    german: 'das Carsharing',
    turkish: 'Araba paylaşımı',
    english: 'Car sharing',
    article: 'das',
    partOfSpeech: 'noun',
    collocations: ['Carsharing nutzen', 'ein Carsharing-Anbieter'],
    emoji: '🔑',
    exampleSentence: 'Carsharing ist in Großstädten sehr beliebt.',
    exampleTranslation: 'Araba paylaşımı büyük şehirlerde çok popüler.',
    exampleTranslationEn: 'Car sharing is very popular in big cities.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-96',
    german: 'der Pendler',
    turkish: 'Banliyöden gidip gelen kişi',
    english: 'Commuter',
    article: 'der',
    plural: 'Pendler',
    partOfSpeech: 'noun',
    collocations: ['als Pendler unterwegs', 'Pendlerzug'],
    emoji: '🏃',
    exampleSentence: 'Viele Pendler fahren täglich nach Berlin.',
    exampleTranslation: 'Birçok kişi her gün Berlin\'e gidip geliyor.',
    exampleTranslationEn: 'Many commuters travel to Berlin daily.',
    category: 'transport',
    level: 'B2',
  },
  {
    id: 'transport-97',
    german: 'der Berufsverkehr',
    turkish: 'İş trafiği',
    english: 'Rush hour traffic',
    article: 'der',
    partOfSpeech: 'noun',
    synonyms: ['Stoßzeit', 'Hauptverkehrszeit'],
    collocations: ['im Berufsverkehr', 'den Berufsverkehr meiden'],
    emoji: '⏰',
    exampleSentence: 'Im Berufsverkehr staut es sich oft.',
    exampleTranslation: 'İş trafiğinde sık sık tıkanıklık oluyor.',
    exampleTranslationEn: 'There are often traffic jams during rush hour.',
    category: 'transport',
    level: 'B2',
  },
  {
    id: 'transport-98',
    german: 'die Nachhaltigkeit',
    turkish: 'Sürdürülebilirlik',
    english: 'Sustainability',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['nachhaltige Mobilität', 'auf Nachhaltigkeit achten'],
    emoji: '🌿',
    exampleSentence: 'Nachhaltigkeit spielt im Verkehr eine wichtige Rolle.',
    exampleTranslation: 'Sürdürülebilirlik ulaşımda önemli bir rol oynuyor.',
    exampleTranslationEn: 'Sustainability plays an important role in transport.',
    category: 'transport',
    level: 'B2',
  },
  {
    id: 'transport-99',
    german: 'die Abgase',
    turkish: 'Egzoz gazları',
    english: 'Exhaust fumes',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Emissionen'],
    collocations: ['Abgase reduzieren', 'giftige Abgase'],
    emoji: '💨',
    exampleSentence: 'Elektroautos produzieren keine Abgase.',
    exampleTranslation: 'Elektrikli arabalar egzoz gazı üretmez.',
    exampleTranslationEn: 'Electric cars produce no exhaust fumes.',
    category: 'transport',
    level: 'B2',
  },
  {
    id: 'transport-100',
    german: 'die Barrierefreiheit',
    turkish: 'Engelsiz erişim',
    english: 'Accessibility',
    article: 'die',
    partOfSpeech: 'noun',
    collocations: ['barrierefreier Zugang', 'Barrierefreiheit gewährleisten'],
    emoji: '♿',
    exampleSentence: 'Barrierefreiheit im öffentlichen Nahverkehr ist wichtig.',
    exampleTranslation: 'Toplu taşımada engelsiz erişim önemlidir.',
    exampleTranslationEn: 'Accessibility in public transport is important.',
    category: 'transport',
    level: 'B2',
  },
];
