import { VocabularyWord } from '@/lib/types';

export const transportWords: VocabularyWord[] = [
  {
    id: 'transport-1',
    german: 'das Auto',
    turkish: 'Araba',
    english: 'Car',
    article: 'das',
    plural: 'Autos',
    partOfSpeech: 'noun',
    synonyms: ['Wagen', 'Fahrzeug', 'PKW'],
    collocations: ['Auto fahren', 'ein Auto kaufen'],
    emoji: '🚗',
    exampleSentence: 'Ich fahre mit dem Auto zur Arbeit.',
    exampleTranslation: 'İşe arabayla gidiyorum.',
    exampleTranslationEn: 'I drive to work by car.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-2',
    german: 'der Bus',
    turkish: 'Otobüs',
    english: 'Bus',
    article: 'der',
    plural: 'Busse',
    partOfSpeech: 'noun',
    synonyms: ['Linienbus', 'Reisebus'],
    collocations: ['den Bus nehmen', 'auf den Bus warten'],
    emoji: '🚌',
    exampleSentence: 'Der Bus kommt in fünf Minuten.',
    exampleTranslation: 'Otobüs beş dakika içinde gelecek.',
    exampleTranslationEn: 'The bus comes in five minutes.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-3',
    german: 'der Zug',
    turkish: 'Tren',
    english: 'Train',
    article: 'der',
    plural: 'Züge',
    partOfSpeech: 'noun',
    synonyms: ['Eisenbahn', 'Bahn'],
    collocations: ['mit dem Zug fahren', 'den Zug nehmen'],
    emoji: '🚂',
    exampleSentence: 'Der Zug nach Berlin fährt um 10 Uhr.',
    exampleTranslation: 'Berlin treni saat 10\'da kalkıyor.',
    exampleTranslationEn: 'The train to Berlin departs at 10 o\'clock.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-4',
    german: 'das Fahrrad',
    turkish: 'Bisiklet',
    english: 'Bicycle',
    article: 'das',
    plural: 'Fahrräder',
    partOfSpeech: 'noun',
    synonyms: ['Rad', 'Bike'],
    collocations: ['Fahrrad fahren', 'mit dem Fahrrad'],
    emoji: '🚲',
    exampleSentence: 'Ich fahre gerne Fahrrad.',
    exampleTranslation: 'Bisiklet sürmeyi seviyorum.',
    exampleTranslationEn: 'I like to ride a bicycle.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-5',
    german: 'das Flugzeug',
    turkish: 'Uçak',
    english: 'Airplane',
    article: 'das',
    plural: 'Flugzeuge',
    partOfSpeech: 'noun',
    synonyms: ['Flieger', 'Maschine'],
    collocations: ['mit dem Flugzeug fliegen', 'das Flugzeug landet'],
    emoji: '✈️',
    exampleSentence: 'Das Flugzeug startet in einer Stunde.',
    exampleTranslation: 'Uçak bir saat içinde kalkıyor.',
    exampleTranslationEn: 'The airplane departs in one hour.',
    category: 'transport',
    level: 'A1',
  },
  {
    id: 'transport-6',
    german: 'die Straßenbahn',
    turkish: 'Tramvay',
    english: 'Tram',
    article: 'die',
    plural: 'Straßenbahnen',
    partOfSpeech: 'noun',
    synonyms: ['Tram'],
    collocations: ['mit der Straßenbahn fahren', 'die Straßenbahn nehmen'],
    emoji: '🚃',
    exampleSentence: 'Die Straßenbahn fährt alle zehn Minuten.',
    exampleTranslation: 'Tramvay her on dakikada bir geliyor.',
    exampleTranslationEn: 'The tram runs every ten minutes.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-7',
    german: 'die U-Bahn',
    turkish: 'Metro',
    english: 'Subway',
    article: 'die',
    plural: 'U-Bahnen',
    partOfSpeech: 'noun',
    synonyms: ['Metro', 'Untergrundbahn'],
    collocations: ['mit der U-Bahn fahren', 'die U-Bahn nehmen'],
    emoji: '🚇',
    exampleSentence: 'Die U-Bahn ist schneller als der Bus.',
    exampleTranslation: 'Metro otobüsten daha hızlı.',
    exampleTranslationEn: 'The subway is faster than the bus.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-8',
    german: 'der Führerschein',
    turkish: 'Ehliyet',
    english: 'Driver\'s license',
    article: 'der',
    plural: 'Führerscheine',
    partOfSpeech: 'noun',
    synonyms: ['Fahrerlaubnis'],
    collocations: ['den Führerschein machen', 'den Führerschein verlieren'],
    emoji: '🪪',
    exampleSentence: 'Ich habe meinen Führerschein mit 18 gemacht.',
    exampleTranslation: '18 yaşında ehliyetimi aldım.',
    exampleTranslationEn: 'I got my driver\'s license at 18.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-9',
    german: 'die Fahrkarte',
    turkish: 'Bilet',
    english: 'Ticket',
    article: 'die',
    plural: 'Fahrkarten',
    partOfSpeech: 'noun',
    synonyms: ['Ticket', 'Fahrschein'],
    collocations: ['eine Fahrkarte kaufen', 'die Fahrkarte zeigen'],
    emoji: '🎫',
    exampleSentence: 'Wo kann ich eine Fahrkarte kaufen?',
    exampleTranslation: 'Nereden bilet alabilirim?',
    exampleTranslationEn: 'Where can I buy a ticket?',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-10',
    german: 'die Haltestelle',
    turkish: 'Durak',
    english: 'Stop (bus/tram)',
    article: 'die',
    plural: 'Haltestellen',
    partOfSpeech: 'noun',
    synonyms: ['Station'],
    collocations: ['an der Haltestelle warten', 'die nächste Haltestelle'],
    emoji: '🚏',
    exampleSentence: 'Die Haltestelle ist gleich um die Ecke.',
    exampleTranslation: 'Durak hemen köşede.',
    exampleTranslationEn: 'The stop is just around the corner.',
    category: 'transport',
    level: 'A2',
  },
  {
    id: 'transport-11',
    german: 'der Stau',
    turkish: 'Trafik sıkışıklığı',
    english: 'Traffic jam',
    article: 'der',
    plural: 'Staus',
    partOfSpeech: 'noun',
    synonyms: ['Verkehrsstau'],
    collocations: ['im Stau stehen', 'einen Stau umfahren'],
    emoji: '🚗',
    exampleSentence: 'Ich stehe seit einer Stunde im Stau.',
    exampleTranslation: 'Bir saattir trafikte bekliyorum.',
    exampleTranslationEn: 'I have been stuck in a traffic jam for an hour.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-12',
    german: 'umsteigen',
    turkish: 'Aktarma yapmak',
    english: 'To transfer / change',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['wechseln'],
    collocations: ['in Berlin umsteigen', 'einmal umsteigen'],
    emoji: '🔄',
    exampleSentence: 'Sie müssen in München umsteigen.',
    exampleTranslation: 'Münih\'te aktarma yapmanız gerekiyor.',
    exampleTranslationEn: 'You need to transfer in Munich.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-13',
    german: 'die Verspätung',
    turkish: 'Gecikme / Rötar',
    english: 'Delay',
    article: 'die',
    plural: 'Verspätungen',
    partOfSpeech: 'noun',
    synonyms: ['Verzögerung'],
    collocations: ['Verspätung haben', 'mit Verspätung ankommen'],
    emoji: '⏰',
    exampleSentence: 'Der Zug hat zwanzig Minuten Verspätung.',
    exampleTranslation: 'Trenin yirmi dakika rötarı var.',
    exampleTranslationEn: 'The train has a twenty-minute delay.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-14',
    german: 'die Autobahn',
    turkish: 'Otoyol',
    english: 'Highway / Motorway',
    article: 'die',
    plural: 'Autobahnen',
    partOfSpeech: 'noun',
    synonyms: ['Schnellstraße'],
    collocations: ['auf der Autobahn fahren', 'die Autobahn nehmen'],
    emoji: '🛣️',
    exampleSentence: 'Auf der deutschen Autobahn gibt es kein Tempolimit.',
    exampleTranslation: 'Alman otoyollarında hız sınırı yok.',
    exampleTranslationEn: 'There is no speed limit on the German highway.',
    category: 'transport',
    level: 'B1',
  },
  {
    id: 'transport-15',
    german: 'die Infrastruktur',
    turkish: 'Altyapı',
    english: 'Infrastructure',
    article: 'die',
    plural: 'Infrastrukturen',
    partOfSpeech: 'noun',
    synonyms: ['Verkehrsnetz'],
    collocations: ['die Infrastruktur ausbauen', 'öffentliche Infrastruktur'],
    emoji: '🏗️',
    exampleSentence: 'Die Infrastruktur in Deutschland ist gut ausgebaut.',
    exampleTranslation: 'Almanya\'daki altyapı iyi gelişmiş.',
    exampleTranslationEn: 'The infrastructure in Germany is well developed.',
    category: 'transport',
    level: 'B2',
  },
  {
    id: 'transport-16',
    german: 'die Verkehrswende',
    turkish: 'Ulaşım dönüşümü',
    english: 'Transport transition',
    article: 'die',
    partOfSpeech: 'noun',
    synonyms: ['Mobilitätswende'],
    collocations: ['die Verkehrswende vorantreiben', 'nachhaltige Verkehrswende'],
    emoji: '🌱',
    exampleSentence: 'Die Verkehrswende ist ein wichtiges Thema in der Politik.',
    exampleTranslation: 'Ulaşım dönüşümü siyasette önemli bir konu.',
    exampleTranslationEn: 'The transport transition is an important political topic.',
    category: 'transport',
    level: 'B2',
  },
];
