import { VocabularyWord } from '@/lib/types';
export const travelWords: VocabularyWord[] = [
  {
    id: 'travel-1',
    german: 'Flugzeug',
    turkish: 'Uçak',
    english: 'Airplane',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Flugzeuge',
    emoji: '✈️',
    synonyms: ['Flieger', 'Maschine'],
    collocations: ['ein Flugzeug nehmen', 'das Flugzeug landet', 'mit dem Flugzeug fliegen'],
    exampleSentence: 'Das Flugzeug fliegt nach Berlin.',
    exampleTranslation: 'Uçak Berlin\'e uçuyor.',
    exampleTranslationEn: 'The airplane flies to Berlin.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-2',
    german: 'Zug',
    turkish: 'Tren',
    english: 'Train',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Züge',
    emoji: '🚆',
    synonyms: ['Bahn', 'Eisenbahn'],
    collocations: ['den Zug nehmen', 'der Zug hat Verspätung', 'mit dem Zug fahren'],
    exampleSentence: 'Der Zug kommt um 10 Uhr.',
    exampleTranslation: 'Tren saat 10\'da geliyor.',
    exampleTranslationEn: 'The train arrives at 10 o\'clock.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-3',
    german: 'Bus',
    turkish: 'Otobüs',
    english: 'Bus',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Busse',
    emoji: '🚌',
    collocations: ['mit dem Bus fahren', 'den Bus verpassen', 'auf den Bus warten'],
    exampleSentence: 'Ich fahre mit dem Bus zur Arbeit.',
    exampleTranslation: 'İşe otobüsle gidiyorum.',
    exampleTranslationEn: 'I take the bus to work.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-4',
    german: 'Bahnhof',
    turkish: 'Tren istasyonu',
    english: 'Train station',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Bahnhöfe',
    emoji: '🚉',
    synonyms: ['Station', 'Haltestelle'],
    collocations: ['am Bahnhof ankommen', 'zum Bahnhof gehen', 'der Hauptbahnhof'],
    exampleSentence: 'Der Bahnhof ist in der Stadtmitte.',
    exampleTranslation: 'Tren istasyonu şehir merkezinde.',
    exampleTranslationEn: 'The train station is in the city center.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-5',
    german: 'Flughafen',
    turkish: 'Havalimanı',
    english: 'Airport',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Flughäfen',
    emoji: '🛫',
    synonyms: ['Airport'],
    collocations: ['zum Flughafen fahren', 'am Flughafen ankommen', 'der internationale Flughafen'],
    exampleSentence: 'Wir fahren zum Flughafen.',
    exampleTranslation: 'Havalimanına gidiyoruz.',
    exampleTranslationEn: 'We are going to the airport.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-6',
    german: 'Fahrkarte',
    turkish: 'Bilet',
    english: 'Ticket',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Fahrkarten',
    emoji: '🎫',
    synonyms: ['Ticket', 'Fahrschein'],
    collocations: ['eine Fahrkarte kaufen', 'eine Fahrkarte lösen', 'die Fahrkarte entwerten'],
    exampleSentence: 'Ich brauche eine Fahrkarte nach Hamburg.',
    exampleTranslation: 'Hamburg\'a bir bilet lazım.',
    exampleTranslationEn: 'I need a ticket to Hamburg.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-7',
    german: 'Koffer',
    turkish: 'Bavul',
    english: 'Suitcase',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Koffer',
    emoji: '🧳',
    synonyms: ['Gepäck', 'Reisetasche'],
    collocations: ['den Koffer packen', 'den Koffer aufgeben', 'einen Koffer tragen'],
    exampleSentence: 'Mein Koffer ist sehr schwer.',
    exampleTranslation: 'Bavulum çok ağır.',
    exampleTranslationEn: 'My suitcase is very heavy.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-8',
    german: 'Hotel',
    turkish: 'Otel',
    english: 'Hotel',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Hotels',
    emoji: '🏨',
    synonyms: ['Unterkunft', 'Pension'],
    collocations: ['ein Hotel buchen', 'im Hotel übernachten', 'ein Hotel suchen'],
    exampleSentence: 'Das Hotel ist am Strand.',
    exampleTranslation: 'Otel sahilde.',
    exampleTranslationEn: 'The hotel is on the beach.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-9',
    german: 'Reisepass',
    turkish: 'Pasaport',
    english: 'Passport',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Reisepässe',
    emoji: '🛂',
    synonyms: ['Pass'],
    collocations: ['den Reisepass vorzeigen', 'den Reisepass verlängern', 'einen Reisepass beantragen'],
    exampleSentence: 'Haben Sie Ihren Reisepass?',
    exampleTranslation: 'Pasaportunuz var mı?',
    exampleTranslationEn: 'Do you have your passport?',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-10',
    german: 'Urlaub',
    turkish: 'Tatil',
    english: 'Vacation',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Urlaube',
    emoji: '🏖️',
    synonyms: ['Ferien', 'Freizeit'],
    collocations: ['Urlaub machen', 'in den Urlaub fahren', 'Urlaub nehmen'],
    exampleSentence: 'Im Sommer machen wir Urlaub.',
    exampleTranslation: 'Yazın tatil yapıyoruz.',
    exampleTranslationEn: 'In summer we go on vacation.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-11',
    german: 'Straße',
    turkish: 'Sokak/Cadde',
    english: 'Street',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Straßen',
    emoji: '🛣️',
    synonyms: ['Weg', 'Gasse'],
    collocations: ['die Straße überqueren', 'auf der Straße gehen', 'eine breite Straße'],
    exampleSentence: 'Die Straße ist sehr lang.',
    exampleTranslation: 'Cadde çok uzun.',
    exampleTranslationEn: 'The street is very long.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-12',
    german: 'links',
    turkish: 'sol',
    english: 'Left',
    article: null,
    partOfSpeech: 'adverb',
    emoji: '⬅️',
    antonyms: ['rechts'],
    collocations: ['nach links gehen', 'links abbiegen'],
    exampleSentence: 'Gehen Sie links!',
    exampleTranslation: 'Sola gidin!',
    exampleTranslationEn: 'Go left!',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-13',
    german: 'rechts',
    turkish: 'sağ',
    english: 'Right',
    article: null,
    partOfSpeech: 'adverb',
    emoji: '➡️',
    antonyms: ['links'],
    collocations: ['nach rechts gehen', 'rechts abbiegen'],
    exampleSentence: 'Die Bank ist rechts.',
    exampleTranslation: 'Banka sağda.',
    exampleTranslationEn: 'The bank is on the right.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-14',
    german: 'geradeaus',
    turkish: 'düz/ileri',
    english: 'Straight ahead',
    article: null,
    partOfSpeech: 'adverb',
    emoji: '⬆️',
    collocations: ['geradeaus gehen', 'immer geradeaus fahren'],
    exampleSentence: 'Gehen Sie geradeaus!',
    exampleTranslation: 'Düz gidin!',
    exampleTranslationEn: 'Go straight ahead!',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-15',
    german: 'Meer',
    turkish: 'Deniz',
    english: 'Sea',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Meere',
    emoji: '🌊',
    synonyms: ['Ozean', 'See'],
    collocations: ['ans Meer fahren', 'am Meer wohnen', 'das offene Meer'],
    exampleSentence: 'Das Meer ist blau und warm.',
    exampleTranslation: 'Deniz mavi ve sıcak.',
    exampleTranslationEn: 'The sea is blue and warm.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-16',
    german: 'Unterkunft',
    turkish: 'Konaklama',
    english: 'Accommodation',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Unterkünfte',
    emoji: '🏠',
    synonyms: ['Bleibe', 'Quartier', 'Übernachtungsmöglichkeit'],
    collocations: ['eine Unterkunft buchen', 'eine günstige Unterkunft finden', 'die Unterkunft wechseln'],
    exampleSentence: 'Wir haben eine gemütliche Unterkunft direkt am See gefunden.',
    exampleTranslation: 'Gölün hemen yanında rahat bir konaklama yeri bulduk.',
    exampleTranslationEn: 'We found a cozy accommodation right by the lake.',
    category: 'travel',
    level: 'B2',
    tags: ['accommodation', 'booking'],
  },
  {
    id: 'travel-17',
    german: 'Verspätung',
    turkish: 'Gecikme/Rötar',
    english: 'Delay',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Verspätungen',
    emoji: '⏳',
    synonyms: ['Verzögerung', 'Aufschub'],
    antonyms: ['Pünktlichkeit'],
    collocations: ['eine Verspätung haben', 'mit Verspätung ankommen', 'die Verspätung beträgt 30 Minuten'],
    exampleSentence: 'Wegen des schlechten Wetters hatte unser Flug zwei Stunden Verspätung.',
    exampleTranslation: 'Kötü hava nedeniyle uçuşumuz iki saat rötar yaptı.',
    exampleTranslationEn: 'Due to the bad weather, our flight was delayed by two hours.',
    category: 'travel',
    level: 'B2',
    tags: ['delay', 'transport'],
  },
  {
    id: 'travel-18',
    german: 'umsteigen',
    turkish: 'Aktarma yapmak',
    english: 'To transfer/change',
    article: null,
    partOfSpeech: 'verb',
    emoji: '🔄',
    synonyms: ['wechseln', 'umsatteln'],
    collocations: ['in einen anderen Zug umsteigen', 'am Hauptbahnhof umsteigen', 'ohne Umsteigen fahren'],
    exampleSentence: 'Sie müssen in Frankfurt umsteigen, um nach München zu gelangen.',
    exampleTranslation: 'Münih\'e ulaşmak için Frankfurt\'ta aktarma yapmanız gerekiyor.',
    exampleTranslationEn: 'You have to transfer in Frankfurt to get to Munich.',
    category: 'travel',
    level: 'B2',
    tags: ['transport', 'connection'],
  },
  {
    id: 'travel-19',
    german: 'Sehenswürdigkeit',
    turkish: 'Turistik yer/Görülmeye değer yer',
    english: 'Tourist attraction/Sight',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Sehenswürdigkeiten',
    emoji: '🏛️',
    synonyms: ['Attraktion', 'Wahrzeichen'],
    collocations: ['Sehenswürdigkeiten besichtigen', 'die wichtigsten Sehenswürdigkeiten', 'eine berühmte Sehenswürdigkeit'],
    exampleSentence: 'Das Brandenburger Tor ist eine der bekanntesten Sehenswürdigkeiten Berlins.',
    exampleTranslation: 'Brandenburg Kapısı, Berlin\'in en ünlü turistik yerlerinden biridir.',
    exampleTranslationEn: 'The Brandenburg Gate is one of the most famous sights in Berlin.',
    category: 'travel',
    level: 'B2',
    tags: ['sightseeing', 'tourism'],
  },
  {
    id: 'travel-20',
    german: 'Reiseführer',
    turkish: 'Gezi rehberi',
    english: 'Travel guide',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Reiseführer',
    emoji: '📗',
    synonyms: ['Touristenführer', 'Guide'],
    collocations: ['einen Reiseführer kaufen', 'im Reiseführer nachschlagen', 'ein deutschsprachiger Reiseführer'],
    exampleSentence: 'Der Reiseführer empfiehlt dieses kleine Restaurant abseits der Touristenpfade.',
    exampleTranslation: 'Gezi rehberi, turist yollarından uzaktaki bu küçük restoranı tavsiye ediyor.',
    exampleTranslationEn: 'The travel guide recommends this small restaurant off the beaten tourist path.',
    category: 'travel',
    level: 'B2',
    tags: ['guide', 'information'],
  },
  {
    id: 'travel-21',
    german: 'Botschaft',
    turkish: 'Büyükelçilik',
    english: 'Embassy',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Botschaften',
    emoji: '🏛️',
    synonyms: ['Konsulat', 'Vertretung'],
    collocations: ['die Botschaft kontaktieren', 'bei der Botschaft vorsprechen', 'ein Visum bei der Botschaft beantragen'],
    exampleSentence: 'Im Notfall sollten Sie sich an die Botschaft Ihres Landes wenden.',
    exampleTranslation: 'Acil bir durumda ülkenizin büyükelçiliğine başvurmalısınız.',
    exampleTranslationEn: 'In an emergency, you should contact your country\'s embassy.',
    category: 'travel',
    level: 'B2',
    tags: ['embassy', 'official'],
  },
  {
    id: 'travel-22',
    german: 'Versicherung',
    turkish: 'Sigorta',
    english: 'Insurance',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Versicherungen',
    emoji: '🛡️',
    synonyms: ['Absicherung', 'Schutz'],
    collocations: ['eine Versicherung abschließen', 'eine Reiseversicherung haben', 'die Versicherung deckt die Kosten'],
    exampleSentence: 'Eine Reiseversicherung ist bei Auslandsreisen dringend zu empfehlen.',
    exampleTranslation: 'Yurt dışı seyahatlerinde seyahat sigortası şiddetle tavsiye edilir.',
    exampleTranslationEn: 'Travel insurance is highly recommended for trips abroad.',
    category: 'travel',
    level: 'B2',
    tags: ['insurance', 'safety'],
  },
  {
    id: 'travel-23',
    german: 'Aufenthalt',
    turkish: 'Kalış/İkamet',
    english: 'Stay/Sojourn',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Aufenthalte',
    emoji: '🏡',
    synonyms: ['Verweilen', 'Bleibe'],
    collocations: ['ein angenehmer Aufenthalt', 'den Aufenthalt verlängern', 'einen kurzen Aufenthalt haben'],
    exampleSentence: 'Während unseres Aufenthalts in Wien haben wir zahlreiche Museen besucht.',
    exampleTranslation: 'Viyana\'daki kalışımız süresince birçok müze ziyaret ettik.',
    exampleTranslationEn: 'During our stay in Vienna, we visited numerous museums.',
    category: 'travel',
    level: 'B2',
    tags: ['stay', 'duration'],
  },
  {
    id: 'travel-24',
    german: 'Abflug',
    turkish: 'Kalkış',
    english: 'Departure (flight)',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Abflüge',
    emoji: '🛫',
    synonyms: ['Start', 'Abreise'],
    antonyms: ['Ankunft', 'Landung'],
    collocations: ['der Abflug ist um 8 Uhr', 'den Abflug verpassen', 'die Abflugtafel prüfen'],
    exampleSentence: 'Der Abflug wurde wegen eines technischen Problems auf den Nachmittag verschoben.',
    exampleTranslation: 'Kalkış, teknik bir sorun nedeniyle öğleden sonraya ertelendi.',
    exampleTranslationEn: 'The departure was postponed to the afternoon due to a technical problem.',
    category: 'travel',
    level: 'B2',
    tags: ['flight', 'departure'],
  },
  {
    id: 'travel-25',
    german: 'Ankunft',
    turkish: 'Varış',
    english: 'Arrival',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Ankünfte',
    emoji: '🛬',
    synonyms: ['Eintreffen', 'Anreise'],
    antonyms: ['Abflug', 'Abreise'],
    collocations: ['die Ankunft verzögert sich', 'pünktliche Ankunft', 'bei Ankunft am Flughafen'],
    exampleSentence: 'Nach der Ankunft am Flughafen haben wir direkt ein Taxi zum Hotel genommen.',
    exampleTranslation: 'Havalimanına varışımızın ardından doğrudan otele bir taksi aldık.',
    exampleTranslationEn: 'After arriving at the airport, we immediately took a taxi to the hotel.',
    category: 'travel',
    level: 'B2',
    tags: ['flight', 'arrival'],
  },
];
