import { VocabularyWord } from '@/lib/types';
export const travelWords: VocabularyWord[] = [
  {
    id: 'travel-1',
    german: 'Flugzeug',
    turkish: 'Uçak',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Flugzeuge',
    emoji: '✈️',
    synonyms: ['Flieger', 'Maschine'],
    collocations: ['ein Flugzeug nehmen', 'das Flugzeug landet', 'mit dem Flugzeug fliegen'],
    exampleSentence: 'Das Flugzeug fliegt nach Berlin.',
    exampleTranslation: 'Uçak Berlin\'e uçuyor.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-2',
    german: 'Zug',
    turkish: 'Tren',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Züge',
    emoji: '🚆',
    synonyms: ['Bahn', 'Eisenbahn'],
    collocations: ['den Zug nehmen', 'der Zug hat Verspätung', 'mit dem Zug fahren'],
    exampleSentence: 'Der Zug kommt um 10 Uhr.',
    exampleTranslation: 'Tren saat 10\'da geliyor.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-3',
    german: 'Bus',
    turkish: 'Otobüs',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Busse',
    emoji: '🚌',
    collocations: ['mit dem Bus fahren', 'den Bus verpassen', 'auf den Bus warten'],
    exampleSentence: 'Ich fahre mit dem Bus zur Arbeit.',
    exampleTranslation: 'İşe otobüsle gidiyorum.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-4',
    german: 'Bahnhof',
    turkish: 'Tren istasyonu',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Bahnhöfe',
    emoji: '🚉',
    synonyms: ['Station', 'Haltestelle'],
    collocations: ['am Bahnhof ankommen', 'zum Bahnhof gehen', 'der Hauptbahnhof'],
    exampleSentence: 'Der Bahnhof ist in der Stadtmitte.',
    exampleTranslation: 'Tren istasyonu şehir merkezinde.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-5',
    german: 'Flughafen',
    turkish: 'Havalimanı',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Flughäfen',
    emoji: '🛫',
    synonyms: ['Airport'],
    collocations: ['zum Flughafen fahren', 'am Flughafen ankommen', 'der internationale Flughafen'],
    exampleSentence: 'Wir fahren zum Flughafen.',
    exampleTranslation: 'Havalimanına gidiyoruz.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-6',
    german: 'Fahrkarte',
    turkish: 'Bilet',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Fahrkarten',
    emoji: '🎫',
    synonyms: ['Ticket', 'Fahrschein'],
    collocations: ['eine Fahrkarte kaufen', 'eine Fahrkarte lösen', 'die Fahrkarte entwerten'],
    exampleSentence: 'Ich brauche eine Fahrkarte nach Hamburg.',
    exampleTranslation: 'Hamburg\'a bir bilet lazım.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-7',
    german: 'Koffer',
    turkish: 'Bavul',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Koffer',
    emoji: '🧳',
    synonyms: ['Gepäck', 'Reisetasche'],
    collocations: ['den Koffer packen', 'den Koffer aufgeben', 'einen Koffer tragen'],
    exampleSentence: 'Mein Koffer ist sehr schwer.',
    exampleTranslation: 'Bavulum çok ağır.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-8',
    german: 'Hotel',
    turkish: 'Otel',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Hotels',
    emoji: '🏨',
    synonyms: ['Unterkunft', 'Pension'],
    collocations: ['ein Hotel buchen', 'im Hotel übernachten', 'ein Hotel suchen'],
    exampleSentence: 'Das Hotel ist am Strand.',
    exampleTranslation: 'Otel sahilde.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-9',
    german: 'Reisepass',
    turkish: 'Pasaport',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Reisepässe',
    emoji: '🛂',
    synonyms: ['Pass'],
    collocations: ['den Reisepass vorzeigen', 'den Reisepass verlängern', 'einen Reisepass beantragen'],
    exampleSentence: 'Haben Sie Ihren Reisepass?',
    exampleTranslation: 'Pasaportunuz var mı?',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-10',
    german: 'Urlaub',
    turkish: 'Tatil',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Urlaube',
    emoji: '🏖️',
    synonyms: ['Ferien', 'Freizeit'],
    collocations: ['Urlaub machen', 'in den Urlaub fahren', 'Urlaub nehmen'],
    exampleSentence: 'Im Sommer machen wir Urlaub.',
    exampleTranslation: 'Yazın tatil yapıyoruz.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-11',
    german: 'Straße',
    turkish: 'Sokak/Cadde',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Straßen',
    emoji: '🛣️',
    synonyms: ['Weg', 'Gasse'],
    collocations: ['die Straße überqueren', 'auf der Straße gehen', 'eine breite Straße'],
    exampleSentence: 'Die Straße ist sehr lang.',
    exampleTranslation: 'Cadde çok uzun.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-12',
    german: 'links',
    turkish: 'sol',
    article: null,
    partOfSpeech: 'adverb',
    emoji: '⬅️',
    antonyms: ['rechts'],
    collocations: ['nach links gehen', 'links abbiegen'],
    exampleSentence: 'Gehen Sie links!',
    exampleTranslation: 'Sola gidin!',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-13',
    german: 'rechts',
    turkish: 'sağ',
    article: null,
    partOfSpeech: 'adverb',
    emoji: '➡️',
    antonyms: ['links'],
    collocations: ['nach rechts gehen', 'rechts abbiegen'],
    exampleSentence: 'Die Bank ist rechts.',
    exampleTranslation: 'Banka sağda.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-14',
    german: 'geradeaus',
    turkish: 'düz/ileri',
    article: null,
    partOfSpeech: 'adverb',
    emoji: '⬆️',
    collocations: ['geradeaus gehen', 'immer geradeaus fahren'],
    exampleSentence: 'Gehen Sie geradeaus!',
    exampleTranslation: 'Düz gidin!',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-15',
    german: 'Meer',
    turkish: 'Deniz',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Meere',
    emoji: '🌊',
    synonyms: ['Ozean', 'See'],
    collocations: ['ans Meer fahren', 'am Meer wohnen', 'das offene Meer'],
    exampleSentence: 'Das Meer ist blau und warm.',
    exampleTranslation: 'Deniz mavi ve sıcak.',
    category: 'travel',
    level: 'A2',
  },
  {
    id: 'travel-16',
    german: 'Unterkunft',
    turkish: 'Konaklama',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Unterkünfte',
    emoji: '🏠',
    synonyms: ['Bleibe', 'Quartier', 'Übernachtungsmöglichkeit'],
    collocations: ['eine Unterkunft buchen', 'eine günstige Unterkunft finden', 'die Unterkunft wechseln'],
    exampleSentence: 'Wir haben eine gemütliche Unterkunft direkt am See gefunden.',
    exampleTranslation: 'Gölün hemen yanında rahat bir konaklama yeri bulduk.',
    category: 'travel',
    level: 'B2',
    tags: ['accommodation', 'booking'],
  },
  {
    id: 'travel-17',
    german: 'Verspätung',
    turkish: 'Gecikme/Rötar',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Verspätungen',
    emoji: '⏳',
    synonyms: ['Verzögerung', 'Aufschub'],
    antonyms: ['Pünktlichkeit'],
    collocations: ['eine Verspätung haben', 'mit Verspätung ankommen', 'die Verspätung beträgt 30 Minuten'],
    exampleSentence: 'Wegen des schlechten Wetters hatte unser Flug zwei Stunden Verspätung.',
    exampleTranslation: 'Kötü hava nedeniyle uçuşumuz iki saat rötar yaptı.',
    category: 'travel',
    level: 'B2',
    tags: ['delay', 'transport'],
  },
  {
    id: 'travel-18',
    german: 'umsteigen',
    turkish: 'Aktarma yapmak',
    article: null,
    partOfSpeech: 'verb',
    emoji: '🔄',
    synonyms: ['wechseln', 'umsatteln'],
    collocations: ['in einen anderen Zug umsteigen', 'am Hauptbahnhof umsteigen', 'ohne Umsteigen fahren'],
    exampleSentence: 'Sie müssen in Frankfurt umsteigen, um nach München zu gelangen.',
    exampleTranslation: 'Münih\'e ulaşmak için Frankfurt\'ta aktarma yapmanız gerekiyor.',
    category: 'travel',
    level: 'B2',
    tags: ['transport', 'connection'],
  },
  {
    id: 'travel-19',
    german: 'Sehenswürdigkeit',
    turkish: 'Turistik yer/Görülmeye değer yer',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Sehenswürdigkeiten',
    emoji: '🏛️',
    synonyms: ['Attraktion', 'Wahrzeichen'],
    collocations: ['Sehenswürdigkeiten besichtigen', 'die wichtigsten Sehenswürdigkeiten', 'eine berühmte Sehenswürdigkeit'],
    exampleSentence: 'Das Brandenburger Tor ist eine der bekanntesten Sehenswürdigkeiten Berlins.',
    exampleTranslation: 'Brandenburg Kapısı, Berlin\'in en ünlü turistik yerlerinden biridir.',
    category: 'travel',
    level: 'B2',
    tags: ['sightseeing', 'tourism'],
  },
  {
    id: 'travel-20',
    german: 'Reiseführer',
    turkish: 'Gezi rehberi',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Reiseführer',
    emoji: '📗',
    synonyms: ['Touristenführer', 'Guide'],
    collocations: ['einen Reiseführer kaufen', 'im Reiseführer nachschlagen', 'ein deutschsprachiger Reiseführer'],
    exampleSentence: 'Der Reiseführer empfiehlt dieses kleine Restaurant abseits der Touristenpfade.',
    exampleTranslation: 'Gezi rehberi, turist yollarından uzaktaki bu küçük restoranı tavsiye ediyor.',
    category: 'travel',
    level: 'B2',
    tags: ['guide', 'information'],
  },
  {
    id: 'travel-21',
    german: 'Botschaft',
    turkish: 'Büyükelçilik',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Botschaften',
    emoji: '🏛️',
    synonyms: ['Konsulat', 'Vertretung'],
    collocations: ['die Botschaft kontaktieren', 'bei der Botschaft vorsprechen', 'ein Visum bei der Botschaft beantragen'],
    exampleSentence: 'Im Notfall sollten Sie sich an die Botschaft Ihres Landes wenden.',
    exampleTranslation: 'Acil bir durumda ülkenizin büyükelçiliğine başvurmalısınız.',
    category: 'travel',
    level: 'B2',
    tags: ['embassy', 'official'],
  },
  {
    id: 'travel-22',
    german: 'Versicherung',
    turkish: 'Sigorta',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Versicherungen',
    emoji: '🛡️',
    synonyms: ['Absicherung', 'Schutz'],
    collocations: ['eine Versicherung abschließen', 'eine Reiseversicherung haben', 'die Versicherung deckt die Kosten'],
    exampleSentence: 'Eine Reiseversicherung ist bei Auslandsreisen dringend zu empfehlen.',
    exampleTranslation: 'Yurt dışı seyahatlerinde seyahat sigortası şiddetle tavsiye edilir.',
    category: 'travel',
    level: 'B2',
    tags: ['insurance', 'safety'],
  },
  {
    id: 'travel-23',
    german: 'Aufenthalt',
    turkish: 'Kalış/İkamet',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Aufenthalte',
    emoji: '🏡',
    synonyms: ['Verweilen', 'Bleibe'],
    collocations: ['ein angenehmer Aufenthalt', 'den Aufenthalt verlängern', 'einen kurzen Aufenthalt haben'],
    exampleSentence: 'Während unseres Aufenthalts in Wien haben wir zahlreiche Museen besucht.',
    exampleTranslation: 'Viyana\'daki kalışımız süresince birçok müze ziyaret ettik.',
    category: 'travel',
    level: 'B2',
    tags: ['stay', 'duration'],
  },
  {
    id: 'travel-24',
    german: 'Abflug',
    turkish: 'Kalkış',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Abflüge',
    emoji: '🛫',
    synonyms: ['Start', 'Abreise'],
    antonyms: ['Ankunft', 'Landung'],
    collocations: ['der Abflug ist um 8 Uhr', 'den Abflug verpassen', 'die Abflugtafel prüfen'],
    exampleSentence: 'Der Abflug wurde wegen eines technischen Problems auf den Nachmittag verschoben.',
    exampleTranslation: 'Kalkış, teknik bir sorun nedeniyle öğleden sonraya ertelendi.',
    category: 'travel',
    level: 'B2',
    tags: ['flight', 'departure'],
  },
  {
    id: 'travel-25',
    german: 'Ankunft',
    turkish: 'Varış',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Ankünfte',
    emoji: '🛬',
    synonyms: ['Eintreffen', 'Anreise'],
    antonyms: ['Abflug', 'Abreise'],
    collocations: ['die Ankunft verzögert sich', 'pünktliche Ankunft', 'bei Ankunft am Flughafen'],
    exampleSentence: 'Nach der Ankunft am Flughafen haben wir direkt ein Taxi zum Hotel genommen.',
    exampleTranslation: 'Havalimanına varışımızın ardından doğrudan otele bir taksi aldık.',
    category: 'travel',
    level: 'B2',
    tags: ['flight', 'arrival'],
  },
];
