import { VocabularyWord } from '@/lib/types';

export const verbsWords: VocabularyWord[] = [
  {
    id: 'verbs-1',
    german: 'sein',
    turkish: 'Olmak',
    english: 'To be',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['existieren', 'dasein'],
    collocations: ['glücklich sein', 'müde sein', 'zu Hause sein'],
    emoji: '🔵',
    exampleSentence: 'Ich bin Student.',
    exampleTranslation: 'Ben öğrenciyim.',
    exampleTranslationEn: 'I am a student.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-2',
    german: 'haben',
    turkish: 'Sahip olmak',
    english: 'To have',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['besitzen', 'verfügen über'],
    collocations: ['Hunger haben', 'Zeit haben', 'Recht haben'],
    emoji: '✋',
    exampleSentence: 'Ich habe zwei Geschwister.',
    exampleTranslation: 'İki kardeşim var.',
    exampleTranslationEn: 'I have two siblings.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-3',
    german: 'machen',
    turkish: 'Yapmak',
    english: 'To do / To make',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['tun', 'herstellen'],
    collocations: ['Hausaufgaben machen', 'Sport machen', 'Urlaub machen'],
    emoji: '🛠️',
    exampleSentence: 'Was machst du heute Abend?',
    exampleTranslation: 'Bu akşam ne yapıyorsun?',
    exampleTranslationEn: 'What are you doing tonight?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-4',
    german: 'gehen',
    turkish: 'Gitmek / Yürümek',
    english: 'To go / To walk',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['laufen', 'spazieren'],
    collocations: ['nach Hause gehen', 'spazieren gehen', 'einkaufen gehen'],
    emoji: '🚶',
    exampleSentence: 'Ich gehe jeden Morgen spazieren.',
    exampleTranslation: 'Her sabah yürüyüşe gidiyorum.',
    exampleTranslationEn: 'I go for a walk every morning.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-5',
    german: 'kommen',
    turkish: 'Gelmek',
    english: 'To come',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['ankommen', 'eintreffen'],
    collocations: ['aus Deutschland kommen', 'zu Besuch kommen'],
    emoji: '👋',
    exampleSentence: 'Woher kommst du?',
    exampleTranslation: 'Nerelisin?',
    exampleTranslationEn: 'Where do you come from?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-6',
    german: 'essen',
    turkish: 'Yemek yemek',
    english: 'To eat',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['speisen', 'sich ernähren'],
    collocations: ['zu Mittag essen', 'zu Abend essen'],
    emoji: '🍽️',
    exampleSentence: 'Was möchtest du essen?',
    exampleTranslation: 'Ne yemek istersin?',
    exampleTranslationEn: 'What would you like to eat?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-7',
    german: 'trinken',
    turkish: 'İçmek',
    english: 'To drink',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['schlürfen', 'nippen'],
    collocations: ['Wasser trinken', 'Kaffee trinken'],
    emoji: '🥤',
    exampleSentence: 'Ich trinke morgens immer Kaffee.',
    exampleTranslation: 'Sabahları hep kahve içerim.',
    exampleTranslationEn: 'I always drink coffee in the morning.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-8',
    german: 'sprechen',
    turkish: 'Konuşmak',
    english: 'To speak',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['reden', 'sich unterhalten'],
    collocations: ['Deutsch sprechen', 'über etwas sprechen'],
    emoji: '🗣️',
    exampleSentence: 'Sprechen Sie Deutsch?',
    exampleTranslation: 'Almanca konuşuyor musunuz?',
    exampleTranslationEn: 'Do you speak German?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-9',
    german: 'wohnen',
    turkish: 'Oturmak / İkamet etmek',
    english: 'To live (reside)',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['leben', 'residieren'],
    collocations: ['in Berlin wohnen', 'allein wohnen'],
    emoji: '🏠',
    exampleSentence: 'Wo wohnst du?',
    exampleTranslation: 'Nerede oturuyorsun?',
    exampleTranslationEn: 'Where do you live?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-10',
    german: 'arbeiten',
    turkish: 'Çalışmak',
    english: 'To work',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['schaffen', 'tätig sein'],
    collocations: ['hart arbeiten', 'als Ingenieur arbeiten'],
    emoji: '💼',
    exampleSentence: 'Ich arbeite als Programmierer.',
    exampleTranslation: 'Programcı olarak çalışıyorum.',
    exampleTranslationEn: 'I work as a programmer.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-11',
    german: 'kaufen',
    turkish: 'Satın almak',
    english: 'To buy',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['erwerben', 'anschaffen'],
    antonyms: ['verkaufen'],
    collocations: ['ein Auto kaufen', 'online kaufen'],
    emoji: '🛒',
    exampleSentence: 'Ich möchte ein neues Buch kaufen.',
    exampleTranslation: 'Yeni bir kitap almak istiyorum.',
    exampleTranslationEn: 'I want to buy a new book.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-12',
    german: 'schlafen',
    turkish: 'Uyumak',
    english: 'To sleep',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['ruhen', 'pennen'],
    antonyms: ['aufwachen'],
    collocations: ['gut schlafen', 'lange schlafen'],
    emoji: '😴',
    exampleSentence: 'Ich habe letzte Nacht schlecht geschlafen.',
    exampleTranslation: 'Dün gece kötü uyudum.',
    exampleTranslationEn: 'I slept badly last night.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-13',
    german: 'verstehen',
    turkish: 'Anlamak',
    english: 'To understand',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['begreifen', 'kapieren'],
    collocations: ['gut verstehen', 'nicht verstehen'],
    emoji: '💡',
    exampleSentence: 'Ich verstehe die Frage nicht.',
    exampleTranslation: 'Soruyu anlamıyorum.',
    exampleTranslationEn: 'I don\'t understand the question.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-14',
    german: 'helfen',
    turkish: 'Yardım etmek',
    english: 'To help',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['unterstützen', 'beistehen'],
    collocations: ['jemandem helfen', 'bei der Arbeit helfen'],
    emoji: '🤝',
    exampleSentence: 'Kann ich dir helfen?',
    exampleTranslation: 'Sana yardım edebilir miyim?',
    exampleTranslationEn: 'Can I help you?',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-15',
    german: 'denken',
    turkish: 'Düşünmek',
    english: 'To think',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['überlegen', 'nachdenken', 'glauben'],
    collocations: ['an jemanden denken', 'darüber nachdenken'],
    emoji: '🤔',
    exampleSentence: 'Was denkst du darüber?',
    exampleTranslation: 'Bu konuda ne düşünüyorsun?',
    exampleTranslationEn: 'What do you think about it?',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-16',
    german: 'wissen',
    turkish: 'Bilmek',
    english: 'To know (facts)',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['kennen', 'Bescheid wissen'],
    collocations: ['das weiß ich nicht', 'Bescheid wissen'],
    emoji: '🧠',
    exampleSentence: 'Ich weiß nicht, wo er ist.',
    exampleTranslation: 'Nerede olduğunu bilmiyorum.',
    exampleTranslationEn: 'I don\'t know where he is.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-17',
    german: 'brauchen',
    turkish: 'İhtiyacı olmak',
    english: 'To need',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['benötigen', 'erfordern'],
    collocations: ['Hilfe brauchen', 'Zeit brauchen'],
    emoji: '❗',
    exampleSentence: 'Ich brauche deine Hilfe.',
    exampleTranslation: 'Yardımına ihtiyacım var.',
    exampleTranslationEn: 'I need your help.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-18',
    german: 'finden',
    turkish: 'Bulmak',
    english: 'To find',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['entdecken', 'aufspüren'],
    antonyms: ['verlieren'],
    collocations: ['einen Job finden', 'etwas gut finden'],
    emoji: '🔍',
    exampleSentence: 'Ich finde meinen Schlüssel nicht.',
    exampleTranslation: 'Anahtarımı bulamıyorum.',
    exampleTranslationEn: 'I can\'t find my key.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-19',
    german: 'geben',
    turkish: 'Vermek',
    english: 'To give',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['überreichen', 'schenken'],
    antonyms: ['nehmen'],
    collocations: ['ein Geschenk geben', 'es gibt'],
    emoji: '🎁',
    exampleSentence: 'Gibst du mir bitte das Salz?',
    exampleTranslation: 'Bana tuzu verir misin lütfen?',
    exampleTranslationEn: 'Can you give me the salt please?',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-20',
    german: 'nehmen',
    turkish: 'Almak',
    english: 'To take',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['greifen', 'ergreifen'],
    antonyms: ['geben'],
    collocations: ['den Bus nehmen', 'Platz nehmen'],
    emoji: '👊',
    exampleSentence: 'Ich nehme den Bus zur Arbeit.',
    exampleTranslation: 'İşe otobüsle gidiyorum.',
    exampleTranslationEn: 'I take the bus to work.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-21',
    german: 'sich entscheiden',
    turkish: 'Karar vermek',
    english: 'To decide',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['beschließen', 'sich festlegen'],
    collocations: ['sich für etwas entscheiden', 'schnell entscheiden'],
    emoji: '⚖️',
    exampleSentence: 'Ich kann mich nicht entscheiden.',
    exampleTranslation: 'Karar veremiyorum.',
    exampleTranslationEn: 'I can\'t decide.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-22',
    german: 'sich beschweren',
    turkish: 'Şikayet etmek',
    english: 'To complain',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['reklamieren', 'protestieren'],
    collocations: ['sich über etwas beschweren', 'sich beim Chef beschweren'],
    emoji: '😤',
    exampleSentence: 'Er beschwert sich immer über das Essen.',
    exampleTranslation: 'Her zaman yemekten şikayet ediyor.',
    exampleTranslationEn: 'He always complains about the food.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-23',
    german: 'vorschlagen',
    turkish: 'Önermek / Teklif etmek',
    english: 'To suggest',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['empfehlen', 'anregen'],
    collocations: ['einen Plan vorschlagen', 'etwas Neues vorschlagen'],
    emoji: '💬',
    exampleSentence: 'Ich schlage vor, dass wir morgen anfangen.',
    exampleTranslation: 'Yarın başlamamızı öneriyorum.',
    exampleTranslationEn: 'I suggest that we start tomorrow.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-24',
    german: 'sich gewöhnen',
    turkish: 'Alışmak',
    english: 'To get used to',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich anpassen'],
    collocations: ['sich an etwas gewöhnen', 'sich daran gewöhnen'],
    emoji: '🔄',
    exampleSentence: 'Ich habe mich an das kalte Wetter gewöhnt.',
    exampleTranslation: 'Soğuk havaya alıştım.',
    exampleTranslationEn: 'I got used to the cold weather.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-25',
    german: 'beeinflussen',
    turkish: 'Etkilemek',
    english: 'To influence',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['einwirken', 'prägen'],
    collocations: ['positiv beeinflussen', 'stark beeinflussen'],
    emoji: '🎯',
    exampleSentence: 'Soziale Medien beeinflussen unser Verhalten.',
    exampleTranslation: 'Sosyal medya davranışlarımızı etkiliyor.',
    exampleTranslationEn: 'Social media influences our behavior.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-26',
    german: 'berücksichtigen',
    turkish: 'Göz önünde bulundurmak',
    english: 'To take into consideration',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['beachten', 'einbeziehen'],
    collocations: ['alle Faktoren berücksichtigen', 'berücksichtigt werden'],
    emoji: '📊',
    exampleSentence: 'Wir müssen alle Aspekte berücksichtigen.',
    exampleTranslation: 'Tüm yönleri göz önünde bulundurmalıyız.',
    exampleTranslationEn: 'We must take all aspects into consideration.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-27',
    german: 'verwirklichen',
    turkish: 'Gerçekleştirmek',
    english: 'To realize / To achieve',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['realisieren', 'umsetzen'],
    collocations: ['einen Traum verwirklichen', 'Ideen verwirklichen'],
    emoji: '🌟',
    exampleSentence: 'Sie hat ihren Traum verwirklicht.',
    exampleTranslation: 'Hayalini gerçekleştirdi.',
    exampleTranslationEn: 'She realized her dream.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-28',
    german: 'zusammenfassen',
    turkish: 'Özetlemek',
    english: 'To summarize',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['resümieren', 'auf den Punkt bringen'],
    collocations: ['die Ergebnisse zusammenfassen', 'kurz zusammenfassen'],
    emoji: '📋',
    exampleSentence: 'Können Sie die wichtigsten Punkte zusammenfassen?',
    exampleTranslation: 'En önemli noktaları özetleyebilir misiniz?',
    exampleTranslationEn: 'Can you summarize the most important points?',
    category: 'verbs',
    level: 'B2',
  },
  // === NEW A1 VERBS (verbs-29 to verbs-41) ===
  {
    id: 'verbs-29',
    german: 'lesen',
    turkish: 'Okumak',
    english: 'To read',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['durchlesen', 'studieren'],
    collocations: ['ein Buch lesen', 'Zeitung lesen'],
    emoji: '📖',
    exampleSentence: 'Ich lese gern Romane.',
    exampleTranslation: 'Roman okumayı severim.',
    exampleTranslationEn: 'I like to read novels.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-30',
    german: 'schreiben',
    turkish: 'Yazmak',
    english: 'To write',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['verfassen', 'notieren'],
    collocations: ['einen Brief schreiben', 'eine E-Mail schreiben'],
    emoji: '✍️',
    exampleSentence: 'Ich schreibe meiner Mutter eine E-Mail.',
    exampleTranslation: 'Anneme bir e-posta yazıyorum.',
    exampleTranslationEn: 'I am writing an email to my mother.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-31',
    german: 'lernen',
    turkish: 'Öğrenmek',
    english: 'To learn',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['studieren', 'sich aneignen'],
    collocations: ['Deutsch lernen', 'für die Prüfung lernen'],
    emoji: '📚',
    exampleSentence: 'Ich lerne seit zwei Jahren Deutsch.',
    exampleTranslation: 'İki yıldır Almanca öğreniyorum.',
    exampleTranslationEn: 'I have been learning German for two years.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-32',
    german: 'spielen',
    turkish: 'Oynamak',
    english: 'To play',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich vergnügen', 'musizieren'],
    collocations: ['Fußball spielen', 'Klavier spielen', 'eine Rolle spielen'],
    emoji: '⚽',
    exampleSentence: 'Die Kinder spielen im Garten.',
    exampleTranslation: 'Çocuklar bahçede oynuyor.',
    exampleTranslationEn: 'The children are playing in the garden.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-33',
    german: 'fahren',
    turkish: 'Sürmek / Gitmek (araçla)',
    english: 'To drive / To go (by vehicle)',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['reisen', 'steuern'],
    collocations: ['Auto fahren', 'mit dem Zug fahren', 'Fahrrad fahren'],
    emoji: '🚗',
    exampleSentence: 'Ich fahre mit dem Zug nach München.',
    exampleTranslation: 'Trenle Münih\'e gidiyorum.',
    exampleTranslationEn: 'I am going to Munich by train.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-34',
    german: 'sehen',
    turkish: 'Görmek',
    english: 'To see',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['erblicken', 'bemerken'],
    collocations: ['einen Film sehen', 'gut sehen'],
    emoji: '👀',
    exampleSentence: 'Ich sehe dich morgen.',
    exampleTranslation: 'Yarın görüşürüz.',
    exampleTranslationEn: 'I will see you tomorrow.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-35',
    german: 'hören',
    turkish: 'Duymak / Dinlemek',
    english: 'To hear / To listen',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['lauschen', 'zuhören'],
    collocations: ['Musik hören', 'gut hören'],
    emoji: '👂',
    exampleSentence: 'Ich höre gerne Musik.',
    exampleTranslation: 'Müzik dinlemeyi severim.',
    exampleTranslationEn: 'I like listening to music.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-36',
    german: 'kochen',
    turkish: 'Yemek pişirmek',
    english: 'To cook',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['zubereiten', 'braten'],
    collocations: ['das Essen kochen', 'Wasser kochen'],
    emoji: '🍳',
    exampleSentence: 'Meine Mutter kocht sehr gut.',
    exampleTranslation: 'Annem çok iyi yemek pişirir.',
    exampleTranslationEn: 'My mother cooks very well.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-37',
    german: 'fragen',
    turkish: 'Sormak',
    english: 'To ask',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['befragen', 'sich erkundigen'],
    antonyms: ['antworten'],
    collocations: ['eine Frage fragen', 'nach dem Weg fragen'],
    emoji: '❓',
    exampleSentence: 'Darf ich Sie etwas fragen?',
    exampleTranslation: 'Size bir şey sorabilir miyim?',
    exampleTranslationEn: 'May I ask you something?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-38',
    german: 'antworten',
    turkish: 'Cevap vermek',
    english: 'To answer',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['erwidern', 'reagieren'],
    antonyms: ['fragen'],
    collocations: ['auf eine Frage antworten', 'schnell antworten'],
    emoji: '💬',
    exampleSentence: 'Er antwortet nicht auf meine Nachricht.',
    exampleTranslation: 'Mesajıma cevap vermiyor.',
    exampleTranslationEn: 'He is not answering my message.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-39',
    german: 'heißen',
    turkish: 'Adı olmak',
    english: 'To be called',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich nennen', 'bedeuten'],
    collocations: ['Wie heißen Sie?', 'das heißt'],
    emoji: '🏷️',
    exampleSentence: 'Wie heißen Sie?',
    exampleTranslation: 'Adınız ne?',
    exampleTranslationEn: 'What is your name?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-40',
    german: 'möchten',
    turkish: 'İstemek',
    english: 'To would like',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['wollen', 'wünschen'],
    collocations: ['etwas möchten', 'gerne möchten'],
    emoji: '🙏',
    exampleSentence: 'Ich möchte ein Glas Wasser, bitte.',
    exampleTranslation: 'Bir bardak su istiyorum, lütfen.',
    exampleTranslationEn: 'I would like a glass of water, please.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-41',
    german: 'öffnen',
    turkish: 'Açmak',
    english: 'To open',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['aufmachen', 'erschließen'],
    antonyms: ['schließen'],
    collocations: ['die Tür öffnen', 'ein Fenster öffnen'],
    emoji: '🚪',
    exampleSentence: 'Bitte öffnen Sie das Fenster.',
    exampleTranslation: 'Lütfen pencereyi açın.',
    exampleTranslationEn: 'Please open the window.',
    category: 'verbs',
    level: 'A1',
  },
  // === NEW A2 VERBS (verbs-42 to verbs-58) ===
  {
    id: 'verbs-42',
    german: 'warten',
    turkish: 'Beklemek',
    english: 'To wait',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['abwarten', 'ausharren'],
    collocations: ['auf jemanden warten', 'lange warten'],
    emoji: '⏳',
    exampleSentence: 'Ich warte seit einer Stunde auf dich.',
    exampleTranslation: 'Bir saattir seni bekliyorum.',
    exampleTranslationEn: 'I have been waiting for you for an hour.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-43',
    german: 'bringen',
    turkish: 'Getirmek',
    english: 'To bring',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['mitbringen', 'liefern'],
    collocations: ['etwas mitbringen', 'nach Hause bringen'],
    emoji: '📦',
    exampleSentence: 'Kannst du mir ein Glas Wasser bringen?',
    exampleTranslation: 'Bana bir bardak su getirir misin?',
    exampleTranslationEn: 'Can you bring me a glass of water?',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-44',
    german: 'beginnen',
    turkish: 'Başlamak',
    english: 'To begin',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['anfangen', 'starten'],
    antonyms: ['beenden', 'aufhören'],
    collocations: ['mit der Arbeit beginnen', 'von vorne beginnen'],
    emoji: '▶️',
    exampleSentence: 'Der Unterricht beginnt um neun Uhr.',
    exampleTranslation: 'Ders saat dokuzda başlıyor.',
    exampleTranslationEn: 'The class begins at nine o\'clock.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-45',
    german: 'aufhören',
    turkish: 'Bırakmak / Durmak',
    english: 'To stop / To cease',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['beenden', 'stoppen'],
    antonyms: ['anfangen', 'beginnen'],
    collocations: ['mit dem Rauchen aufhören', 'aufhören zu regnen'],
    emoji: '🛑',
    exampleSentence: 'Hör bitte auf zu rauchen!',
    exampleTranslation: 'Lütfen sigara içmeyi bırak!',
    exampleTranslationEn: 'Please stop smoking!',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-46',
    german: 'vergessen',
    turkish: 'Unutmak',
    english: 'To forget',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['entfallen', 'nicht daran denken'],
    antonyms: ['sich erinnern'],
    collocations: ['den Termin vergessen', 'nie vergessen'],
    emoji: '🤷',
    exampleSentence: 'Ich habe meinen Regenschirm vergessen.',
    exampleTranslation: 'Şemsiyemi unuttum.',
    exampleTranslationEn: 'I forgot my umbrella.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-47',
    german: 'sich erinnern',
    turkish: 'Hatırlamak',
    english: 'To remember',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich entsinnen', 'sich besinnen'],
    antonyms: ['vergessen'],
    collocations: ['sich an etwas erinnern', 'sich gut erinnern'],
    emoji: '💭',
    exampleSentence: 'Ich erinnere mich nicht an seinen Namen.',
    exampleTranslation: 'Adını hatırlamıyorum.',
    exampleTranslationEn: 'I don\'t remember his name.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-48',
    german: 'bekommen',
    turkish: 'Almak / Elde etmek',
    english: 'To get / To receive',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['erhalten', 'kriegen'],
    collocations: ['ein Geschenk bekommen', 'Besuch bekommen'],
    emoji: '🎉',
    exampleSentence: 'Ich habe eine gute Note bekommen.',
    exampleTranslation: 'İyi bir not aldım.',
    exampleTranslationEn: 'I got a good grade.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-49',
    german: 'versuchen',
    turkish: 'Denemek',
    english: 'To try',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['probieren', 'es wagen'],
    collocations: ['es versuchen', 'etwas Neues versuchen'],
    emoji: '💪',
    exampleSentence: 'Ich versuche, früher aufzustehen.',
    exampleTranslation: 'Daha erken kalkmaya çalışıyorum.',
    exampleTranslationEn: 'I am trying to get up earlier.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-50',
    german: 'erklären',
    turkish: 'Açıklamak',
    english: 'To explain',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['erläutern', 'verdeutlichen'],
    collocations: ['etwas erklären', 'genau erklären'],
    emoji: '📝',
    exampleSentence: 'Können Sie mir das bitte erklären?',
    exampleTranslation: 'Bunu bana açıklayabilir misiniz lütfen?',
    exampleTranslationEn: 'Can you please explain this to me?',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-51',
    german: 'zeigen',
    turkish: 'Göstermek',
    english: 'To show',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['vorführen', 'demonstrieren'],
    collocations: ['den Weg zeigen', 'Interesse zeigen'],
    emoji: '👉',
    exampleSentence: 'Können Sie mir den Weg zeigen?',
    exampleTranslation: 'Bana yolu gösterebilir misiniz?',
    exampleTranslationEn: 'Can you show me the way?',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-52',
    german: 'stellen',
    turkish: 'Koymak / Yerleştirmek',
    english: 'To put / To place',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['setzen', 'legen'],
    collocations: ['eine Frage stellen', 'auf den Tisch stellen'],
    emoji: '📍',
    exampleSentence: 'Stell die Blumen auf den Tisch.',
    exampleTranslation: 'Çiçekleri masanın üstüne koy.',
    exampleTranslationEn: 'Put the flowers on the table.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-53',
    german: 'laufen',
    turkish: 'Koşmak / Yürümek',
    english: 'To run / To walk',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['rennen', 'joggen'],
    collocations: ['schnell laufen', 'Marathon laufen'],
    emoji: '🏃',
    exampleSentence: 'Er läuft jeden Tag fünf Kilometer.',
    exampleTranslation: 'Her gün beş kilometre koşuyor.',
    exampleTranslationEn: 'He runs five kilometers every day.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-54',
    german: 'tragen',
    turkish: 'Taşımak / Giymek',
    english: 'To carry / To wear',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['transportieren', 'anhaben'],
    collocations: ['eine Brille tragen', 'Verantwortung tragen'],
    emoji: '👔',
    exampleSentence: 'Sie trägt heute ein rotes Kleid.',
    exampleTranslation: 'Bugün kırmızı bir elbise giyiyor.',
    exampleTranslationEn: 'She is wearing a red dress today.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-55',
    german: 'bezahlen',
    turkish: 'Ödemek',
    english: 'To pay',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['zahlen', 'begleichen'],
    collocations: ['die Rechnung bezahlen', 'bar bezahlen'],
    emoji: '💳',
    exampleSentence: 'Ich möchte bitte bezahlen.',
    exampleTranslation: 'Hesabı ödemek istiyorum lütfen.',
    exampleTranslationEn: 'I would like to pay, please.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-56',
    german: 'glauben',
    turkish: 'İnanmak',
    english: 'To believe',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['meinen', 'vertrauen'],
    collocations: ['an Gott glauben', 'ich glaube schon'],
    emoji: '🙌',
    exampleSentence: 'Ich glaube, er hat recht.',
    exampleTranslation: 'Haklı olduğuna inanıyorum.',
    exampleTranslationEn: 'I believe he is right.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-57',
    german: 'sich freuen',
    turkish: 'Sevinmek',
    english: 'To be glad / To look forward to',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['froh sein', 'sich begeistern'],
    collocations: ['sich auf etwas freuen', 'sich über etwas freuen'],
    emoji: '😊',
    exampleSentence: 'Ich freue mich auf den Urlaub.',
    exampleTranslation: 'Tatili dört gözle bekliyorum.',
    exampleTranslationEn: 'I am looking forward to the vacation.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-58',
    german: 'besuchen',
    turkish: 'Ziyaret etmek',
    english: 'To visit',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['aufsuchen', 'vorbeikommen'],
    collocations: ['Freunde besuchen', 'einen Kurs besuchen'],
    emoji: '🏡',
    exampleSentence: 'Ich besuche meine Großeltern am Wochenende.',
    exampleTranslation: 'Hafta sonu büyükannemi ve büyükbabamı ziyaret ediyorum.',
    exampleTranslationEn: 'I visit my grandparents on the weekend.',
    category: 'verbs',
    level: 'A2',
  },
  // === NEW B1 VERBS (verbs-59 to verbs-79) ===
  {
    id: 'verbs-59',
    german: 'sich bewerben',
    turkish: 'Başvurmak',
    english: 'To apply (for a job)',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['kandidieren', 'sich vorstellen'],
    collocations: ['sich um eine Stelle bewerben', 'sich online bewerben'],
    emoji: '📄',
    exampleSentence: 'Ich bewerbe mich um die Stelle als Ingenieur.',
    exampleTranslation: 'Mühendislik pozisyonuna başvuruyorum.',
    exampleTranslationEn: 'I am applying for the position as an engineer.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-60',
    german: 'empfehlen',
    turkish: 'Tavsiye etmek',
    english: 'To recommend',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['raten', 'vorschlagen'],
    collocations: ['ein Restaurant empfehlen', 'dringend empfehlen'],
    emoji: '👍',
    exampleSentence: 'Ich kann dieses Buch empfehlen.',
    exampleTranslation: 'Bu kitabı tavsiye edebilirim.',
    exampleTranslationEn: 'I can recommend this book.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-61',
    german: 'erlauben',
    turkish: 'İzin vermek',
    english: 'To allow / To permit',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['gestatten', 'genehmigen'],
    antonyms: ['verbieten'],
    collocations: ['jemandem etwas erlauben', 'nicht erlaubt sein'],
    emoji: '✅',
    exampleSentence: 'Meine Eltern erlauben mir nicht, spät auszugehen.',
    exampleTranslation: 'Ailem geç saatlerde dışarı çıkmama izin vermiyor.',
    exampleTranslationEn: 'My parents do not allow me to go out late.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-62',
    german: 'verbieten',
    turkish: 'Yasaklamak',
    english: 'To forbid / To prohibit',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['untersagen', 'nicht erlauben'],
    antonyms: ['erlauben'],
    collocations: ['das Rauchen verbieten', 'streng verboten'],
    emoji: '🚫',
    exampleSentence: 'Rauchen ist hier verboten.',
    exampleTranslation: 'Burada sigara içmek yasak.',
    exampleTranslationEn: 'Smoking is forbidden here.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-63',
    german: 'vergleichen',
    turkish: 'Karşılaştırmak',
    english: 'To compare',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['gegenüberstellen', 'abwägen'],
    collocations: ['Preise vergleichen', 'miteinander vergleichen'],
    emoji: '🔀',
    exampleSentence: 'Man sollte die Preise vergleichen, bevor man kauft.',
    exampleTranslation: 'Satın almadan önce fiyatları karşılaştırmalısınız.',
    exampleTranslationEn: 'You should compare prices before buying.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-64',
    german: 'sich unterhalten',
    turkish: 'Sohbet etmek',
    english: 'To have a conversation',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['plaudern', 'sich austauschen'],
    collocations: ['sich über etwas unterhalten', 'sich gut unterhalten'],
    emoji: '🗨️',
    exampleSentence: 'Wir haben uns lange über Politik unterhalten.',
    exampleTranslation: 'Uzun süre siyaset hakkında sohbet ettik.',
    exampleTranslationEn: 'We had a long conversation about politics.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-65',
    german: 'sich vorstellen',
    turkish: 'Hayal etmek / Kendini tanıtmak',
    english: 'To imagine / To introduce oneself',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich ausmalen', 'sich präsentieren'],
    collocations: ['sich etwas vorstellen', 'darf ich mich vorstellen'],
    emoji: '🤝',
    exampleSentence: 'Ich kann mir nicht vorstellen, dort zu leben.',
    exampleTranslation: 'Orada yaşamayı hayal edemiyorum.',
    exampleTranslationEn: 'I cannot imagine living there.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-66',
    german: 'verbessern',
    turkish: 'İyileştirmek / Düzeltmek',
    english: 'To improve / To correct',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['optimieren', 'korrigieren'],
    antonyms: ['verschlechtern'],
    collocations: ['die Leistung verbessern', 'sich verbessern'],
    emoji: '📈',
    exampleSentence: 'Ich möchte mein Deutsch verbessern.',
    exampleTranslation: 'Almancamı geliştirmek istiyorum.',
    exampleTranslationEn: 'I want to improve my German.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-67',
    german: 'versprechen',
    turkish: 'Söz vermek',
    english: 'To promise',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['zusichern', 'garantieren'],
    collocations: ['etwas versprechen', 'ein Versprechen geben'],
    emoji: '🤞',
    exampleSentence: 'Ich verspreche dir, pünktlich zu sein.',
    exampleTranslation: 'Sana zamanında olacağıma söz veriyorum.',
    exampleTranslationEn: 'I promise you to be on time.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-68',
    german: 'sich kümmern',
    turkish: 'İlgilenmek / Bakmak',
    english: 'To take care of',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sorgen für', 'betreuen'],
    collocations: ['sich um jemanden kümmern', 'sich darum kümmern'],
    emoji: '🫶',
    exampleSentence: 'Ich kümmere mich um die Kinder.',
    exampleTranslation: 'Çocuklarla ilgileniyorum.',
    exampleTranslationEn: 'I am taking care of the children.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-69',
    german: 'beschreiben',
    turkish: 'Tanımlamak / Betimlemek',
    english: 'To describe',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['schildern', 'darstellen'],
    collocations: ['genau beschreiben', 'eine Situation beschreiben'],
    emoji: '🖊️',
    exampleSentence: 'Können Sie den Täter beschreiben?',
    exampleTranslation: 'Suçluyu tanımlayabilir misiniz?',
    exampleTranslationEn: 'Can you describe the perpetrator?',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-70',
    german: 'sich entschuldigen',
    turkish: 'Özür dilemek',
    english: 'To apologize',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['um Verzeihung bitten', 'bedauern'],
    collocations: ['sich bei jemandem entschuldigen', 'sich für etwas entschuldigen'],
    emoji: '🙇',
    exampleSentence: 'Ich möchte mich für die Verspätung entschuldigen.',
    exampleTranslation: 'Gecikmeden dolayı özür dilemek istiyorum.',
    exampleTranslationEn: 'I would like to apologize for the delay.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-71',
    german: 'vermeiden',
    turkish: 'Kaçınmak',
    english: 'To avoid',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['umgehen', 'ausweichen'],
    collocations: ['Fehler vermeiden', 'Stress vermeiden'],
    emoji: '🚧',
    exampleSentence: 'Ich versuche, Fehler zu vermeiden.',
    exampleTranslation: 'Hatalardan kaçınmaya çalışıyorum.',
    exampleTranslationEn: 'I try to avoid mistakes.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-72',
    german: 'sich anmelden',
    turkish: 'Kayıt olmak',
    english: 'To register / To sign up',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich registrieren', 'sich einschreiben'],
    antonyms: ['sich abmelden'],
    collocations: ['sich für einen Kurs anmelden', 'sich online anmelden'],
    emoji: '📋',
    exampleSentence: 'Ich habe mich für den Deutschkurs angemeldet.',
    exampleTranslation: 'Almanca kursuna kayıt oldum.',
    exampleTranslationEn: 'I registered for the German course.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-73',
    german: 'übersetzen',
    turkish: 'Tercüme etmek / Çevirmek',
    english: 'To translate',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['übertragen', 'dolmetschen'],
    collocations: ['einen Text übersetzen', 'ins Deutsche übersetzen'],
    emoji: '🌐',
    exampleSentence: 'Können Sie diesen Satz übersetzen?',
    exampleTranslation: 'Bu cümleyi çevirebilir misiniz?',
    exampleTranslationEn: 'Can you translate this sentence?',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-74',
    german: 'vorbereiten',
    turkish: 'Hazırlamak',
    english: 'To prepare',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['zubereiten', 'planen'],
    collocations: ['sich auf die Prüfung vorbereiten', 'das Essen vorbereiten'],
    emoji: '📐',
    exampleSentence: 'Ich muss mich auf die Prüfung vorbereiten.',
    exampleTranslation: 'Sınava hazırlanmalıyım.',
    exampleTranslationEn: 'I have to prepare for the exam.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-75',
    german: 'teilnehmen',
    turkish: 'Katılmak',
    english: 'To participate',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['mitmachen', 'sich beteiligen'],
    collocations: ['an einem Kurs teilnehmen', 'an einer Veranstaltung teilnehmen'],
    emoji: '🙋',
    exampleSentence: 'Möchtest du an dem Workshop teilnehmen?',
    exampleTranslation: 'Çalıştaya katılmak ister misin?',
    exampleTranslationEn: 'Would you like to participate in the workshop?',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-76',
    german: 'sich bemühen',
    turkish: 'Çabalamak / Gayret etmek',
    english: 'To make an effort',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich anstrengen', 'sich Mühe geben'],
    collocations: ['sich um etwas bemühen', 'sich sehr bemühen'],
    emoji: '🏋️',
    exampleSentence: 'Er bemüht sich, besser zu werden.',
    exampleTranslation: 'Daha iyi olmak için çabalıyor.',
    exampleTranslationEn: 'He is making an effort to get better.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-77',
    german: 'stattfinden',
    turkish: 'Gerçekleşmek / Yer almak',
    english: 'To take place',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['passieren', 'geschehen'],
    collocations: ['die Veranstaltung findet statt', 'regelmäßig stattfinden'],
    emoji: '📅',
    exampleSentence: 'Das Konzert findet morgen statt.',
    exampleTranslation: 'Konser yarın gerçekleşecek.',
    exampleTranslationEn: 'The concert takes place tomorrow.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-78',
    german: 'sich verabschieden',
    turkish: 'Vedalaşmak',
    english: 'To say goodbye',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['Abschied nehmen', 'sich empfehlen'],
    collocations: ['sich von jemandem verabschieden', 'sich herzlich verabschieden'],
    emoji: '👋',
    exampleSentence: 'Sie hat sich von ihren Kollegen verabschiedet.',
    exampleTranslation: 'İş arkadaşlarıyla vedalaştı.',
    exampleTranslationEn: 'She said goodbye to her colleagues.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-79',
    german: 'enttäuschen',
    turkish: 'Hayal kırıklığına uğratmak',
    english: 'To disappoint',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['frustrieren', 'desillusionieren'],
    collocations: ['jemanden enttäuschen', 'enttäuscht sein'],
    emoji: '😞',
    exampleSentence: 'Das Ergebnis hat mich enttäuscht.',
    exampleTranslation: 'Sonuç beni hayal kırıklığına uğrattı.',
    exampleTranslationEn: 'The result disappointed me.',
    category: 'verbs',
    level: 'B1',
  },
  // === NEW B2 VERBS (verbs-80 to verbs-100) ===
  {
    id: 'verbs-80',
    german: 'sich auseinandersetzen',
    turkish: 'Bir konuyu ele almak / İncelemek',
    english: 'To deal with / To engage with',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich befassen', 'sich beschäftigen mit'],
    collocations: ['sich mit einem Thema auseinandersetzen', 'kritisch auseinandersetzen'],
    emoji: '🔬',
    exampleSentence: 'Wir müssen uns mit diesem Problem auseinandersetzen.',
    exampleTranslation: 'Bu sorunla ilgilenmeliyiz.',
    exampleTranslationEn: 'We must deal with this problem.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-81',
    german: 'beitragen',
    turkish: 'Katkıda bulunmak',
    english: 'To contribute',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['mitwirken', 'beisteuern'],
    collocations: ['zu etwas beitragen', 'seinen Teil beitragen'],
    emoji: '🤲',
    exampleSentence: 'Jeder kann zum Umweltschutz beitragen.',
    exampleTranslation: 'Herkes çevre korumaya katkıda bulunabilir.',
    exampleTranslationEn: 'Everyone can contribute to environmental protection.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-82',
    german: 'behaupten',
    turkish: 'İddia etmek',
    english: 'To claim / To assert',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['beharrren', 'versichern'],
    collocations: ['etwas behaupten', 'steif und fest behaupten'],
    emoji: '📢',
    exampleSentence: 'Er behauptet, dass er unschuldig ist.',
    exampleTranslation: 'Masum olduğunu iddia ediyor.',
    exampleTranslationEn: 'He claims that he is innocent.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-83',
    german: 'überzeugen',
    turkish: 'İkna etmek',
    english: 'To convince',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['überreden', 'bekehren'],
    collocations: ['jemanden überzeugen', 'davon überzeugt sein'],
    emoji: '🎤',
    exampleSentence: 'Sie hat mich von ihrer Idee überzeugt.',
    exampleTranslation: 'Beni fikrine ikna etti.',
    exampleTranslationEn: 'She convinced me of her idea.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-84',
    german: 'sich herausstellen',
    turkish: 'Ortaya çıkmak / Anlaşılmak',
    english: 'To turn out',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich zeigen', 'sich erweisen'],
    collocations: ['es stellt sich heraus', 'als falsch herausstellen'],
    emoji: '🔎',
    exampleSentence: 'Es hat sich herausgestellt, dass er recht hatte.',
    exampleTranslation: 'Haklı olduğu ortaya çıktı.',
    exampleTranslationEn: 'It turned out that he was right.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-85',
    german: 'sich ausdrücken',
    turkish: 'Kendini ifade etmek',
    english: 'To express oneself',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['formulieren', 'sich äußern'],
    collocations: ['sich klar ausdrücken', 'sich gut ausdrücken'],
    emoji: '🎭',
    exampleSentence: 'Er kann sich auf Deutsch gut ausdrücken.',
    exampleTranslation: 'Kendini Almanca iyi ifade edebiliyor.',
    exampleTranslationEn: 'He can express himself well in German.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-86',
    german: 'voraussetzen',
    turkish: 'Ön koşul olarak kabul etmek',
    english: 'To presuppose / To require',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['erfordern', 'bedingen'],
    collocations: ['Erfahrung voraussetzen', 'vorausgesetzt dass'],
    emoji: '📌',
    exampleSentence: 'Dieser Job setzt Berufserfahrung voraus.',
    exampleTranslation: 'Bu iş, iş deneyimi gerektiriyor.',
    exampleTranslationEn: 'This job requires work experience.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-87',
    german: 'sich weigern',
    turkish: 'Reddetmek / Karşı çıkmak',
    english: 'To refuse',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['ablehnen', 'verweigern'],
    antonyms: ['zustimmen'],
    collocations: ['sich weigern etwas zu tun', 'sich strikt weigern'],
    emoji: '✋',
    exampleSentence: 'Er weigert sich, die Arbeit zu machen.',
    exampleTranslation: 'İşi yapmayı reddediyor.',
    exampleTranslationEn: 'He refuses to do the work.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-88',
    german: 'widersprechen',
    turkish: 'Çelişmek / İtiraz etmek',
    english: 'To contradict',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['entgegnen', 'dagegenhalten'],
    antonyms: ['zustimmen'],
    collocations: ['jemandem widersprechen', 'sich widersprechen'],
    emoji: '⚡',
    exampleSentence: 'Er hat mir öffentlich widersprochen.',
    exampleTranslation: 'Bana açıkça itiraz etti.',
    exampleTranslationEn: 'He publicly contradicted me.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-89',
    german: 'ersetzen',
    turkish: 'Değiştirmek / Yerine koymak',
    english: 'To replace',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['austauschen', 'substituieren'],
    collocations: ['jemanden ersetzen', 'durch etwas ersetzen'],
    emoji: '🔄',
    exampleSentence: 'Maschinen ersetzen viele Arbeitsplätze.',
    exampleTranslation: 'Makineler birçok iş yerinin yerini alıyor.',
    exampleTranslationEn: 'Machines are replacing many jobs.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-90',
    german: 'sich einsetzen',
    turkish: 'Savunmak / Çaba göstermek',
    english: 'To advocate / To stand up for',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['kämpfen für', 'sich engagieren'],
    collocations: ['sich für etwas einsetzen', 'sich für Gerechtigkeit einsetzen'],
    emoji: '✊',
    exampleSentence: 'Sie setzt sich für Menschenrechte ein.',
    exampleTranslation: 'İnsan hakları için mücadele ediyor.',
    exampleTranslationEn: 'She advocates for human rights.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-91',
    german: 'durchführen',
    turkish: 'Gerçekleştirmek / Uygulamak',
    english: 'To carry out / To conduct',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['ausführen', 'umsetzen'],
    collocations: ['eine Studie durchführen', 'ein Projekt durchführen'],
    emoji: '⚙️',
    exampleSentence: 'Wir führen eine Umfrage durch.',
    exampleTranslation: 'Bir anket yapıyoruz.',
    exampleTranslationEn: 'We are conducting a survey.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-92',
    german: 'bewältigen',
    turkish: 'Üstesinden gelmek / Başa çıkmak',
    english: 'To cope with / To manage',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['meistern', 'schaffen'],
    collocations: ['eine Aufgabe bewältigen', 'den Alltag bewältigen'],
    emoji: '🏔️',
    exampleSentence: 'Sie hat die schwierige Situation gut bewältigt.',
    exampleTranslation: 'Zor durumun üstesinden iyi geldi.',
    exampleTranslationEn: 'She managed the difficult situation well.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-93',
    german: 'sich eignen',
    turkish: 'Uygun olmak / Elverişli olmak',
    english: 'To be suitable',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['passen', 'taugen'],
    collocations: ['sich für etwas eignen', 'sich gut eignen'],
    emoji: '🎯',
    exampleSentence: 'Dieses Buch eignet sich gut für Anfänger.',
    exampleTranslation: 'Bu kitap yeni başlayanlar için çok uygun.',
    exampleTranslationEn: 'This book is well suited for beginners.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-94',
    german: 'gefährden',
    turkish: 'Tehlikeye atmak',
    english: 'To endanger',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['riskieren', 'bedrohen'],
    antonyms: ['schützen'],
    collocations: ['die Gesundheit gefährden', 'die Umwelt gefährden'],
    emoji: '⚠️',
    exampleSentence: 'Rauchen gefährdet Ihre Gesundheit.',
    exampleTranslation: 'Sigara sağlığınızı tehlikeye atar.',
    exampleTranslationEn: 'Smoking endangers your health.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-95',
    german: 'vorwerfen',
    turkish: 'Suçlamak / İtham etmek',
    english: 'To accuse / To reproach',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['beschuldigen', 'anklagen'],
    collocations: ['jemandem etwas vorwerfen', 'sich nichts vorzuwerfen haben'],
    emoji: '👆',
    exampleSentence: 'Sie wirft ihm vor, gelogen zu haben.',
    exampleTranslation: 'Onu yalan söylemekle suçluyor.',
    exampleTranslationEn: 'She accuses him of having lied.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-96',
    german: 'auseinanderhalten',
    turkish: 'Ayırt etmek',
    english: 'To distinguish / To tell apart',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['unterscheiden', 'differenzieren'],
    collocations: ['kaum auseinanderhalten', 'deutlich auseinanderhalten'],
    emoji: '🔍',
    exampleSentence: 'Man kann die Zwillinge kaum auseinanderhalten.',
    exampleTranslation: 'İkizleri neredeyse ayırt edemezsiniz.',
    exampleTranslationEn: 'You can barely tell the twins apart.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-97',
    german: 'sich durchsetzen',
    turkish: 'Kendini kabul ettirmek / Başarmak',
    english: 'To assert oneself / To prevail',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['siegen', 'sich behaupten'],
    antonyms: ['nachgeben'],
    collocations: ['sich gegen jemanden durchsetzen', 'eine Idee setzt sich durch'],
    emoji: '🏆',
    exampleSentence: 'Sie hat sich in der Diskussion durchgesetzt.',
    exampleTranslation: 'Tartışmada fikrini kabul ettirdi.',
    exampleTranslationEn: 'She prevailed in the discussion.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-98',
    german: 'auswerten',
    turkish: 'Değerlendirmek / Analiz etmek',
    english: 'To evaluate / To analyze',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['analysieren', 'bewerten'],
    collocations: ['Daten auswerten', 'Ergebnisse auswerten'],
    emoji: '📊',
    exampleSentence: 'Wir müssen die Ergebnisse noch auswerten.',
    exampleTranslation: 'Sonuçları hâlâ değerlendirmemiz gerekiyor.',
    exampleTranslationEn: 'We still need to evaluate the results.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-99',
    german: 'vernachlässigen',
    turkish: 'İhmal etmek',
    english: 'To neglect',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['missachten', 'versäumen'],
    collocations: ['seine Pflichten vernachlässigen', 'die Gesundheit vernachlässigen'],
    emoji: '😔',
    exampleSentence: 'Man sollte seine Gesundheit nicht vernachlässigen.',
    exampleTranslation: 'Sağlığını ihmal etmemelisin.',
    exampleTranslationEn: 'One should not neglect one\'s health.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-100',
    german: 'sich auskennen',
    turkish: 'Bilgi sahibi olmak / Bir konuda bilgili olmak',
    english: 'To be knowledgeable / To know one\'s way around',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['Bescheid wissen', 'sich zurechtfinden'],
    collocations: ['sich mit etwas auskennen', 'sich in der Stadt auskennen'],
    emoji: '🧭',
    exampleSentence: 'Er kennt sich mit Computern gut aus.',
    exampleTranslation: 'Bilgisayarlar konusunda çok bilgili.',
    exampleTranslationEn: 'He is very knowledgeable about computers.',
    category: 'verbs',
    level: 'B2',
  },
];
