import { VocabularyWord } from '@/lib/types';

export const verbsWords: VocabularyWord[] = [
  {
    id: 'verbs-1',
    german: 'sein',
    turkish: 'Olmak',
    english: 'To be',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['existieren', 'dasein'],
    collocations: ['glücklich sein', 'müde sein', 'zu Hause sein'],
    emoji: '🔵',
    exampleSentence: 'Ich bin Student.',
    exampleTranslation: 'Ben öğrenciyim.',
    exampleTranslationEn: 'I am a student.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-2',
    german: 'haben',
    turkish: 'Sahip olmak',
    english: 'To have',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['besitzen', 'verfügen über'],
    collocations: ['Hunger haben', 'Zeit haben', 'Recht haben'],
    emoji: '✋',
    exampleSentence: 'Ich habe zwei Geschwister.',
    exampleTranslation: 'İki kardeşim var.',
    exampleTranslationEn: 'I have two siblings.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-3',
    german: 'machen',
    turkish: 'Yapmak',
    english: 'To do / To make',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['tun', 'herstellen'],
    collocations: ['Hausaufgaben machen', 'Sport machen', 'Urlaub machen'],
    emoji: '🛠️',
    exampleSentence: 'Was machst du heute Abend?',
    exampleTranslation: 'Bu akşam ne yapıyorsun?',
    exampleTranslationEn: 'What are you doing tonight?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-4',
    german: 'gehen',
    turkish: 'Gitmek / Yürümek',
    english: 'To go / To walk',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['laufen', 'spazieren'],
    collocations: ['nach Hause gehen', 'spazieren gehen', 'einkaufen gehen'],
    emoji: '🚶',
    exampleSentence: 'Ich gehe jeden Morgen spazieren.',
    exampleTranslation: 'Her sabah yürüyüşe gidiyorum.',
    exampleTranslationEn: 'I go for a walk every morning.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-5',
    german: 'kommen',
    turkish: 'Gelmek',
    english: 'To come',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['ankommen', 'eintreffen'],
    collocations: ['aus Deutschland kommen', 'zu Besuch kommen'],
    emoji: '👋',
    exampleSentence: 'Woher kommst du?',
    exampleTranslation: 'Nerelisin?',
    exampleTranslationEn: 'Where do you come from?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-6',
    german: 'essen',
    turkish: 'Yemek yemek',
    english: 'To eat',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['speisen', 'sich ernähren'],
    collocations: ['zu Mittag essen', 'zu Abend essen'],
    emoji: '🍽️',
    exampleSentence: 'Was möchtest du essen?',
    exampleTranslation: 'Ne yemek istersin?',
    exampleTranslationEn: 'What would you like to eat?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-7',
    german: 'trinken',
    turkish: 'İçmek',
    english: 'To drink',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['schlürfen', 'nippen'],
    collocations: ['Wasser trinken', 'Kaffee trinken'],
    emoji: '🥤',
    exampleSentence: 'Ich trinke morgens immer Kaffee.',
    exampleTranslation: 'Sabahları hep kahve içerim.',
    exampleTranslationEn: 'I always drink coffee in the morning.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-8',
    german: 'sprechen',
    turkish: 'Konuşmak',
    english: 'To speak',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['reden', 'sich unterhalten'],
    collocations: ['Deutsch sprechen', 'über etwas sprechen'],
    emoji: '🗣️',
    exampleSentence: 'Sprechen Sie Deutsch?',
    exampleTranslation: 'Almanca konuşuyor musunuz?',
    exampleTranslationEn: 'Do you speak German?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-9',
    german: 'wohnen',
    turkish: 'Oturmak / İkamet etmek',
    english: 'To live (reside)',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['leben', 'residieren'],
    collocations: ['in Berlin wohnen', 'allein wohnen'],
    emoji: '🏠',
    exampleSentence: 'Wo wohnst du?',
    exampleTranslation: 'Nerede oturuyorsun?',
    exampleTranslationEn: 'Where do you live?',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-10',
    german: 'arbeiten',
    turkish: 'Çalışmak',
    english: 'To work',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['schaffen', 'tätig sein'],
    collocations: ['hart arbeiten', 'als Ingenieur arbeiten'],
    emoji: '💼',
    exampleSentence: 'Ich arbeite als Programmierer.',
    exampleTranslation: 'Programcı olarak çalışıyorum.',
    exampleTranslationEn: 'I work as a programmer.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-11',
    german: 'kaufen',
    turkish: 'Satın almak',
    english: 'To buy',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['erwerben', 'anschaffen'],
    antonyms: ['verkaufen'],
    collocations: ['ein Auto kaufen', 'online kaufen'],
    emoji: '🛒',
    exampleSentence: 'Ich möchte ein neues Buch kaufen.',
    exampleTranslation: 'Yeni bir kitap almak istiyorum.',
    exampleTranslationEn: 'I want to buy a new book.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-12',
    german: 'schlafen',
    turkish: 'Uyumak',
    english: 'To sleep',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['ruhen', 'pennen'],
    antonyms: ['aufwachen'],
    collocations: ['gut schlafen', 'lange schlafen'],
    emoji: '😴',
    exampleSentence: 'Ich habe letzte Nacht schlecht geschlafen.',
    exampleTranslation: 'Dün gece kötü uyudum.',
    exampleTranslationEn: 'I slept badly last night.',
    category: 'verbs',
    level: 'A1',
  },
  {
    id: 'verbs-13',
    german: 'verstehen',
    turkish: 'Anlamak',
    english: 'To understand',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['begreifen', 'kapieren'],
    collocations: ['gut verstehen', 'nicht verstehen'],
    emoji: '💡',
    exampleSentence: 'Ich verstehe die Frage nicht.',
    exampleTranslation: 'Soruyu anlamıyorum.',
    exampleTranslationEn: 'I don\'t understand the question.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-14',
    german: 'helfen',
    turkish: 'Yardım etmek',
    english: 'To help',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['unterstützen', 'beistehen'],
    collocations: ['jemandem helfen', 'bei der Arbeit helfen'],
    emoji: '🤝',
    exampleSentence: 'Kann ich dir helfen?',
    exampleTranslation: 'Sana yardım edebilir miyim?',
    exampleTranslationEn: 'Can I help you?',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-15',
    german: 'denken',
    turkish: 'Düşünmek',
    english: 'To think',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['überlegen', 'nachdenken', 'glauben'],
    collocations: ['an jemanden denken', 'darüber nachdenken'],
    emoji: '🤔',
    exampleSentence: 'Was denkst du darüber?',
    exampleTranslation: 'Bu konuda ne düşünüyorsun?',
    exampleTranslationEn: 'What do you think about it?',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-16',
    german: 'wissen',
    turkish: 'Bilmek',
    english: 'To know (facts)',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['kennen', 'Bescheid wissen'],
    collocations: ['das weiß ich nicht', 'Bescheid wissen'],
    emoji: '🧠',
    exampleSentence: 'Ich weiß nicht, wo er ist.',
    exampleTranslation: 'Nerede olduğunu bilmiyorum.',
    exampleTranslationEn: 'I don\'t know where he is.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-17',
    german: 'brauchen',
    turkish: 'İhtiyacı olmak',
    english: 'To need',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['benötigen', 'erfordern'],
    collocations: ['Hilfe brauchen', 'Zeit brauchen'],
    emoji: '❗',
    exampleSentence: 'Ich brauche deine Hilfe.',
    exampleTranslation: 'Yardımına ihtiyacım var.',
    exampleTranslationEn: 'I need your help.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-18',
    german: 'finden',
    turkish: 'Bulmak',
    english: 'To find',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['entdecken', 'aufspüren'],
    antonyms: ['verlieren'],
    collocations: ['einen Job finden', 'etwas gut finden'],
    emoji: '🔍',
    exampleSentence: 'Ich finde meinen Schlüssel nicht.',
    exampleTranslation: 'Anahtarımı bulamıyorum.',
    exampleTranslationEn: 'I can\'t find my key.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-19',
    german: 'geben',
    turkish: 'Vermek',
    english: 'To give',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['überreichen', 'schenken'],
    antonyms: ['nehmen'],
    collocations: ['ein Geschenk geben', 'es gibt'],
    emoji: '🎁',
    exampleSentence: 'Gibst du mir bitte das Salz?',
    exampleTranslation: 'Bana tuzu verir misin lütfen?',
    exampleTranslationEn: 'Can you give me the salt please?',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-20',
    german: 'nehmen',
    turkish: 'Almak',
    english: 'To take',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['greifen', 'ergreifen'],
    antonyms: ['geben'],
    collocations: ['den Bus nehmen', 'Platz nehmen'],
    emoji: '👊',
    exampleSentence: 'Ich nehme den Bus zur Arbeit.',
    exampleTranslation: 'İşe otobüsle gidiyorum.',
    exampleTranslationEn: 'I take the bus to work.',
    category: 'verbs',
    level: 'A2',
  },
  {
    id: 'verbs-21',
    german: 'sich entscheiden',
    turkish: 'Karar vermek',
    english: 'To decide',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['beschließen', 'sich festlegen'],
    collocations: ['sich für etwas entscheiden', 'schnell entscheiden'],
    emoji: '⚖️',
    exampleSentence: 'Ich kann mich nicht entscheiden.',
    exampleTranslation: 'Karar veremiyorum.',
    exampleTranslationEn: 'I can\'t decide.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-22',
    german: 'sich beschweren',
    turkish: 'Şikayet etmek',
    english: 'To complain',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['reklamieren', 'protestieren'],
    collocations: ['sich über etwas beschweren', 'sich beim Chef beschweren'],
    emoji: '😤',
    exampleSentence: 'Er beschwert sich immer über das Essen.',
    exampleTranslation: 'Her zaman yemekten şikayet ediyor.',
    exampleTranslationEn: 'He always complains about the food.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-23',
    german: 'vorschlagen',
    turkish: 'Önermek / Teklif etmek',
    english: 'To suggest',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['empfehlen', 'anregen'],
    collocations: ['einen Plan vorschlagen', 'etwas Neues vorschlagen'],
    emoji: '💬',
    exampleSentence: 'Ich schlage vor, dass wir morgen anfangen.',
    exampleTranslation: 'Yarın başlamamızı öneriyorum.',
    exampleTranslationEn: 'I suggest that we start tomorrow.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-24',
    german: 'sich gewöhnen',
    turkish: 'Alışmak',
    english: 'To get used to',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['sich anpassen'],
    collocations: ['sich an etwas gewöhnen', 'sich daran gewöhnen'],
    emoji: '🔄',
    exampleSentence: 'Ich habe mich an das kalte Wetter gewöhnt.',
    exampleTranslation: 'Soğuk havaya alıştım.',
    exampleTranslationEn: 'I got used to the cold weather.',
    category: 'verbs',
    level: 'B1',
  },
  {
    id: 'verbs-25',
    german: 'beeinflussen',
    turkish: 'Etkilemek',
    english: 'To influence',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['einwirken', 'prägen'],
    collocations: ['positiv beeinflussen', 'stark beeinflussen'],
    emoji: '🎯',
    exampleSentence: 'Soziale Medien beeinflussen unser Verhalten.',
    exampleTranslation: 'Sosyal medya davranışlarımızı etkiliyor.',
    exampleTranslationEn: 'Social media influences our behavior.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-26',
    german: 'berücksichtigen',
    turkish: 'Göz önünde bulundurmak',
    english: 'To take into consideration',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['beachten', 'einbeziehen'],
    collocations: ['alle Faktoren berücksichtigen', 'berücksichtigt werden'],
    emoji: '📊',
    exampleSentence: 'Wir müssen alle Aspekte berücksichtigen.',
    exampleTranslation: 'Tüm yönleri göz önünde bulundurmalıyız.',
    exampleTranslationEn: 'We must take all aspects into consideration.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-27',
    german: 'verwirklichen',
    turkish: 'Gerçekleştirmek',
    english: 'To realize / To achieve',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['realisieren', 'umsetzen'],
    collocations: ['einen Traum verwirklichen', 'Ideen verwirklichen'],
    emoji: '🌟',
    exampleSentence: 'Sie hat ihren Traum verwirklicht.',
    exampleTranslation: 'Hayalini gerçekleştirdi.',
    exampleTranslationEn: 'She realized her dream.',
    category: 'verbs',
    level: 'B2',
  },
  {
    id: 'verbs-28',
    german: 'zusammenfassen',
    turkish: 'Özetlemek',
    english: 'To summarize',
    article: null,
    partOfSpeech: 'verb',
    synonyms: ['resümieren', 'auf den Punkt bringen'],
    collocations: ['die Ergebnisse zusammenfassen', 'kurz zusammenfassen'],
    emoji: '📋',
    exampleSentence: 'Können Sie die wichtigsten Punkte zusammenfassen?',
    exampleTranslation: 'En önemli noktaları özetleyebilir misiniz?',
    exampleTranslationEn: 'Can you summarize the most important points?',
    category: 'verbs',
    level: 'B2',
  },
];
