import { VocabularyWord } from '@/lib/types';
export const workWords: VocabularyWord[] = [
  {
    id: 'work-1',
    german: 'Arbeit',
    turkish: 'İş',
    english: 'Work',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Arbeiten',
    emoji: '💼',
    synonyms: ['Job', 'Beschäftigung', 'Tätigkeit'],
    collocations: ['zur Arbeit gehen', 'eine Arbeit suchen', 'die Arbeit erledigen'],
    exampleSentence: 'Ich gehe zur Arbeit.',
    exampleTranslation: 'İşe gidiyorum.',
    exampleTranslationEn: 'I am going to work.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-2',
    german: 'Beruf',
    turkish: 'Meslek',
    english: 'Profession/Occupation',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Berufe',
    emoji: '👔',
    synonyms: ['Job', 'Tätigkeit'],
    collocations: ['einen Beruf ausüben', 'einen Beruf erlernen', 'von Beruf sein'],
    exampleSentence: 'Was ist Ihr Beruf?',
    exampleTranslation: 'Mesleğiniz ne?',
    exampleTranslationEn: 'What is your profession?',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-3',
    german: 'Büro',
    turkish: 'Ofis',
    english: 'Office',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Büros',
    emoji: '🏢',
    synonyms: ['Arbeitszimmer', 'Kanzlei'],
    collocations: ['im Büro arbeiten', 'ins Büro gehen', 'das Büro verlassen'],
    exampleSentence: 'Ich arbeite im Büro.',
    exampleTranslation: 'Ofiste çalışıyorum.',
    exampleTranslationEn: 'I work in the office.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-4',
    german: 'Chef',
    turkish: 'Patron/Şef',
    english: 'Boss',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Chefs',
    emoji: '👨‍💼',
    synonyms: ['Vorgesetzter', 'Boss', 'Leiter'],
    collocations: ['der Chef entscheidet', 'mit dem Chef sprechen', 'den Chef informieren'],
    exampleSentence: 'Mein Chef ist sehr nett.',
    exampleTranslation: 'Patronum çok iyi.',
    exampleTranslationEn: 'My boss is very nice.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-5',
    german: 'Gehalt',
    turkish: 'Maaş',
    english: 'Salary',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Gehälter',
    emoji: '💰',
    synonyms: ['Lohn', 'Einkommen', 'Verdienst'],
    collocations: ['ein gutes Gehalt verdienen', 'das Gehalt verhandeln', 'das Gehalt bekommen'],
    exampleSentence: 'Das Gehalt kommt am Monatsende.',
    exampleTranslation: 'Maaş ay sonunda gelir.',
    exampleTranslationEn: 'The salary comes at the end of the month.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-6',
    german: 'Arzt',
    turkish: 'Doktor',
    english: 'Doctor',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Ärzte',
    emoji: '👨‍⚕️',
    synonyms: ['Doktor', 'Mediziner'],
    collocations: ['zum Arzt gehen', 'einen Arzt aufsuchen', 'der Arzt untersucht'],
    exampleSentence: 'Mein Bruder ist Arzt.',
    exampleTranslation: 'Erkek kardeşim doktor.',
    exampleTranslationEn: 'My brother is a doctor.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-7',
    german: 'Lehrer',
    turkish: 'Öğretmen',
    english: 'Teacher',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Lehrer',
    emoji: '👨‍🏫',
    synonyms: ['Pädagoge', 'Dozent'],
    collocations: ['als Lehrer arbeiten', 'der Lehrer erklärt', 'einen guten Lehrer haben'],
    exampleSentence: 'Die Lehrerin erklärt die Grammatik.',
    exampleTranslation: 'Öğretmen grameri açıklıyor.',
    exampleTranslationEn: 'The teacher explains the grammar.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-8',
    german: 'arbeiten',
    turkish: 'çalışmak',
    english: 'To work',
    article: null,
    partOfSpeech: 'verb',
    emoji: '⚒️',
    synonyms: ['tätig sein', 'schaffen'],
    collocations: ['hart arbeiten', 'als ... arbeiten', 'bei einer Firma arbeiten'],
    exampleSentence: 'Ich arbeite von Montag bis Freitag.',
    exampleTranslation: 'Pazartesiden Cumaya çalışıyorum.',
    exampleTranslationEn: 'I work from Monday to Friday.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-9',
    german: 'Firma',
    turkish: 'Şirket',
    english: 'Company',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Firmen',
    emoji: '🏭',
    synonyms: ['Unternehmen', 'Betrieb', 'Konzern'],
    collocations: ['eine Firma gründen', 'bei einer Firma arbeiten', 'die Firma leiten'],
    exampleSentence: 'Die Firma hat 200 Mitarbeiter.',
    exampleTranslation: 'Şirketin 200 çalışanı var.',
    exampleTranslationEn: 'The company has 200 employees.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-10',
    german: 'Termin',
    turkish: 'Randevu',
    english: 'Appointment',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Termine',
    emoji: '📅',
    synonyms: ['Verabredung', 'Zeitpunkt'],
    collocations: ['einen Termin vereinbaren', 'einen Termin absagen', 'einen Termin haben'],
    exampleSentence: 'Ich habe einen Termin um 14 Uhr.',
    exampleTranslation: 'Saat 14\'te randevum var.',
    exampleTranslationEn: 'I have an appointment at 2 PM.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-11',
    german: 'Ingenieur',
    turkish: 'Mühendis',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Ingenieure',
    emoji: '👷',
    synonyms: ['Techniker'],
    collocations: ['als Ingenieur arbeiten', 'Ingenieur studieren', 'ein erfahrener Ingenieur'],
    exampleSentence: 'Er arbeitet als Ingenieur.',
    exampleTranslation: 'Mühendis olarak çalışıyor.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-12',
    german: 'Bewerbung',
    turkish: 'Başvuru',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Bewerbungen',
    emoji: '📝',
    collocations: ['eine Bewerbung schreiben', 'eine Bewerbung einreichen', 'die Bewerbung abschicken'],
    exampleSentence: 'Ich schreibe eine Bewerbung.',
    exampleTranslation: 'Bir başvuru yazıyorum.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-13',
    german: 'Erfahrung',
    turkish: 'Deneyim',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Erfahrungen',
    emoji: '🎓',
    synonyms: ['Praxis', 'Kenntnis'],
    collocations: ['Erfahrung sammeln', 'Erfahrung haben', 'berufliche Erfahrung'],
    exampleSentence: 'Haben Sie Erfahrung?',
    exampleTranslation: 'Deneyiminiz var mı?',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-14',
    german: 'Kollege',
    turkish: 'İş arkadaşı',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Kollegen',
    emoji: '🤝',
    synonyms: ['Mitarbeiter', 'Arbeitskollege'],
    collocations: ['ein netter Kollege', 'mit Kollegen zusammenarbeiten', 'die Kollegen treffen'],
    exampleSentence: 'Mein Kollege hilft mir.',
    exampleTranslation: 'İş arkadaşım bana yardım ediyor.',
    category: 'work',
    level: 'A2',
  },
  {
    id: 'work-15',
    german: 'Projekt',
    turkish: 'Proje',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Projekte',
    emoji: '📊',
    synonyms: ['Vorhaben', 'Aufgabe'],
    collocations: ['ein Projekt leiten', 'an einem Projekt arbeiten', 'das Projekt abschließen'],
    exampleSentence: 'Das Projekt ist fast fertig.',
    exampleTranslation: 'Proje neredeyse bitti.',
    category: 'work',
    level: 'A2',
  },
  // B1 - Office, careers
  {
    id: 'work-b1-1',
    german: 'die Erfahrung',
    turkish: 'deneyim',
    english: 'experience',
    article: 'die',
    plural: 'Erfahrungen',
    partOfSpeech: 'noun',
    exampleSentence: 'Ich habe viel Erfahrung in diesem Bereich.',
    exampleTranslation: 'Bu alanda çok deneyimim var.',
    exampleTranslationEn: 'I have a lot of experience in this field.',
    category: 'work',
    level: 'B1',
    tags: ['career', 'skills'],
  },
  {
    id: 'work-b1-2',
    german: 'das Vorstellungsgespräch',
    turkish: 'iş görüşmesi',
    english: 'job interview',
    article: 'das',
    plural: 'Vorstellungsgespräche',
    partOfSpeech: 'noun',
    exampleSentence: 'Ich habe morgen ein Vorstellungsgespräch.',
    exampleTranslation: 'Yarın bir iş görüşmem var.',
    exampleTranslationEn: 'I have a job interview tomorrow.',
    category: 'work',
    level: 'B1',
    tags: ['application', 'interview'],
  },
  {
    id: 'work-b1-3',
    german: 'der Lebenslauf',
    turkish: 'özgeçmiş',
    english: 'resume / CV',
    article: 'der',
    plural: 'Lebensläufe',
    partOfSpeech: 'noun',
    exampleSentence: 'Bitte schicken Sie Ihren Lebenslauf per E-Mail.',
    exampleTranslation: 'Lütfen özgeçmişinizi e-posta ile gönderin.',
    exampleTranslationEn: 'Please send your resume by email.',
    category: 'work',
    level: 'B1',
    tags: ['application', 'documents'],
  },
  {
    id: 'work-b1-4',
    german: 'die Abteilung',
    turkish: 'departman / bölüm',
    english: 'department',
    article: 'die',
    plural: 'Abteilungen',
    partOfSpeech: 'noun',
    exampleSentence: 'In welcher Abteilung arbeiten Sie?',
    exampleTranslation: 'Hangi departmanda çalışıyorsunuz?',
    exampleTranslationEn: 'In which department do you work?',
    category: 'work',
    level: 'B1',
    tags: ['office', 'organization'],
  },
  {
    id: 'work-b1-5',
    german: 'kündigen',
    turkish: 'istifa etmek / işten çıkarmak',
    english: 'to resign / to terminate',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Er hat seinen Job gekündigt, weil er eine bessere Stelle gefunden hat.',
    exampleTranslation: 'Daha iyi bir iş bulduğu için işinden istifa etti.',
    exampleTranslationEn: 'He quit his job because he found a better position.',
    category: 'work',
    level: 'B1',
    tags: ['career', 'resignation'],
  },
  {
    id: 'work-b1-6',
    german: 'die Besprechung',
    turkish: 'toplantı',
    english: 'meeting',
    article: 'die',
    plural: 'Besprechungen',
    partOfSpeech: 'noun',
    exampleSentence: 'Die Besprechung beginnt um 10 Uhr im Konferenzraum.',
    exampleTranslation: 'Toplantı saat 10\'da konferans odasında başlıyor.',
    exampleTranslationEn: 'The meeting starts at 10 o\'clock in the conference room.',
    category: 'work',
    level: 'B1',
    tags: ['office', 'meeting'],
  },
  {
    id: 'work-b1-7',
    german: 'die Überstunde',
    turkish: 'fazla mesai',
    english: 'overtime',
    article: 'die',
    plural: 'Überstunden',
    partOfSpeech: 'noun',
    exampleSentence: 'Diese Woche muss ich viele Überstunden machen.',
    exampleTranslation: 'Bu hafta çok fazla mesai yapmam gerekiyor.',
    exampleTranslationEn: 'This week I have to work a lot of overtime.',
    category: 'work',
    level: 'B1',
    tags: ['working-hours', 'overtime'],
  },
  {
    id: 'work-b1-8',
    german: 'sich bewerben',
    turkish: 'başvurmak',
    english: 'to apply (for a job)',
    article: null,
    partOfSpeech: 'verb',
    exampleSentence: 'Ich möchte mich um diese Stelle bewerben.',
    exampleTranslation: 'Bu pozisyona başvurmak istiyorum.',
    exampleTranslationEn: 'I would like to apply for this position.',
    category: 'work',
    level: 'B1',
    tags: ['application', 'career'],
  },
  {
    id: 'work-b1-9',
    german: 'das Praktikum',
    turkish: 'staj',
    english: 'internship',
    article: 'das',
    plural: 'Praktika',
    partOfSpeech: 'noun',
    exampleSentence: 'Im Sommer mache ich ein Praktikum bei einer Firma.',
    exampleTranslation: 'Yazın bir şirkette staj yapıyorum.',
    exampleTranslationEn: 'In summer I am doing an internship at a company.',
    category: 'work',
    level: 'B1',
    tags: ['internship', 'career'],
  },
  {
    id: 'work-b1-10',
    german: 'der Arbeitsvertrag',
    turkish: 'iş sözleşmesi',
    english: 'employment contract',
    article: 'der',
    plural: 'Arbeitsverträge',
    partOfSpeech: 'noun',
    exampleSentence: 'Lesen Sie den Arbeitsvertrag sorgfältig durch.',
    exampleTranslation: 'İş sözleşmesini dikkatlice okuyun.',
    exampleTranslationEn: 'Read the employment contract carefully.',
    category: 'work',
    level: 'B1',
    tags: ['contract', 'legal'],
  },
  {
    id: 'work-16',
    german: 'Beförderung',
    turkish: 'Terfi',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Beförderungen',
    emoji: '📈',
    synonyms: ['Aufstieg', 'Karrieresprung'],
    antonyms: ['Degradierung', 'Rückstufung'],
    collocations: ['eine Beförderung bekommen', 'auf eine Beförderung hoffen', 'jemanden zur Beförderung vorschlagen'],
    exampleSentence: 'Nach fünf Jahren harter Arbeit hat sie endlich die verdiente Beförderung erhalten.',
    exampleTranslation: 'Beş yıllık sıkı çalışmanın ardından sonunda hak ettiği terfiyi aldı.',
    category: 'work',
    level: 'B2',
    tags: ['career', 'advancement'],
  },
  {
    id: 'work-17',
    german: 'Kündigung',
    turkish: 'İşten çıkarma/Fesih',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Kündigungen',
    emoji: '📄',
    synonyms: ['Entlassung', 'Freistellung'],
    antonyms: ['Einstellung', 'Anstellung'],
    collocations: ['eine Kündigung einreichen', 'die Kündigung erhalten', 'fristlose Kündigung'],
    exampleSentence: 'Die Kündigung muss schriftlich und unter Einhaltung der Frist erfolgen.',
    exampleTranslation: 'Fesih, yazılı olarak ve süreye uyularak yapılmalıdır.',
    category: 'work',
    level: 'B2',
    tags: ['contract', 'legal'],
  },
  {
    id: 'work-18',
    german: 'Vorstellungsgespräch',
    turkish: 'İş görüşmesi',
    article: 'das',
    partOfSpeech: 'noun',
    plural: 'Vorstellungsgespräche',
    emoji: '🤝',
    synonyms: ['Bewerbungsgespräch', 'Jobinterview'],
    collocations: ['ein Vorstellungsgespräch führen', 'zum Vorstellungsgespräch eingeladen werden', 'sich auf das Vorstellungsgespräch vorbereiten'],
    exampleSentence: 'Ich habe morgen ein wichtiges Vorstellungsgespräch bei einer internationalen Firma.',
    exampleTranslation: 'Yarın uluslararası bir şirkette önemli bir iş görüşmem var.',
    category: 'work',
    level: 'B2',
    tags: ['application', 'interview'],
  },
  {
    id: 'work-19',
    german: 'Überstunden',
    turkish: 'Fazla mesai',
    article: 'die (pl)',
    partOfSpeech: 'noun',
    emoji: '⏰',
    synonyms: ['Mehrarbeit'],
    collocations: ['Überstunden machen', 'Überstunden abbauen', 'Überstunden bezahlt bekommen'],
    exampleSentence: 'In der letzten Woche musste ich jeden Tag Überstunden machen, um das Projekt abzuschließen.',
    exampleTranslation: 'Geçen hafta projeyi bitirmek için her gün fazla mesai yapmak zorunda kaldım.',
    category: 'work',
    level: 'B2',
    tags: ['working-hours', 'overtime'],
  },
  {
    id: 'work-20',
    german: 'Weiterbildung',
    turkish: 'İleri eğitim/Mesleki gelişim',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Weiterbildungen',
    emoji: '📚',
    synonyms: ['Fortbildung', 'Qualifizierung'],
    collocations: ['eine Weiterbildung besuchen', 'sich durch Weiterbildung qualifizieren', 'berufliche Weiterbildung'],
    exampleSentence: 'Das Unternehmen bietet seinen Mitarbeitern regelmäßig Weiterbildungen an.',
    exampleTranslation: 'Şirket, çalışanlarına düzenli olarak ileri eğitim imkanları sunuyor.',
    category: 'work',
    level: 'B2',
    tags: ['education', 'development'],
  },
  {
    id: 'work-21',
    german: 'Verantwortung',
    turkish: 'Sorumluluk',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Verantwortungen',
    emoji: '⚖️',
    synonyms: ['Pflicht', 'Zuständigkeit'],
    collocations: ['Verantwortung übernehmen', 'Verantwortung tragen', 'jemanden zur Verantwortung ziehen'],
    exampleSentence: 'In meiner neuen Position trage ich die Verantwortung für ein Team von zehn Personen.',
    exampleTranslation: 'Yeni pozisyonumda on kişilik bir ekibin sorumluluğunu taşıyorum.',
    category: 'work',
    level: 'B2',
    tags: ['leadership', 'management'],
  },
  {
    id: 'work-22',
    german: 'selbstständig',
    turkish: 'Serbest meslek sahibi/Bağımsız',
    article: null,
    partOfSpeech: 'adjective',
    emoji: '🧑‍💻',
    synonyms: ['eigenständig', 'freiberuflich', 'unabhängig'],
    antonyms: ['angestellt', 'abhängig'],
    collocations: ['sich selbstständig machen', 'selbstständig arbeiten', 'selbstständig tätig sein'],
    exampleSentence: 'Nach zehn Jahren als Angestellter hat er sich selbstständig gemacht und eine eigene Agentur gegründet.',
    exampleTranslation: 'On yıl çalışan olarak çalıştıktan sonra kendi işini kurdu ve kendi ajansını açtı.',
    category: 'work',
    level: 'B2',
    tags: ['entrepreneurship', 'freelance'],
  },
  {
    id: 'work-23',
    german: 'Abteilung',
    turkish: 'Departman/Bölüm',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Abteilungen',
    emoji: '🏬',
    synonyms: ['Bereich', 'Sektion'],
    collocations: ['in einer Abteilung arbeiten', 'die Abteilung leiten', 'die Abteilung wechseln'],
    exampleSentence: 'Unsere Abteilung ist für die Entwicklung neuer Produkte zuständig.',
    exampleTranslation: 'Departmanımız yeni ürünlerin geliştirilmesinden sorumludur.',
    category: 'work',
    level: 'B2',
    tags: ['organization', 'structure'],
  },
  {
    id: 'work-24',
    german: 'Lebenslauf',
    turkish: 'Özgeçmiş',
    article: 'der',
    partOfSpeech: 'noun',
    plural: 'Lebensläufe',
    emoji: '📋',
    synonyms: ['CV', 'Curriculum Vitae'],
    collocations: ['einen Lebenslauf schreiben', 'den Lebenslauf aktualisieren', 'einen tabellarischen Lebenslauf erstellen'],
    exampleSentence: 'Vergessen Sie nicht, Ihren Lebenslauf vor der Bewerbung zu aktualisieren.',
    exampleTranslation: 'Başvurudan önce özgeçmişinizi güncellemeyi unutmayın.',
    category: 'work',
    level: 'B2',
    tags: ['application', 'documents'],
  },
  {
    id: 'work-25',
    german: 'Gehaltserhöhung',
    turkish: 'Maaş artışı/Zam',
    article: 'die',
    partOfSpeech: 'noun',
    plural: 'Gehaltserhöhungen',
    emoji: '💵',
    synonyms: ['Lohnerhöhung', 'Gehaltsanpassung'],
    antonyms: ['Gehaltskürzung'],
    collocations: ['eine Gehaltserhöhung fordern', 'eine Gehaltserhöhung bekommen', 'über eine Gehaltserhöhung verhandeln'],
    exampleSentence: 'Nach der erfolgreichen Projektleitung hat er seinen Chef um eine Gehaltserhöhung gebeten.',
    exampleTranslation: 'Başarılı proje yönetiminin ardından patronundan zam istedi.',
    category: 'work',
    level: 'B2',
    tags: ['salary', 'negotiation'],
  },
];
